infix using "C:\COUNTRIES\LS61\LSMR61FL.dct"

label variable mcaseid  "Case Identification"
label variable mv000    "Country code and phase"
label variable mv001    "Cluster number"
label variable mv002    "Household number"
label variable mv003    "Respondent's line number"
label variable mv004    "Ultimate area unit"
label variable mv005    "Sample weight"
label variable mv006    "Month of interview"
label variable mv007    "Year of interview"
label variable mv008    "Date of interview (CMC)"
label variable mv009    "Respondent's month of birth"
label variable mv010    "Respondent's year of birth"
label variable mv011    "Date of birth (CMC)"
label variable mv012    "Current age - respondent"
label variable mv013    "Age 5-year groups"
label variable mv014    "Completeness of information"
label variable mv015    "Result of individual interview"
label variable mv016    "Day of interview"
label variable mv021    "Primary sampling unit"
label variable mv022    "Sample stratum number"
label variable mv023    "Sample domain"
label variable mv024    "Region"
label variable mv025    "Type of place of residence"
label variable mv026    "NA - De facto place of residence"
label variable mv027    "Number of visits"
label variable mv028    "Interviewer identification"
label variable mv029    "NA - Keyer identification"
label variable mv030    "Field supervisor"
label variable mv031    "NA - Field editor"
label variable mv032    "NA - Office editor"
label variable mv033    "NA - Ultimate area selection prob."
label variable mv034_1  "Line numbers of wives, partners"
label variable mv034_2  "Line numbers of wives, partners"
label variable mv034_3  "Line numbers of wives, partners"
label variable mv034_4  "Line numbers of wives, partners"
label variable mv034_5  "Line numbers of wives, partners"
label variable mv034_6  "Line numbers of wives, partners"
label variable mv034_7  "Line numbers of wives, partners"
label variable mv034_8  "Line numbers of wives, partners"
label variable mv034a_1 "NA - Wife or partner"
label variable mv034a_2 "NA - Wife or partner"
label variable mv034a_3 "NA - Wife or partner"
label variable mv034a_4 "NA - Wife or partner"
label variable mv034a_5 "NA - Wife or partner"
label variable mv034a_6 "NA - Wife or partner"
label variable mv034a_7 "NA - Wife or partner"
label variable mv034a_8 "NA - Wife or partner"
label variable mv034b_1 "Age of wife/partner"
label variable mv034b_2 "Age of wife/partner"
label variable mv034b_3 "Age of wife/partner"
label variable mv034b_4 "Age of wife/partner"
label variable mv034b_5 "Age of wife/partner"
label variable mv034b_6 "Age of wife/partner"
label variable mv034b_7 "Age of wife/partner"
label variable mv034b_8 "Age of wife/partner"
label variable mv035    "Number of wives, partners"
label variable mv801    "Time interview started"
label variable mv802    "Time interview ended"
label variable mv803    "Length of interview in minutes"
label variable mv101    "Region"
label variable mv102    "Type of place of residence"
label variable mv103    "NA - Childhood place of residence"
label variable mv104    "Years lived in place of res."
label variable mv105    "Type of place of previous res."
label variable mv106    "Highest educational level"
label variable mv107    "Highest year of education"
label variable mv130    "Religion"
label variable mv131    "NA - Ethnicity"
label variable mv133    "Education in single years"
label variable mv134    "De facto place of residence"
label variable mv135    "Usual resident or visitor"
label variable mv136    "Number of household members"
label variable mv138    "Number of eligible men in HH"
label variable mv149    "Educational attainment"
label variable mv150    "Relationship to household head"
label variable mv151    "Sex of household head"
label variable mv152    "Age of household head"
label variable mv155    "Literacy"
label variable mv156    "Ever participated in a literacy program outside of primary"
label variable mv157    "Frequency of reading newspaper or magazine"
label variable mv158    "Frequency of listening to radio"
label variable mv159    "Frequency of watching television"
label variable mv167    "Times away from home in last 12 months"
label variable mv168    "Away for more than one month"
label variable mv190    "Wealth index"
label variable mv191    "Wealth index factor score (5 decimals)"
label variable mv201    "Total children ever born"
label variable mv202    "Sons at home"
label variable mv203    "Daughters at home"
label variable mv204    "Sons elsewhere"
label variable mv205    "Daughters elsewhere"
label variable mv206    "Sons who have died"
label variable mv207    "Daughters who have died"
label variable mv212    "Age of respondent at 1st birth"
label variable mv213    "Partner currently pregnant"
label variable mv217    "Knowledge of ovulatory cycle"
label variable mv218    "Number of living children"
label variable mv225    "NA - Current pregnancy wanted"
label variable mv245    "Women fathered children with"
label variable mv246    "NA - Married to mother when first child was born"
label variable mv247    "Age of youngest child"
label variable mv248    "Antenatal check-ups for the mother for youngest child"
label variable mv249    "Respondent present during check-ups for youngest child"
label variable mv250    "Place of birth of youngest child"
label variable mv251    "Reason for not delivering youngest child in health facility"
label variable mv252    "Drinking pattern when child has diarrhea"
label variable mv301    "Knowledge of any method"
label variable mv302    "Ever use of any method"
label variable m304a_01 "Type of method"
label variable m304a_02 "Type of method"
label variable m304a_03 "Type of method"
label variable m304a_04 "Type of method"
label variable m304a_05 "Type of method"
label variable m304a_06 "Type of method"
label variable m304a_07 "Type of method"
label variable m304a_08 "Type of method"
label variable m304a_09 "Type of method"
label variable m304a_10 "Type of method"
label variable m304a_11 "Type of method"
label variable m304a_12 "Type of method"
label variable m304a_13 "Type of method"
label variable m304a_14 "Type of method"
label variable m304a_15 "Type of method"
label variable m304a_16 "Type of method"
label variable m304a_17 "Type of method"
label variable m304a_18 "Type of method"
label variable m304a_19 "Type of method"
label variable m304a_20 "Type of method"
label variable mv304_01 "Knows method"
label variable mv304_02 "Knows method"
label variable mv304_03 "Knows method"
label variable mv304_04 "Knows method"
label variable mv304_05 "Knows method"
label variable mv304_06 "Knows method"
label variable mv304_07 "Knows method"
label variable mv304_08 "Knows method"
label variable mv304_09 "Knows method"
label variable mv304_10 "Knows method"
label variable mv304_11 "Knows method"
label variable mv304_12 "Knows method"
label variable mv304_13 "Knows method"
label variable mv304_14 "Knows method"
label variable mv304_15 "Knows method"
label variable mv304_16 "Knows method"
label variable mv304_17 "Knows method"
label variable mv304_18 "Knows method"
label variable mv304_19 "Knows method"
label variable mv304_20 "Knows method"
label variable mv305_01 "NA - Ever used method"
label variable mv305_02 "NA - Ever used method"
label variable mv305_03 "NA - Ever used method"
label variable mv305_04 "NA - Ever used method"
label variable mv305_05 "NA - Ever used method"
label variable mv305_06 "NA - Ever used method"
label variable mv305_07 "NA - Ever used method"
label variable mv305_08 "NA - Ever used method"
label variable mv305_09 "NA - Ever used method"
label variable mv305_10 "NA - Ever used method"
label variable mv305_11 "NA - Ever used method"
label variable mv305_12 "NA - Ever used method"
label variable mv305_13 "NA - Ever used method"
label variable mv305_14 "NA - Ever used method"
label variable mv305_15 "NA - Ever used method"
label variable mv305_16 "NA - Ever used method"
label variable mv305_17 "NA - Ever used method"
label variable mv305_18 "NA - Ever used method"
label variable mv305_19 "NA - Ever used method"
label variable mv305_20 "NA - Ever used method"
label variable mv307_01 "Method currently used"
label variable mv307_02 "Method currently used"
label variable mv307_03 "Method currently used"
label variable mv307_04 "Method currently used"
label variable mv307_05 "Method currently used"
label variable mv307_06 "Method currently used"
label variable mv307_07 "Method currently used"
label variable mv307_08 "Method currently used"
label variable mv307_09 "Method currently used"
label variable mv307_10 "Method currently used"
label variable mv307_11 "Method currently used"
label variable mv307_12 "Method currently used"
label variable mv307_13 "Method currently used"
label variable mv307_14 "Method currently used"
label variable mv307_15 "Method currently used"
label variable mv307_16 "Method currently used"
label variable mv307_17 "Method currently used"
label variable mv307_18 "Method currently used"
label variable mv307_19 "Method currently used"
label variable mv307_20 "Method currently used"
label variable mv312    "Current contraceptive method"
label variable mv313    "Current use by method type"
label variable mv323a   "NA - Brand of condom used"
label variable mv325b   "NA - Cost of condoms last time obtained"
label variable mv372a   "NA - Shown condom package"
label variable mv384a   "Heard FP on radio last months"
label variable mv384b   "Heard FP on TV last months"
label variable mv384c   "Heard FP newspaper last months"
label variable mv395    "NA - Discussed FP with health worker last few months"
label variable mv396    "Can a woman who is breastfeeding get pregnant"
label variable mv3a09b  "NA - How many condoms did get last time"
label variable mv3b17   "NA - Source of condoms"
label variable mv3b25a  "Contraception is woman's business, man should not worry"
label variable mv3b25b  "Women who use contraception become promiscuous"
label variable mv463a   "Smokes cigarettes"
label variable mv463b   "Smokes pipe"
label variable mv463c   "Chewing  tobacco"
label variable mv463d   "Uses snuff"
label variable mv463e   "NA - Smokes country specific"
label variable mv463f   "NA - Smokes country specific"
label variable mv463g   "NA - Smokes country specific"
label variable mv463x   "Smokes other"
label variable mv463z   "Smokes nothing"
label variable mv464    "Number of cigarettes in last 24 hours"
label variable mv474    "Heard of Tuberculosis or TB"
label variable mv474a   "Tuberculosis spread by: air when coughing or sneezing"
label variable mv474b   "Tuberculosis spread by: sharing utensils"
label variable mv474c   "Tuberculosis spread by: touching a person with TB"
label variable mv474d   "Tuberculosis spread through food"
label variable mv474e   "Tuberculosis spread by: sexual contact"
label variable mv474f   "Tuberculosis spread by: mosquito bites"
label variable mv474g   "NA - Tuberculosis spread by: CS"
label variable mv474h   "NA - Tuberculosis spread by: CS"
label variable mv474i   "NA - Tuberculosis spread by: CS"
label variable mv474j   "NA - Tuberculosis spread by: CS"
label variable mv474x   "Tuberculosis spread by: other"
label variable mv474z   "Tuberculosis spread by: don't know"
label variable mv475    "Can tuberculosis be cured"
label variable mv476    "Keep secret when family member gets TB"
label variable mv477    "Number of injections in last 12 months"
label variable mv478    "Injections administered by a health worker"
label variable mv479    "Source for injection by health worker"
label variable mv480    "NA - Syringe and needle from new, unopened package"
label variable mv481    "Covered by health insurance"
label variable mv481a   "Health insurance type: mutual/community organization"
label variable mv481b   "Health insurance type: provided by employer"
label variable mv481c   "NA - Health insurance type: social security"
label variable mv481d   "Health insurance type: private/commercial purchased"
label variable mv481e   "NA - Health insurance type: CS"
label variable mv481f   "NA - Health insurance type: CS"
label variable mv481g   "NA - Health insurance type: CS"
label variable mv481h   "NA - Health insurance type: CS"
label variable mv481x   "Health insurance type: other"
label variable mv482a   "Arrange care of biological children under age 18"
label variable mv482b   "Primary caregiver of children under age 18"
label variable mv482c   "Arrange care of non-biological children < 18"
label variable mv483    "Is respondent circumcised"
label variable mv501    "Current marital status"
label variable mv502    "Currently/formerly/never marr."
label variable mv503    "Number of unions"
label variable mv504    "Wife/partner lives with respondent"
label variable mv505    "Number of wives, partners"
label variable mv507    "Month of first marriage"
label variable mv508    "Year of first marriage"
label variable mv509    "Date of first marriage (CMC)"
label variable mv510    "Completeness of date inform."
label variable mv511    "Age at first marriage"
label variable mv512    "Years since first marriage"
label variable mv513    "Marital duration (grouped)"
label variable mv525    "Age at first intercourse"
label variable mv527    "Time since last intercourse"
label variable mv528    "Time in days since last intercourse(g)"
label variable mv529    "Time in months since last intercourse (imputed)"
label variable mv531    "Age at first intercourse (imp)"
label variable mv532    "Flag for MV531"
label variable mv535    "Have ever been married"
label variable mv536    "Recent sexual activity"
label variable mv541    "NA - Intend to wait until married to have sex"
label variable mv602    "Fertility preference"
label variable mv603    "Preferred waiting time"
label variable mv604    "Preferred waiting time (grpd)"
label variable mv605    "Desire for more children"
label variable mv613    "Ideal number of children"
label variable mv614    "Ideal number of children (grp)"
label variable mv616    "Time for future birth"
label variable mv621    "NA - Wifes desire for children"
label variable mv627    "Ideal number of boys"
label variable mv628    "Ideal number of girls"
label variable mv629    "Ideal number of either sex"
label variable mv631    "NA - Problem if became pregnant"
label variable mv633a   "Reason for not having sex: Husband has STD"
label variable mv633b   "Reason for not having sex: Husband has other women"
label variable mv633c   "NA - Reason for not having sex: Recent birth"
label variable mv633d   "Reason for not having sex: Tired, mood"
label variable mv633e   "NA - Reason for not having sex: CS"
label variable mv633f   "NA - Reason for not having sex: CS"
label variable mv633g   "NA - Reason for not having sex: CS"
label variable mv634a   "Husband has right to: get angry"
label variable mv634b   "Husband has right to: refuse financial support"
label variable mv634c   "Husband has right to: use force for unwanted sex"
label variable mv634d   "Husband has right to: have sex with another women"
label variable mv714    "Respondent currently working"
label variable mv714a   "Have a job from which respondent was absent"
label variable mv716    "Respondent's occupation"
label variable mv717    "Respondent's occupation"
label variable mv719    "Work for family, others, self"
label variable mv721    "NA - Works at home or away"
label variable mv731    "Worked in last 12 months"
label variable mv732    "Employment all year/seasonal"
label variable mv739    "Who decides how to spend money"
label variable mv740    "Type of land where resp. works"
label variable mv741    "Type of earnings for work"
label variable mv743a   "NA - Final say on own health care"
label variable mv743b   "Final say on making large household purchases"
label variable mv743c   "Final say on making household purchases for daily needs"
label variable mv743d   "Final say on visits to family or relatives"
label variable mv743e   "NA - Final say on food to be cooked each day"
label variable mv743f   "Final say on deciding what to do with money wife earns"
label variable mv743g   "Final say on deciding how many children to have"
label variable mv744a   "Wife beating justified if she goes out without telling him"
label variable mv744b   "Wife beating justified if she neglects the children"
label variable mv744c   "Wife beating justified if she argues with him"
label variable mv744d   "Wife beating justified if she refuses to have sex with him"
label variable mv744e   "Wife beating justified if she burns the food"
label variable mv747a   "Childbearing is a woman's concern"
label variable mv747b   "Important for mother/child health to get assistance at delivery"
label variable mv750    "Heard sexual transmit. disease"
label variable mv751    "Ever heard of AIDS"
label variable mv754bp  "Reduce risk of getting AIDS by not having sex at all"
label variable mv754cp  "Reduce chances of AIDS by always using condoms during sex"
label variable mv754dp  "Reduce chance of AIDS: have 1 sex partner with no oth partner"
label variable mv754jp  "Get AIDS from mosquito bites"
label variable mv754wp  "Get AIDS by sharing food with person who has AIDS"
label variable mv756    "Can a healthy person have AIDS"
label variable mv761    "Last intercourse used condom"
label variable mv761b   "Intercourse with other woman (1) used condom"
label variable mv761c   "Intercourse with other woman (2) used condom"
label variable mv762aa  "Source for condoms: Government hospital"
label variable mv762ab  "Source for condoms: Government health center/post"
label variable mv762ac  "NA - Source for condoms: Family planning clinic"
label variable mv762ad  "NA - Source for condoms: Mobile clinic"
label variable mv762ae  "NA - Source for condoms: Public field worker"
label variable mv762af  "Source for condoms: Other public"
label variable mv762ag  "NA - Source for condoms: Public CS"
label variable mv762ah  "NA - Source for condoms: Public CS"
label variable mv762ai  "NA - Source for condoms: Public CS"
label variable mv762aj  "Source for condoms: Private hosp, clinic"
label variable mv762ak  "Source for condoms: Pharmacy"
label variable mv762al  "Source for condoms: Private doctor"
label variable mv762am  "Source for condoms: Lesotho Planned Parenthood Association (LPPA) (CS)"
label variable mv762an  "Source for condoms: CBD (CS)"
label variable mv762ao  "Source for condoms: Other private"
label variable mv762ap  "Source for condoms: CHAL hospital (CS-NGO)"
label variable mv762aq  "Source for condoms: CHAL health centre (CS-NGO)"
label variable mv762ar  "Source for condoms: CHAL health post (CS-NGO)"
label variable mv762as  "Source for condoms: Community Health Worker (CS)"
label variable mv762at  "Source for condoms: Shop"
label variable mv762au  "Source for condoms: Church"
label variable mv762av  "Source for condoms: Support Groups (CS)"
label variable mv762aw  "Source for condoms: Friends, relatives"
label variable mv762ax  "Source for condoms: Other"
label variable mv762az  "Source for condoms: DK source for condom"
label variable mv762ba  "Source for Female condoms: Government hospital"
label variable mv762bb  "Source for Female condoms: Government health center/post"
label variable mv762bc  "NA - Source for Female condoms: Family planning clinic"
label variable mv762bd  "NA - Source for Female condoms: Mobile clinic"
label variable mv762be  "NA - Source for Female condoms: Public field worker"
label variable mv762bf  "Source for Female condoms: Other public"
label variable mv762bg  "NA - Source for Female condoms: Public CS"
label variable mv762bh  "NA - Source for Female condoms: Public CS"
label variable mv762bi  "NA - Source for Female condoms: Public CS"
label variable mv762bj  "Source for Female condoms: Private hosp, clinic"
label variable mv762bk  "Source for Female condoms: Pharmacy"
label variable mv762bl  "Source for Female condoms: Private doctor"
label variable mv762bm  "Source for Female condoms: Lesotho Planned Parenthood Association (LPPA) (CS)"
label variable mv762bn  "Source for Female condoms: CBD (CS)"
label variable mv762bo  "Source for Female condoms: Other private"
label variable mv762bp  "Source for Female condoms: CHAL hospital (CS-NGO)"
label variable mv762bq  "Source for Female condoms: CHAL health centre (CS-NGO)"
label variable mv762br  "Source for Female condoms: CHAL health post (CS-NGO)"
label variable mv762bs  "Source for Female condoms: Community Health Worker (CS)"
label variable mv762bt  "Source for Female condoms: Shop"
label variable mv762bu  "Source for Female condoms: Church"
label variable mv762bv  "Source for Female condoms: Support Groups (CS)"
label variable mv762bw  "Source for Female condoms: Friends, relatives"
label variable mv762bx  "Source for Female condoms: Other"
label variable mv762bz  "Source for Female condoms: DK source for condom"
label variable mv763a   "Had any STD in last 12 months"
label variable mv763b   "Had genital sore/ulcer in last 12 months"
label variable mv763c   "Had genital discharge in last 12 months"
label variable mv763d   "NA - Last 12 months had CS STD"
label variable mv763e   "NA - Last 12 months had CS STD"
label variable mv763f   "NA - Last 12 months had CS STD"
label variable mv763g   "NA - Last 12 months had CS STD"
label variable mv766a   "No. other than wife had sex in last 12 months"
label variable mv766b   "No. had sex including wife in last 12 months"
label variable mv767a   "Relationship with last sex partner"
label variable mv767b   "Relationship with other sex partner (1)"
label variable mv767c   "Relationship with other sex partner (2)"
label variable mv768a   "Length of time knows last partner"
label variable mv768b   "Length of time knows other partner (1)"
label variable mv768c   "Length of time knows other partner (2)"
label variable mv769    "Could get a condom"
label variable mv769a   "Could get a female condom"
label variable mv770    "Seek advice for last disease"
label variable mv770a   "Seek advice STI: govt hospital"
label variable mv770b   "Seek advice STI: health center"
label variable mv770c   "NA - Seek advice STI: public VCT center"
label variable mv770d   "Seek advice STI: FP clinic"
label variable mv770e   "NA - Seek advice STI: mobile clinic"
label variable mv770f   "NA - Seek advice STI: fieldworker"
label variable mv770g   "NA - Seek advice STI: CS public"
label variable mv770h   "NA - Seek advice STI: CS public"
label variable mv770i   "NA - Seek advice STI: CS public"
label variable mv770j   "Seek advice STI: other public"
label variable mv770k   "Seek advice STI: private hosp/clinic/doctor"
label variable mv770l   "Seek advice STI: community health worker"
label variable mv770m   "Seek advice STI: pharmacy"
label variable mv770n   "Sought STI advice/treatment from: Support Groups"
label variable mv770o   "Seek advice STI: CBD"
label variable mv770p   "Seek advice STI: Private doctor (CS)"
label variable mv770q   "Source for condoms: CHAL hospital (CS-NGO)"
label variable mv770r   "Source for condoms: CHAL health centre (CS-NGO)"
label variable mv770s   "Seek advice STI: other private"
label variable mv770t   "Seek advice STI: shop"
label variable mv770u   "Seek advice STI: Traditional healer (CS)"
label variable mv770v   "Seek advice STI: Friends, relatives"
label variable mv770w   "Seek advice STI: Church"
label variable mv770x   "Seek advice other"
label variable mv774a   "AIDS transmit. during pregnancy"
label variable mv774b   "AIDS transmit. during delivery"
label variable mv774c   "AIDS transmit. by breastfeeding"
label variable mv775    "Knows someone who has or died of AIDS"
label variable mv777    "Allowed to keep AIDS infection secret"
label variable mv778    "Willing to care for relative with AIDS"
label variable mv779    "Person with AIDS allowed to continue teaching"
label variable mv780    "Should children be taught about condoms"
label variable mv781    "Ever been tested for AIDS"
label variable mv783    "Know a place to get AIDS test"
label variable mv784a   "Place for AIDS test: govt hospital"
label variable mv784b   "Place for AIDS test:health center"
label variable mv784c   "NA - Place for AIDS test: public VCT center"
label variable mv784d   "NA - Place for AIDS test: FP clinic"
label variable mv784e   "NA - Place for AIDS test: mobile clinic"
label variable mv784f   "NA - Place for AIDS test: filedworker"
label variable mv784g   "NA - Place for AIDS test: CS public"
label variable mv784h   "NA - Place for AIDS test: CS public"
label variable mv784i   "NA - Place for AIDS test: CS public"
label variable mv784j   "Place for AIDS test: other public"
label variable mv784k   "Place for AIDS test: private hosp/clinic/doctor"
label variable mv784l   "NA - Place for AIDS test: private VCT center"
label variable mv784m   "Place for AIDS test: pharmacy"
label variable mv784n   "NA - Place for AIDS test: mobile clinic"
label variable mv784o   "Place for AIDS test: Lesotho Planned Parenthood Association (LPPA) (CS)"
label variable mv784p   "Place for AIDS test: CHAL hospital (CS-NGO)"
label variable mv784q   "Place for AIDS test: CHAL health centre (CS-NGO)"
label variable mv784r   "Place for AIDS test: Private doctor (CS)"
label variable mv784s   "Place for AIDS test: other private"
label variable mv784t   "Place for AIDS test: Community health worker/Support groups (CS)"
label variable mv784u   "NA - Place for AIDS test: CS other"
label variable mv784v   "NA - Place for AIDS test: CS other"
label variable mv784x   "Place for AIDS test: other"
label variable mv785    "Heard about other STDs"
label variable mv793    "Paid for sex last 12 months"
label variable mv793a   "Condom used when paid for sex last 12 months"
label variable mv793b   "Condom used every time paid for sex last 12 months"
label variable mv820    "NA - Condom used at first sexual intercourse"
label variable mv822    "Wife justified to ask husband to use condom if he has STD"
label variable mv823    "Can get AIDS by witchcraft or supernatural means"
label variable mv824    "Drugs to avoid AIDS transmission to baby during pregnancy"
label variable mv825    "Would buy vegetables from vendor with AIDS"
label variable mv826    "When was last time you were tested"
label variable mv827    "Last test was on your own, offered or required"
label variable mv828    "Did get results for last test"
label variable mv829    "Place were last AIDS test was taken"
label variable mv832b   "Time since last intercourse with next to last sexual partner"
label variable mv832c   "Time since last intercourse with second to last sexual partner"
label variable mv833a   "Used condom every time had sex with last sex partner (last 12 months)"
label variable mv833b   "Used condom every time had sex with next to last sex partner (last 12 months)"
label variable mv833c   "Used condom every time had sex with second to last sex partner (last 12 months)"
label variable mv835a   "Alcohol consumption last time had sex"
label variable mv835b   "Alcohol consumption next to last time had sex"
label variable mv835c   "Alcohol consumption second to last time had sex"
label variable mv836    "Total lifetime number of sexual partners"
label variable mv837    "Heard of drugs to help infected people to live longer"
label variable mv844    "Knows someone denied health services because of AIDS last 12 months"
label variable mv845    "Knows someone denied social events because of AIDS last 12 months"
label variable mv846    "Knows someone verbally abused because of AIDS last 12 months"
label variable mv847    "People with AIDS should be ashamed of themselves"
label variable mv848    "People with AIDS should be blamed for bringing disease to community"
label variable mv849    "NA - Children 12-14 should wait for sex until marriage"
label variable mv851a   "NA - Young men should wait for sex until marriage"
label variable mv851b   "NA - Most young men wait for sex until marriage"
label variable mv851c   "NA - Unmarried sexually active men should only having sex with one partner"
label variable mv851d   "NA - Most unmarried sexually active men have only one partner"
label variable mv851e   "NA - Married men should only have sex with their wives"
label variable mv851f   "NA - Most married men only have sex with their wives"
label variable mv851g   "NA - Young women should wait for sex until marriage"
label variable mv851h   "NA - Most young women wait for sex until marriage"
label variable mv851i   "NA - Unmarried sexually active women should have only one partner"
label variable mv851j   "NA - Most unmarried sexually active women have only one partner"
label variable mv851k   "NA - Married women should only have sex with their husbands"
label variable mv851l   "NA - Most married women only have sex with their husbands"
label variable smzone   "Lesotho Ecological Zone"
label variable smlangin "Language of interview"
label variable smlangrs "Language of respondent"
label variable sminterp "Interpreter used"
label variable sm102    "Respondent's consent to BP measurement"
label variable sm102aa  "Factors that could affect BP measurement : Eaten"
label variable sm102ab  "Factors that could affect BP measurement : Had caffeinated drink"
label variable sm102ac  "Factors that could affect BP measurement : Smoked"
label variable sm102b   "Arm circumference"
label variable sm102c   "Model and cuff size"
label variable smbp1s   "1st BP measurement : Systolic"
label variable smbp1d   "1st BP measurement : Diastolic"
label variable smbp2s   "2nd BP measurement : Systolic"
label variable smbp2d   "2nd BP measurement : Diastolic"
label variable smbp3s   "3rd BP measurement : Diastolic"
label variable smbp3d   "3rd BP measurement : Systolic"
label variable smbpaves "Blood pressure Averaged : Systolic"
label variable smbpaved "Blood pressure Averaged : Diastolic"
label variable smbpref  "Blood pressure referral reading"
label variable sm109    "Highest educational level (country specific)"
label variable sm109a   "Highest educational level"
label variable sm115aa  "Type of newspaper read : Lesotho newspaper/ magazine"
label variable sm115ab  "Type of newspaper read : South African newspaper/ magazine"
label variable sm115ax  "Type of newspaper read : Other"
label variable sm116aa  "Type of radio listened to :Lesotho radio"
label variable sm116ab  "Type of radio listened to : South African radio"
label variable sm116ax  "Type of radio listened to : Other"
label variable sm117aa  "Type of television watched :Lesotho TV"
label variable sm117ab  "Type of television watched : South African TV"
label variable sm117ax  "Type of television watched : Other"
label variable sm303d   "Saw FP billboard, poster, pamphlet last month"
label variable sm308c   "Women get pregnant so should be responsible for contraception"
label variable sm308d   "Women use contraception may have problem getting pregnant"
label variable sm425ba  "Number times had sex with 1st person in last 12 months"
label variable sm425bb  "Number times had sex with 2nd person in last 12 months"
label variable sm425bc  "Number times had sex with 3rd person in last 12 months"
label variable sm425ca  "Age of 1st person"
label variable sm425cb  "Age of 2nd person"
label variable sm425cc  "Age of 3rd person"
label variable sm429ba  "Experienced any problems with using condoms : Difficult to dispose of"
label variable sm429bc  "Experienced any problems with using condoms :Difficult to put on/take off/ spoil"
label variable sm429bd  "Experienced any problems with using condoms :Diminishes pleasure"
label variable sm429be  "Experienced any problems with using condoms :Wife partner objects/does not like"
label variable sm429bg  "Experienced any problems with using condoms :Wife/partner got pregnant/ inconven"
label variable sm429bh  "Experienced any problems with using condoms :Condom broke"
label variable sm429bx  "Experienced any problems with using condoms :Other"
label variable sm429by  "Experienced any problems with using condoms :No problem"
label variable sm429ca  "Condoms diminish sexual pleasure of man"
label variable sm429cb  "Condoms are inconvenient to use"
label variable sm429cc  "Male condom can be reused"
label variable sm429cd  "Condom protects against STD's"
label variable sm429ce  "Buying condoms is embarrassing"
label variable sm429cf  "Woman has no right to ask man to use condom"
label variable sm429cg  "Male condom has AIDS virus"
label variable sm429ch  "Male condom best way to prevent unwanted pregnancy"
label variable sm429ci  "People who use condoms are not faithful"
label variable sm432a   "Ever paid for sex"
label variable sm433    "Used condom in last paid sex (CS - not restricted to sex in last 12 months)"
label variable sm443    "Used FP during last intercourse"
label variable sm603a   "Number of months worked in last 12 months"
label variable sm613f   "Decision on using contraception"
label variable sm613aa  "Person who makes decisions about health care"
label variable sm613ab  "Person who makes decisions about making major household purchases"
label variable sm613cc  "Owns this or any other house"
label variable sm613dd  "Owns house jointly or with someone else"
label variable sm613ee  "Owns this or any other land"
label variable sm613ff  "Owns land jointly or with someone else"
label variable sm615f   "NA - Beating justification: unfaithful"
label variable sm723a   "Male teacher with AIDS can continue teaching"
label variable sm741a   "Did something to avoid infecting partner"
label variable sm741b   "Infomed partner about STD"
label variable sm741ca  "Action taken to avoid infecting partner : Used medicine"
label variable sm741cb  "Action taken to avoid infecting partner : Stopped having sex"
label variable sm741cc  "Action taken to avoid infecting partner : Used condom"
label variable sm801aa  "Symptoms since aged 15 : Cough for two weeks +"
label variable sm801ab  "Symptoms since aged 15 : Fever for two weeks +"
label variable sm801ac  "Symptoms since aged 15 : Chest or back pain"
label variable sm801ad  "Symptoms since aged 15 : Coughing up blood"
label variable sm801ae  "Symptoms since aged 15 : Sweating at night"
label variable sm801c   "Sought consultation or treatment for symptoms"
label variable sm801d   "Main reason did not seek treatment"
label variable sm801e   "Source of advice or treatment for last STD"
label variable sm801f   "How soon after symptoms sought treatment"
label variable sm801g   "Told had TB during first visit by health professional"
label variable sm801h   "Given medicine to treat TB"
label variable sm801i   "How long told to take medicine"
label variable sm801j   "Went elsewhere for advice or treatment after diagnosis of TB"
label variable sm801k   "Other source for advice/treatment"
label variable sm804ba  "Signs or symptoms of TB :Coughing"
label variable sm804bb  "Signs or symptoms of TB :Coughing with sputum"
label variable sm804bc  "Signs or symptoms of TB :Coughing for several weeks"
label variable sm804bd  "Signs or symptoms of TB :Fever"
label variable sm804be  "Signs or symptoms of TB :Blood in sputum"
label variable sm804bf  "Signs or symptoms of TB :Loss of appetite"
label variable sm804bg  "Signs or symptoms of TB :Night sweating"
label variable sm804bh  "Signs or symptoms of TB :Pain in chest or back"
label variable sm804bi  "Signs or symptoms of TB :Tiredness/fatigue"
label variable sm804bj  "Signs or symptoms of TB :Weight loss"
label variable sm804bx  "Signs or symptoms of TB :Other"
label variable sm804by  "Signs or symptoms of TB :No symptoms"
label variable sm804bz  "Signs or symptoms of TB :Don't know"
label variable sm804ca  "Causes of TB :Microbes/germs/bacteria"
label variable sm804cb  "Causes of TB :Inherited"
label variable sm804cc  "Causes of TB :Lifestyle"
label variable sm804cd  "Causes of TB :Smoking"
label variable sm804ce  "Causes of TB :Alcohol drinking"
label variable sm804cf  "Causes of TB :Exposure to cold temp."
label variable sm804cg  "Causes of TB :Dust/pollution"
label variable sm804cx  "Causes of TB :Other"
label variable sm804cz  "Causes of TB :Don't know"
label variable sm804a   "Would be willing to work with someone previously treated for TB"
label variable sm805a   "Age at circumcision"
label variable sm805b   "Person who performed circumcision"
label variable sm805c   "Where circumcision was performed"
label variable sm813a   "Ever drunk alcohol"
label variable sm813b   "Number of days drank alcohol in last 3 months"
label variable sm813c   "Ever got drunk"
label variable sm813e   "Number of days got drunk in last 3 months"
label variable sm813f   "Heard of diabetes"
label variable sm813g   "Ever diagnosed with diabetes"
label variable sm813h   "Taking medication for diabetes"
label variable sm813i   "How takes medicine for diabetes"
label variable sm813j   "Ever had blood pressure checked"
label variable sm813k   "Person who checked blood pressure"
label variable sm813l   "When last had blood pressure checked"
label variable sm813m   "Ever diagnosed with high blood pressure by doctor or nurse"
label variable sm813na  "Action taken to lower BP : take medicine"
label variable sm813nb  "Action taken to lower BP : Control weight"
label variable sm813nc  "Action taken to lower BP : Cut down salt"
label variable sm813nd  "Action taken to lower BP : Exercise"
label variable sm813ne  "Action taken to lower BP : Cut down alcohol"
label variable sm813nf  "Action taken to lower BP : Stop smoking"
label variable sm813ng  "Action taken to lower BP : Traditional medicine/herbs"
label variable sm902    "Sex of last born child"
label variable sm903m   "Time of last birth (Month)"
label variable sm903y   "Time of last birth (Year)"
label variable sm904    "Child still alive"
label variable sm905    "Age at death"
label variable sm906    "Line number of mother of last born"
label variable sm908    "Relationship with last born's mother"
label variable sm910a   "Mother recieved advice or care : Pregnancy"
label variable sm910b   "Mother recieved advice or care : Delivery"
label variable sm910c   "Mother recieved advice or care : Six weeks after"
label variable sm911a   "Provider of money or  goods to pay for the care : Pregnancy"
label variable sm911b   "Provider of money or  goods to pay for the care : Delivery"
label variable sm911c   "Provider of money or  goods to pay for the care : Six weeks after"
label variable sm912a   "Reason did not receive care : Pregnancy"
label variable sm912b   "Reason did not receive care : Delivery"
label variable sm912c   "Reason did not receive care : Six weeks after"
label variable smconc1  "Point of prevalence concurrency"
label variable smconc2  "Concurrency #2"
label variable smconc3  "Concurrency #3"
label variable smconc4  "Concurrency #4"
label variable smconc5  "Concurrency #5"

#delimit ;
label define MV013   
     1 "15-19"
     2 "20-24"
     3 "25-29"
     4 "30-34"
     5 "35-39"
     6 "40-44"
     7 "45-49"
     8 "50-54"
     9 "55-59"
    10 "60-64"
;
label define MV014   
     1 "Month and year"
     2 "Month and age -y imp"
     3 "Year and age - m imp"
     4 "Y & age - y ignored"
     5 "Year - a, m imp"
     6 "Age - y, m imp"
     7 "Month - a, y imp"
     8 "None - all imp"
;
label define MV015   
     1 "Completed"
     2 "Not at home"
     3 "Postponed"
     4 "Refused"
     5 "Partly completed"
     6 "Incapacitated"
     7 "Other"
;
label define MV022   
     1 "Butha-Bothe : Rural"
     2 "Butha-Bothe : Urban"
     3 "Leribe : Rural"
     4 "Leribe : Urban"
     5 "Berea : Rural"
     6 "Berea : Urban"
     7 "Maseru : Rural"
     8 "Maseru : Urban"
     9 "Mafeteng : Rural"
    10 "Mafeteng : Urban"
    11 "Mohale's Hoek : Rural"
    12 "Mohale's Hoek : Urban"
    13 "Quthing : Rural"
    14 "Quthing : Urban"
    15 "Qacha's Nek : Rural"
    16 "Qacha's Nek : Urban"
    17 "Mokhotlong : Rural"
    18 "Mokhotlong : Urban"
    19 "Thaba Tseka : Rural"
    20 "Thaba Tseka : Urban"
;
label define MV023   
     1 "Butha-Bothe : Rural"
     2 "Butha-Bothe : Urban"
     3 "Leribe : Rural"
     4 "Leribe : Urban"
     5 "Berea : Rural"
     6 "Berea : Urban"
     7 "Maseru : Rural"
     8 "Maseru : Urban"
     9 "Mafeteng : Rural"
    10 "Mafeteng : Urban"
    11 "Mohale's Hoek : Rural"
    12 "Mohale's Hoek : Urban"
    13 "Quthing : Rural"
    14 "Quthing : Urban"
    15 "Qacha's Nek : Rural"
    16 "Qacha's Nek : Urban"
    17 "Mokhotlong : Rural"
    18 "Mokhotlong : Urban"
    19 "Thaba Tseka : Rural"
    20 "Thaba Tseka : Urban"
;
label define MV024   
     1 "Butha-bothe"
     2 "Leribe"
     3 "Berea"
     4 "Maseru"
     5 "Mafeteng"
     6 "Mohale's Hoek"
     7 "Quthing"
     8 "Qacha's-Nek"
     9 "Mokhotlong"
    10 "Thaba Tseka"
;
label define MV025   
     1 "Urban"
     2 "Rural"
;
label define MV026   
     0 "Capital, large city"
     1 "Small city"
     2 "Town"
     3 "Countryside"
;
label define MV028   
   999 "Missing"
;
label define MV029   
    99 "Missing"
;
label define MV030   
   999 "Missing"
;
label define MV031   
   999 "Missing"
;
label define MV032   
    99 "Missing"
;
label define MV034   
     0 "Wife not in HH"
;
label define MV034A  
     1 "Wife"
     2 "Partner"
;
label define MV035   
     0 "No wives/partners"
;
label define MV801   
  9999 "Missing"
;
label define MV802   
  9999 "Missing"
;
label define MV803   
    95 "95+"
    96 "2+ visits"
    97 "Inconsistent"
;
label define MV101   
     1 "Butha-bothe"
     2 "Leribe"
     3 "Berea"
     4 "Maseru"
     5 "Mafeteng"
     6 "Mohale's Hoek"
     7 "Quthing"
     8 "Qacha's-Nek"
     9 "Mokhotlong"
    10 "Thaba Tseka"
;
label define MV102   
     1 "Urban"
     2 "Rural"
;
label define MV103   
     0 "Capital, large city"
     1 "City"
     2 "Town"
     3 "Countryside"
     4 "Abroad"
;
label define MV104   
    95 "Always"
    96 "Visitor"
    97 "Inconsistent"
    98 "Don't know"
;
label define MV105   
     0 "Capital, large city"
     1 "City"
     2 "Town"
     3 "Countryside"
     4 "Abroad"
;
label define MV106   
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
;
label define MV107   
    99 "Missing"
;
label define MV130   
     1 "Roman Catholic church"
     2 "Methodist"
     3 "Lesotho Evangelical church"
     4 "Anglican Church"
     5 "Seventh Day Adventist"
     6 "Pentecostal"
     7 "Other Christian"
     8 "Islam"
     9 "Hindu"
    10 "NONE"
    96 "Other"
;
label define MV131   
    99 "Missing"
;
label define MV133   
    97 "Inconsistent"
;
label define MV134   
     0 "Capital, large city"
     1 "Small city"
     2 "Town"
     3 "Countryside"
;
label define MV135   
     1 "Usual resident"
     2 "Visitor"
;
label define MV149   
     0 "No education"
     1 "Incomplete primary"
     2 "Complete primary"
     3 "Incomplete secondary"
     4 "Complete secondary"
     5 "Higher"
;
label define MV150   
     1 "Head"
     2 "Wife or husband"
     3 "Son/daughter"
     4 "Son/daughter-in-law"
     5 "Grandchild"
     6 "Parent"
     7 "Parent-in-law"
     8 "Brother/sister"
    10 "Other relative"
    11 "Adopted/foster child"
    12 "Not related"
    15 "Domestic employee (CS)"
    16 "Herdboy (CS)"
    98 "DK"
;
label define MV151   
     1 "Male"
     2 "Female"
;
label define MV152   
    97 "97+"
    98 "DK"
;
label define MV155   
     0 "Cannot read at all"
     1 "Able to read only parts of sentence"
     2 "Able to read whole sentence"
     3 "No card with required language"
     4 "Blind/visually impaired"
;
label define MV156   
     0 "No"
     1 "Yes"
;
label define MV157   
     0 "Not at all"
     1 "Less than once a week"
     2 "At least once a week"
     3 "Almost every day"
;
label define MV158   
     0 "Not at all"
     1 "Less than once a week"
     2 "At least once a week"
     3 "Almost every day"
;
label define MV159   
     0 "Not at all"
     1 "Less than once a week"
     2 "At least once a week"
     3 "Almost every day"
;
label define MV167   
    97 "Inconsistent"
    98 "DK"
;
label define MV168   
     0 "No"
     1 "Yes"
;
label define MV190   
     1 "Poorest"
     2 "Poorer"
     3 "Middle"
     4 "Richer"
     5 "Richest"
;
label define MV212   
    99 "Missing"
;
label define MV213   
     0 "No"
     1 "Yes"
     8 "Unsure"
;
label define MV217   
     1 "During her period"
     2 "After period ended"
     3 "Middle of the cycle"
     4 "Before period begins"
     5 "At any time"
     6 "Other"
     8 "Don't know"
;
label define MV225   
     1 "Then"
     2 "Later"
     3 "Not at all"
;
label define MV245   
    99 "Missing"
;
label define MV246   
     0 "No"
     1 "Yes"
;
label define MV247   
    99 "Missing"
;
label define MV248   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define MV249   
     0 "Not present"
     1 "Present"
;
label define MV250   
     1 "Hospital, health facility"
     2 "Other"
;
label define MV251   
     1 "Cost too much"
     2 "Facility closed"
     3 "Too far/no transportation"
     4 "Don't trust facility/poor quality service"
     5 "No female provider"
     6 "Not the first child"
     7 "Mother did not think necessary"
     8 "Respondent did not think necessary"
     9 "Family did not think necessary"
    96 "Other"
    98 "DK"
;
label define MV252   
     0 "Nothing to drink"
     2 "Less than usual/much less"
     3 "Somewhat less"
     4 "About the same"
     5 "More"
     8 "Don't know"
;
label define MV301   
     0 "Knows no method"
     1 "Knows only folkloric"
     2 "Knows only trad. mth"
     3 "Knows modern method"
;
label define MV302   
     0 "Never used"
     1 "Used only folkloric"
     2 "Used only trad. meth"
     3 "Used modern method"
;
label define M304A   
     1 "Modern method"
     2 "Traditional method"
     3 "Folkloric method"
;
label define MV304   
     0 "No"
     1 "Yes"
     7 "Not in contraception table, but as a current method"
     8 "Not asked"
;
label define MV305   
     0 "No"
     1 "Yes"
;
label define MV307   
     0 "No"
     1 "Yes"
;
label define MV312   
     0 "Not using"
     1 "Pill"
     2 "IUD"
     3 "Injections"
     4 "Diaphragm"
     5 "Condom"
     6 "Female Sterilization"
     7 "Male Sterilization"
     8 "Periodic Abstinence"
     9 "Withdrawal"
    10 "Other"
    11 "Norplant"
    12 "Abstinence"
    13 "Lactational amenorrhea"
    14 "Female condom"
    15 "Foam or jelly"
    17 "Specific method 1"
    18 "Specific method 2"
    19 "Specific method 3"
    20 "Specific method 4"
    98 "Don't know"
;
label define MV313   
     0 "No method"
     1 "Folkloric method"
     2 "Traditional method"
     3 "Modern method"
     8 "Don't know"
;
label define MV323A  
    98 "Don't know"
;
label define MV325B  
9999995 "Free"
9999998 "Don't know"
;
label define MV372A  
     0 "Package not seen"
     1 "Package seen"
;
label define MV384A  
     0 "No"
     1 "Yes"
;
label define MV384B  
     0 "No"
     1 "Yes"
;
label define MV384C  
     0 "No"
     1 "Yes"
;
label define MV395   
     0 "No"
     1 "Yes"
     2 "Depends"
     8 "DK"
;
label define MV396   
     0 "No"
     1 "Yes"
     2 "Depends"
     8 "DK"
;
label define MV3A09B 
   998 "Don't know"
;
label define MV3B17  
    10 "PUBLIC SECTOR"
    11 "Government hospital"
    12 "Government health center"
    13 "FP clinic"
    14 "Mobile clinic"
    15 "Field worker"
    16 "Other public"
    20 "PRIVATE MEDICAL SECTOR"
    21 "Private hospital, clinic"
    22 "Pharmacy"
    23 "Private doctor"
    24 "Mobile clinic"
    25 "Field worker"
    26 "Other private medical"
    30 "OTHER SOURCE"
    31 "Shop"
    32 "Church"
    33 "Friend, relative"
    34 "School"
    96 "OTHER"
;
label define MV3B25A 
     0 "Disagree"
     1 "Agree"
     8 "DK"
;
label define MV3B25B 
     0 "Disagree"
     1 "Agree"
     8 "DK"
;
label define MV463A  
     0 "No"
     1 "Yes"
;
label define MV463B  
     0 "No"
     1 "Yes"
;
label define MV463C  
     0 "No"
     1 "Yes"
;
label define MV463D  
     0 "No"
     1 "Yes"
;
label define MV463E  
     0 "No"
     1 "Yes"
;
label define MV463F  
     0 "No"
     1 "Yes"
;
label define MV463G  
     0 "No"
     1 "Yes"
;
label define MV463X  
     0 "No"
     1 "Yes"
;
label define MV463Z  
     0 "No"
     1 "Yes, smokes nothing"
;
label define MV464   
    99 "Missing"
;
label define MV474   
     0 "No"
     1 "Yes"
;
label define MV474A  
     0 "No"
     1 "Yes"
;
label define MV474B  
     0 "No"
     1 "Yes"
;
label define MV474C  
     0 "No"
     1 "Yes"
;
label define MV474D  
     0 "No"
     1 "Yes"
;
label define MV474E  
     0 "No"
     1 "Yes"
;
label define MV474F  
     0 "No"
     1 "Yes"
;
label define MV474G  
     0 "No"
     1 "Yes"
;
label define MV474H  
     0 "No"
     1 "Yes"
;
label define MV474I  
     0 "No"
     1 "Yes"
;
label define MV474J  
     0 "No"
     1 "Yes"
;
label define MV474X  
     0 "No"
     1 "Yes"
;
label define MV474Z  
     0 "No"
     1 "Yes"
;
label define MV475   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV476   
     0 "No"
     1 "Yes, remain a secret"
     8 "Don't know / not sure / depends"
;
label define MV477   
     0 "None"
    90 "90+"
    98 "Don't know"
;
label define MV478   
     0 "None"
    90 "90+"
    98 "Don't know"
;
label define MV479   
    10 "PUBLIC SECTOR"
    11 "Government hospital"
    12 "Government health center"
    13 "CHAL hospital"
    14 "CHAL Health Center"
    16 "Other public"
    20 "PRIVATE MEDICAL"
    21 "Private hospital/clinic/doctor"
    22 "Pharmacy"
    23 "Private Doctor"
    26 "Other private medical"
    30 "OTHERS NON-MEDICAL"
    31 "Other place at home"
    96 "Other"
;
label define MV480   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV481   
     0 "No"
     1 "Yes"
;
label define MV481A  
     0 "No"
     1 "Yes"
;
label define MV481B  
     0 "No"
     1 "Yes"
;
label define MV481C  
     0 "No"
     1 "Yes"
;
label define MV481D  
     0 "No"
     1 "Yes"
;
label define MV481E  
     0 "No"
     1 "Yes"
;
label define MV481F  
     0 "No"
     1 "Yes"
;
label define MV481G  
     0 "No"
     1 "Yes"
;
label define MV481H  
     0 "No"
     1 "Yes"
;
label define MV481X  
     0 "No"
     1 "Yes"
;
label define MV482A  
     0 "No"
     1 "Yes"
     8 "Unsure"
;
label define MV482B  
     0 "No"
     1 "Yes"
;
label define MV482C  
     0 "No"
     1 "Yes"
     8 "Unsure"
;
label define MV483   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV501   
     0 "Never married"
     1 "Married"
     2 "Living together"
     3 "Widowed"
     4 "Divorced"
     5 "Not living together"
;
label define MV502   
     0 "Never married"
     1 "Currently married"
     2 "Formerly married"
;
label define MV503   
     1 "Once"
     2 "More than once"
;
label define MV504   
     1 "Living with him"
     2 "Staying elsewhere"
;
label define MV505   
    99 "Missing"
;
label define MV510   
     1 "Month and year"
     2 "Month and age -y imp"
     3 "Year and age - m imp"
     5 "Year - a, m imp"
     6 "Age - y, m imp"
     7 "Month - a, y imp"
     8 "None - all imp"
;
label define MV513   
     0 "Never married"
     1 "0-4"
     2 "5-9"
     3 "10-14"
     4 "15-19"
     5 "20-24"
     6 "25-29"
     7 "30+"
;
label define MV525   
     0 "Not had intercourse"
    96 "At first union"
    97 "Inconsistent"
    98 "Don't know"
;
label define MV527   
   100 "<1 day ago"
   101 "Days: 1"
   201 "Weeks: 1"
   301 "Months: 1"
   401 "Years: 1"
   995 "Within last 4 weeks"
   996 "Before last birth"
   997 "Inconsistent"
   998 "Don't know"
;
label define MV528   
    31 "31+ days"
    95 "Within last 4 weeks"
    96 "Before last birth"
    97 "Inconsistent"
    98 "Don't know"
;
label define MV529   
   995 "Within last 4 weeks"
   996 "Before last birth"
   997 "Inconsistent"
   998 "Don't know"
;
label define MV531   
     0 "Not had intercourse"
    97 "Inconsistent"
    98 "Don't know"
;
label define MV532   
     0 "No flag"
     1 "After interview"
     2 "After concep >= 1 yr"
     3 "After concep < 1 yr"
     4 "At marr, never marr"
     5 "At marr,after concep"
     6 "After marriage"
;
label define MV535   
     0 "No"
     1 "Formerly married"
     2 "Lived with a woman"
     3 "Both, formerly married and lived with a woman"
;
label define MV536   
     0 "Never had intercourse"
     1 "Active in last 4 weeks"
     3 "Not active in last 4 weeks"
;
label define MV541   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV602   
     1 "Have another"
     2 "Undecided"
     3 "No more"
     4 "Sterilized"
     5 "Couple/wife declared infecund"
     6 "Never had sex"
     7 "Man declared infecund"
     8 "Man has no partner"
;
label define MV603   
   100 "Zero Months"
   200 "Zero Years"
   993 "After marriage"
   994 "Soon, now"
   996 "Other, Non-numeric"
   997 "Inconsistent"
   998 "Don't know"
;
label define MV604   
     0 "<12 months"
     1 "1 year"
     2 "2 years"
     3 "3 years"
     4 "4 years"
     5 "5 years"
     6 "6+ years"
     7 "Non-numeric"
     8 "Don't know"
;
label define MV605   
     1 "Wants within 2 years"
     2 "Wants after 2+ years"
     3 "Wants, unsure timing"
     4 "Undecided"
     5 "Wants no more"
     6 "Sterilized"
     7 "Declared infecund"
     8 "Never had sex"
;
label define MV613   
    96 "Non-numeric response"
    98 "DK"
;
label define MV614   
     6 "6+"
     7 "Non-numeric response"
;
label define MV616   
   100 "0 Months"
   200 "0 Years"
   993 "After marriage"
   994 "Soon/now"
   995 "Can't get pregnant"
   996 "Other"
   998 "DK"
;
label define MV621   
     1 "Both want same"
     2 "Wife wants more"
     3 "Wife wants fewer"
     8 "DK"
;
label define MV627   
    96 "Other"
    98 "DK"
;
label define MV628   
    96 "Other"
    98 "DK"
;
label define MV629   
    96 "Other"
    98 "DK"
;
label define MV631   
     1 "Big problem"
     2 "Small problem"
     3 "No problem"
     4 "Says she can't get pregnant /not having sex"
;
label define MV633A  
     0 "No"
     1 "Yes"
     8 "DK"
;
label define MV633B  
     0 "No"
     1 "Yes"
     8 "DK"
;
label define MV633C  
     0 "No"
     1 "Yes"
     8 "DK"
;
label define MV633D  
     0 "No"
     1 "Yes"
     8 "DK"
;
label define MV633E  
     0 "No"
     1 "Yes"
     8 "DK"
;
label define MV633F  
     0 "No"
     1 "Yes"
     8 "DK"
;
label define MV633G  
     0 "No"
     1 "Yes"
     8 "DK"
;
label define MV634A  
     0 "No"
     1 "Yes"
     8 "DK, Depends"
;
label define MV634B  
     0 "No"
     1 "Yes"
     8 "DK, Depends"
;
label define MV634C  
     0 "No"
     1 "Yes"
     8 "DK, Depends"
;
label define MV634D  
     0 "No"
     1 "Yes"
     8 "DK, Depends"
;
label define MV714   
     0 "No"
     1 "Yes"
;
label define MV714A  
     0 "No"
     1 "Yes"
;
label define MV716   
     0 "Not working"
     1 "[1110]Legislators and senior government officials"
     2 "[1141]Senior officials of political party organisations"
     3 "[1142]Senior officials of employers,worker and other"
     4 "[1210]Directors and chief executives"
     5 "[1213]Finance and administration managers"
     6 "[1225]Production and operations managers in restaurants and hotels"
     7 "[1228]Production and operations managers in personal care, cleaning and related services"
     8 "[1229]Production and operations managers not  elsewhere classified"
     9 "[1231]Finance and administration managers"
    10 "[1232]Personnel and Industrial relations managers"
    11 "[1235]Supply and distribution manager"
    12 "[1239]Other specialist managers not elsewhere classified"
    13 "[1311]Managers of small enterprises in agriculture,hunting,forestry and fishing"
    14 "[1314]Managers of small enterprises in wholesale and retail trade"
    15 "[1316]Managers of small enterprises in transport,storage and communications"
    16 "[1317]Managers of small enterprises of business services enterprises"
    17 "[1319]Managers of small enterprises not elsewhere classified"
    18 "[2112]Meteorologists"
    19 "[2131]Computer system designers,analysts and programmers"
    20 "[2139]Other specialist managers not elsewhere classified"
    21 "[2141]Architects, town and traffic planners"
    22 "[2142]Civil engineers"
    23 "[2145]Mechanical engineers"
    24 "[2147]Mining engineers, metallurgists and related professionals"
    25 "[2148]Cartographers and surveyors"
    26 "[2149]Architects,engineers and related professionals not elsewhere classified"
    27 "[2221]Medical doctors"
    28 "[2222]Dentists"
    29 "[2229]Health professionals (except nursing) not elsewhere classified"
    30 "[2230]Nursing and midwifery professionals"
    31 "[2310]College, university and higher education teaching professionals."
    32 "[2320]Secondary education teaching professionals"
    33 "[2331]Primary education teaching professionals"
    34 "[2351]Education methods specialists"
    35 "[2359]Other teaching professionals not elsewhere classified"
    36 "[2411]Accountant"
    37 "[2412]Personnel and careers professionals"
    38 "[2421]Lawyers"
    39 "[2422]Judges"
    40 "[2429]Legal professionals not elsewhere classified"
    41 "[2432]Librarians and related information professional"
    42 "[2446]Social work professionals"
    43 "[2451]Author,journalists and other writers"
    44 "[2453]Composers,musicians and singers"
    45 "[2455]Film,stage and related actors and directors"
    46 "[2460]Religious professionals"
    47 "[2470]Public service administrative professional"
    48 "[3113]Electrical engineering technicians"
    49 "[3115]Mechanical engineering technicians"
    50 "[3119]Physical and engineering science technicians not elsewhere classified"
    51 "[3131]Photographers and image and sound recording equipment operators"
    52 "[3132]Broadcasting and telecommunications equipment operators"
    53 "[3152]Safety,health and quality inspectors"
    54 "[3213]Farming and forestry advisers"
    55 "[3221]Medical assistants"
    56 "[3222]Hygienists,health and environmental officers"
    57 "[3223]Dieticians and nutritionists"
    58 "[3227]Veterinary assistants"
    59 "[3229]Health associate professionals (except nursing) not elsewhere classified"
    60 "[3231]Nursing associate professionals"
    61 "[3232]Midwifery associate professionals"
    62 "[3320]Pre-primary education teaching associate professionals"
    63 "[3330]Special education teaching associate professionals"
    64 "[3340]Other teaching associate professionals"
    65 "[3340]Other teaching associate professionals"
    66 "[3411]Securities and finance dealers and brokers"
    67 "[3412]Insurance representatives"
    68 "[3414]Travel consultants and organisers"
    69 "[3421]Trade brokers"
    70 "[3429]Business services agents and trade broker not elsewhere classified"
    71 "[3431]Administrative secretaries and related associate professions"
    72 "[3433]Bookkeepers"
    73 "[3434]Statistical, mathematical and related associate professionals"
    74 "[3441]Customs and border inspectors"
    75 "[3449]Customs, tax and related government associate professionals not elsewhere classified"
    76 "[3450]Police inspectors and detectives"
    77 "[3460]Social work associate professionals"
    78 "[3470]Artists,entertainment and sports associate professionals"
    79 "[3471]Decorators and commercial designer"
    80 "[3473]Street ,night-club and related musicians,singers and dancers"
    81 "[3474]Trade brokers"
    82 "[4111]Stenographers and typists"
    83 "[4112]Word-processors and related operators"
    84 "[4113]Data entry operators"
    85 "[4115]Secretaries"
    86 "[4121]Accounting & Book-keeping Clerks"
    87 "[4122]Statistical and finance clerks"
    88 "[4131]Stock clerks"
    89 "[4132]Production clerks"
    90 "[4190]Other office clerks"
    91 "[4211]Cashiers and tickets clerks"
    92 "[4212]Tellers and other counter clerks"
    93 "[4213]Pawnbrokers and money-lenders"
    94 "[4214]Pawnbrokers and money-lenders"
    95 "[4221]Travel agency and related clerks"
    96 "[4222]Receptionists and information clerk"
    97 "[4223]Telephone switchboard operators"
    98 "[5111]Travel attendants and travel stewards"
    99 "[5122]Cooks"
   100 "[5123]Waiters, waitresses and bartenders"
   101 "[5131]Child-care workers"
   102 "[5132]Institution-based personal care workers"
   103 "[5133]Home-based personal care workers"
   104 "[5141]Hairdressers, barbers, beauticians and related workers"
   105 "[5143]Undertakers and embalmers"
   106 "[5161]Fire-fighters"
   107 "[5162]Police officers"
   108 "[5163]Prison guards"
   109 "[5169]Protective services workers not elsewhere classified"
   110 "[5210]Fashion and other models"
   111 "[5220]Shops, stall and market salespersons and demonstrators"
   112 "[6111]Farm-hands and labourers"
   113 "[6112]Gardeners, horticultural and nursery growers"
   114 "[6121]Dairy and livestock producers"
   115 "[6122]Poultry producers"
   116 "[6122]Gardeners, horticultural and nursery growers"
   117 "[6122]Poultry producers"
   118 "[6129]Animal producers and related workers not elsewhere classified"
   119 "[6130]Crop and animal producers"
   120 "[6141]Forestry workers and loggers"
   121 "[6151]Aquatic life cultivation worker"
   122 "[7000]Craft  and related worker"
   123 "[7100]Craft  and related worker"
   124 "[7111]Miners and quarry workers"
   125 "[7113]Stone splitters, cutters and carvers"
   126 "[7121]Builders"
   127 "[7122]Bricklayers and stonemasons"
   128 "[7124]Carpenters and joiners"
   129 "[7129]Building frame and related trades workers not elsewhere classified"
   130 "[7131]Roofers"
   131 "[7132]Floor layers and tile setters"
   132 "[7133]Plasterers"
   133 "[7133]Tailors, dressmakers and hatters"
   134 "[7136]Plumbers and pipe fitters"
   135 "[7139]Building finishers and related trade works elsewhere classified"
   136 "[7141]Painters and related workers"
   137 "[7143]Building structure cleaners"
   138 "[7211]Metal moulders and coremakers"
   139 "[7212]Welders and flame cutters"
   140 "[7231]Motor vehicle machine and fitters"
   141 "[7233]Agricultural-industrial -machinery mechanics and fitters"
   142 "[7241]Electrical mechanics fitters and services"
   143 "[7244]Telegraph and telephone installers and services"
   144 "[7245]Electrical line installers;[repairer and cable jointers"
   145 "[7312]Musical-instrument makers and tuners"
   146 "[7321]Abrasive wheel formers, potters and related workers"
   147 "[7324]Glass,ceramic and related decorative painters"
   148 "[7331]Handicraft workers in wood and related materials"
   149 "[7341] compositors, typesetters and related workers"
   150 "[7343]Abrasive wheel formers, potters and related workers"
   151 "[7344]Photographic and related workers"
   152 "[7411]Butchers,fishmongers"
   153 "[7411]Butchers, fishmongers and related food preparers"
   154 "[7412]Bakers, pastry-cooks and confectionery makers"
   155 "[7415]Food and beverage testers and graders"
   156 "[7416]Tobacco preparers and tobacco product makers"
   157 "[7424]Basketry weavers, brush makers and related workers"
   158 "[7432]Weavers,knitters and related workers"
   159 "[7433]Tailors, dressmakers and hatters"
   160 "[7436]Sewers, embroiderers and related workers"
   161 "[7442]Shoe-makers and related workers"
   162 "[8111]Mining plant operators"
   163 "[8112]Mineral-ore and stone-processing--plant operators"
   164 "[8113]Well drillers and borers and related workers"
   165 "[8139]Glass,ceramic and related plant operator not elsewhere classified"
   166 "[8163]Incinerator, water-treatment and related plant operators"
   167 "[8263]Sewing-machine operators"
   168 "[8273]Production clerks"
   169 "[8278]Brewers, wine and other beverage machine operators"
   170 "[8281]Mechanical-machinery assemblers"
   171 "[8290]Other machine operators not elsewhere classified"
   172 "[8300]Motor vehicle drivers"
   173 "[8311]Locomotive engine drivers"
   174 "[8312]Railway brakers, signallers and shunters"
   175 "[8321]Motorcycle drivers"
   176 "[8322]Car, taxi and van drivers"
   177 "[8323]Bus and tram drivers"
   178 "[8324]Commercial vehicle drivers"
   179 "[8333]Crane,hoist and related plant operator"
   180 "[8334]Lifting-truck operators"
   181 "[8340]Ship' deck crew and related workers"
   182 "[8549]Paralegal training"
   183 "[9111]Street vendors"
   184 "[9113]Door-to-door and telephone salespersons"
   185 "[9120]Shoe cleaning and other street services elementary occupations"
   186 "[9131]Domestic helpers and cleaners"
   187 "[9132]Helpers and cleaners in offices,hotels and other establishments"
   188 "[9133]Domestic helpers and cleaners"
   189 "[9141]Building caretakers"
   190 "[9142]Vehicle ,window and related cleaners"
   191 "[9151]Messengers, package and luggage porters and deliverers"
   192 "[9152]Doorkeepers, watchpersons and related workers"
   193 "[9153]Vending-machine money collectors,meter readers and related workers"
   194 "[9153]Vending-machine money collectors,meter readers and related workers"
   195 "[9153]Vending-machine money collectors, meter readers and related workers"
   196 "[9161]Garbage collectors"
   197 "[9162]Sweepers and related labourers"
   198 "[9211]Farm-hands and labourers"
   199 "[9212]Forestry labourers"
   200 "[9311]Mining and quarrying labourers"
   201 "[9312]Construction and maintenance labourers: roads, dams and similar constructions"
   202 "[9313]Building construction labourers"
   203 "[9320]Manufacturing labourers"
   204 "[9330]Transport labourers and freight handlers"
   996 "[9996]Other occupation"
;
label define MV717   
     0 "Not working"
     1 "Prof., Tech., Manag."
     2 "Clerical"
     3 "Sales"
     4 "Agric-self employed"
     5 "Agric-employee"
     6 "Household & domestic"
     7 "Services"
     8 "Skilled manual"
     9 "Unskilled manual"
    98 "Don't know"
;
label define MV719   
     1 "For family member"
     2 "For someone else"
     3 "Self-employed"
;
label define MV721   
     1 "At home"
     2 "Away"
;
label define MV731   
     0 "No"
     1 "In the past year"
     2 "Currently working"
;
label define MV732   
     1 "All year"
     2 "Seasonal"
     3 "Occasional"
;
label define MV739   
     1 "Respondent alone"
     2 "Respondent and wife/partner"
     3 "Respondent and other person"
     4 "Wife/partner alone"
     5 "Someone else"
;
label define MV740   
     0 "Own land"
     1 "Family land"
     2 "Someone else's land"
     3 "Rented land"
     8 "Don't know"
;
label define MV741   
     0 "Not paid"
     1 "Cash only"
     2 "Cash and kind"
     3 "In kind only"
;
label define MV743A  
     1 "Husband"
     2 "Both equally"
     3 "Respondent and other person"
     4 "Wife"
     5 "Someone else"
     6 "Decision not made/not applicable"
     8 "DK/depends"
;
label define MV743B  
     1 "Husband"
     2 "Both equally"
     3 "Respondent and other person"
     4 "Wife"
     5 "Someone else"
     6 "Decision not made/not applicable"
     8 "DK/depends"
;
label define MV743C  
     1 "Husband"
     2 "Both equally"
     3 "Respondent and other person"
     4 "Wife"
     5 "Someone else"
     6 "Decision not made/not applicable"
     8 "DK/depends"
;
label define MV743D  
     1 "Husband"
     2 "Both equally"
     3 "Respondent and other person"
     4 "Wife"
     5 "Someone else"
     6 "Decision not made/not applicable"
     8 "DK/depends"
;
label define MV743E  
     1 "Husband"
     2 "Both equally"
     3 "Respondent and other person"
     4 "Wife"
     5 "Someone else"
     6 "Decision not made/not applicable"
     8 "DK/depends"
;
label define MV743F  
     1 "Husband"
     2 "Both equally"
     3 "Respondent and other person"
     4 "Wife"
     5 "Someone else"
     6 "Decision not made/not applicable"
     8 "DK/depends"
;
label define MV743G  
     1 "Husband"
     2 "Both equally"
     3 "Respondent and other person"
     4 "Wife"
     5 "Someone else"
     6 "Decision not made/not applicable"
     8 "DK/depends"
;
label define MV744A  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV744B  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV744C  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV744D  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV744E  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV747A  
     0 "Disagree"
     1 "Agree"
     8 "Don't know"
;
label define MV747B  
     0 "Disagree"
     1 "Agree"
     8 "Don't know"
;
label define MV750   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define MV751   
     0 "No"
     1 "Yes"
;
label define MV754BP 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV754CP 
     0 "No"
     1 "Reduce chances of AIDS by always using condoms during sex"
     8 "Don't know"
;
label define MV754DP 
     0 "No"
     1 "Reduce chance of AIDS: have 1 sex partner with no oth partner"
     8 "Don't know"
;
label define MV754JP 
     0 "No"
     1 "Get AIDS from mosquito bites"
     8 "Don't know"
;
label define MV754WP 
     0 "No"
     1 "Get AIDS by sharing food with person who has AIDS"
     8 "Don't know"
;
label define MV756   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define MV761   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define MV761B  
     0 "No"
     1 "Yes"
     8 "DK"
;
label define MV761C  
     0 "No"
     1 "Yes"
     8 "DK"
;
label define MV762AA 
     0 "No"
     1 "Yes"
;
label define MV762AB 
     0 "No"
     1 "Yes"
;
label define MV762AC 
     0 "No"
     1 "Yes"
;
label define MV762AD 
     0 "No"
     1 "Yes"
;
label define MV762AE 
     0 "No"
     1 "Yes"
;
label define MV762AF 
     0 "No"
     1 "Yes"
;
label define MV762AG 
     0 "No"
     1 "Yes"
;
label define MV762AH 
     0 "No"
     1 "Yes"
;
label define MV762AI 
     0 "No"
     1 "Yes"
;
label define MV762AJ 
     0 "No"
     1 "Yes"
;
label define MV762AK 
     0 "No"
     1 "Yes"
;
label define MV762AL 
     0 "No"
     1 "Yes"
;
label define MV762AM 
     0 "No"
     1 "Yes"
;
label define MV762AN 
     0 "No"
     1 "Yes"
;
label define MV762AO 
     0 "No"
     1 "Yes"
;
label define MV762AP 
     0 "No"
     1 "Yes"
;
label define MV762AQ 
     0 "No"
     1 "Yes"
;
label define MV762AR 
     0 "No"
     1 "Yes"
;
label define MV762AS 
     0 "No"
     1 "Yes"
;
label define MV762AT 
     0 "No"
     1 "Yes"
;
label define MV762AU 
     0 "No"
     1 "Yes"
;
label define MV762AV 
     0 "No"
     1 "Yes"
;
label define MV762AW 
     0 "No"
     1 "Yes"
;
label define MV762AX 
     0 "No"
     1 "Yes"
;
label define MV762AZ 
     0 "No: source known"
     1 "Yes: no source known"
;
label define MV762BA 
     0 "No"
     1 "Yes"
;
label define MV762BB 
     0 "No"
     1 "Yes"
;
label define MV762BC 
     0 "No"
     1 "Yes"
;
label define MV762BD 
     0 "No"
     1 "Yes"
;
label define MV762BE 
     0 "No"
     1 "Yes"
;
label define MV762BF 
     0 "No"
     1 "Yes"
;
label define MV762BG 
     0 "No"
     1 "Yes"
;
label define MV762BH 
     0 "No"
     1 "Yes"
;
label define MV762BI 
     0 "No"
     1 "Yes"
;
label define MV762BJ 
     0 "No"
     1 "Yes"
;
label define MV762BK 
     0 "No"
     1 "Yes"
;
label define MV762BL 
     0 "No"
     1 "Yes"
;
label define MV762BM 
     0 "No"
     1 "Yes"
;
label define MV762BN 
     0 "No"
     1 "Yes"
;
label define MV762BO 
     0 "No"
     1 "Yes"
;
label define MV762BP 
     0 "No"
     1 "Yes"
;
label define MV762BQ 
     0 "No"
     1 "Yes"
;
label define MV762BR 
     0 "No"
     1 "Yes"
;
label define MV762BS 
     0 "No"
     1 "Yes"
;
label define MV762BT 
     0 "No"
     1 "Yes"
;
label define MV762BU 
     0 "No"
     1 "Yes"
;
label define MV762BV 
     0 "No"
     1 "Yes"
;
label define MV762BW 
     0 "No"
     1 "Yes"
;
label define MV762BX 
     0 "No"
     1 "Yes"
;
label define MV762BZ 
     0 "No: source known"
     1 "Yes: no source known"
;
label define MV763A  
     0 "No"
     1 "Yes"
     8 "DK"
;
label define MV763B  
     0 "No"
     1 "Yes"
     8 "DK"
;
label define MV763C  
     0 "No"
     1 "Yes"
     8 "DK"
;
label define MV763D  
     0 "No"
     1 "Country specific"
     8 "DK"
;
label define MV763E  
     0 "No"
     1 "Country specific"
     8 "DK"
;
label define MV763F  
     0 "No"
     1 "Country specific"
     8 "DK"
;
label define MV763G  
     0 "No"
     1 "Country specific"
     8 "DK"
;
label define MV766A  
    98 "DK"
;
label define MV766B  
    98 "DK"
;
label define MV767A  
     1 "Spouse"
     2 "Girlfriend/fiancee"
     3 "Other friend"
     4 "Casual acquaintance"
     5 "Relative"
     6 "Commercial sex worker"
     7 "Live-in partner"
    96 "Other"
;
label define MV767B  
     1 "Spouse"
     2 "Girlfriend/fiancee"
     3 "Other friend"
     4 "Casual acquaintance"
     5 "Relative"
     6 "Commercial sex worker"
     7 "Live-in partner"
    96 "Other"
;
label define MV767C  
     1 "Spouse"
     2 "Girlfriend/fiancee"
     3 "Other friend"
     4 "Casual acquaintance"
     5 "Relative"
     6 "Commercial sex worker"
     7 "Live-in partner"
    96 "Other"
;
label define MV768A  
   100 "Same day"
   101 "One day"
   201 "One month"
   301 "One year"
;
label define MV768B  
   100 "Same day"
   101 "One day"
   201 "One month"
   301 "One year"
;
label define MV768C  
   100 "Same day"
   101 "One day"
   201 "One month"
   301 "One year"
;
label define MV769   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define MV769A  
     0 "No"
     1 "Yes"
     8 "DK"
;
label define MV770   
     0 "No"
     1 "Yes"
;
label define MV770A  
     0 "No"
     1 "Yes"
;
label define MV770B  
     0 "No"
     1 "Yes"
;
label define MV770C  
     0 "No"
     1 "Yes"
;
label define MV770D  
     0 "No"
     1 "Yes"
;
label define MV770E  
     0 "No"
     1 "Yes"
;
label define MV770F  
     0 "No"
     1 "Yes"
;
label define MV770G  
     0 "No"
     1 "Yes"
;
label define MV770H  
     0 "No"
     1 "Yes"
;
label define MV770I  
     0 "No"
     1 "Yes"
;
label define MV770J  
     0 "No"
     1 "Yes"
;
label define MV770K  
     0 "No"
     1 "Yes"
;
label define MV770L  
     0 "No"
     1 "Yes"
;
label define MV770M  
     0 "No"
     1 "Yes"
;
label define MV770N  
     0 "No"
     1 "Yes"
;
label define MV770O  
     0 "No"
     1 "Yes"
;
label define MV770P  
     0 "No"
     1 "Yes"
;
label define MV770Q  
     0 "No"
     1 "Yes"
;
label define MV770R  
     0 "No"
     1 "Yes"
;
label define MV770S  
     0 "No"
     1 "Yes"
;
label define MV770T  
     0 "No"
     1 "Yes"
;
label define MV770U  
     0 "No"
     1 "Yes"
;
label define MV770V  
     0 "No"
     1 "Yes"
;
label define MV770W  
     0 "No"
     1 "Yes"
;
label define MV770X  
     0 "No"
     1 "Yes"
;
label define MV774A  
     0 "No"
     1 "Yes"
     8 "DK"
;
label define MV774B  
     0 "No"
     1 "Yes"
     8 "DK"
;
label define MV774C  
     0 "No"
     1 "Yes"
     8 "DK"
;
label define MV775   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define MV777   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define MV778   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define MV779   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define MV780   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define MV781   
     0 "No"
     1 "Yes"
;
label define MV783   
     0 "No"
     1 "Yes"
;
label define MV784A  
     0 "No"
     1 "Yes"
;
label define MV784B  
     0 "No"
     1 "Yes"
;
label define MV784C  
     0 "No"
     1 "Yes"
;
label define MV784D  
     0 "No"
     1 "Yes"
;
label define MV784E  
     0 "No"
     1 "Yes"
;
label define MV784F  
     0 "No"
     1 "Yes"
;
label define MV784G  
     0 "No"
     1 "Yes"
;
label define MV784H  
     0 "No"
     1 "Yes"
;
label define MV784I  
     0 "No"
     1 "Yes"
;
label define MV784J  
     0 "No"
     1 "Yes"
;
label define MV784K  
     0 "No"
     1 "Yes"
;
label define MV784L  
     0 "No"
     1 "Yes"
;
label define MV784M  
     0 "No"
     1 "Yes"
;
label define MV784N  
     0 "No"
     1 "Yes"
;
label define MV784O  
     0 "No"
     1 "Yes"
;
label define MV784P  
     0 "No"
     1 "Yes"
;
label define MV784Q  
     0 "No"
     1 "Yes"
;
label define MV784R  
     0 "No"
     1 "Yes"
;
label define MV784S  
     0 "No"
     1 "Yes"
;
label define MV784T  
     0 "No"
     1 "Yes"
;
label define MV784U  
     0 "No"
     1 "Yes"
;
label define MV784V  
     0 "No"
     1 "Yes"
;
label define MV784X  
     0 "No"
     1 "Yes"
;
label define MV785   
     0 "No"
     1 "Yes"
;
label define MV793   
     0 "No"
     1 "Yes"
;
label define MV793A  
     0 "No"
     1 "Yes"
;
label define MV793B  
     0 "No"
     1 "Yes"
;
label define MV820   
     0 "No"
     1 "Yes"
;
label define MV822   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV823   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV824   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV825   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV826   
     1 "Less than 12 months"
     2 "12-23 months"
     3 "2 years or more"
;
label define MV827   
     1 "Asked for the test"
     2 "Offered and accepted"
     3 "Required"
;
label define MV828   
     0 "No"
     1 "Yes"
;
label define MV829   
    10 "PUBLIC SECTOR"
    11 "Government Hospital"
    12 "Government Health center"
    13 "CHAL Hospital"
    14 "CHAL Health Center"
    16 "OTHER PUBLIC SECTOR"
    20 "PRIVATE MEDICAL"
    21 "Private hospital/clinic"
    22 "LPPA"
    23 "Pharmacy"
    24 "Private doctor"
    25 "Community support groups"
    26 "OTHER PRIVATE MEDICAL SECTOR"
    96 "Other"
;
label define MV832B  
   100 "<1 day ago"
   101 "Days: 1"
   201 "Weeks: 1"
   300 "Months: 0"
   301 "Months: 1"
   401 "Years: 1"
   995 "Within last 4 weeks"
   996 "Before last birth"
   997 "Inconsistent"
   998 "Don't know"
;
label define MV832C  
   100 "<1 day ago"
   101 "Days: 1"
   201 "Weeks: 1"
   301 "Months: 1"
   401 "Years: 1"
   995 "Within last 4 weeks"
   996 "Before last birth"
   997 "Inconsistent"
   998 "Don't know"
;
label define MV833A  
     0 "No"
     1 "Yes"
;
label define MV833B  
     0 "No"
     1 "Yes"
;
label define MV833C  
     0 "No"
     1 "Yes"
;
label define MV835A  
     0 "No"
     1 "Respondent drunk only"
     2 "Partner drunk only"
     3 "Both drunk"
     4 "Neither drunk but consumed alcohol"
;
label define MV835B  
     0 "No"
     1 "Respondent drunk only"
     2 "Partner drunk only"
     3 "Both drunk"
     4 "Neither drunk but consumed alcohol"
;
label define MV835C  
     0 "No"
     1 "Respondent drunk only"
     2 "Partner drunk only"
     3 "Both drunk"
     4 "Neither drunk but consumed alcohol"
;
label define MV836   
    95 "95+"
    98 "Don't know"
;
label define MV837   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV844   
     0 "No"
     1 "Yes"
     2 "Don't know anyone with AIDS"
;
label define MV845   
     0 "No"
     1 "Yes"
;
label define MV846   
     0 "No"
     1 "Yes"
;
label define MV847   
     0 "Disagree"
     1 "Agree"
     8 "Don't know / no opinion"
;
label define MV848   
     0 "Disagree"
     1 "Agree"
     8 "Don't know / no opinion"
;
label define MV849   
     0 "No"
     1 "Yes"
     8 "Don't know / depends"
;
label define MV851A  
     0 "No"
     1 "Yes"
     8 "DK, not sure, depends"
;
label define MV851B  
     0 "No"
     1 "Yes"
     8 "DK, not sure, depends"
;
label define MV851C  
     0 "No"
     1 "Yes"
     8 "DK, not sure, depends"
;
label define MV851D  
     0 "No"
     1 "Yes"
     8 "DK, not sure, depends"
;
label define MV851E  
     0 "No"
     1 "Yes"
     8 "DK, not sure, depends"
;
label define MV851F  
     0 "No"
     1 "Yes"
     8 "DK, not sure, depends"
;
label define MV851G  
     0 "No"
     1 "Yes"
     8 "DK, not sure, depends"
;
label define MV851H  
     0 "No"
     1 "Yes"
     8 "DK, not sure, depends"
;
label define MV851I  
     0 "No"
     1 "Yes"
     8 "DK, not sure, depends"
;
label define MV851J  
     0 "No"
     1 "Yes"
     8 "DK, not sure, depends"
;
label define MV851K  
     0 "No"
     1 "Yes"
     8 "DK, not sure, depends"
;
label define MV851L  
     0 "No"
     1 "Yes"
     8 "DK, not sure, depends"
;
label define SMZONE  
     1 "Lowlands"
     2 "Foothills"
     3 "Mountains"
     4 "Senqu River Valley"
;
label define SMLANGIN
     2 "Sesotho"
     1 "English"
     6 "Other"
;
label define SMLANGRS
     2 "Sesotho"
     1 "English"
     6 "Other"
;
label define SMINTERP
     1 "Yes"
     0 "No"
;
label define SM102   
     0 "Respondent does not agree"
     1 "Respondent agrees"
     3 "Not in male sub-sample"
;
label define SM102AA 
     1 "Yes"
     0 "No"
;
label define SM102AB 
     1 "Yes"
     0 "No"
;
label define SM102AC 
     1 "Yes"
     0 "No"
;
label define SM102C  
     1 "SMALL: 17 CM – 22 CM"
     2 "MEDIUM: 23 CM – 32 CM"
     3 "LARGE: 33 CM – 42 CM"
;
label define SMBP1S  
   994 "Refused"
   995 "Technical problems"
   996 "Other"
;
label define SMBP1D  
   994 "Refused"
   995 "Technical problems"
   996 "Other"
;
label define SMBP2S  
   994 "Refused"
   995 "Technical problems"
   996 "Other"
;
label define SMBP2D  
   994 "Refused"
   995 "Technical problems"
   996 "Other"
;
label define SMBP3S  
   994 "Refused"
   995 "Technical problems"
   996 "Other"
;
label define SMBP3D  
   994 "Refused"
   995 "Technical problems"
   996 "Other"
;
label define SMBPAVES
   994 "Refused"
   995 "Technical problems"
   996 "Other"
;
label define SMBPAVED
   994 "Refused"
   995 "Technical problems"
   996 "Other"
;
label define SMBPREF 
     1 "Systolic <=129 and Diastolic <= 84"
     2 "Systolic 130-139 and/or Diastolic 85-89"
     3 "Systolic 140-159 and/or Diastolic 90-99"
     4 "Systolic 160-179 and/or Diastolic 100-109"
     5 "Systolic 180-209 and/or Diastolic 110-119"
     6 "Systolic >=210 and/or Diastolic >=120"
     9 "Other result"
;
label define SM109   
     0 "No education"
     1 "Primary"
     2 "Post Primary :Vocational/Tech.training"
     3 "Secondary/Higher"
     4 "Post secondary:Vocational/tech.training"
     5 "College"
     6 "Graduate/Post Graduate"
;
label define SM109A  
     0 "No education"
     1 "Primary incomplete"
     2 "Primary complete"
     3 "Secondary+"
;
label define SM115AA 
     0 "No"
     1 "Yes"
;
label define SM115AB 
     0 "No"
     1 "Yes"
;
label define SM115AX 
     0 "No"
     1 "Yes"
;
label define SM116AA 
     0 "No"
     1 "Yes"
;
label define SM116AB 
     0 "No"
     1 "Yes"
;
label define SM116AX 
     0 "No"
     1 "Yes"
;
label define SM117AA 
     0 "No"
     1 "Yes"
;
label define SM117AB 
     0 "No"
     1 "Yes"
;
label define SM117AX 
     0 "No"
     1 "Yes"
;
label define SM303D  
     1 "Yes"
     0 "No"
;
label define SM308C  
     0 "Disagree"
     1 "Agree"
     8 "Don't know"
;
label define SM308D  
     0 "Disagree"
     1 "Agree"
     8 "Don't know"
;
label define SM425BA 
    95 "95 times or more"
;
label define SM425BB 
    95 "95 times or more"
;
label define SM425BC 
    95 "95 times or more"
;
label define SM425CA 
     1 "Younger"
     2 "About the same age"
     3 "Less than 10 years older"
     4 "10 or more years older"
     5 "Older, don't know difference"
     8 "Don't know"
;
label define SM425CB 
     1 "Younger"
     2 "About the same age"
     3 "Less than 10 years older"
     4 "10 or more years older"
     5 "Older, don't know difference"
     8 "Don't know"
;
label define SM425CC 
     1 "Younger"
     2 "About the same age"
     3 "Less than 10 years older"
     4 "10 or more years older"
     5 "Older, don't know difference"
     8 "Don't know"
;
label define SM429BA 
     0 "No"
     1 "Yes"
;
label define SM429BC 
     0 "No"
     1 "Yes"
;
label define SM429BD 
     0 "No"
     1 "Yes"
;
label define SM429BE 
     0 "No"
     1 "Yes"
;
label define SM429BG 
     0 "No"
     1 "Yes"
;
label define SM429BH 
     0 "No"
     1 "Yes"
;
label define SM429BX 
     0 "No"
     1 "Yes"
;
label define SM429BY 
     0 "No"
     1 "Yes"
;
label define SM429CA 
     1 "Yes"
     0 "No"
     8 "DK, don't remember"
;
label define SM429CB 
     0 "No"
     1 "Yes"
     8 "DK, don't remember"
;
label define SM429CC 
     1 "Yes"
     0 "No"
     8 "DK, don't remember"
;
label define SM429CD 
     1 "Yes"
     0 "No"
     8 "DK, don't remember"
;
label define SM429CE 
     1 "Yes"
     0 "No"
     8 "DK, don't remember"
;
label define SM429CF 
     1 "Yes"
     0 "No"
     8 "DK, don't remember"
;
label define SM429CG 
     1 "Yes"
     0 "No"
     8 "DK, don't remember"
;
label define SM429CH 
     1 "Yes"
     0 "No"
     8 "DK, don't remember"
;
label define SM429CI 
     1 "Yes"
     0 "No"
     8 "DK, don't remember"
;
label define SM432A  
     1 "Yes"
     0 "No"
;
label define SM433   
     0 "No"
     1 "Yes"
;
label define SM443   
     1 "Yes"
     0 "No"
     8 "DON'T KNOW"
;
label define SM603A  
     0 "Months 0"
     1 "Months 1"
     2 "Months 2"
     3 "Months 3"
     4 "Months 4"
     5 "Months 5"
     6 "Months 6"
     7 "Months 7"
     8 "Months 8"
     9 "Months 9"
    10 "Months 10"
    11 "Months 11"
    12 "Months 12"
;
label define SM613F  
     1 "Husband"
     2 "Wife"
     3 "Both"
     8 "DK, depends"
;
label define SM613AA 
     1 "Husband"
     2 "Wife"
     3 "Both"
     8 "DK, depends"
;
label define SM613AB 
     1 "Husband"
     2 "Wife"
     3 "Both"
     8 "DK, depends"
;
label define SM613CC 
     0 "No"
     1 "Yes"
;
label define SM613DD 
     1 "ALONE"
     2 "JOINTLY WITH WIFE/PARTNER"
     3 "JOINTLY WITH SOMEONE ELSE"
     4 "BOTH ALONE AND JOINTLY"
;
label define SM613EE 
     1 "Yes"
     0 "No"
;
label define SM613FF 
     1 "ALONE"
     2 "JOINTLY WITH WIFE/PARTNER"
     3 "JOINTLY WITH SOMEONE ELSE"
     4 "BOTH ALONE AND JOINTLY"
;
label define SM615F  
     1 "Yes"
     0 "No"
     8 "DK"
;
label define SM723A  
     0 "SHOULD NOT BE ALLOWED"
     1 "SHOULD BE ALLOWED"
     8 "DK/NOT SURE/DEPENDS"
;
label define SM741A  
     1 "Yes"
     0 "No"
     3 "PARTNER ALREADY INFECTED"
;
label define SM741B  
     0 "NO"
     1 "Yes"
     2 "SOME/NOT ALL"
     4 "DID NOT HAVE A  PARTNER"
;
label define SM741CA 
     1 "Yes"
     0 "No"
     8 "Don't know"
;
label define SM741CB 
     1 "Yes"
     0 "No"
     8 "Don't know"
;
label define SM741CC 
     1 "Yes"
     0 "No"
     8 "Don't know"
;
label define SM801AA 
     1 "Yes"
     0 "No"
;
label define SM801AB 
     1 "Yes"
     0 "No"
;
label define SM801AC 
     1 "Yes"
     0 "No"
;
label define SM801AD 
     1 "Yes"
     0 "No"
;
label define SM801AE 
     1 "Yes"
     0 "No"
;
label define SM801C  
     1 "Yes"
     0 "No"
;
label define SM801D  
     1 "SYMPTOMS HARMLESS"
     2 "COST"
     3 "DISTANCE"
     4 "EMBARASSED"
     5 "LONG QUEUE"
     6 "OTHER"
;
label define SM801E  
    11 "GOVERNMENT HOSPITAL"
    12 "GOVERNMENT HEALTH CENTER"
    16 "OTHER PUBLIC SECTOR"
    21 "PRIVATE HOSPITAL/CLINIC"
    22 "PHARMACY"
    23 "PRIVATE DOCTOR"
    26 "OTHER PRIVATE MEDICAL SECTOR"
    31 "CHAL HOSPITAL"
    32 "CHAL HEALTH CENTER"
    41 "CBD"
    42 "COMMUNITY HEALTH WORKER"
    43 "SUPPORT GROUPS"
    51 "OTHER SOURCE SHOP"
    52 "CHURCH"
    53 "FRIENDS/RELATIVES"
    54 "TRADITIONAL HEALER"
    96 "OTHER"
;
label define SM801F  
   100 " Same day"
   101 " 1 Day"
   201 " 1 Week"
   301 " 1 Month"
   998 "Don't know"
;
label define SM801G  
     1 "Yes"
     0 "No"
;
label define SM801H  
     1 "Yes"
     0 "No"
;
label define SM801I  
    96 "8 years or more"
    98 "Don't know"
;
label define SM801J  
     1 "Yes"
     0 "No"
;
label define SM801K  
    11 "GOVERNMENT HOSPITAL"
    12 "GOVERNMENT HEALTH CENTER"
    16 "OTHER PUBLIC SECTOR"
    21 "PRIVATE HOSPITAL/CLINIC"
    22 "PHARMACY"
    23 "PRIVATE DOCTOR"
    26 "OTHER PRIVATE MEDICAL SECTOR"
    31 "CHAL HOSPITAL"
    32 "CHAL HEALTH CENTER"
    41 "CBD"
    42 "COMMUNITY HEALTH WORKER"
    43 "SUPPORT GROUPS"
    51 "OTHER SOURCE SHOP"
    52 "CHURCH"
    53 "FRIENDS/RELATIVES"
    54 "TRADITIONAL HEALER"
    96 "OTHER"
;
label define SM804BA 
     0 "No"
     1 "Yes"
;
label define SM804BB 
     0 "No"
     1 "Yes"
;
label define SM804BC 
     0 "No"
     1 "Yes"
;
label define SM804BD 
     0 "No"
     1 "Yes"
;
label define SM804BE 
     0 "No"
     1 "Yes"
;
label define SM804BF 
     0 "No"
     1 "Yes"
;
label define SM804BG 
     0 "No"
     1 "Yes"
;
label define SM804BH 
     0 "No"
     1 "Yes"
;
label define SM804BI 
     0 "No"
     1 "Yes"
;
label define SM804BJ 
     0 "No"
     1 "Yes"
;
label define SM804BX 
     0 "No"
     1 "Yes"
;
label define SM804BY 
     0 "No"
     1 "Yes"
;
label define SM804BZ 
     0 "No"
     1 "Yes"
;
label define SM804CA 
     0 "No"
     1 "Yes"
;
label define SM804CB 
     0 "No"
     1 "Yes"
;
label define SM804CC 
     0 "No"
     1 "Yes"
;
label define SM804CD 
     0 "No"
     1 "Yes"
;
label define SM804CE 
     0 "No"
     1 "Yes"
;
label define SM804CF 
     0 "No"
     1 "Yes"
;
label define SM804CG 
     0 "No"
     1 "Yes"
;
label define SM804CX 
     0 "No"
     1 "Yes"
;
label define SM804CZ 
     0 "No"
     1 "Yes"
;
label define SM804A  
     1 "Yes"
     0 "No"
;
label define SM805A  
    96 "During childhood (< 5 years)"
    98 "Don't know"
;
label define SM805B  
     1 "TRADITIONAL PRACTITIONER/ FAMILY/FRIENDS"
     2 "HEALTH PROFESSIONAL"
     3 "OTHER"
     8 "DON'T KNOW"
;
label define SM805C  
     1 "Health facility"
     2 "Home of a health worker/ professional"
     3 "Initiation school"
     4 "Other"
     8 "Don't know"
;
label define SM813A  
     0 "No"
     1 "Yes"
;
label define SM813B  
    95 "Every day"
    98 "Don't know"
;
label define SM813C  
     0 "No"
     1 "Yes"
;
label define SM813E  
     0 "None"
    98 "DK"
;
label define SM813F  
     1 "Yes"
     0 "No"
;
label define SM813G  
     1 "Yes"
     0 "No"
;
label define SM813H  
     1 "Yes"
     0 "No"
;
label define SM813I  
     1 "INJECTED"
     2 "ORALLY"
;
label define SM813J  
     1 "Yes"
     0 "No"
;
label define SM813K  
     1 "DOCTOR"
     2 "NURSE"
     3 "PHARMACIST"
     6 "OTHER"
     8 "DON'T KNOW"
;
label define SM813L  
     1 "LESS THAN 6 MONTHS AGO"
     2 "6 - 11 MONTHS AGO"
     3 "1 - 5 YEARS AGO"
     4 "MORE THAN 5 YEARS AGO"
     8 "DON'T KNOW"
;
label define SM813M  
     1 "Yes"
     0 "No"
;
label define SM813NA 
     1 "Yes"
     0 "No"
     3 "Does not apply"
;
label define SM813NB 
     1 "Yes"
     0 "No"
     3 "Does not apply"
;
label define SM813NC 
     1 "Yes"
     0 "No"
     3 "Does not apply"
;
label define SM813ND 
     1 "Yes"
     0 "No"
     3 "Does not apply"
;
label define SM813NE 
     1 "Yes"
     0 "No"
     3 "Does not apply"
;
label define SM813NF 
     1 "Yes"
     0 "No"
     3 "Does not apply"
;
label define SM813NG 
     1 "Yes"
     0 "No"
     3 "Does not apply"
;
label define SM902   
     1 "BOY"
     2 "GIRL"
;
label define SM903M  
     1 "1"
     2 "2"
     3 "3"
     4 "4"
     5 "5"
     6 "6"
     7 "7"
     8 "8"
     9 "9"
    10 "10"
    11 "11"
    12 "12"
    98 "DK"
;
label define SM903Y  
  9998 "Don't know"
;
label define SM904   
     1 "Yes"
     0 "No"
     8 "DON’T KNOW"
;
label define SM905   
   100 "0 Day"
   101 "1 Day"
   201 "1 Week"
   301 "1 Month"
   401 "1 Year"
   998 "Don't know"
;
label define SM906   
     0 "Not in HH"
    95 "Mother deceased"
;
label define SM908   
     1 "Current spouse"
     2 "Former spouse"
     3 "Current live-in partner"
     4 "Former live-in partner"
     5 "Regular sexual partner"
     6 "Woman is girlfriend, fiancée"
     7 "Occasional sexual partner"
     8 "Friend, acquaintance"
    96 "Other"
;
label define SM910A  
     1 "Yes"
     0 "No"
     8 "DK"
;
label define SM910B  
     1 "Yes"
     0 "No"
     8 "DK"
;
label define SM910C  
     1 "Yes"
     0 "No"
     8 "DK"
;
label define SM911A  
     1 "FREE"
     2 "INSURANCE"
     3 "RESPONDENT"
     5 "CHILD'S MOTHER04 RESPONDENT AND CHILD'S MOTHER"
     6 "RESPONDENT'S FAMILY"
     7 "CHILD'S MOTHER FAMILY"
     8 "OTHER"
;
label define SM911B  
     1 "FREE"
     2 "INSURANCE"
     3 "RESPONDENT"
     5 "CHILD'S MOTHER04 RESPONDENT AND CHILD'S MOTHER"
     6 "RESPONDENT'S FAMILY"
     7 "CHILD'S MOTHER FAMILY"
     8 "OTHER"
;
label define SM911C  
     1 "FREE"
     2 "INSURANCE"
     3 "RESPONDENT"
     5 "CHILD'S MOTHER04 RESPONDENT AND CHILD'S MOTHER"
     6 "RESPONDENT'S FAMILY"
     7 "CHILD'S MOTHER FAMILY"
     8 "OTHER"
;
label define SM912A  
     1 "NOT NECESSARY"
     2 "NOT CUSTOMARY"
     3 "RESPONDENT DIDN’T ALLOW"
     4 "TOO COSTLY"
     5 "TOO FAR/NO TRANSPORT"
     6 "POOR SERVICE"
     7 "LACK OF KNOWLEDGE"
     8 "OTHER"
;
label define SM912B  
     1 "NOT NECESSARY"
     2 "NOT CUSTOMARY"
     3 "RESPONDENT DIDN’T ALLOW"
     4 "TOO COSTLY"
     5 "TOO FAR/NO TRANSPORT"
     6 "POOR SERVICE"
     7 "LACK OF KNOWLEDGE"
     8 "OTHER"
;
label define SM912C  
     1 "NOT NECESSARY"
     2 "NOT CUSTOMARY"
     3 "RESPONDENT DIDN’T ALLOW"
     4 "TOO COSTLY"
     5 "TOO FAR/NO TRANSPORT"
     6 "POOR SERVICE"
     7 "LACK OF KNOWLEDGE"
     8 "OTHER"
;

#delimit cr
label values mv013    MV013   
label values mv014    MV014   
label values mv015    MV015   
label values mv022    MV022   
label values mv023    MV023   
label values mv024    MV024   
label values mv025    MV025   
label values mv026    MV026   
label values mv034_1  MV034   
label values mv034_2  MV034   
label values mv034_3  MV034   
label values mv034_4  MV034   
label values mv034_5  MV034   
label values mv034_6  MV034   
label values mv034_7  MV034   
label values mv034_8  MV034   
label values mv034a_1 MV034A  
label values mv034a_2 MV034A  
label values mv034a_3 MV034A  
label values mv034a_4 MV034A  
label values mv034a_5 MV034A  
label values mv034a_6 MV034A  
label values mv034a_7 MV034A  
label values mv034a_8 MV034A  
label values mv035    MV035   
label values mv803    MV803   
label values mv101    MV101   
label values mv102    MV102   
label values mv103    MV103   
label values mv104    MV104   
label values mv105    MV105   
label values mv106    MV106   
label values mv130    MV130   
label values mv133    MV133   
label values mv134    MV134   
label values mv135    MV135   
label values mv149    MV149   
label values mv150    MV150   
label values mv151    MV151   
label values mv152    MV152   
label values mv155    MV155   
label values mv156    MV156   
label values mv157    MV157   
label values mv158    MV158   
label values mv159    MV159   
label values mv167    MV167   
label values mv168    MV168   
label values mv190    MV190   
label values mv213    MV213   
label values mv217    MV217   
label values mv225    MV225   
label values mv246    MV246   
label values mv248    MV248   
label values mv249    MV249   
label values mv250    MV250   
label values mv251    MV251   
label values mv252    MV252   
label values mv301    MV301   
label values mv302    MV302   
label values m304a_01 M304A   
label values m304a_02 M304A   
label values m304a_03 M304A   
label values m304a_04 M304A   
label values m304a_05 M304A   
label values m304a_06 M304A   
label values m304a_07 M304A   
label values m304a_08 M304A   
label values m304a_09 M304A   
label values m304a_10 M304A   
label values m304a_11 M304A   
label values m304a_12 M304A   
label values m304a_13 M304A   
label values m304a_14 M304A   
label values m304a_15 M304A   
label values m304a_16 M304A   
label values m304a_17 M304A   
label values m304a_18 M304A   
label values m304a_19 M304A   
label values m304a_20 M304A   
label values mv304_01 MV304   
label values mv304_02 MV304   
label values mv304_03 MV304   
label values mv304_04 MV304   
label values mv304_05 MV304   
label values mv304_06 MV304   
label values mv304_07 MV304   
label values mv304_08 MV304   
label values mv304_09 MV304   
label values mv304_10 MV304   
label values mv304_11 MV304   
label values mv304_12 MV304   
label values mv304_13 MV304   
label values mv304_14 MV304   
label values mv304_15 MV304   
label values mv304_16 MV304   
label values mv304_17 MV304   
label values mv304_18 MV304   
label values mv304_19 MV304   
label values mv304_20 MV304   
label values mv305_01 MV305   
label values mv305_02 MV305   
label values mv305_03 MV305   
label values mv305_04 MV305   
label values mv305_05 MV305   
label values mv305_06 MV305   
label values mv305_07 MV305   
label values mv305_08 MV305   
label values mv305_09 MV305   
label values mv305_10 MV305   
label values mv305_11 MV305   
label values mv305_12 MV305   
label values mv305_13 MV305   
label values mv305_14 MV305   
label values mv305_15 MV305   
label values mv305_16 MV305   
label values mv305_17 MV305   
label values mv305_18 MV305   
label values mv305_19 MV305   
label values mv305_20 MV305   
label values mv307_01 MV307   
label values mv307_02 MV307   
label values mv307_03 MV307   
label values mv307_04 MV307   
label values mv307_05 MV307   
label values mv307_06 MV307   
label values mv307_07 MV307   
label values mv307_08 MV307   
label values mv307_09 MV307   
label values mv307_10 MV307   
label values mv307_11 MV307   
label values mv307_12 MV307   
label values mv307_13 MV307   
label values mv307_14 MV307   
label values mv307_15 MV307   
label values mv307_16 MV307   
label values mv307_17 MV307   
label values mv307_18 MV307   
label values mv307_19 MV307   
label values mv307_20 MV307   
label values mv312    MV312   
label values mv313    MV313   
label values mv323a   MV323A  
label values mv325b   MV325B  
label values mv372a   MV372A  
label values mv384a   MV384A  
label values mv384b   MV384B  
label values mv384c   MV384C  
label values mv395    MV395   
label values mv396    MV396   
label values mv3a09b  MV3A09B 
label values mv3b17   MV3B17  
label values mv3b25a  MV3B25A 
label values mv3b25b  MV3B25B 
label values mv463a   MV463A  
label values mv463b   MV463B  
label values mv463c   MV463C  
label values mv463d   MV463D  
label values mv463e   MV463E  
label values mv463f   MV463F  
label values mv463g   MV463G  
label values mv463x   MV463X  
label values mv463z   MV463Z  
label values mv474    MV474   
label values mv474a   MV474A  
label values mv474b   MV474B  
label values mv474c   MV474C  
label values mv474d   MV474D  
label values mv474e   MV474E  
label values mv474f   MV474F  
label values mv474g   MV474G  
label values mv474h   MV474H  
label values mv474i   MV474I  
label values mv474j   MV474J  
label values mv474x   MV474X  
label values mv474z   MV474Z  
label values mv475    MV475   
label values mv476    MV476   
label values mv477    MV477   
label values mv478    MV478   
label values mv479    MV479   
label values mv480    MV480   
label values mv481    MV481   
label values mv481a   MV481A  
label values mv481b   MV481B  
label values mv481c   MV481C  
label values mv481d   MV481D  
label values mv481e   MV481E  
label values mv481f   MV481F  
label values mv481g   MV481G  
label values mv481h   MV481H  
label values mv481x   MV481X  
label values mv482a   MV482A  
label values mv482b   MV482B  
label values mv482c   MV482C  
label values mv483    MV483   
label values mv501    MV501   
label values mv502    MV502   
label values mv503    MV503   
label values mv504    MV504   
label values mv510    MV510   
label values mv513    MV513   
label values mv525    MV525   
label values mv527    MV527   
label values mv528    MV528   
label values mv529    MV529   
label values mv531    MV531   
label values mv532    MV532   
label values mv535    MV535   
label values mv536    MV536   
label values mv541    MV541   
label values mv602    MV602   
label values mv603    MV603   
label values mv604    MV604   
label values mv605    MV605   
label values mv613    MV613   
label values mv614    MV614   
label values mv616    MV616   
label values mv621    MV621   
label values mv627    MV627   
label values mv628    MV628   
label values mv629    MV629   
label values mv631    MV631   
label values mv633a   MV633A  
label values mv633b   MV633B  
label values mv633c   MV633C  
label values mv633d   MV633D  
label values mv633e   MV633E  
label values mv633f   MV633F  
label values mv633g   MV633G  
label values mv634a   MV634A  
label values mv634b   MV634B  
label values mv634c   MV634C  
label values mv634d   MV634D  
label values mv714    MV714   
label values mv714a   MV714A  
label values mv716    MV716   
label values mv717    MV717   
label values mv719    MV719   
label values mv721    MV721   
label values mv731    MV731   
label values mv732    MV732   
label values mv739    MV739   
label values mv740    MV740   
label values mv741    MV741   
label values mv743a   MV743A  
label values mv743b   MV743B  
label values mv743c   MV743C  
label values mv743d   MV743D  
label values mv743e   MV743E  
label values mv743f   MV743F  
label values mv743g   MV743G  
label values mv744a   MV744A  
label values mv744b   MV744B  
label values mv744c   MV744C  
label values mv744d   MV744D  
label values mv744e   MV744E  
label values mv747a   MV747A  
label values mv747b   MV747B  
label values mv750    MV750   
label values mv751    MV751   
label values mv754bp  MV754BP 
label values mv754cp  MV754CP 
label values mv754dp  MV754DP 
label values mv754jp  MV754JP 
label values mv754wp  MV754WP 
label values mv756    MV756   
label values mv761    MV761   
label values mv761b   MV761B  
label values mv761c   MV761C  
label values mv762aa  MV762AA 
label values mv762ab  MV762AB 
label values mv762ac  MV762AC 
label values mv762ad  MV762AD 
label values mv762ae  MV762AE 
label values mv762af  MV762AF 
label values mv762ag  MV762AG 
label values mv762ah  MV762AH 
label values mv762ai  MV762AI 
label values mv762aj  MV762AJ 
label values mv762ak  MV762AK 
label values mv762al  MV762AL 
label values mv762am  MV762AM 
label values mv762an  MV762AN 
label values mv762ao  MV762AO 
label values mv762ap  MV762AP 
label values mv762aq  MV762AQ 
label values mv762ar  MV762AR 
label values mv762as  MV762AS 
label values mv762at  MV762AT 
label values mv762au  MV762AU 
label values mv762av  MV762AV 
label values mv762aw  MV762AW 
label values mv762ax  MV762AX 
label values mv762az  MV762AZ 
label values mv762ba  MV762BA 
label values mv762bb  MV762BB 
label values mv762bc  MV762BC 
label values mv762bd  MV762BD 
label values mv762be  MV762BE 
label values mv762bf  MV762BF 
label values mv762bg  MV762BG 
label values mv762bh  MV762BH 
label values mv762bi  MV762BI 
label values mv762bj  MV762BJ 
label values mv762bk  MV762BK 
label values mv762bl  MV762BL 
label values mv762bm  MV762BM 
label values mv762bn  MV762BN 
label values mv762bo  MV762BO 
label values mv762bp  MV762BP 
label values mv762bq  MV762BQ 
label values mv762br  MV762BR 
label values mv762bs  MV762BS 
label values mv762bt  MV762BT 
label values mv762bu  MV762BU 
label values mv762bv  MV762BV 
label values mv762bw  MV762BW 
label values mv762bx  MV762BX 
label values mv762bz  MV762BZ 
label values mv763a   MV763A  
label values mv763b   MV763B  
label values mv763c   MV763C  
label values mv763d   MV763D  
label values mv763e   MV763E  
label values mv763f   MV763F  
label values mv763g   MV763G  
label values mv766a   MV766A  
label values mv766b   MV766B  
label values mv767a   MV767A  
label values mv767b   MV767B  
label values mv767c   MV767C  
label values mv768a   MV768A  
label values mv768b   MV768B  
label values mv768c   MV768C  
label values mv769    MV769   
label values mv769a   MV769A  
label values mv770    MV770   
label values mv770a   MV770A  
label values mv770b   MV770B  
label values mv770c   MV770C  
label values mv770d   MV770D  
label values mv770e   MV770E  
label values mv770f   MV770F  
label values mv770g   MV770G  
label values mv770h   MV770H  
label values mv770i   MV770I  
label values mv770j   MV770J  
label values mv770k   MV770K  
label values mv770l   MV770L  
label values mv770m   MV770M  
label values mv770n   MV770N  
label values mv770o   MV770O  
label values mv770p   MV770P  
label values mv770q   MV770Q  
label values mv770r   MV770R  
label values mv770s   MV770S  
label values mv770t   MV770T  
label values mv770u   MV770U  
label values mv770v   MV770V  
label values mv770w   MV770W  
label values mv770x   MV770X  
label values mv774a   MV774A  
label values mv774b   MV774B  
label values mv774c   MV774C  
label values mv775    MV775   
label values mv777    MV777   
label values mv778    MV778   
label values mv779    MV779   
label values mv780    MV780   
label values mv781    MV781   
label values mv783    MV783   
label values mv784a   MV784A  
label values mv784b   MV784B  
label values mv784c   MV784C  
label values mv784d   MV784D  
label values mv784e   MV784E  
label values mv784f   MV784F  
label values mv784g   MV784G  
label values mv784h   MV784H  
label values mv784i   MV784I  
label values mv784j   MV784J  
label values mv784k   MV784K  
label values mv784l   MV784L  
label values mv784m   MV784M  
label values mv784n   MV784N  
label values mv784o   MV784O  
label values mv784p   MV784P  
label values mv784q   MV784Q  
label values mv784r   MV784R  
label values mv784s   MV784S  
label values mv784t   MV784T  
label values mv784u   MV784U  
label values mv784v   MV784V  
label values mv784x   MV784X  
label values mv785    MV785   
label values mv793    MV793   
label values mv793a   MV793A  
label values mv793b   MV793B  
label values mv820    MV820   
label values mv822    MV822   
label values mv823    MV823   
label values mv824    MV824   
label values mv825    MV825   
label values mv826    MV826   
label values mv827    MV827   
label values mv828    MV828   
label values mv829    MV829   
label values mv832b   MV832B  
label values mv832c   MV832C  
label values mv833a   MV833A  
label values mv833b   MV833B  
label values mv833c   MV833C  
label values mv835a   MV835A  
label values mv835b   MV835B  
label values mv835c   MV835C  
label values mv836    MV836   
label values mv837    MV837   
label values mv844    MV844   
label values mv845    MV845   
label values mv846    MV846   
label values mv847    MV847   
label values mv848    MV848   
label values mv849    MV849   
label values mv851a   MV851A  
label values mv851b   MV851B  
label values mv851c   MV851C  
label values mv851d   MV851D  
label values mv851e   MV851E  
label values mv851f   MV851F  
label values mv851g   MV851G  
label values mv851h   MV851H  
label values mv851i   MV851I  
label values mv851j   MV851J  
label values mv851k   MV851K  
label values mv851l   MV851L  
label values smzone   SMZONE  
label values smlangin SMLANGIN
label values smlangrs SMLANGRS
label values sminterp SMINTERP
label values sm102    SM102   
label values sm102aa  SM102AA 
label values sm102ab  SM102AB 
label values sm102ac  SM102AC 
label values sm102c   SM102C  
label values smbp1s   SMBP1S  
label values smbp1d   SMBP1D  
label values smbp2s   SMBP2S  
label values smbp2d   SMBP2D  
label values smbp3s   SMBP3S  
label values smbp3d   SMBP3D  
label values smbpaves SMBPAVES
label values smbpaved SMBPAVED
label values smbpref  SMBPREF 
label values sm109    SM109   
label values sm109a   SM109A  
label values sm115aa  SM115AA 
label values sm115ab  SM115AB 
label values sm115ax  SM115AX 
label values sm116aa  SM116AA 
label values sm116ab  SM116AB 
label values sm116ax  SM116AX 
label values sm117aa  SM117AA 
label values sm117ab  SM117AB 
label values sm117ax  SM117AX 
label values sm303d   SM303D  
label values sm308c   SM308C  
label values sm308d   SM308D  
label values sm425ba  SM425BA 
label values sm425bb  SM425BB 
label values sm425bc  SM425BC 
label values sm425ca  SM425CA 
label values sm425cb  SM425CB 
label values sm425cc  SM425CC 
label values sm429ba  SM429BA 
label values sm429bc  SM429BC 
label values sm429bd  SM429BD 
label values sm429be  SM429BE 
label values sm429bg  SM429BG 
label values sm429bh  SM429BH 
label values sm429bx  SM429BX 
label values sm429by  SM429BY 
label values sm429ca  SM429CA 
label values sm429cb  SM429CB 
label values sm429cc  SM429CC 
label values sm429cd  SM429CD 
label values sm429ce  SM429CE 
label values sm429cf  SM429CF 
label values sm429cg  SM429CG 
label values sm429ch  SM429CH 
label values sm429ci  SM429CI 
label values sm432a   SM432A  
label values sm433    SM433   
label values sm443    SM443   
label values sm603a   SM603A  
label values sm613f   SM613F  
label values sm613aa  SM613AA 
label values sm613ab  SM613AB 
label values sm613cc  SM613CC 
label values sm613dd  SM613DD 
label values sm613ee  SM613EE 
label values sm613ff  SM613FF 
label values sm615f   SM615F  
label values sm723a   SM723A  
label values sm741a   SM741A  
label values sm741b   SM741B  
label values sm741ca  SM741CA 
label values sm741cb  SM741CB 
label values sm741cc  SM741CC 
label values sm801aa  SM801AA 
label values sm801ab  SM801AB 
label values sm801ac  SM801AC 
label values sm801ad  SM801AD 
label values sm801ae  SM801AE 
label values sm801c   SM801C  
label values sm801d   SM801D  
label values sm801e   SM801E  
label values sm801f   SM801F  
label values sm801g   SM801G  
label values sm801h   SM801H  
label values sm801i   SM801I  
label values sm801j   SM801J  
label values sm801k   SM801K  
label values sm804ba  SM804BA 
label values sm804bb  SM804BB 
label values sm804bc  SM804BC 
label values sm804bd  SM804BD 
label values sm804be  SM804BE 
label values sm804bf  SM804BF 
label values sm804bg  SM804BG 
label values sm804bh  SM804BH 
label values sm804bi  SM804BI 
label values sm804bj  SM804BJ 
label values sm804bx  SM804BX 
label values sm804by  SM804BY 
label values sm804bz  SM804BZ 
label values sm804ca  SM804CA 
label values sm804cb  SM804CB 
label values sm804cc  SM804CC 
label values sm804cd  SM804CD 
label values sm804ce  SM804CE 
label values sm804cf  SM804CF 
label values sm804cg  SM804CG 
label values sm804cx  SM804CX 
label values sm804cz  SM804CZ 
label values sm804a   SM804A  
label values sm805a   SM805A  
label values sm805b   SM805B  
label values sm805c   SM805C  
label values sm813a   SM813A  
label values sm813b   SM813B  
label values sm813c   SM813C  
label values sm813e   SM813E  
label values sm813f   SM813F  
label values sm813g   SM813G  
label values sm813h   SM813H  
label values sm813i   SM813I  
label values sm813j   SM813J  
label values sm813k   SM813K  
label values sm813l   SM813L  
label values sm813m   SM813M  
label values sm813na  SM813NA 
label values sm813nb  SM813NB 
label values sm813nc  SM813NC 
label values sm813nd  SM813ND 
label values sm813ne  SM813NE 
label values sm813nf  SM813NF 
label values sm813ng  SM813NG 
label values sm902    SM902   
label values sm903m   SM903M  
label values sm903y   SM903Y  
label values sm904    SM904   
label values sm905    SM905   
label values sm906    SM906   
label values sm908    SM908   
label values sm910a   SM910A  
label values sm910b   SM910B  
label values sm910c   SM910C  
label values sm911a   SM911A  
label values sm911b   SM911B  
label values sm911c   SM911C  
label values sm912a   SM912A  
label values sm912b   SM912B  
label values sm912c   SM912C  
