infix using "C:\COUNTRIES\LS71\LSHR71FL.dct"

label variable hhid     "Case Identification"
label variable hv000    "Country code and phase"
label variable hv001    "Cluster number"
label variable hv002    "Household number"
label variable hv003    "Respondent's line number (answering Household questionnaire)"
label variable hv004    "Ultimate area unit"
label variable hv005    "Household sample weight (6 decimals)"
label variable hv006    "Month of interview"
label variable hv007    "Year of interview"
label variable hv008    "Date of interview (CMC)"
label variable hv009    "Number of household members"
label variable hv010    "Number of eligible women in household"
label variable hv011    "Number of eligible men in household"
label variable hv012    "Number of de jure members"
label variable hv013    "Number of de facto members"
label variable hv014    "Number of children 5 and under (de jure)"
label variable hv015    "Result of household interview"
label variable hv016    "Day of interview"
label variable hv017    "Number of visits"
label variable hv018    "Interviewer identification"
label variable hv019    "NA - Keyer identification"
label variable hv020    "Ever-married sample"
label variable hv021    "Primary sampling unit"
label variable hv022    "Sample strata for sampling errors"
label variable hv023    "Stratification used in sample design"
label variable hv024    "Region"
label variable hv025    "Type of place of residence"
label variable hv026    "NA - Place of residence"
label variable hv027    "Household selected for male interview"
label variable hv028    "Household weight for male subsample (6 decimals)"
label variable hv030    "Field supervisor"
label variable hv031    "NA - Field editor"
label variable hv032    "NA - Office editor"
label variable hv035    "Number of eligible children for height and weight"
label variable hv040    "Cluster altitude in meters"
label variable hv041    "Total adults measured"
label variable hv042    "Household selected for hemoglobin"
label variable hv044    "NA - Household selected for Domestic Violence module"
label variable hv201    "Source of drinking water"
label variable hv202    "NA - Source of non-drinking water"
label variable hv204    "Time to get to water source (minutes)"
label variable hv205    "Type of toilet facility"
label variable hv206    "Has electricity"
label variable hv207    "Has radio"
label variable hv208    "Has television"
label variable hv209    "Has refrigerator"
label variable hv210    "Has bicycle"
label variable hv211    "Has motorcycle/scooter"
label variable hv212    "Has car/truck"
label variable hv213    "Main floor material"
label variable hv214    "Main wall material"
label variable hv215    "Main roof material"
label variable hv216    "Number of rooms used for sleeping"
label variable hv217    "Relationship structure"
label variable hv218    "Line number of head of household"
label variable hv219    "Sex of head of household"
label variable hv220    "Age of head of household"
label variable hv221    "Has telephone (land-line)"
label variable hv225    "Share toilet with other households"
label variable hv226    "Type of cooking fuel"
label variable hv227    "NA - Has mosquito bed net for sleeping"
label variable hv228    "NA - Children under 5 slept under mosquito bed net last night"
label variable hv230a   "Place where household members wash their hands"
label variable hv230b   "Presence of water at hand washing place"
label variable hv232    "Items present: Soap or detergent"
label variable hv232b   "Items present: Ash, mud, sand"
label variable hv232c   "NA - Items present: CS"
label variable hv232d   "NA - Items present: CS"
label variable hv232e   "NA - Items present: CS"
label variable hv232y   "Items present: None"
label variable hv234    "NA - Result of salt test for iodine (PPM)"
label variable hv234a   "Result of salt test for iodine"
label variable hv235    "Location of source for water"
label variable hv236    "NA - Person fetching water"
label variable hv237    "Anything done to water to make safe to drink"
label variable hv237a   "Water usually treated by: boil"
label variable hv237b   "Water usually treated by: add bleach/chlorine"
label variable hv237c   "Water usually treated by: strain through a cloth"
label variable hv237d   "Water usually treated by: use water filter"
label variable hv237e   "Water usually treated by: solar disinfection"
label variable hv237f   "Water usually treated by: let it stand and settle"
label variable hv237g   "NA - Water usually treated by: CS"
label variable hv237h   "NA - Water usually treated by: CS"
label variable hv237i   "NA - Water usually treated by: CS"
label variable hv237j   "NA - Water usually treated by: CS"
label variable hv237k   "NA - Water usually treated by: CS"
label variable hv237x   "Water usually treated by: other"
label variable hv237z   "Water usually treated by: don't know"
label variable hv238    "Number of households sharing toilet"
label variable hv239    "NA - Food cooked on stove or open fire"
label variable hv240    "NA - Household has a chimney, hood or neither"
label variable hv241    "Food cooked in the house/ separate building/ outdoors"
label variable hv242    "Household has separate room used as kitchen"
label variable hv243a   "Has mobile telephone"
label variable hv243b   "Has watch"
label variable hv243c   "Has animal-drawn cart"
label variable hv243d   "NA - Has boat with a motor"
label variable hv244    "Owns land usable for agriculture"
label variable hv245    "Hectares of agricultural land (1 decimal)"
label variable hv246    "Owns livestock, herds or farm animals"
label variable hv246a   "Owns cattle"
label variable hv246b   "Owns cows/ bulls"
label variable hv246c   "Owns horses/ donkeys/ mules"
label variable hv246d   "Owns goats"
label variable hv246e   "Owns sheep"
label variable hv246f   "Owns chickens"
label variable hv246g   "Owns Bulls (CS)"
label variable hv246h   "Owns cows(CS)"
label variable hv246i   "Owns Improved chickens(CS)"
label variable hv246j   "Ordinary Pigs (CS)"
label variable hv246k   "Improved pigs (CS)"
label variable hv247    "Has bank account"
label variable hv252    "Frequency household members smoke inside the house"
label variable hv253    "NA - Has dwelling been sprayed against mosquitoes in last 12 months"
label variable hv253a   "NA - Dwelling sprayed by: government worker/program"
label variable hv253b   "NA - Dwelling sprayed by: private company"
label variable hv253c   "NA - Dwelling sprayed by: NGO"
label variable hv253d   "NA - Dwelling sprayed by: CS"
label variable hv253e   "NA - Dwelling sprayed by: CS"
label variable hv253f   "NA - Dwelling sprayed by: CS"
label variable hv253g   "NA - Dwelling sprayed by: CS"
label variable hv253h   "NA - Dwelling sprayed by: CS"
label variable hv253x   "NA - Dwelling sprayed by: other"
label variable hv253z   "NA - Dwelling sprayed by: don't know"
label variable hv270    "Wealth index"
label variable hv271    "Wealth index factor score (5 decimals)"
label variable hml1     "NA - Number of mosquito bed nets"
label variable hml1a    "NA - Number of mosquito bed nets with specific information"
label variable hml2     "NA - Number of children under mosquito bed net previous night"
label variable chl0     "NA - Number of de-jure children 5-14 for child labor module"
label variable shzone   "Ecological zone"
label variable sh110b   "Battery or generator"
label variable sh110c   "Solar panel"
label variable sh110i   "Bed/mattress"
label variable sh110j   "Computer"
label variable sh110k   "Internet access"
label variable sh122k   "Owns Rabbits"
label variable sh124    "Nearest health facility"
label variable sh125    "Mode of transport to nearest health facility"
label variable sh126h   "Time taken to nearest health facility in hours"
label variable sh126m   "Time taken to nearest health facility in minutes"
label variable hvidx_01 "Line number"
label variable hvidx_02 "Line number"
label variable hvidx_03 "Line number"
label variable hvidx_04 "Line number"
label variable hvidx_05 "Line number"
label variable hvidx_06 "Line number"
label variable hvidx_07 "Line number"
label variable hvidx_08 "Line number"
label variable hvidx_09 "Line number"
label variable hvidx_10 "Line number"
label variable hvidx_11 "Line number"
label variable hvidx_12 "Line number"
label variable hvidx_13 "Line number"
label variable hvidx_14 "Line number"
label variable hvidx_15 "Line number"
label variable hvidx_16 "Line number"
label variable hvidx_17 "Line number"
label variable hvidx_18 "Line number"
label variable hvidx_19 "Line number"
label variable hvidx_20 "Line number"
label variable hv101_01 "Relationship to head"
label variable hv101_02 "Relationship to head"
label variable hv101_03 "Relationship to head"
label variable hv101_04 "Relationship to head"
label variable hv101_05 "Relationship to head"
label variable hv101_06 "Relationship to head"
label variable hv101_07 "Relationship to head"
label variable hv101_08 "Relationship to head"
label variable hv101_09 "Relationship to head"
label variable hv101_10 "Relationship to head"
label variable hv101_11 "Relationship to head"
label variable hv101_12 "Relationship to head"
label variable hv101_13 "Relationship to head"
label variable hv101_14 "Relationship to head"
label variable hv101_15 "Relationship to head"
label variable hv101_16 "Relationship to head"
label variable hv101_17 "Relationship to head"
label variable hv101_18 "Relationship to head"
label variable hv101_19 "Relationship to head"
label variable hv101_20 "Relationship to head"
label variable hv102_01 "Usual resident"
label variable hv102_02 "Usual resident"
label variable hv102_03 "Usual resident"
label variable hv102_04 "Usual resident"
label variable hv102_05 "Usual resident"
label variable hv102_06 "Usual resident"
label variable hv102_07 "Usual resident"
label variable hv102_08 "Usual resident"
label variable hv102_09 "Usual resident"
label variable hv102_10 "Usual resident"
label variable hv102_11 "Usual resident"
label variable hv102_12 "Usual resident"
label variable hv102_13 "Usual resident"
label variable hv102_14 "Usual resident"
label variable hv102_15 "Usual resident"
label variable hv102_16 "Usual resident"
label variable hv102_17 "Usual resident"
label variable hv102_18 "Usual resident"
label variable hv102_19 "Usual resident"
label variable hv102_20 "Usual resident"
label variable hv103_01 "Slept last night"
label variable hv103_02 "Slept last night"
label variable hv103_03 "Slept last night"
label variable hv103_04 "Slept last night"
label variable hv103_05 "Slept last night"
label variable hv103_06 "Slept last night"
label variable hv103_07 "Slept last night"
label variable hv103_08 "Slept last night"
label variable hv103_09 "Slept last night"
label variable hv103_10 "Slept last night"
label variable hv103_11 "Slept last night"
label variable hv103_12 "Slept last night"
label variable hv103_13 "Slept last night"
label variable hv103_14 "Slept last night"
label variable hv103_15 "Slept last night"
label variable hv103_16 "Slept last night"
label variable hv103_17 "Slept last night"
label variable hv103_18 "Slept last night"
label variable hv103_19 "Slept last night"
label variable hv103_20 "Slept last night"
label variable hv104_01 "Sex of household member"
label variable hv104_02 "Sex of household member"
label variable hv104_03 "Sex of household member"
label variable hv104_04 "Sex of household member"
label variable hv104_05 "Sex of household member"
label variable hv104_06 "Sex of household member"
label variable hv104_07 "Sex of household member"
label variable hv104_08 "Sex of household member"
label variable hv104_09 "Sex of household member"
label variable hv104_10 "Sex of household member"
label variable hv104_11 "Sex of household member"
label variable hv104_12 "Sex of household member"
label variable hv104_13 "Sex of household member"
label variable hv104_14 "Sex of household member"
label variable hv104_15 "Sex of household member"
label variable hv104_16 "Sex of household member"
label variable hv104_17 "Sex of household member"
label variable hv104_18 "Sex of household member"
label variable hv104_19 "Sex of household member"
label variable hv104_20 "Sex of household member"
label variable hv105_01 "Age of household members"
label variable hv105_02 "Age of household members"
label variable hv105_03 "Age of household members"
label variable hv105_04 "Age of household members"
label variable hv105_05 "Age of household members"
label variable hv105_06 "Age of household members"
label variable hv105_07 "Age of household members"
label variable hv105_08 "Age of household members"
label variable hv105_09 "Age of household members"
label variable hv105_10 "Age of household members"
label variable hv105_11 "Age of household members"
label variable hv105_12 "Age of household members"
label variable hv105_13 "Age of household members"
label variable hv105_14 "Age of household members"
label variable hv105_15 "Age of household members"
label variable hv105_16 "Age of household members"
label variable hv105_17 "Age of household members"
label variable hv105_18 "Age of household members"
label variable hv105_19 "Age of household members"
label variable hv105_20 "Age of household members"
label variable hv106_01 "Highest educational level attained"
label variable hv106_02 "Highest educational level attained"
label variable hv106_03 "Highest educational level attained"
label variable hv106_04 "Highest educational level attained"
label variable hv106_05 "Highest educational level attained"
label variable hv106_06 "Highest educational level attained"
label variable hv106_07 "Highest educational level attained"
label variable hv106_08 "Highest educational level attained"
label variable hv106_09 "Highest educational level attained"
label variable hv106_10 "Highest educational level attained"
label variable hv106_11 "Highest educational level attained"
label variable hv106_12 "Highest educational level attained"
label variable hv106_13 "Highest educational level attained"
label variable hv106_14 "Highest educational level attained"
label variable hv106_15 "Highest educational level attained"
label variable hv106_16 "Highest educational level attained"
label variable hv106_17 "Highest educational level attained"
label variable hv106_18 "Highest educational level attained"
label variable hv106_19 "Highest educational level attained"
label variable hv106_20 "Highest educational level attained"
label variable hv107_01 "Highest year of education completed"
label variable hv107_02 "Highest year of education completed"
label variable hv107_03 "Highest year of education completed"
label variable hv107_04 "Highest year of education completed"
label variable hv107_05 "Highest year of education completed"
label variable hv107_06 "Highest year of education completed"
label variable hv107_07 "Highest year of education completed"
label variable hv107_08 "Highest year of education completed"
label variable hv107_09 "Highest year of education completed"
label variable hv107_10 "Highest year of education completed"
label variable hv107_11 "Highest year of education completed"
label variable hv107_12 "Highest year of education completed"
label variable hv107_13 "Highest year of education completed"
label variable hv107_14 "Highest year of education completed"
label variable hv107_15 "Highest year of education completed"
label variable hv107_16 "Highest year of education completed"
label variable hv107_17 "Highest year of education completed"
label variable hv107_18 "Highest year of education completed"
label variable hv107_19 "Highest year of education completed"
label variable hv107_20 "Highest year of education completed"
label variable hv108_01 "Education completed in single years"
label variable hv108_02 "Education completed in single years"
label variable hv108_03 "Education completed in single years"
label variable hv108_04 "Education completed in single years"
label variable hv108_05 "Education completed in single years"
label variable hv108_06 "Education completed in single years"
label variable hv108_07 "Education completed in single years"
label variable hv108_08 "Education completed in single years"
label variable hv108_09 "Education completed in single years"
label variable hv108_10 "Education completed in single years"
label variable hv108_11 "Education completed in single years"
label variable hv108_12 "Education completed in single years"
label variable hv108_13 "Education completed in single years"
label variable hv108_14 "Education completed in single years"
label variable hv108_15 "Education completed in single years"
label variable hv108_16 "Education completed in single years"
label variable hv108_17 "Education completed in single years"
label variable hv108_18 "Education completed in single years"
label variable hv108_19 "Education completed in single years"
label variable hv108_20 "Education completed in single years"
label variable hv109_01 "Educational attainment"
label variable hv109_02 "Educational attainment"
label variable hv109_03 "Educational attainment"
label variable hv109_04 "Educational attainment"
label variable hv109_05 "Educational attainment"
label variable hv109_06 "Educational attainment"
label variable hv109_07 "Educational attainment"
label variable hv109_08 "Educational attainment"
label variable hv109_09 "Educational attainment"
label variable hv109_10 "Educational attainment"
label variable hv109_11 "Educational attainment"
label variable hv109_12 "Educational attainment"
label variable hv109_13 "Educational attainment"
label variable hv109_14 "Educational attainment"
label variable hv109_15 "Educational attainment"
label variable hv109_16 "Educational attainment"
label variable hv109_17 "Educational attainment"
label variable hv109_18 "Educational attainment"
label variable hv109_19 "Educational attainment"
label variable hv109_20 "Educational attainment"
label variable hv110_01 "NA - Member still in school"
label variable hv110_02 "NA - Member still in school"
label variable hv110_03 "NA - Member still in school"
label variable hv110_04 "NA - Member still in school"
label variable hv110_05 "NA - Member still in school"
label variable hv110_06 "NA - Member still in school"
label variable hv110_07 "NA - Member still in school"
label variable hv110_08 "NA - Member still in school"
label variable hv110_09 "NA - Member still in school"
label variable hv110_10 "NA - Member still in school"
label variable hv110_11 "NA - Member still in school"
label variable hv110_12 "NA - Member still in school"
label variable hv110_13 "NA - Member still in school"
label variable hv110_14 "NA - Member still in school"
label variable hv110_15 "NA - Member still in school"
label variable hv110_16 "NA - Member still in school"
label variable hv110_17 "NA - Member still in school"
label variable hv110_18 "NA - Member still in school"
label variable hv110_19 "NA - Member still in school"
label variable hv110_20 "NA - Member still in school"
label variable hv111_01 "Mother alive"
label variable hv111_02 "Mother alive"
label variable hv111_03 "Mother alive"
label variable hv111_04 "Mother alive"
label variable hv111_05 "Mother alive"
label variable hv111_06 "Mother alive"
label variable hv111_07 "Mother alive"
label variable hv111_08 "Mother alive"
label variable hv111_09 "Mother alive"
label variable hv111_10 "Mother alive"
label variable hv111_11 "Mother alive"
label variable hv111_12 "Mother alive"
label variable hv111_13 "Mother alive"
label variable hv111_14 "Mother alive"
label variable hv111_15 "Mother alive"
label variable hv111_16 "Mother alive"
label variable hv111_17 "Mother alive"
label variable hv111_18 "Mother alive"
label variable hv111_19 "Mother alive"
label variable hv111_20 "Mother alive"
label variable hv112_01 "Mother's line number"
label variable hv112_02 "Mother's line number"
label variable hv112_03 "Mother's line number"
label variable hv112_04 "Mother's line number"
label variable hv112_05 "Mother's line number"
label variable hv112_06 "Mother's line number"
label variable hv112_07 "Mother's line number"
label variable hv112_08 "Mother's line number"
label variable hv112_09 "Mother's line number"
label variable hv112_10 "Mother's line number"
label variable hv112_11 "Mother's line number"
label variable hv112_12 "Mother's line number"
label variable hv112_13 "Mother's line number"
label variable hv112_14 "Mother's line number"
label variable hv112_15 "Mother's line number"
label variable hv112_16 "Mother's line number"
label variable hv112_17 "Mother's line number"
label variable hv112_18 "Mother's line number"
label variable hv112_19 "Mother's line number"
label variable hv112_20 "Mother's line number"
label variable hv113_01 "Father alive"
label variable hv113_02 "Father alive"
label variable hv113_03 "Father alive"
label variable hv113_04 "Father alive"
label variable hv113_05 "Father alive"
label variable hv113_06 "Father alive"
label variable hv113_07 "Father alive"
label variable hv113_08 "Father alive"
label variable hv113_09 "Father alive"
label variable hv113_10 "Father alive"
label variable hv113_11 "Father alive"
label variable hv113_12 "Father alive"
label variable hv113_13 "Father alive"
label variable hv113_14 "Father alive"
label variable hv113_15 "Father alive"
label variable hv113_16 "Father alive"
label variable hv113_17 "Father alive"
label variable hv113_18 "Father alive"
label variable hv113_19 "Father alive"
label variable hv113_20 "Father alive"
label variable hv114_01 "Father's line number"
label variable hv114_02 "Father's line number"
label variable hv114_03 "Father's line number"
label variable hv114_04 "Father's line number"
label variable hv114_05 "Father's line number"
label variable hv114_06 "Father's line number"
label variable hv114_07 "Father's line number"
label variable hv114_08 "Father's line number"
label variable hv114_09 "Father's line number"
label variable hv114_10 "Father's line number"
label variable hv114_11 "Father's line number"
label variable hv114_12 "Father's line number"
label variable hv114_13 "Father's line number"
label variable hv114_14 "Father's line number"
label variable hv114_15 "Father's line number"
label variable hv114_16 "Father's line number"
label variable hv114_17 "Father's line number"
label variable hv114_18 "Father's line number"
label variable hv114_19 "Father's line number"
label variable hv114_20 "Father's line number"
label variable hv115_01 "Current marital status"
label variable hv115_02 "Current marital status"
label variable hv115_03 "Current marital status"
label variable hv115_04 "Current marital status"
label variable hv115_05 "Current marital status"
label variable hv115_06 "Current marital status"
label variable hv115_07 "Current marital status"
label variable hv115_08 "Current marital status"
label variable hv115_09 "Current marital status"
label variable hv115_10 "Current marital status"
label variable hv115_11 "Current marital status"
label variable hv115_12 "Current marital status"
label variable hv115_13 "Current marital status"
label variable hv115_14 "Current marital status"
label variable hv115_15 "Current marital status"
label variable hv115_16 "Current marital status"
label variable hv115_17 "Current marital status"
label variable hv115_18 "Current marital status"
label variable hv115_19 "Current marital status"
label variable hv115_20 "Current marital status"
label variable hv116_01 "Currently, formerly, never married"
label variable hv116_02 "Currently, formerly, never married"
label variable hv116_03 "Currently, formerly, never married"
label variable hv116_04 "Currently, formerly, never married"
label variable hv116_05 "Currently, formerly, never married"
label variable hv116_06 "Currently, formerly, never married"
label variable hv116_07 "Currently, formerly, never married"
label variable hv116_08 "Currently, formerly, never married"
label variable hv116_09 "Currently, formerly, never married"
label variable hv116_10 "Currently, formerly, never married"
label variable hv116_11 "Currently, formerly, never married"
label variable hv116_12 "Currently, formerly, never married"
label variable hv116_13 "Currently, formerly, never married"
label variable hv116_14 "Currently, formerly, never married"
label variable hv116_15 "Currently, formerly, never married"
label variable hv116_16 "Currently, formerly, never married"
label variable hv116_17 "Currently, formerly, never married"
label variable hv116_18 "Currently, formerly, never married"
label variable hv116_19 "Currently, formerly, never married"
label variable hv116_20 "Currently, formerly, never married"
label variable hv117_01 "Eligibility for female interview"
label variable hv117_02 "Eligibility for female interview"
label variable hv117_03 "Eligibility for female interview"
label variable hv117_04 "Eligibility for female interview"
label variable hv117_05 "Eligibility for female interview"
label variable hv117_06 "Eligibility for female interview"
label variable hv117_07 "Eligibility for female interview"
label variable hv117_08 "Eligibility for female interview"
label variable hv117_09 "Eligibility for female interview"
label variable hv117_10 "Eligibility for female interview"
label variable hv117_11 "Eligibility for female interview"
label variable hv117_12 "Eligibility for female interview"
label variable hv117_13 "Eligibility for female interview"
label variable hv117_14 "Eligibility for female interview"
label variable hv117_15 "Eligibility for female interview"
label variable hv117_16 "Eligibility for female interview"
label variable hv117_17 "Eligibility for female interview"
label variable hv117_18 "Eligibility for female interview"
label variable hv117_19 "Eligibility for female interview"
label variable hv117_20 "Eligibility for female interview"
label variable hv118_01 "Eligibility for male interview"
label variable hv118_02 "Eligibility for male interview"
label variable hv118_03 "Eligibility for male interview"
label variable hv118_04 "Eligibility for male interview"
label variable hv118_05 "Eligibility for male interview"
label variable hv118_06 "Eligibility for male interview"
label variable hv118_07 "Eligibility for male interview"
label variable hv118_08 "Eligibility for male interview"
label variable hv118_09 "Eligibility for male interview"
label variable hv118_10 "Eligibility for male interview"
label variable hv118_11 "Eligibility for male interview"
label variable hv118_12 "Eligibility for male interview"
label variable hv118_13 "Eligibility for male interview"
label variable hv118_14 "Eligibility for male interview"
label variable hv118_15 "Eligibility for male interview"
label variable hv118_16 "Eligibility for male interview"
label variable hv118_17 "Eligibility for male interview"
label variable hv118_18 "Eligibility for male interview"
label variable hv118_19 "Eligibility for male interview"
label variable hv118_20 "Eligibility for male interview"
label variable hv120_01 "Children eligibility for height/weight and hemoglobin"
label variable hv120_02 "Children eligibility for height/weight and hemoglobin"
label variable hv120_03 "Children eligibility for height/weight and hemoglobin"
label variable hv120_04 "Children eligibility for height/weight and hemoglobin"
label variable hv120_05 "Children eligibility for height/weight and hemoglobin"
label variable hv120_06 "Children eligibility for height/weight and hemoglobin"
label variable hv120_07 "Children eligibility for height/weight and hemoglobin"
label variable hv120_08 "Children eligibility for height/weight and hemoglobin"
label variable hv120_09 "Children eligibility for height/weight and hemoglobin"
label variable hv120_10 "Children eligibility for height/weight and hemoglobin"
label variable hv120_11 "Children eligibility for height/weight and hemoglobin"
label variable hv120_12 "Children eligibility for height/weight and hemoglobin"
label variable hv120_13 "Children eligibility for height/weight and hemoglobin"
label variable hv120_14 "Children eligibility for height/weight and hemoglobin"
label variable hv120_15 "Children eligibility for height/weight and hemoglobin"
label variable hv120_16 "Children eligibility for height/weight and hemoglobin"
label variable hv120_17 "Children eligibility for height/weight and hemoglobin"
label variable hv120_18 "Children eligibility for height/weight and hemoglobin"
label variable hv120_19 "Children eligibility for height/weight and hemoglobin"
label variable hv120_20 "Children eligibility for height/weight and hemoglobin"
label variable hv121_01 "Member attended school during current school year"
label variable hv121_02 "Member attended school during current school year"
label variable hv121_03 "Member attended school during current school year"
label variable hv121_04 "Member attended school during current school year"
label variable hv121_05 "Member attended school during current school year"
label variable hv121_06 "Member attended school during current school year"
label variable hv121_07 "Member attended school during current school year"
label variable hv121_08 "Member attended school during current school year"
label variable hv121_09 "Member attended school during current school year"
label variable hv121_10 "Member attended school during current school year"
label variable hv121_11 "Member attended school during current school year"
label variable hv121_12 "Member attended school during current school year"
label variable hv121_13 "Member attended school during current school year"
label variable hv121_14 "Member attended school during current school year"
label variable hv121_15 "Member attended school during current school year"
label variable hv121_16 "Member attended school during current school year"
label variable hv121_17 "Member attended school during current school year"
label variable hv121_18 "Member attended school during current school year"
label variable hv121_19 "Member attended school during current school year"
label variable hv121_20 "Member attended school during current school year"
label variable hv122_01 "Educational level during current school year"
label variable hv122_02 "Educational level during current school year"
label variable hv122_03 "Educational level during current school year"
label variable hv122_04 "Educational level during current school year"
label variable hv122_05 "Educational level during current school year"
label variable hv122_06 "Educational level during current school year"
label variable hv122_07 "Educational level during current school year"
label variable hv122_08 "Educational level during current school year"
label variable hv122_09 "Educational level during current school year"
label variable hv122_10 "Educational level during current school year"
label variable hv122_11 "Educational level during current school year"
label variable hv122_12 "Educational level during current school year"
label variable hv122_13 "Educational level during current school year"
label variable hv122_14 "Educational level during current school year"
label variable hv122_15 "Educational level during current school year"
label variable hv122_16 "Educational level during current school year"
label variable hv122_17 "Educational level during current school year"
label variable hv122_18 "Educational level during current school year"
label variable hv122_19 "Educational level during current school year"
label variable hv122_20 "Educational level during current school year"
label variable hv123_01 "Grade of education during current school year"
label variable hv123_02 "Grade of education during current school year"
label variable hv123_03 "Grade of education during current school year"
label variable hv123_04 "Grade of education during current school year"
label variable hv123_05 "Grade of education during current school year"
label variable hv123_06 "Grade of education during current school year"
label variable hv123_07 "Grade of education during current school year"
label variable hv123_08 "Grade of education during current school year"
label variable hv123_09 "Grade of education during current school year"
label variable hv123_10 "Grade of education during current school year"
label variable hv123_11 "Grade of education during current school year"
label variable hv123_12 "Grade of education during current school year"
label variable hv123_13 "Grade of education during current school year"
label variable hv123_14 "Grade of education during current school year"
label variable hv123_15 "Grade of education during current school year"
label variable hv123_16 "Grade of education during current school year"
label variable hv123_17 "Grade of education during current school year"
label variable hv123_18 "Grade of education during current school year"
label variable hv123_19 "Grade of education during current school year"
label variable hv123_20 "Grade of education during current school year"
label variable hv124_01 "Education in single years - current school year"
label variable hv124_02 "Education in single years - current school year"
label variable hv124_03 "Education in single years - current school year"
label variable hv124_04 "Education in single years - current school year"
label variable hv124_05 "Education in single years - current school year"
label variable hv124_06 "Education in single years - current school year"
label variable hv124_07 "Education in single years - current school year"
label variable hv124_08 "Education in single years - current school year"
label variable hv124_09 "Education in single years - current school year"
label variable hv124_10 "Education in single years - current school year"
label variable hv124_11 "Education in single years - current school year"
label variable hv124_12 "Education in single years - current school year"
label variable hv124_13 "Education in single years - current school year"
label variable hv124_14 "Education in single years - current school year"
label variable hv124_15 "Education in single years - current school year"
label variable hv124_16 "Education in single years - current school year"
label variable hv124_17 "Education in single years - current school year"
label variable hv124_18 "Education in single years - current school year"
label variable hv124_19 "Education in single years - current school year"
label variable hv124_20 "Education in single years - current school year"
label variable hv125_01 "NA - Member attended school during previous school year"
label variable hv125_02 "NA - Member attended school during previous school year"
label variable hv125_03 "NA - Member attended school during previous school year"
label variable hv125_04 "NA - Member attended school during previous school year"
label variable hv125_05 "NA - Member attended school during previous school year"
label variable hv125_06 "NA - Member attended school during previous school year"
label variable hv125_07 "NA - Member attended school during previous school year"
label variable hv125_08 "NA - Member attended school during previous school year"
label variable hv125_09 "NA - Member attended school during previous school year"
label variable hv125_10 "NA - Member attended school during previous school year"
label variable hv125_11 "NA - Member attended school during previous school year"
label variable hv125_12 "NA - Member attended school during previous school year"
label variable hv125_13 "NA - Member attended school during previous school year"
label variable hv125_14 "NA - Member attended school during previous school year"
label variable hv125_15 "NA - Member attended school during previous school year"
label variable hv125_16 "NA - Member attended school during previous school year"
label variable hv125_17 "NA - Member attended school during previous school year"
label variable hv125_18 "NA - Member attended school during previous school year"
label variable hv125_19 "NA - Member attended school during previous school year"
label variable hv125_20 "NA - Member attended school during previous school year"
label variable hv126_01 "NA - Educational level during previous school year"
label variable hv126_02 "NA - Educational level during previous school year"
label variable hv126_03 "NA - Educational level during previous school year"
label variable hv126_04 "NA - Educational level during previous school year"
label variable hv126_05 "NA - Educational level during previous school year"
label variable hv126_06 "NA - Educational level during previous school year"
label variable hv126_07 "NA - Educational level during previous school year"
label variable hv126_08 "NA - Educational level during previous school year"
label variable hv126_09 "NA - Educational level during previous school year"
label variable hv126_10 "NA - Educational level during previous school year"
label variable hv126_11 "NA - Educational level during previous school year"
label variable hv126_12 "NA - Educational level during previous school year"
label variable hv126_13 "NA - Educational level during previous school year"
label variable hv126_14 "NA - Educational level during previous school year"
label variable hv126_15 "NA - Educational level during previous school year"
label variable hv126_16 "NA - Educational level during previous school year"
label variable hv126_17 "NA - Educational level during previous school year"
label variable hv126_18 "NA - Educational level during previous school year"
label variable hv126_19 "NA - Educational level during previous school year"
label variable hv126_20 "NA - Educational level during previous school year"
label variable hv127_01 "NA - Grade of education during previous school year"
label variable hv127_02 "NA - Grade of education during previous school year"
label variable hv127_03 "NA - Grade of education during previous school year"
label variable hv127_04 "NA - Grade of education during previous school year"
label variable hv127_05 "NA - Grade of education during previous school year"
label variable hv127_06 "NA - Grade of education during previous school year"
label variable hv127_07 "NA - Grade of education during previous school year"
label variable hv127_08 "NA - Grade of education during previous school year"
label variable hv127_09 "NA - Grade of education during previous school year"
label variable hv127_10 "NA - Grade of education during previous school year"
label variable hv127_11 "NA - Grade of education during previous school year"
label variable hv127_12 "NA - Grade of education during previous school year"
label variable hv127_13 "NA - Grade of education during previous school year"
label variable hv127_14 "NA - Grade of education during previous school year"
label variable hv127_15 "NA - Grade of education during previous school year"
label variable hv127_16 "NA - Grade of education during previous school year"
label variable hv127_17 "NA - Grade of education during previous school year"
label variable hv127_18 "NA - Grade of education during previous school year"
label variable hv127_19 "NA - Grade of education during previous school year"
label variable hv127_20 "NA - Grade of education during previous school year"
label variable hv128_01 "NA - Education in single years - previous school year"
label variable hv128_02 "NA - Education in single years - previous school year"
label variable hv128_03 "NA - Education in single years - previous school year"
label variable hv128_04 "NA - Education in single years - previous school year"
label variable hv128_05 "NA - Education in single years - previous school year"
label variable hv128_06 "NA - Education in single years - previous school year"
label variable hv128_07 "NA - Education in single years - previous school year"
label variable hv128_08 "NA - Education in single years - previous school year"
label variable hv128_09 "NA - Education in single years - previous school year"
label variable hv128_10 "NA - Education in single years - previous school year"
label variable hv128_11 "NA - Education in single years - previous school year"
label variable hv128_12 "NA - Education in single years - previous school year"
label variable hv128_13 "NA - Education in single years - previous school year"
label variable hv128_14 "NA - Education in single years - previous school year"
label variable hv128_15 "NA - Education in single years - previous school year"
label variable hv128_16 "NA - Education in single years - previous school year"
label variable hv128_17 "NA - Education in single years - previous school year"
label variable hv128_18 "NA - Education in single years - previous school year"
label variable hv128_19 "NA - Education in single years - previous school year"
label variable hv128_20 "NA - Education in single years - previous school year"
label variable hv129_01 "NA - School attendance status"
label variable hv129_02 "NA - School attendance status"
label variable hv129_03 "NA - School attendance status"
label variable hv129_04 "NA - School attendance status"
label variable hv129_05 "NA - School attendance status"
label variable hv129_06 "NA - School attendance status"
label variable hv129_07 "NA - School attendance status"
label variable hv129_08 "NA - School attendance status"
label variable hv129_09 "NA - School attendance status"
label variable hv129_10 "NA - School attendance status"
label variable hv129_11 "NA - School attendance status"
label variable hv129_12 "NA - School attendance status"
label variable hv129_13 "NA - School attendance status"
label variable hv129_14 "NA - School attendance status"
label variable hv129_15 "NA - School attendance status"
label variable hv129_16 "NA - School attendance status"
label variable hv129_17 "NA - School attendance status"
label variable hv129_18 "NA - School attendance status"
label variable hv129_19 "NA - School attendance status"
label variable hv129_20 "NA - School attendance status"
label variable hv140_01 "Member has a birth certificate"
label variable hv140_02 "Member has a birth certificate"
label variable hv140_03 "Member has a birth certificate"
label variable hv140_04 "Member has a birth certificate"
label variable hv140_05 "Member has a birth certificate"
label variable hv140_06 "Member has a birth certificate"
label variable hv140_07 "Member has a birth certificate"
label variable hv140_08 "Member has a birth certificate"
label variable hv140_09 "Member has a birth certificate"
label variable hv140_10 "Member has a birth certificate"
label variable hv140_11 "Member has a birth certificate"
label variable hv140_12 "Member has a birth certificate"
label variable hv140_13 "Member has a birth certificate"
label variable hv140_14 "Member has a birth certificate"
label variable hv140_15 "Member has a birth certificate"
label variable hv140_16 "Member has a birth certificate"
label variable hv140_17 "Member has a birth certificate"
label variable hv140_18 "Member has a birth certificate"
label variable hv140_19 "Member has a birth certificate"
label variable hv140_20 "Member has a birth certificate"
label variable idxh4_01 "Index to Household Schedule"
label variable idxh4_02 "Index to Household Schedule"
label variable idxh4_03 "Index to Household Schedule"
label variable idxh4_04 "Index to Household Schedule"
label variable idxh4_05 "Index to Household Schedule"
label variable idxh4_06 "Index to Household Schedule"
label variable idxh4_07 "Index to Household Schedule"
label variable idxh4_08 "Index to Household Schedule"
label variable idxh4_09 "Index to Household Schedule"
label variable idxh4_10 "Index to Household Schedule"
label variable idxh4_11 "Index to Household Schedule"
label variable idxh4_12 "Index to Household Schedule"
label variable idxh4_13 "Index to Household Schedule"
label variable idxh4_14 "Index to Household Schedule"
label variable idxh4_15 "Index to Household Schedule"
label variable idxh4_16 "Index to Household Schedule"
label variable idxh4_17 "Index to Household Schedule"
label variable idxh4_18 "Index to Household Schedule"
label variable idxh4_19 "Index to Household Schedule"
label variable idxh4_20 "Index to Household Schedule"
label variable sh06_01  "Country member is living in"
label variable sh06_02  "Country member is living in"
label variable sh06_03  "Country member is living in"
label variable sh06_04  "Country member is living in"
label variable sh06_05  "Country member is living in"
label variable sh06_06  "Country member is living in"
label variable sh06_07  "Country member is living in"
label variable sh06_08  "Country member is living in"
label variable sh06_09  "Country member is living in"
label variable sh06_10  "Country member is living in"
label variable sh06_11  "Country member is living in"
label variable sh06_12  "Country member is living in"
label variable sh06_13  "Country member is living in"
label variable sh06_14  "Country member is living in"
label variable sh06_15  "Country member is living in"
label variable sh06_16  "Country member is living in"
label variable sh06_17  "Country member is living in"
label variable sh06_18  "Country member is living in"
label variable sh06_19  "Country member is living in"
label variable sh06_20  "Country member is living in"
label variable sh07_01  "How long member has lived in country"
label variable sh07_02  "How long member has lived in country"
label variable sh07_03  "How long member has lived in country"
label variable sh07_04  "How long member has lived in country"
label variable sh07_05  "How long member has lived in country"
label variable sh07_06  "How long member has lived in country"
label variable sh07_07  "How long member has lived in country"
label variable sh07_08  "How long member has lived in country"
label variable sh07_09  "How long member has lived in country"
label variable sh07_10  "How long member has lived in country"
label variable sh07_11  "How long member has lived in country"
label variable sh07_12  "How long member has lived in country"
label variable sh07_13  "How long member has lived in country"
label variable sh07_14  "How long member has lived in country"
label variable sh07_15  "How long member has lived in country"
label variable sh07_16  "How long member has lived in country"
label variable sh07_17  "How long member has lived in country"
label variable sh07_18  "How long member has lived in country"
label variable sh07_19  "How long member has lived in country"
label variable sh07_20  "How long member has lived in country"
label variable sh19a_01 "Level of education attended"
label variable sh19a_02 "Level of education attended"
label variable sh19a_03 "Level of education attended"
label variable sh19a_04 "Level of education attended"
label variable sh19a_05 "Level of education attended"
label variable sh19a_06 "Level of education attended"
label variable sh19a_07 "Level of education attended"
label variable sh19a_08 "Level of education attended"
label variable sh19a_09 "Level of education attended"
label variable sh19a_10 "Level of education attended"
label variable sh19a_11 "Level of education attended"
label variable sh19a_12 "Level of education attended"
label variable sh19a_13 "Level of education attended"
label variable sh19a_14 "Level of education attended"
label variable sh19a_15 "Level of education attended"
label variable sh19a_16 "Level of education attended"
label variable sh19a_17 "Level of education attended"
label variable sh19a_18 "Level of education attended"
label variable sh19a_19 "Level of education attended"
label variable sh19a_20 "Level of education attended"
label variable sh21a_01 "Level of education attended in current school year"
label variable sh21a_02 "Level of education attended in current school year"
label variable sh21a_03 "Level of education attended in current school year"
label variable sh21a_04 "Level of education attended in current school year"
label variable sh21a_05 "Level of education attended in current school year"
label variable sh21a_06 "Level of education attended in current school year"
label variable sh21a_07 "Level of education attended in current school year"
label variable sh21a_08 "Level of education attended in current school year"
label variable sh21a_09 "Level of education attended in current school year"
label variable sh21a_10 "Level of education attended in current school year"
label variable sh21a_11 "Level of education attended in current school year"
label variable sh21a_12 "Level of education attended in current school year"
label variable sh21a_13 "Level of education attended in current school year"
label variable sh21a_14 "Level of education attended in current school year"
label variable sh21a_15 "Level of education attended in current school year"
label variable sh21a_16 "Level of education attended in current school year"
label variable sh21a_17 "Level of education attended in current school year"
label variable sh21a_18 "Level of education attended in current school year"
label variable sh21a_19 "Level of education attended in current school year"
label variable sh21a_20 "Level of education attended in current school year"
label variable ha0_1    "Index to Household Schedule"
label variable ha0_2    "Index to Household Schedule"
label variable ha0_3    "Index to Household Schedule"
label variable ha0_4    "Index to Household Schedule"
label variable ha0_5    "Index to Household Schedule"
label variable ha1_1    "Woman's age in years"
label variable ha1_2    "Woman's age in years"
label variable ha1_3    "Woman's age in years"
label variable ha1_4    "Woman's age in years"
label variable ha1_5    "Woman's age in years"
label variable ha2_1    "Woman's weight in kilograms (1 decimal)"
label variable ha2_2    "Woman's weight in kilograms (1 decimal)"
label variable ha2_3    "Woman's weight in kilograms (1 decimal)"
label variable ha2_4    "Woman's weight in kilograms (1 decimal)"
label variable ha2_5    "Woman's weight in kilograms (1 decimal)"
label variable ha3_1    "Woman's height in centimeters (1 decimal)"
label variable ha3_2    "Woman's height in centimeters (1 decimal)"
label variable ha3_3    "Woman's height in centimeters (1 decimal)"
label variable ha3_4    "Woman's height in centimeters (1 decimal)"
label variable ha3_5    "Woman's height in centimeters (1 decimal)"
label variable ha4_1    "Height/Age percentile"
label variable ha4_2    "Height/Age percentile"
label variable ha4_3    "Height/Age percentile"
label variable ha4_4    "Height/Age percentile"
label variable ha4_5    "Height/Age percentile"
label variable ha5_1    "Height/Age standard deviation"
label variable ha5_2    "Height/Age standard deviation"
label variable ha5_3    "Height/Age standard deviation"
label variable ha5_4    "Height/Age standard deviation"
label variable ha5_5    "Height/Age standard deviation"
label variable ha6_1    "Height/Age percent ref. median"
label variable ha6_2    "Height/Age percent ref. median"
label variable ha6_3    "Height/Age percent ref. median"
label variable ha6_4    "Height/Age percent ref. median"
label variable ha6_5    "Height/Age percent ref. median"
label variable ha11_1   "Weight/Height standard deviation (DHS)"
label variable ha11_2   "Weight/Height standard deviation (DHS)"
label variable ha11_3   "Weight/Height standard deviation (DHS)"
label variable ha11_4   "Weight/Height standard deviation (DHS)"
label variable ha11_5   "Weight/Height standard deviation (DHS)"
label variable ha12_1   "Weight/Height percent ref. median (DHS)"
label variable ha12_2   "Weight/Height percent ref. median (DHS)"
label variable ha12_3   "Weight/Height percent ref. median (DHS)"
label variable ha12_4   "Weight/Height percent ref. median (DHS)"
label variable ha12_5   "Weight/Height percent ref. median (DHS)"
label variable ha12a_1  "Weight/Height percent ref. median (Fog)"
label variable ha12a_2  "Weight/Height percent ref. median (Fog)"
label variable ha12a_3  "Weight/Height percent ref. median (Fog)"
label variable ha12a_4  "Weight/Height percent ref. median (Fog)"
label variable ha12a_5  "Weight/Height percent ref. median (Fog)"
label variable ha12b_1  "Weight/Height percent ref. median (WHO)"
label variable ha12b_2  "Weight/Height percent ref. median (WHO)"
label variable ha12b_3  "Weight/Height percent ref. median (WHO)"
label variable ha12b_4  "Weight/Height percent ref. median (WHO)"
label variable ha12b_5  "Weight/Height percent ref. median (WHO)"
label variable ha13_1   "Result of measurement - height/weight"
label variable ha13_2   "Result of measurement - height/weight"
label variable ha13_3   "Result of measurement - height/weight"
label variable ha13_4   "Result of measurement - height/weight"
label variable ha13_5   "Result of measurement - height/weight"
label variable ha32_1   "Date of birth (CMC)"
label variable ha32_2   "Date of birth (CMC)"
label variable ha32_3   "Date of birth (CMC)"
label variable ha32_4   "Date of birth (CMC)"
label variable ha32_5   "Date of birth (CMC)"
label variable ha33_1   "Completeness of HA32 information"
label variable ha33_2   "Completeness of HA32 information"
label variable ha33_3   "Completeness of HA32 information"
label variable ha33_4   "Completeness of HA32 information"
label variable ha33_5   "Completeness of HA32 information"
label variable ha35_1   "Smoking (cigarettes in last 24 hours)"
label variable ha35_2   "Smoking (cigarettes in last 24 hours)"
label variable ha35_3   "Smoking (cigarettes in last 24 hours)"
label variable ha35_4   "Smoking (cigarettes in last 24 hours)"
label variable ha35_5   "Smoking (cigarettes in last 24 hours)"
label variable ha40_1   "Body Mass Index"
label variable ha40_2   "Body Mass Index"
label variable ha40_3   "Body Mass Index"
label variable ha40_4   "Body Mass Index"
label variable ha40_5   "Body Mass Index"
label variable ha41_1   "Rohrer's index"
label variable ha41_2   "Rohrer's index"
label variable ha41_3   "Rohrer's index"
label variable ha41_4   "Rohrer's index"
label variable ha41_5   "Rohrer's index"
label variable ha50_1   "Under age 18"
label variable ha50_2   "Under age 18"
label variable ha50_3   "Under age 18"
label variable ha50_4   "Under age 18"
label variable ha50_5   "Under age 18"
label variable ha51_1   "Line number of parent/caretaker"
label variable ha51_2   "Line number of parent/caretaker"
label variable ha51_3   "Line number of parent/caretaker"
label variable ha51_4   "Line number of parent/caretaker"
label variable ha51_5   "Line number of parent/caretaker"
label variable ha52_1   "Read consent statement - hemoglobin"
label variable ha52_2   "Read consent statement - hemoglobin"
label variable ha52_3   "Read consent statement - hemoglobin"
label variable ha52_4   "Read consent statement - hemoglobin"
label variable ha52_5   "Read consent statement - hemoglobin"
label variable ha53_1   "Hemoglobin level (g/dl - 1 decimal)"
label variable ha53_2   "Hemoglobin level (g/dl - 1 decimal)"
label variable ha53_3   "Hemoglobin level (g/dl - 1 decimal)"
label variable ha53_4   "Hemoglobin level (g/dl - 1 decimal)"
label variable ha53_5   "Hemoglobin level (g/dl - 1 decimal)"
label variable ha54_1   "Currently pregnant"
label variable ha54_2   "Currently pregnant"
label variable ha54_3   "Currently pregnant"
label variable ha54_4   "Currently pregnant"
label variable ha54_5   "Currently pregnant"
label variable ha55_1   "Result of measurement - hemoglobin"
label variable ha55_2   "Result of measurement - hemoglobin"
label variable ha55_3   "Result of measurement - hemoglobin"
label variable ha55_4   "Result of measurement - hemoglobin"
label variable ha55_5   "Result of measurement - hemoglobin"
label variable ha56_1   "Hemoglobin level adjusted for altitude and smoking (g/dl - 1 decimal)"
label variable ha56_2   "Hemoglobin level adjusted for altitude and smoking (g/dl - 1 decimal)"
label variable ha56_3   "Hemoglobin level adjusted for altitude and smoking (g/dl - 1 decimal)"
label variable ha56_4   "Hemoglobin level adjusted for altitude and smoking (g/dl - 1 decimal)"
label variable ha56_5   "Hemoglobin level adjusted for altitude and smoking (g/dl - 1 decimal)"
label variable ha57_1   "Anemia level"
label variable ha57_2   "Anemia level"
label variable ha57_3   "Anemia level"
label variable ha57_4   "Anemia level"
label variable ha57_5   "Anemia level"
label variable ha58_1   "NA - Agrees to referral - anemia"
label variable ha58_2   "NA - Agrees to referral - anemia"
label variable ha58_3   "NA - Agrees to referral - anemia"
label variable ha58_4   "NA - Agrees to referral - anemia"
label variable ha58_5   "NA - Agrees to referral - anemia"
label variable ha60_1   "Marital status"
label variable ha60_2   "Marital status"
label variable ha60_3   "Marital status"
label variable ha60_4   "Marital status"
label variable ha60_5   "Marital status"
label variable ha61_1   "Read consent statement - HIV"
label variable ha61_2   "Read consent statement - HIV"
label variable ha61_3   "Read consent statement - HIV"
label variable ha61_4   "Read consent statement - HIV"
label variable ha61_5   "Read consent statement - HIV"
label variable ha62_1   "Bar code for HIV blood sample"
label variable ha62_2   "Bar code for HIV blood sample"
label variable ha62_3   "Bar code for HIV blood sample"
label variable ha62_4   "Bar code for HIV blood sample"
label variable ha62_5   "Bar code for HIV blood sample"
label variable ha63_1   "Result of measurement - HIV"
label variable ha63_2   "Result of measurement - HIV"
label variable ha63_3   "Result of measurement - HIV"
label variable ha63_4   "Result of measurement - HIV"
label variable ha63_5   "Result of measurement - HIV"
label variable ha64_1   "NA - Consent for additional tests"
label variable ha64_2   "NA - Consent for additional tests"
label variable ha64_3   "NA - Consent for additional tests"
label variable ha64_4   "NA - Consent for additional tests"
label variable ha64_5   "NA - Consent for additional tests"
label variable ha65_1   "Result of woman's individual interview"
label variable ha65_2   "Result of woman's individual interview"
label variable ha65_3   "Result of woman's individual interview"
label variable ha65_4   "Result of woman's individual interview"
label variable ha65_5   "Result of woman's individual interview"
label variable ha66_1   "Woman's highest educational level"
label variable ha66_2   "Woman's highest educational level"
label variable ha66_3   "Woman's highest educational level"
label variable ha66_4   "Woman's highest educational level"
label variable ha66_5   "Woman's highest educational level"
label variable ha67_1   "Woman's highest year of education"
label variable ha67_2   "Woman's highest year of education"
label variable ha67_3   "Woman's highest year of education"
label variable ha67_4   "Woman's highest year of education"
label variable ha67_5   "Woman's highest year of education"
label variable ha68_1   "Woman's highest educational level (for preliminary and final report)"
label variable ha68_2   "Woman's highest educational level (for preliminary and final report)"
label variable ha68_3   "Woman's highest educational level (for preliminary and final report)"
label variable ha68_4   "Woman's highest educational level (for preliminary and final report)"
label variable ha68_5   "Woman's highest educational level (for preliminary and final report)"
label variable ha69_1   "HIV weight (6 decimals)"
label variable ha69_2   "HIV weight (6 decimals)"
label variable ha69_3   "HIV weight (6 decimals)"
label variable ha69_4   "HIV weight (6 decimals)"
label variable ha69_5   "HIV weight (6 decimals)"
label variable ha70_1   "Interviewer that took blood for HIV testing"
label variable ha70_2   "Interviewer that took blood for HIV testing"
label variable ha70_3   "Interviewer that took blood for HIV testing"
label variable ha70_4   "Interviewer that took blood for HIV testing"
label variable ha70_5   "Interviewer that took blood for HIV testing"
label variable hc0_1    "Index to Household Schedule"
label variable hc0_2    "Index to Household Schedule"
label variable hc0_3    "Index to Household Schedule"
label variable hc0_4    "Index to Household Schedule"
label variable hc0_5    "Index to Household Schedule"
label variable hc1_1    "Child's age in months"
label variable hc1_2    "Child's age in months"
label variable hc1_3    "Child's age in months"
label variable hc1_4    "Child's age in months"
label variable hc1_5    "Child's age in months"
label variable hc2_1    "Child's weight in kilograms (1 decimal)"
label variable hc2_2    "Child's weight in kilograms (1 decimal)"
label variable hc2_3    "Child's weight in kilograms (1 decimal)"
label variable hc2_4    "Child's weight in kilograms (1 decimal)"
label variable hc2_5    "Child's weight in kilograms (1 decimal)"
label variable hc3_1    "Child's height in centimeters (1 decimal)"
label variable hc3_2    "Child's height in centimeters (1 decimal)"
label variable hc3_3    "Child's height in centimeters (1 decimal)"
label variable hc3_4    "Child's height in centimeters (1 decimal)"
label variable hc3_5    "Child's height in centimeters (1 decimal)"
label variable hc4_1    "Height/Age percentile"
label variable hc4_2    "Height/Age percentile"
label variable hc4_3    "Height/Age percentile"
label variable hc4_4    "Height/Age percentile"
label variable hc4_5    "Height/Age percentile"
label variable hc5_1    "Height/Age standard deviation"
label variable hc5_2    "Height/Age standard deviation"
label variable hc5_3    "Height/Age standard deviation"
label variable hc5_4    "Height/Age standard deviation"
label variable hc5_5    "Height/Age standard deviation"
label variable hc6_1    "Height/Age percent of ref. median"
label variable hc6_2    "Height/Age percent of ref. median"
label variable hc6_3    "Height/Age percent of ref. median"
label variable hc6_4    "Height/Age percent of ref. median"
label variable hc6_5    "Height/Age percent of ref. median"
label variable hc7_1    "Weight/Age percentile"
label variable hc7_2    "Weight/Age percentile"
label variable hc7_3    "Weight/Age percentile"
label variable hc7_4    "Weight/Age percentile"
label variable hc7_5    "Weight/Age percentile"
label variable hc8_1    "Weight/Age standard deviation"
label variable hc8_2    "Weight/Age standard deviation"
label variable hc8_3    "Weight/Age standard deviation"
label variable hc8_4    "Weight/Age standard deviation"
label variable hc8_5    "Weight/Age standard deviation"
label variable hc9_1    "Weight/Age percent of ref. median"
label variable hc9_2    "Weight/Age percent of ref. median"
label variable hc9_3    "Weight/Age percent of ref. median"
label variable hc9_4    "Weight/Age percent of ref. median"
label variable hc9_5    "Weight/Age percent of ref. median"
label variable hc10_1   "Weight/Height percentile"
label variable hc10_2   "Weight/Height percentile"
label variable hc10_3   "Weight/Height percentile"
label variable hc10_4   "Weight/Height percentile"
label variable hc10_5   "Weight/Height percentile"
label variable hc11_1   "Weight/Height standard deviation"
label variable hc11_2   "Weight/Height standard deviation"
label variable hc11_3   "Weight/Height standard deviation"
label variable hc11_4   "Weight/Height standard deviation"
label variable hc11_5   "Weight/Height standard deviation"
label variable hc12_1   "Weight/Height percent of ref. median"
label variable hc12_2   "Weight/Height percent of ref. median"
label variable hc12_3   "Weight/Height percent of ref. median"
label variable hc12_4   "Weight/Height percent of ref. median"
label variable hc12_5   "Weight/Height percent of ref. median"
label variable hc13_1   "Result of measurement - height/weight"
label variable hc13_2   "Result of measurement - height/weight"
label variable hc13_3   "Result of measurement - height/weight"
label variable hc13_4   "Result of measurement - height/weight"
label variable hc13_5   "Result of measurement - height/weight"
label variable hc15_1   "Height: lying or standing"
label variable hc15_2   "Height: lying or standing"
label variable hc15_3   "Height: lying or standing"
label variable hc15_4   "Height: lying or standing"
label variable hc15_5   "Height: lying or standing"
label variable hc16_1   "Day of birth"
label variable hc16_2   "Day of birth"
label variable hc16_3   "Day of birth"
label variable hc16_4   "Day of birth"
label variable hc16_5   "Day of birth"
label variable hc17_1   "Date measured (day)"
label variable hc17_2   "Date measured (day)"
label variable hc17_3   "Date measured (day)"
label variable hc17_4   "Date measured (day)"
label variable hc17_5   "Date measured (day)"
label variable hc18_1   "Date measured (month)"
label variable hc18_2   "Date measured (month)"
label variable hc18_3   "Date measured (month)"
label variable hc18_4   "Date measured (month)"
label variable hc18_5   "Date measured (month)"
label variable hc19_1   "Date measured (year)"
label variable hc19_2   "Date measured (year)"
label variable hc19_3   "Date measured (year)"
label variable hc19_4   "Date measured (year)"
label variable hc19_5   "Date measured (year)"
label variable hc27_1   "Sex"
label variable hc27_2   "Sex"
label variable hc27_3   "Sex"
label variable hc27_4   "Sex"
label variable hc27_5   "Sex"
label variable hc30_1   "Month of birth"
label variable hc30_2   "Month of birth"
label variable hc30_3   "Month of birth"
label variable hc30_4   "Month of birth"
label variable hc30_5   "Month of birth"
label variable hc31_1   "Year of birth"
label variable hc31_2   "Year of birth"
label variable hc31_3   "Year of birth"
label variable hc31_4   "Year of birth"
label variable hc31_5   "Year of birth"
label variable hc32_1   "Date of birth (CMC)"
label variable hc32_2   "Date of birth (CMC)"
label variable hc32_3   "Date of birth (CMC)"
label variable hc32_4   "Date of birth (CMC)"
label variable hc32_5   "Date of birth (CMC)"
label variable hc33_1   "Completeness of HC32 information"
label variable hc33_2   "Completeness of HC32 information"
label variable hc33_3   "Completeness of HC32 information"
label variable hc33_4   "Completeness of HC32 information"
label variable hc33_5   "Completeness of HC32 information"
label variable hc51_1   "Line number of parent/caretaker"
label variable hc51_2   "Line number of parent/caretaker"
label variable hc51_3   "Line number of parent/caretaker"
label variable hc51_4   "Line number of parent/caretaker"
label variable hc51_5   "Line number of parent/caretaker"
label variable hc52_1   "Read consent statement - hemoglobin"
label variable hc52_2   "Read consent statement - hemoglobin"
label variable hc52_3   "Read consent statement - hemoglobin"
label variable hc52_4   "Read consent statement - hemoglobin"
label variable hc52_5   "Read consent statement - hemoglobin"
label variable hc53_1   "Hemoglobin level (g/dl - 1 decimal)"
label variable hc53_2   "Hemoglobin level (g/dl - 1 decimal)"
label variable hc53_3   "Hemoglobin level (g/dl - 1 decimal)"
label variable hc53_4   "Hemoglobin level (g/dl - 1 decimal)"
label variable hc53_5   "Hemoglobin level (g/dl - 1 decimal)"
label variable hc55_1   "Result of measurement - hemoglobin"
label variable hc55_2   "Result of measurement - hemoglobin"
label variable hc55_3   "Result of measurement - hemoglobin"
label variable hc55_4   "Result of measurement - hemoglobin"
label variable hc55_5   "Result of measurement - hemoglobin"
label variable hc56_1   "Hemoglobin level adjusted for altitude (g/dl - 1 decimal)"
label variable hc56_2   "Hemoglobin level adjusted for altitude (g/dl - 1 decimal)"
label variable hc56_3   "Hemoglobin level adjusted for altitude (g/dl - 1 decimal)"
label variable hc56_4   "Hemoglobin level adjusted for altitude (g/dl - 1 decimal)"
label variable hc56_5   "Hemoglobin level adjusted for altitude (g/dl - 1 decimal)"
label variable hc57_1   "Anemia level"
label variable hc57_2   "Anemia level"
label variable hc57_3   "Anemia level"
label variable hc57_4   "Anemia level"
label variable hc57_5   "Anemia level"
label variable hc58_1   "NA - Agrees to referral - anemia"
label variable hc58_2   "NA - Agrees to referral - anemia"
label variable hc58_3   "NA - Agrees to referral - anemia"
label variable hc58_4   "NA - Agrees to referral - anemia"
label variable hc58_5   "NA - Agrees to referral - anemia"
label variable hc60_1   "Mother's line number (woman's questionnaire)"
label variable hc60_2   "Mother's line number (woman's questionnaire)"
label variable hc60_3   "Mother's line number (woman's questionnaire)"
label variable hc60_4   "Mother's line number (woman's questionnaire)"
label variable hc60_5   "Mother's line number (woman's questionnaire)"
label variable hc61_1   "Mother's highest educational level"
label variable hc61_2   "Mother's highest educational level"
label variable hc61_3   "Mother's highest educational level"
label variable hc61_4   "Mother's highest educational level"
label variable hc61_5   "Mother's highest educational level"
label variable hc62_1   "Mother's highest year of education"
label variable hc62_2   "Mother's highest year of education"
label variable hc62_3   "Mother's highest year of education"
label variable hc62_4   "Mother's highest year of education"
label variable hc62_5   "Mother's highest year of education"
label variable hc63_1   "Preceding birth interval (months)"
label variable hc63_2   "Preceding birth interval (months)"
label variable hc63_3   "Preceding birth interval (months)"
label variable hc63_4   "Preceding birth interval (months)"
label variable hc63_5   "Preceding birth interval (months)"
label variable hc64_1   "Birth order number"
label variable hc64_2   "Birth order number"
label variable hc64_3   "Birth order number"
label variable hc64_4   "Birth order number"
label variable hc64_5   "Birth order number"
label variable hc68_1   "Mother's highest educational level (for preliminary and final report)"
label variable hc68_2   "Mother's highest educational level (for preliminary and final report)"
label variable hc68_3   "Mother's highest educational level (for preliminary and final report)"
label variable hc68_4   "Mother's highest educational level (for preliminary and final report)"
label variable hc68_5   "Mother's highest educational level (for preliminary and final report)"
label variable hc70_1   "Height/Age standard deviation (new WHO)"
label variable hc70_2   "Height/Age standard deviation (new WHO)"
label variable hc70_3   "Height/Age standard deviation (new WHO)"
label variable hc70_4   "Height/Age standard deviation (new WHO)"
label variable hc70_5   "Height/Age standard deviation (new WHO)"
label variable hc71_1   "Weight/Age standard deviation (new WHO)"
label variable hc71_2   "Weight/Age standard deviation (new WHO)"
label variable hc71_3   "Weight/Age standard deviation (new WHO)"
label variable hc71_4   "Weight/Age standard deviation (new WHO)"
label variable hc71_5   "Weight/Age standard deviation (new WHO)"
label variable hc72_1   "Weight/Height standard deviation (new WHO)"
label variable hc72_2   "Weight/Height standard deviation (new WHO)"
label variable hc72_3   "Weight/Height standard deviation (new WHO)"
label variable hc72_4   "Weight/Height standard deviation (new WHO)"
label variable hc72_5   "Weight/Height standard deviation (new WHO)"
label variable hc73_1   "BMI standard deviation (new WHO)"
label variable hc73_2   "BMI standard deviation (new WHO)"
label variable hc73_3   "BMI standard deviation (new WHO)"
label variable hc73_4   "BMI standard deviation (new WHO)"
label variable hc73_5   "BMI standard deviation (new WHO)"
label variable hb0_1    "Index to Household Schedule"
label variable hb0_2    "Index to Household Schedule"
label variable hb0_3    "Index to Household Schedule"
label variable hb0_4    "Index to Household Schedule"
label variable hb0_5    "Index to Household Schedule"
label variable hb0_6    "Index to Household Schedule"
label variable hb1_1    "Man's age in years"
label variable hb1_2    "Man's age in years"
label variable hb1_3    "Man's age in years"
label variable hb1_4    "Man's age in years"
label variable hb1_5    "Man's age in years"
label variable hb1_6    "Man's age in years"
label variable hb2_1    "Man's weight in kilograms (1 decimal)"
label variable hb2_2    "Man's weight in kilograms (1 decimal)"
label variable hb2_3    "Man's weight in kilograms (1 decimal)"
label variable hb2_4    "Man's weight in kilograms (1 decimal)"
label variable hb2_5    "Man's weight in kilograms (1 decimal)"
label variable hb2_6    "Man's weight in kilograms (1 decimal)"
label variable hb3_1    "Man's height in centimeters (1 decimal)"
label variable hb3_2    "Man's height in centimeters (1 decimal)"
label variable hb3_3    "Man's height in centimeters (1 decimal)"
label variable hb3_4    "Man's height in centimeters (1 decimal)"
label variable hb3_5    "Man's height in centimeters (1 decimal)"
label variable hb3_6    "Man's height in centimeters (1 decimal)"
label variable hb4_1    "Height/Age percentile"
label variable hb4_2    "Height/Age percentile"
label variable hb4_3    "Height/Age percentile"
label variable hb4_4    "Height/Age percentile"
label variable hb4_5    "Height/Age percentile"
label variable hb4_6    "Height/Age percentile"
label variable hb5_1    "Height/Age standard deviation"
label variable hb5_2    "Height/Age standard deviation"
label variable hb5_3    "Height/Age standard deviation"
label variable hb5_4    "Height/Age standard deviation"
label variable hb5_5    "Height/Age standard deviation"
label variable hb5_6    "Height/Age standard deviation"
label variable hb6_1    "Height/Age percent ref. median"
label variable hb6_2    "Height/Age percent ref. median"
label variable hb6_3    "Height/Age percent ref. median"
label variable hb6_4    "Height/Age percent ref. median"
label variable hb6_5    "Height/Age percent ref. median"
label variable hb6_6    "Height/Age percent ref. median"
label variable hb11_1   "Weight/Height standard deviation (DHS)"
label variable hb11_2   "Weight/Height standard deviation (DHS)"
label variable hb11_3   "Weight/Height standard deviation (DHS)"
label variable hb11_4   "Weight/Height standard deviation (DHS)"
label variable hb11_5   "Weight/Height standard deviation (DHS)"
label variable hb11_6   "Weight/Height standard deviation (DHS)"
label variable hb12_1   "Weight/Height percent ref. median (DHS)"
label variable hb12_2   "Weight/Height percent ref. median (DHS)"
label variable hb12_3   "Weight/Height percent ref. median (DHS)"
label variable hb12_4   "Weight/Height percent ref. median (DHS)"
label variable hb12_5   "Weight/Height percent ref. median (DHS)"
label variable hb12_6   "Weight/Height percent ref. median (DHS)"
label variable hb12a_1  "Weight/Height percent ref. median (Fog)"
label variable hb12a_2  "Weight/Height percent ref. median (Fog)"
label variable hb12a_3  "Weight/Height percent ref. median (Fog)"
label variable hb12a_4  "Weight/Height percent ref. median (Fog)"
label variable hb12a_5  "Weight/Height percent ref. median (Fog)"
label variable hb12a_6  "Weight/Height percent ref. median (Fog)"
label variable hb12b_1  "Weight/Height percent ref. median (WHO)"
label variable hb12b_2  "Weight/Height percent ref. median (WHO)"
label variable hb12b_3  "Weight/Height percent ref. median (WHO)"
label variable hb12b_4  "Weight/Height percent ref. median (WHO)"
label variable hb12b_5  "Weight/Height percent ref. median (WHO)"
label variable hb12b_6  "Weight/Height percent ref. median (WHO)"
label variable hb13_1   "Result of measurement - height/weight"
label variable hb13_2   "Result of measurement - height/weight"
label variable hb13_3   "Result of measurement - height/weight"
label variable hb13_4   "Result of measurement - height/weight"
label variable hb13_5   "Result of measurement - height/weight"
label variable hb13_6   "Result of measurement - height/weight"
label variable hb32_1   "Date of birth (CMC)"
label variable hb32_2   "Date of birth (CMC)"
label variable hb32_3   "Date of birth (CMC)"
label variable hb32_4   "Date of birth (CMC)"
label variable hb32_5   "Date of birth (CMC)"
label variable hb32_6   "Date of birth (CMC)"
label variable hb33_1   "Completeness of HB32 information"
label variable hb33_2   "Completeness of HB32 information"
label variable hb33_3   "Completeness of HB32 information"
label variable hb33_4   "Completeness of HB32 information"
label variable hb33_5   "Completeness of HB32 information"
label variable hb33_6   "Completeness of HB32 information"
label variable hb35_1   "Smoking (cigarettes in last 24 hours)"
label variable hb35_2   "Smoking (cigarettes in last 24 hours)"
label variable hb35_3   "Smoking (cigarettes in last 24 hours)"
label variable hb35_4   "Smoking (cigarettes in last 24 hours)"
label variable hb35_5   "Smoking (cigarettes in last 24 hours)"
label variable hb35_6   "Smoking (cigarettes in last 24 hours)"
label variable hb40_1   "Body Mass Index"
label variable hb40_2   "Body Mass Index"
label variable hb40_3   "Body Mass Index"
label variable hb40_4   "Body Mass Index"
label variable hb40_5   "Body Mass Index"
label variable hb40_6   "Body Mass Index"
label variable hb41_1   "Rohrer's index"
label variable hb41_2   "Rohrer's index"
label variable hb41_3   "Rohrer's index"
label variable hb41_4   "Rohrer's index"
label variable hb41_5   "Rohrer's index"
label variable hb41_6   "Rohrer's index"
label variable hb50_1   "Under age 18"
label variable hb50_2   "Under age 18"
label variable hb50_3   "Under age 18"
label variable hb50_4   "Under age 18"
label variable hb50_5   "Under age 18"
label variable hb50_6   "Under age 18"
label variable hb51_1   "Line number of parent/caretaker"
label variable hb51_2   "Line number of parent/caretaker"
label variable hb51_3   "Line number of parent/caretaker"
label variable hb51_4   "Line number of parent/caretaker"
label variable hb51_5   "Line number of parent/caretaker"
label variable hb51_6   "Line number of parent/caretaker"
label variable hb52_1   "Read consent statement - hemoglobin"
label variable hb52_2   "Read consent statement - hemoglobin"
label variable hb52_3   "Read consent statement - hemoglobin"
label variable hb52_4   "Read consent statement - hemoglobin"
label variable hb52_5   "Read consent statement - hemoglobin"
label variable hb52_6   "Read consent statement - hemoglobin"
label variable hb53_1   "Hemoglobin level (g/dl - 1 decimal)"
label variable hb53_2   "Hemoglobin level (g/dl - 1 decimal)"
label variable hb53_3   "Hemoglobin level (g/dl - 1 decimal)"
label variable hb53_4   "Hemoglobin level (g/dl - 1 decimal)"
label variable hb53_5   "Hemoglobin level (g/dl - 1 decimal)"
label variable hb53_6   "Hemoglobin level (g/dl - 1 decimal)"
label variable hb55_1   "Result of measurement - hemoglobin"
label variable hb55_2   "Result of measurement - hemoglobin"
label variable hb55_3   "Result of measurement - hemoglobin"
label variable hb55_4   "Result of measurement - hemoglobin"
label variable hb55_5   "Result of measurement - hemoglobin"
label variable hb55_6   "Result of measurement - hemoglobin"
label variable hb56_1   "Hemoglobin level adjusted for altitude and smoking (g/dl - 1 decimal)"
label variable hb56_2   "Hemoglobin level adjusted for altitude and smoking (g/dl - 1 decimal)"
label variable hb56_3   "Hemoglobin level adjusted for altitude and smoking (g/dl - 1 decimal)"
label variable hb56_4   "Hemoglobin level adjusted for altitude and smoking (g/dl - 1 decimal)"
label variable hb56_5   "Hemoglobin level adjusted for altitude and smoking (g/dl - 1 decimal)"
label variable hb56_6   "Hemoglobin level adjusted for altitude and smoking (g/dl - 1 decimal)"
label variable hb57_1   "Anemia level"
label variable hb57_2   "Anemia level"
label variable hb57_3   "Anemia level"
label variable hb57_4   "Anemia level"
label variable hb57_5   "Anemia level"
label variable hb57_6   "Anemia level"
label variable hb58_1   "NA - Agrees to referral - anemia"
label variable hb58_2   "NA - Agrees to referral - anemia"
label variable hb58_3   "NA - Agrees to referral - anemia"
label variable hb58_4   "NA - Agrees to referral - anemia"
label variable hb58_5   "NA - Agrees to referral - anemia"
label variable hb58_6   "NA - Agrees to referral - anemia"
label variable hb60_1   "Marital status"
label variable hb60_2   "Marital status"
label variable hb60_3   "Marital status"
label variable hb60_4   "Marital status"
label variable hb60_5   "Marital status"
label variable hb60_6   "Marital status"
label variable hb61_1   "Read consent statement - HIV"
label variable hb61_2   "Read consent statement - HIV"
label variable hb61_3   "Read consent statement - HIV"
label variable hb61_4   "Read consent statement - HIV"
label variable hb61_5   "Read consent statement - HIV"
label variable hb61_6   "Read consent statement - HIV"
label variable hb62_1   "Bar code for HIV blood sample"
label variable hb62_2   "Bar code for HIV blood sample"
label variable hb62_3   "Bar code for HIV blood sample"
label variable hb62_4   "Bar code for HIV blood sample"
label variable hb62_5   "Bar code for HIV blood sample"
label variable hb62_6   "Bar code for HIV blood sample"
label variable hb63_1   "Result of measurement - HIV"
label variable hb63_2   "Result of measurement - HIV"
label variable hb63_3   "Result of measurement - HIV"
label variable hb63_4   "Result of measurement - HIV"
label variable hb63_5   "Result of measurement - HIV"
label variable hb63_6   "Result of measurement - HIV"
label variable hb64_1   "NA - Consent for additional tests"
label variable hb64_2   "NA - Consent for additional tests"
label variable hb64_3   "NA - Consent for additional tests"
label variable hb64_4   "NA - Consent for additional tests"
label variable hb64_5   "NA - Consent for additional tests"
label variable hb64_6   "NA - Consent for additional tests"
label variable hb65_1   "Result of man's individual interview"
label variable hb65_2   "Result of man's individual interview"
label variable hb65_3   "Result of man's individual interview"
label variable hb65_4   "Result of man's individual interview"
label variable hb65_5   "Result of man's individual interview"
label variable hb65_6   "Result of man's individual interview"
label variable hb66_1   "Man's highest educational level"
label variable hb66_2   "Man's highest educational level"
label variable hb66_3   "Man's highest educational level"
label variable hb66_4   "Man's highest educational level"
label variable hb66_5   "Man's highest educational level"
label variable hb66_6   "Man's highest educational level"
label variable hb67_1   "Man's highest year of education"
label variable hb67_2   "Man's highest year of education"
label variable hb67_3   "Man's highest year of education"
label variable hb67_4   "Man's highest year of education"
label variable hb67_5   "Man's highest year of education"
label variable hb67_6   "Man's highest year of education"
label variable hb68_1   "Man's highest educational level (for preliminary and final report)"
label variable hb68_2   "Man's highest educational level (for preliminary and final report)"
label variable hb68_3   "Man's highest educational level (for preliminary and final report)"
label variable hb68_4   "Man's highest educational level (for preliminary and final report)"
label variable hb68_5   "Man's highest educational level (for preliminary and final report)"
label variable hb68_6   "Man's highest educational level (for preliminary and final report)"
label variable hb69_1   "HIV weight (6 decimals)"
label variable hb69_2   "HIV weight (6 decimals)"
label variable hb69_3   "HIV weight (6 decimals)"
label variable hb69_4   "HIV weight (6 decimals)"
label variable hb69_5   "HIV weight (6 decimals)"
label variable hb69_6   "HIV weight (6 decimals)"
label variable hb70_1   "Interviewer that took blood for HIV testing"
label variable hb70_2   "Interviewer that took blood for HIV testing"
label variable hb70_3   "Interviewer that took blood for HIV testing"
label variable hb70_4   "Interviewer that took blood for HIV testing"
label variable hb70_5   "Interviewer that took blood for HIV testing"
label variable hb70_6   "Interviewer that took blood for HIV testing"

#delimit ;
label define HV003   
     0 "Incomplete household"
;
label define HV015   
     1 "Completed"
     2 "No Household member/no competent member at home"
     3 "Entire Household absent for extended period of time"
     4 "Postponed"
     5 "Refused"
     6 "Dwelling vacant or address not a dwelling"
     7 "Dwelling destroyed"
     8 "Dwelling not found"
     9 "Other"
;
label define HV017   
     9 "Missing"
;
label define HV018   
   999 "Missing"
;
label define HV020   
     0 "All woman sample"
     1 "Ever married sample"
;
label define HV022   
     1 "Botha-bothe - Rural"
     2 "Botha-bothe - Urban"
     3 "Leribe - Rural"
     4 "Leribe - Urban"
     5 "Berea - Rural"
     6 "Berea - Urban"
     7 "Maseru - Rural"
     8 "Maseru - Urban"
     9 "Mafeteng - Rural"
    10 "Mafeteng - Urban"
    11 "Mohale's hoek - Rural"
    12 "Mohale's hoek - Urban"
    13 "Quthing - Rural"
    14 "Quthing - Urban"
    15 "Qacha's-nek - Rural"
    16 "Qacha's-nek - Urban"
    17 "Mokhotlong - Rural"
    18 "Mokhotlong - Urban"
    19 "Thaba Tseka - Rural"
    20 "Thaba Tseka - Urban"
;
label define HV023   
     1 "Botha-bothe - Rural"
     2 "Botha-bothe - Urban"
     3 "Leribe - Rural"
     4 "Leribe - Urban"
     5 "Berea - Rural"
     6 "Berea - Urban"
     7 "Maseru - Rural"
     8 "Maseru - Urban"
     9 "Mafeteng - Rural"
    10 "Mafeteng - Urban"
    11 "Mohale's hoek - Rural"
    12 "Mohale's hoek - Urban"
    13 "Quthing - Rural"
    14 "Quthing - Urban"
    15 "Qacha's-nek - Rural"
    16 "Qacha's-nek - Urban"
    17 "Mokhotlong - Rural"
    18 "Mokhotlong - Urban"
    19 "Thaba Tseka - Rural"
    20 "Thaba Tseka - Urban"
;
label define HV024   
     1 "Botha-bothe"
     2 "Leribe"
     3 "Berea"
     4 "Maseru"
     5 "Mafeteng"
     6 "Mohale's hoek"
     7 "Quthing"
     8 "Qacha's-nek"
     9 "Mokhotlong"
    10 "Thaba Tseka"
;
label define HV025   
     1 "Urban"
     2 "Rural"
;
label define HV026   
     0 "Capital, large city"
     1 "Small city"
     2 "Town"
     3 "Countryside"
;
label define HV027   
     0 "Not selected"
     1 "Men's survey"
     2 "Husband's survey"
;
label define HV030   
   999 "Missing"
;
label define HV040   
  9999 "Missing"
;
label define HV042   
     0 "Not selected"
     1 "Selected"
;
label define HV044   
     0 "Household not selected"
     1 "Household selected"
;
label define HV201   
    10 "PIPED WATER"
    11 "Piped into dwelling"
    12 "Piped to yard/plot"
    13 "Public tap/standpipe"
    14 "Neighbour's tap"
    20 "TUBE WELL WATER"
    21 "Tube well or borehole"
    30 "DUG WELL (OPEN/PROTECTED)"
    31 "Protected well"
    32 "Unprotected well"
    40 "SURFACE WATER"
    41 "Protected spring"
    42 "Unprotected spring"
    43 "River/dam/lake/ponds/stream/canal/irrigation channel"
    51 "Rainwater"
    61 "Tanker truck"
    62 "Cart with small tank"
    71 "Bottled water"
    96 "Other"
;
label define HV202   
    10 "PIPED WATER"
    11 "Piped into dwelling"
    12 "Piped to yard/plot"
    13 "Public tap/standpipe"
    20 "TUBE WELL WATER"
    21 "Tube well or borehole"
    30 "DUG WELL (OPEN/PROTECTED)"
    31 "Protected well"
    32 "Unprotected well"
    40 "SURFACE WATER"
    41 "Protected spring"
    42 "Unprotected spring"
    43 "River/dam/lake/ponds/stream/canal/irrigation channel"
    51 "Rainwater"
    61 "Tanker truck"
    62 "Cart with small tank"
    71 "Bottled water"
    96 "Other"
;
label define HV204   
   996 "On premises"
   998 "Don't know"
;
label define HV205   
    10 "FLUSH TOILET"
    11 "Flush to piped sewer system"
    12 "Flush to septic tank"
    13 "Flush to pit latrine"
    14 "Flush to somewhere else"
    15 "Flush, don't know where"
    20 "PIT TOILET LATRINE"
    21 "Ventilated Improved Pit latrine (VIP)"
    22 "Pit latrine with slab"
    23 "Pit latrine without slab/open pit"
    30 "NO FACILITY"
    31 "No facility/bush/field"
    41 "Composting toilet"
    42 "Bucket toilet"
    43 "Hanging toilet/latrine"
    96 "Other"
;
label define HV206   
     0 "No"
     1 "Yes"
;
label define HV207   
     0 "No"
     1 "Yes"
;
label define HV208   
     0 "No"
     1 "Yes"
;
label define HV209   
     0 "No"
     1 "Yes"
;
label define HV210   
     0 "No"
     1 "Yes"
;
label define HV211   
     0 "No"
     1 "Yes"
;
label define HV212   
     0 "No"
     1 "Yes"
;
label define HV213   
    10 "NATURAL"
    11 "Earth/mud/dung"
    20 "Rudimentary"
    21 "Wood planks"
    30 "FINISHED"
    31 "Parquet or polished wood"
    32 "Vinyl tile/vinyl carpet"
    33 "Ceramic tiles"
    34 "Cement"
    35 "Carpet"
    96 "Other"
;
label define HV214   
    10 "NATURAL"
    11 "Cane/tree trunks"
    12 "Sod"
    20 "Rudimentary"
    21 "Stone with mud"
    22 "Plywood"
    23 "Cardboard"
    24 "Reused wood"
    30 "FINISHED"
    31 "Cement"
    32 "Stone with lime/cement"
    33 "Bricks"
    34 "Cement blocks"
    35 "Wood planks/shingles/metal/corrugated"
    96 "Other"
;
label define HV215   
    10 "NATURAL"
    11 "Thatch/grass"
    12 "Sod"
    20 "RUDIMENTARY"
    21 "Wood planks"
    22 "Cardboard"
    30 "FINISHED"
    31 "Metal/corrugated"
    32 "Wood"
    33 "Asbestos/cement fiber"
    34 "Ceramic/clay tiles"
    35 "Cement"
    36 "Roofing shingles"
    96 "Other"
;
label define HV216   
    99 "Missing"
;
label define HV217   
     0 "No adults"
     1 "One adult"
     2 "Two adults, opposite sex"
     3 "Two adults, same sex"
     4 "Three+ related adults"
     5 "Unrelated adults"
;
label define HV219   
     1 "Male"
     2 "Female"
;
label define HV220   
    97 "97+"
    98 "Don't know"
;
label define HV221   
     0 "No"
     1 "Yes"
;
label define HV225   
     0 "No"
     1 "Yes"
;
label define HV226   
     1 "Electricity"
     2 "LPG"
     3 "Natural gas"
     4 "Biogas"
     5 "Kerosene"
     6 "Coal, lignite"
     7 "Charcoal"
     8 "Wood"
     9 "Straw/shrubs/grass"
    10 "Agricultural crop"
    11 "Animal dung"
    95 "No food cooked in house"
    96 "Other"
;
label define HV227   
     0 "No"
     1 "Yes"
;
label define HV228   
     0 "No"
     1 "All children"
     2 "Some children"
     3 "No net in household"
;
label define HV230A  
     1 "Observed"
     2 "Not observed: not in dwelling"
     3 "Not observed: no permission to see"
     4 "Not observed: other reason"
     5 "Not observed, no specific place"
;
label define HV230B  
     0 "Water not available"
     1 "Water is available"
;
label define HV232   
     0 "No"
     1 "Yes"
;
label define HV232B  
     0 "No"
     1 "Yes"
;
label define HV232C  
     0 "No"
     1 "Yes"
;
label define HV232D  
     0 "No"
     1 "Yes"
;
label define HV232E  
     0 "No"
     1 "Yes"
;
label define HV232Y  
     0 "No"
     1 "Yes: no cleansing agent observed"
;
label define HV234   
     0 "0 PPM (no iodine)"
     7 "Below 15 PPM"
    15 "15 PPM and above"
    30 "30 PPM"
   994 "Salt not tested"
   995 "No salt in household"
;
label define HV234A  
     0 "No iodine"
     1 "Iodine present"
     3 "No salt in household"
     6 "Salt not tested"
;
label define HV235   
     1 "In own dwelling"
     2 "In own yard/plot"
     3 "Elsewhere"
;
label define HV236   
     1 "Adult woman"
     2 "Adult man"
     3 "Female child under 15 years old"
     4 "Male child under 15 years old"
     6 "Other"
;
label define HV237   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237A  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237B  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237C  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237D  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237E  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237F  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237G  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237H  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237I  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237J  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237K  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237X  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237Z  
     0 "No"
     1 "Yes: don't know what is done to water"
     8 "Don't know"
;
label define HV238   
    95 "10 or more households"
    98 "Don't know"
;
label define HV239   
     1 "Open fire"
     2 "Open stove"
     3 "Closed stove with chimney"
     6 "Other"
;
label define HV240   
     0 "Neither chimney or hood"
     1 "Chimney"
     2 "Hood"
;
label define HV241   
     1 "In the house"
     2 "In a separate building"
     3 "Outdoors"
     6 "Other"
;
label define HV242   
     0 "No"
     1 "Yes"
;
label define HV243A  
     0 "No"
     1 "Yes"
;
label define HV243B  
     0 "No"
     1 "Yes"
;
label define HV243C  
     0 "No"
     1 "Yes"
;
label define HV243D  
     0 "No"
     1 "Yes"
;
label define HV244   
     0 "No"
     1 "Yes"
;
label define HV245   
   950 "95 or more"
   998 "Unknown"
;
label define HV246   
     0 "No"
     1 "Yes"
;
label define HV246A  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246B  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246C  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246D  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246E  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246F  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246G  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246H  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246I  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246J  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246K  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV247   
     0 "No"
     1 "Yes"
;
label define HV252   
     0 "Never"
     1 "Daily"
     2 "Weekly"
     3 "Monthly"
     4 "Less than monthly"
;
label define HV253   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV253A  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV253B  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV253C  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV253D  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV253E  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV253F  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV253G  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV253H  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV253X  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV253Z  
     0 "No"
     1 "Yes: don't know who sprayed the dwelling"
     8 "Don't know if it was sprayed"
;
label define HV270   
     1 "Poorest"
     2 "Poorer"
     3 "Middle"
     4 "Richer"
     5 "Richest"
;
label define HML1    
    98 "Don't know"
;
label define HML2    
    99 "Missing"
;
label define SHZONE  
     1 "Lowlands"
     2 "Foothills"
     3 "Mountains"
     4 "Senqu River Valley"
;
label define SH110B  
     1 "Yes"
     0 "No"
;
label define SH110C  
     1 "Yes"
     0 "No"
;
label define SH110I  
     1 "Yes"
     0 "No"
;
label define SH110J  
     1 "Yes"
     0 "No"
;
label define SH110K  
     1 "Yes"
     0 "No"
;
label define SH122K  
     0 "None"
    95 "More than 95"
    98 "Unknown"
;
label define SH124   
     1 "Abia (St Josephs)"
     2 "Auray health center"
     3 "Bafokeng"
     4 "Bathopele clinic"
     5 "Beautitude"
     6 "Berea govt hospital"
     7 "Berea private"
     8 "Bethany mission health center"
     9 "Bethel health center"
    10 "Bobete health center"
    11 "Boiketsiso health center"
    12 "Bongani Leseli nursing health center"
    13 "Bophelong private clinic"
    14 "Botha-Bothe govt hospital"
    15 "Bots'abelo leprosy hospital"
    16 "Carewell health center"
    17 "Caselin clinic"
    18 "Cehal private clinic"
    19 "Center for equal health access clinic"
    20 "City clinic"
    21 "Dilli-Dilli health center"
    22 "Domicilliary health center"
    23 "Dual clinic"
    24 "Emmanuel health center"
    25 "Emmaus health center"
    26 "Fatima/Ramabanta health center"
    27 "Fobane health center"
    28 "Gateway clinic (Queen ‘mamohato memorial hospital)"
    29 "Good shepherd health center"
    30 "Ha Lephoi health center"
    31 "Ha Makoae health center"
    32 "Ha Mokoto health center"
    33 "Ha Pita health center"
    34 "Ha Popa health center"
    35 "Ha Seng health center"
    36 "Ha TŠepo health center"
    37 "Ha-Tlali health center"
    38 "Hanson (private) clinic"
    39 "Health care clinic"
    40 "Hermitage health center"
    41 "Holy Cross health center"
    42 "Immaculate conception"
    43 "Jesse polyclinic"
    44 "Katleho clinic"
    45 "Katse health center"
    46 "Kena health center"
    47 "Khabo health center"
    48 "Khubetsoana health center"
    49 "Koali health center"
    50 "Kolberg/khohlontŠo"
    51 "Kolo health center"
    52 "Kolojane health center"
    53 "Korokoro health center (St. Joseph)"
    54 "Kuebunyane health center"
    55 "L&L family clinic"
    56 "Lebakeng health center"
    57 "Leco-op health center"
    58 "Lehlakeng health center"
    59 "Lejone health center"
    60 "Lenkotong clinic"
    61 "Leqele clinic"
    62 "Leseli (private)"
    63 "Leseli (thabaneng) clinic"
    64 "Lesotho college of education (LCE) clinic"
    65 "Lesotho Planned Parenthood Association (LPPA)"
    66 "LetŠeng diamond mine clinic"
    67 "Libibing health center"
    68 "Likalaneng health center"
    69 "Likotsi filter clinic"
    70 "Linakaneng health center"
    71 "Linakeng (BB) health center"
    72 "Linakeng health center (TT)"
    73 "Linotsing health center"
    74 "Liphiring health center"
    75 "Lisemelo health center"
    76 "Lithipeng health center"
    77 "Little Flower health center"
    78 "LitŠoeneng health center"
    79 "Loretto health center"
    80 "Louis Gerard health center"
    81 "Mabatho clinic"
    82 "Mabote filter clinic"
    83 "Machabeng hospital"
    84 "Mafeteng govt hospital"
    85 "Mafube clinic"
    86 "Mahlatsa health center"
    87 "Mahlompho clinic"
    88 "Mahobong health center"
    89 "Mahobong Holy Trinity health center"
    90 "Makhalanyane clinic"
    91 "Makoa private"
    92 "Makoanyane Military Hospital"
    93 "Malea-Lea health center"
    94 "Maluti hospital"
    95 "Manamaneng health center"
    96 "Manthati (ha seetsi) clinic"
    97 "Mapheleng health center"
    98 "Mapholaneng health center"
    99 "Maputsoe filter clinic"
   100 "Maputsoe SDA Health Center"
   101 "Maqhaka Health Center (HOLY FAMILY)"
   102 "Maqokho Health Center"
   103 "MarakabeI Health Center"
   104 "Maryland Health Center"
   105 "MasechabA CLINIC"
   106 "MasemousE Health Center"
   107 "Maseru children center of exellence"
   108 "MASERU CORRECTIONAL SERVICES CLINIC"
   109 "MASERU PRIVATE HOSPITAL"
   110 "MASERU SDA Health Center"
   111 "MASIANOKENG CLINIC"
   112 "MATEBENG Health Center"
   113 "MATELILE Health Center"
   114 "MATLAMENG Health Center"
   115 "MATSIENG Health Center"
   116 "MATUKENG Health Center"
   117 "MEDICAL ARTS CLINIC"
   118 "MELIKANE Health Center"
   119 "METHALANENG Health Center"
   120 "MOEKETSANE Health Center"
   121 "MOFOKA Health Center"
   122 "MOFUMAHALI OA ROSARI Health Center"
   123 "MOHALE Health Center"
   124 "MOHALEROE PRIVATE"
   125 "MOHALE’S HOEK CORRECTIONAL SERVICES"
   126 "MOHALINYANE Health Center"
   127 "MOHLANAPENG Health Center"
   128 "MOHLAPISO Health Center"
   129 "MOHLOMI MENTAL HOSPITAL"
   130 "MOKHOTLONG HOSPITAL"
   131 "MOLIKALIKO Health Center"
   132 "MOLOPI CLINIC"
   133 "MONTMARTRE Health Center"
   134 "MOOTSINYANE Health Center"
   135 "MORIFI Health Center"
   136 "MOTEBANG HOSPITAL"
   137 "MOTETE Health Center"
   138 "MOTSEKUOA Health Center"
   139 "MOUNT TABOR Health Center"
   140 "MPHAKI Health Center"
   141 "MPHARANE Health Center"
   142 "Mt OLIVET Health Center"
   143 "N.U.L. Health Center"
   144 "NAZARETH Health Center"
   145 "NGOAJANE/KHATIBE Health Center"
   146 "NKAU Health Center"
   147 "NOHANA Health Center"
   148 "NTŠEKHE HOSPITAL"
   149 "OSMAN (PRIVATE)"
   150 "OUR LADY OF LOURDES/MOSITI Health Center"
   151 "PABALLONG PRIVATE ART CENTRE"
   152 "PAKI Health Center"
   153 "PALAMA Health Center"
   154 "PARAY MISSION HOSPITAL"
   155 "PEKA Health Center"
   156 "PHAMONG Health Center"
   157 "PHELA-U-PHELISE CLINIC"
   158 "PILOT Health Center"
   159 "PONTMAIN Health Center"
   160 "PSHATLELLA Health Center"
   161 "QHOLAQHOE Health Center (MAKHUNOANE)"
   162 "QOALING FILTER CLINIC"
   163 "QUEEN ‘MAMOHATO MEMORIAL HOSPITAL"
   164 "QUTHING GovernmentHOSPITAL"
   165 "R.L.D.F. Health Center"
   166 "RAMPAI Health Center"
   167 "RANKAKALA Health Center"
   168 "RIBANENG Health Center"
   169 "ROSYM CLINIC"
   170 "SACRED HEART Health Center"
   171 "SAMARIA Health Center"
   172 "SCOTT MISSION HOSPITAL"
   173 "SEBEDIA Health Center"
   174 "SEBOCHE HOSPITAL"
   175 "SEETSA Health Center"
   176 "SEHLABA-THEBE Health Center"
   177 "SEHONG-HONG Health Center"
   178 "SEKAKE Health Center"
   179 "SEKAMANENG CLINIC"
   180 "SEKAMENG Health Center"
   181 "SEMENANYANA Health Center"
   182 "SEMONKONG Health Center"
   183 "SENKATANA CLINIC"
   184 "SEPINARE Health Center"
   185 "SESHOTE Health Center"
   186 "SHIFAa CLINIC"
   187 "SION Health Center"
   188 "SOS CLINIC"
   189 "SPRINGFIELD Health Center"
   190 "ST ANDREW Health Center"
   191 "ST ANNE Health Center"
   192 "ST BARNABAS Health Center (MASITE)"
   193 "ST BENEDICT Health Center"
   194 "ST BERNARD Health Center"
   195 "ST CLARE Health Center"
   196 "ST DAVID Health Center"
   197 "ST DENIS Health Center"
   198 "ST FRANCIS Health Center"
   199 "ST GABRIEL Health Center"
   200 "ST JAMES Health Center"
   201 "ST JAMES MISSION HOSPITAL"
   202 "ST JOSEPHS HOSPITAL"
   203 "ST LEO Health Center"
   204 "ST LEONARD Health Center"
   205 "ST MAGDALENA Health Center"
   206 "ST MARGRET Health Center"
   207 "ST MARTIN Health Center"
   208 "ST MATTHEWS Health Center"
   209 "ST MONICAS Health Center"
   210 "ST PAUL Health Center"
   211 "ST PETER CLAVER Health Center (TŠOENENG)"
   212 "ST PETER'S Health Center"
   213 "ST PETERS Health Center (MOTENG)"
   214 "ST RODRIGUE Health Center"
   215 "ST ROSE Health Center"
   216 "ST THERESA Health Center"
   217 "ST THERESA (BELA-BELA) Health Center"
   218 "TEBELLONG HOSPITAL"
   219 "THABA TŠOEU Health Center"
   220 "THABA-BOSIU Health Center"
   221 "THABA-PHAT?OA Health Center"
   222 "THABA-TSEKA Health Center"
   223 "THABANA-MORENA Health Center"
   224 "THAMAE Health Center"
   225 "THUSANANG Health Center"
   226 "TLHANYAKU Health Center"
   227 "TSATSANE Health Center"
   228 "TSIME Health Center"
   229 "TŠAKHOLO Health Center"
   230 "TŠENOLA PRIVATEC LINIC(MAMA'S)"
   231 "VILLA MARIA Health Center"
   232 "WILLIES CLINIC"
   233 "‘MALEFILOANE Health Center"
   234 "‘MAMOHAU MISSION HOSPITAL"
   235 "‘MUELA SITE Health Center"
   236 "‘NELESE CLINIC"
   996 "Other"
   998 "Don't know"
;
label define SH125   
     1 "Car/truck/bus/taxi"
     2 "Motorcycle/scooter"
     3 "Bicycle"
     4 "Horse/donkey/mule"
     5 "Scotch cart"
     6 "Walking"
     7 "Combination walking and bus/taxi"
    95 "Household doesn't use nearest health facility"
    98 "Household doesn't know nearest health facility"
    96 "Other"
;
label define SH126H  
    97 "Household doesn't know nearest health facility"
    98 "Don't know"
;
label define SH126M  
    97 "Household doesn't know nearest health facility"
    98 "Don't know"
;
label define HV101   
     1 "Head"
     2 "Wife or husband"
     3 "Son/daughter"
     4 "Son/daughter-in-law"
     5 "Grandchild"
     6 "Parent"
     7 "Parent-in-law"
     8 "Brother/sister"
     9 "Co-spouse"
    10 "Other relative"
    11 "Adopted/foster child"
    12 "Not related"
    13 "Niece/nephew by blood"
    14 "Niece/nephew by marriage"
    15 "Domestic employee"
    16 "Herdboy"
    98 "Don't know"
;
label define HV102   
     0 "No"
     1 "Yes"
;
label define HV103   
     0 "No"
     1 "Yes"
;
label define HV104   
     1 "Male"
     2 "Female"
;
label define HV105   
    95 "95+"
    98 "Don't know"
;
label define HV106   
     0 "No education, preschool"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "Don't know"
;
label define HV107   
    98 "Don't know"
;
label define HV108   
    97 "Inconsistent"
    98 "Don't know"
;
label define HV109   
     0 "No education"
     1 "Incomplete primary"
     2 "Complete primary"
     3 "Incomplete secondary"
     4 "Complete secondary"
     5 "Higher"
     8 "Don't know"
;
label define HV110   
     0 "No"
     1 "Yes"
;
label define HV111   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV112   
     0 "Mother not in household"
;
label define HV113   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV114   
     0 "Father not in household"
;
label define HV115   
     0 "Never married"
     1 "Married"
     2 "Living together"
     3 "Widowed"
     4 "Divorced"
     5 "Not living together"
;
label define HV116   
     0 "Never married"
     1 "Currently married"
     2 "Formerly/ever married"
;
label define HV117   
     0 "Not eligible"
     1 "Eligible"
;
label define HV118   
     0 "Not eligible"
     1 "Eligible"
;
label define HV120   
     0 "Not eligible"
     1 "Eligible"
;
label define HV121   
     0 "No"
     1 "Currently attending"
     2 "Attended at some time"
;
label define HV122   
     0 "No education, preschool"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "Don't know"
;
label define HV123   
    98 "Don't know"
;
label define HV124   
    97 "Inconsistent"
    98 "Don't know"
;
label define HV125   
     0 "No"
     1 "Yes"
;
label define HV126   
     0 "No education, preschool"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "Don't know"
;
label define HV127   
    98 "Don't know"
;
label define HV128   
    97 "Inconsistent"
    98 "Don't know"
;
label define HV129   
     0 "Never attended"
     1 "Entered school"
     2 "Advanced"
     3 "Repeating"
     4 "Dropout"
     5 "Left school 2+ years ago"
     8 "Don't know"
;
label define HV140   
     0 "Neither certificate or registered"
     1 "Has certificate"
     2 "Registered"
     8 "Don't know"
;
label define SH06    
     1 "Lesotho"
     2 "South Africa"
     3 "Other Country"
;
label define SH07    
     0 "Less than one year"
    98 "Don't know"
;
label define SH19A   
     0 "No education"
     1 "Primary"
     2 "After primary:vocational/tech.training"
     3 "Secondary/high"
     4 "After secondary:vocational/tech.training"
     5 "College"
     6 "Graduate/post graduate"
     8 "Don't know"
;
label define SH21A   
     0 "No education"
     1 "Primary"
     2 "After primary:vocational/tech.training"
     3 "Secondary/high"
     4 "After secondary:vocational/tech.training"
     5 "College"
     6 "Graduate/post graduate"
     8 "Don't know"
;
label define HA2     
  9994 "Not present"
  9995 "Refused"
  9996 "Other"
;
label define HA3     
  9994 "Not present"
  9995 "Refused"
  9996 "Other"
;
label define HA4     
  9998 "Flagged cases"
;
label define HA5     
  9998 "Flagged cases"
;
label define HA6     
 99998 "Flagged cases"
;
label define HA11    
  9998 "Flagged cases"
;
label define HA12    
 99998 "Flagged cases"
;
label define HA12A   
 99998 "Flagged cases"
;
label define HA12B   
 99998 "Flagged cases"
;
label define HA13    
     0 "Measured"
     3 "Not present"
     4 "Refused"
     6 "Other"
;
label define HA33    
     1 "Month and year - information complete"
     2 "Month and age - year imputed"
     3 "Year and age - month imputed"
     4 "Year and age - year ignored"
     5 "Year - age/month imputed"
     6 "Age - year/month imputed"
     7 "Month - age/year imputed"
     8 "None - all imputed"
;
label define HA35    
     0 "Doesn't smoke"
    80 "80+"
    94 "Smokes pipes, cigars, etc"
;
label define HA40    
  9998 "Flagged cases"
;
label define HA41    
  9998 "Flagged cases"
;
label define HA50    
     1 "Under age 18"
     2 "Age 18 or older"
;
label define HA51    
     0 "Not in household"
;
label define HA52    
     1 "Granted"
     2 "Parent/other responsible refused"
     3 "Respondent refused"
;
label define HA53    
   994 "Not present"
   995 "Refused"
   996 "Other"
;
label define HA54    
     0 "No/don't know"
     1 "Yes"
;
label define HA55    
     0 "Measured"
     3 "Not present"
     4 "Refused"
     6 "Other"
;
label define HA56    
   997 "Inconsistent"
;
label define HA57    
     1 "Severe"
     2 "Moderate"
     3 "Mild"
     4 "Not anemic"
;
label define HA58    
     0 "No"
     1 "Yes"
;
label define HA60    
     1 "Never in union"
     2 "Other"
;
label define HA61    
     1 "Granted"
     2 "Parent/other responsible refused"
     3 "Respondent refused"
     4 "Sample not tested/lost/not enough DBS"
;
label define HA63    
     1 "Blood taken"
     2 "Not present"
     3 "Refused"
     4 "Sample not tested/lost/damaged/insufficient"
     5 "Not enough DBS to complete protocol"
     6 "Other"
;
label define HA64    
     1 "Granted"
     2 "Parent/other responsible refused"
     3 "Respondent refused"
;
label define HA65    
     1 "Completed"
     2 "Not at home"
     3 "Postponed"
     4 "Refused"
     5 "Partly completed"
     6 "Incapacitated"
     7 "Other"
;
label define HA66    
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "Don't know"
;
label define HA67    
    98 "Don't know"
;
label define HA68    
     0 "No education"
     1 "Primary incomplete"
     2 "Primary complete"
     3 "Secondary"
     4 "More than secondary"
;
label define HA70    
   999 "Missing"
;
label define HC2     
  9994 "Not present"
  9995 "Refused"
  9996 "Other"
;
label define HC3     
  9994 "Not present"
  9995 "Refused"
  9996 "Other"
;
label define HC4     
  9998 "Flagged cases"
;
label define HC5     
  9998 "Flagged cases"
;
label define HC6     
 99998 "Flagged cases"
;
label define HC7     
  9998 "Flagged cases"
;
label define HC8     
  9998 "Flagged cases"
;
label define HC9     
 99998 "Flagged cases"
;
label define HC10    
  9998 "Flagged cases"
;
label define HC11    
  9998 "Flagged cases"
;
label define HC12    
 99998 "Flagged cases"
;
label define HC13    
     0 "Measured"
     3 "Not present"
     4 "Refused"
     6 "Other"
;
label define HC15    
     0 "Not measured"
     1 "Lying"
     2 "Standing"
;
label define HC16    
    97 "Inconsistent"
    98 "Don't know"
;
label define HC27    
     1 "Male"
     2 "Female"
;
label define HC30    
    97 "Inconsistent"
    98 "Don't know"
;
label define HC31    
  9997 "Inconsistent"
  9998 "Don't know"
;
label define HC33    
     1 "Month and year - information complete"
     2 "Month and age - year imputed"
     3 "Year and age - month imputed"
     6 "Age - year/month imputed"
     7 "Month - age/year imputed"
     8 "None - all imputed"
;
label define HC51    
     0 "Not in household"
;
label define HC52    
     1 "Granted"
     2 "Refused"
;
label define HC53    
   994 "Not present"
   995 "Refused"
   996 "Other"
;
label define HC55    
     0 "Measured"
     3 "Not present"
     4 "Refused"
     6 "Other"
;
label define HC56    
   997 "Inconsistent"
;
label define HC57    
     1 "Severe"
     2 "Moderate"
     3 "Mild"
     4 "Not anemic"
;
label define HC58    
     0 "No"
     1 "Yes"
;
label define HC60    
   993 "Mother not de facto"
   994 "Incomplete woman's interview"
   995 "Not in household"
;
label define HC61    
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "Don't know"
;
label define HC62    
    98 "Don't know"
;
label define HC63    
   999 "Missing"
;
label define HC64    
    99 "Missing"
;
label define HC68    
     0 "No education"
     1 "Primary incomplete"
     2 "Primary complete"
     3 "Secondary"
     4 "More than secondary"
;
label define HC70    
  9996 "Height out of plausible limits"
  9997 "Age in days out of plausible limits"
  9998 "Flagged cases"
;
label define HC71    
  9996 "Height out of plausible limits"
  9997 "Age in days out of plausible limits"
  9998 "Flagged cases"
;
label define HC72    
  9996 "Height out of plausible limits"
  9997 "Age in days out of plausible limits"
  9998 "Flagged cases"
;
label define HC73    
  9996 "Height out of plausible limits"
  9997 "Age in days out of plausible limits"
  9998 "Flagged cases"
;
label define HB2     
  9994 "Not present"
  9995 "Refused"
  9996 "Other"
;
label define HB3     
  9994 "Not present"
  9995 "Refused"
  9996 "Other"
;
label define HB4     
  9998 "Flagged cases"
;
label define HB5     
  9998 "Flagged cases"
;
label define HB6     
 99998 "Flagged cases"
;
label define HB11    
  9998 "Flagged cases"
;
label define HB12    
 99998 "Flagged cases"
;
label define HB12A   
 99998 "Flagged cases"
;
label define HB12B   
 99998 "Flagged cases"
;
label define HB13    
     0 "Measured"
     3 "Not present"
     4 "Refused"
     6 "Other"
;
label define HB33    
     1 "Month and year - information complete"
     2 "Month and age - year imputed"
     3 "Year and age - month imputed"
     4 "Year and age - year ignored"
     5 "Year - age/month imputed"
     6 "Age - year/month imputed"
     7 "Month - age/year imputed"
     8 "None - all imputed"
;
label define HB35    
     0 "Doesn't smoke"
    80 "80+"
    94 "Smokes pipes, cigars, etc"
;
label define HB40    
  9998 "Flagged cases"
;
label define HB41    
  9998 "Flagged cases"
;
label define HB50    
     1 "Under age 18"
     2 "Age 18 or older"
;
label define HB51    
     0 "Not in household"
;
label define HB52    
     1 "Granted"
     2 "Parent/other responsible refused"
     3 "Respondent refused"
;
label define HB53    
   994 "Not present"
   995 "Refused"
   996 "Other"
;
label define HB55    
     0 "Measured"
     3 "Not present"
     4 "Refused"
     6 "Other"
;
label define HB56    
   997 "Inconsistent"
;
label define HB57    
     1 "Severe"
     2 "Moderate"
     3 "Mild"
     4 "Not anemic"
;
label define HB58    
     0 "No"
     1 "Yes"
;
label define HB60    
     1 "Never in union"
     2 "Other"
;
label define HB61    
     1 "Granted"
     2 "Parent/other responsible refused"
     3 "Respondent refused"
     4 "Sample not tested/lost/not enough DBS"
;
label define HB63    
     1 "Blood taken"
     2 "Not present"
     3 "Refused"
     4 "Sample not tested/lost/damaged/insufficient"
     5 "Not enough DBS to complete protocol"
     6 "Other"
;
label define HB64    
     1 "Granted"
     2 "Parent/other responsible refused"
     3 "Respondent refused"
;
label define HB65    
     1 "Completed"
     2 "Not at home"
     3 "Postponed"
     4 "Refused"
     5 "Partly completed"
     6 "Incapacitated"
     7 "Other"
;
label define HB66    
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "Don't know"
;
label define HB67    
    98 "Don't know"
;
label define HB68    
     0 "No education"
     1 "Primary incomplete"
     2 "Primary complete"
     3 "Secondary"
     4 "More than secondary"
;
label define HB70    
   999 "Missing"
;

#delimit cr
label values hv003    HV003   
label values hv015    HV015   
label values hv020    HV020   
label values hv022    HV022   
label values hv023    HV023   
label values hv024    HV024   
label values hv025    HV025   
label values hv026    HV026   
label values hv027    HV027   
label values hv042    HV042   
label values hv044    HV044   
label values hv201    HV201   
label values hv202    HV202   
label values hv204    HV204   
label values hv205    HV205   
label values hv206    HV206   
label values hv207    HV207   
label values hv208    HV208   
label values hv209    HV209   
label values hv210    HV210   
label values hv211    HV211   
label values hv212    HV212   
label values hv213    HV213   
label values hv214    HV214   
label values hv215    HV215   
label values hv217    HV217   
label values hv219    HV219   
label values hv220    HV220   
label values hv221    HV221   
label values hv225    HV225   
label values hv226    HV226   
label values hv227    HV227   
label values hv228    HV228   
label values hv230a   HV230A  
label values hv230b   HV230B  
label values hv232    HV232   
label values hv232b   HV232B  
label values hv232c   HV232C  
label values hv232d   HV232D  
label values hv232e   HV232E  
label values hv232y   HV232Y  
label values hv234    HV234   
label values hv234a   HV234A  
label values hv235    HV235   
label values hv236    HV236   
label values hv237    HV237   
label values hv237a   HV237A  
label values hv237b   HV237B  
label values hv237c   HV237C  
label values hv237d   HV237D  
label values hv237e   HV237E  
label values hv237f   HV237F  
label values hv237g   HV237G  
label values hv237h   HV237H  
label values hv237i   HV237I  
label values hv237j   HV237J  
label values hv237k   HV237K  
label values hv237x   HV237X  
label values hv237z   HV237Z  
label values hv238    HV238   
label values hv239    HV239   
label values hv240    HV240   
label values hv241    HV241   
label values hv242    HV242   
label values hv243a   HV243A  
label values hv243b   HV243B  
label values hv243c   HV243C  
label values hv243d   HV243D  
label values hv244    HV244   
label values hv245    HV245   
label values hv246    HV246   
label values hv246a   HV246A  
label values hv246b   HV246B  
label values hv246c   HV246C  
label values hv246d   HV246D  
label values hv246e   HV246E  
label values hv246f   HV246F  
label values hv246g   HV246G  
label values hv246h   HV246H  
label values hv246i   HV246I  
label values hv246j   HV246J  
label values hv246k   HV246K  
label values hv247    HV247   
label values hv252    HV252   
label values hv253    HV253   
label values hv253a   HV253A  
label values hv253b   HV253B  
label values hv253c   HV253C  
label values hv253d   HV253D  
label values hv253e   HV253E  
label values hv253f   HV253F  
label values hv253g   HV253G  
label values hv253h   HV253H  
label values hv253x   HV253X  
label values hv253z   HV253Z  
label values hv270    HV270   
label values hml1     HML1    
label values shzone   SHZONE  
label values sh110b   SH110B  
label values sh110c   SH110C  
label values sh110i   SH110I  
label values sh110j   SH110J  
label values sh110k   SH110K  
label values sh122k   SH122K  
label values sh124    SH124   
label values sh125    SH125   
label values sh126h   SH126H  
label values sh126m   SH126M  
label values hv101_01 HV101   
label values hv101_02 HV101   
label values hv101_03 HV101   
label values hv101_04 HV101   
label values hv101_05 HV101   
label values hv101_06 HV101   
label values hv101_07 HV101   
label values hv101_08 HV101   
label values hv101_09 HV101   
label values hv101_10 HV101   
label values hv101_11 HV101   
label values hv101_12 HV101   
label values hv101_13 HV101   
label values hv101_14 HV101   
label values hv101_15 HV101   
label values hv101_16 HV101   
label values hv101_17 HV101   
label values hv101_18 HV101   
label values hv101_19 HV101   
label values hv101_20 HV101   
label values hv102_01 HV102   
label values hv102_02 HV102   
label values hv102_03 HV102   
label values hv102_04 HV102   
label values hv102_05 HV102   
label values hv102_06 HV102   
label values hv102_07 HV102   
label values hv102_08 HV102   
label values hv102_09 HV102   
label values hv102_10 HV102   
label values hv102_11 HV102   
label values hv102_12 HV102   
label values hv102_13 HV102   
label values hv102_14 HV102   
label values hv102_15 HV102   
label values hv102_16 HV102   
label values hv102_17 HV102   
label values hv102_18 HV102   
label values hv102_19 HV102   
label values hv102_20 HV102   
label values hv103_01 HV103   
label values hv103_02 HV103   
label values hv103_03 HV103   
label values hv103_04 HV103   
label values hv103_05 HV103   
label values hv103_06 HV103   
label values hv103_07 HV103   
label values hv103_08 HV103   
label values hv103_09 HV103   
label values hv103_10 HV103   
label values hv103_11 HV103   
label values hv103_12 HV103   
label values hv103_13 HV103   
label values hv103_14 HV103   
label values hv103_15 HV103   
label values hv103_16 HV103   
label values hv103_17 HV103   
label values hv103_18 HV103   
label values hv103_19 HV103   
label values hv103_20 HV103   
label values hv104_01 HV104   
label values hv104_02 HV104   
label values hv104_03 HV104   
label values hv104_04 HV104   
label values hv104_05 HV104   
label values hv104_06 HV104   
label values hv104_07 HV104   
label values hv104_08 HV104   
label values hv104_09 HV104   
label values hv104_10 HV104   
label values hv104_11 HV104   
label values hv104_12 HV104   
label values hv104_13 HV104   
label values hv104_14 HV104   
label values hv104_15 HV104   
label values hv104_16 HV104   
label values hv104_17 HV104   
label values hv104_18 HV104   
label values hv104_19 HV104   
label values hv104_20 HV104   
label values hv105_01 HV105   
label values hv105_02 HV105   
label values hv105_03 HV105   
label values hv105_04 HV105   
label values hv105_05 HV105   
label values hv105_06 HV105   
label values hv105_07 HV105   
label values hv105_08 HV105   
label values hv105_09 HV105   
label values hv105_10 HV105   
label values hv105_11 HV105   
label values hv105_12 HV105   
label values hv105_13 HV105   
label values hv105_14 HV105   
label values hv105_15 HV105   
label values hv105_16 HV105   
label values hv105_17 HV105   
label values hv105_18 HV105   
label values hv105_19 HV105   
label values hv105_20 HV105   
label values hv106_01 HV106   
label values hv106_02 HV106   
label values hv106_03 HV106   
label values hv106_04 HV106   
label values hv106_05 HV106   
label values hv106_06 HV106   
label values hv106_07 HV106   
label values hv106_08 HV106   
label values hv106_09 HV106   
label values hv106_10 HV106   
label values hv106_11 HV106   
label values hv106_12 HV106   
label values hv106_13 HV106   
label values hv106_14 HV106   
label values hv106_15 HV106   
label values hv106_16 HV106   
label values hv106_17 HV106   
label values hv106_18 HV106   
label values hv106_19 HV106   
label values hv106_20 HV106   
label values hv107_01 HV107   
label values hv107_02 HV107   
label values hv107_03 HV107   
label values hv107_04 HV107   
label values hv107_05 HV107   
label values hv107_06 HV107   
label values hv107_07 HV107   
label values hv107_08 HV107   
label values hv107_09 HV107   
label values hv107_10 HV107   
label values hv107_11 HV107   
label values hv107_12 HV107   
label values hv107_13 HV107   
label values hv107_14 HV107   
label values hv107_15 HV107   
label values hv107_16 HV107   
label values hv107_17 HV107   
label values hv107_18 HV107   
label values hv107_19 HV107   
label values hv107_20 HV107   
label values hv108_01 HV108   
label values hv108_02 HV108   
label values hv108_03 HV108   
label values hv108_04 HV108   
label values hv108_05 HV108   
label values hv108_06 HV108   
label values hv108_07 HV108   
label values hv108_08 HV108   
label values hv108_09 HV108   
label values hv108_10 HV108   
label values hv108_11 HV108   
label values hv108_12 HV108   
label values hv108_13 HV108   
label values hv108_14 HV108   
label values hv108_15 HV108   
label values hv108_16 HV108   
label values hv108_17 HV108   
label values hv108_18 HV108   
label values hv108_19 HV108   
label values hv108_20 HV108   
label values hv109_01 HV109   
label values hv109_02 HV109   
label values hv109_03 HV109   
label values hv109_04 HV109   
label values hv109_05 HV109   
label values hv109_06 HV109   
label values hv109_07 HV109   
label values hv109_08 HV109   
label values hv109_09 HV109   
label values hv109_10 HV109   
label values hv109_11 HV109   
label values hv109_12 HV109   
label values hv109_13 HV109   
label values hv109_14 HV109   
label values hv109_15 HV109   
label values hv109_16 HV109   
label values hv109_17 HV109   
label values hv109_18 HV109   
label values hv109_19 HV109   
label values hv109_20 HV109   
label values hv110_01 HV110   
label values hv110_02 HV110   
label values hv110_03 HV110   
label values hv110_04 HV110   
label values hv110_05 HV110   
label values hv110_06 HV110   
label values hv110_07 HV110   
label values hv110_08 HV110   
label values hv110_09 HV110   
label values hv110_10 HV110   
label values hv110_11 HV110   
label values hv110_12 HV110   
label values hv110_13 HV110   
label values hv110_14 HV110   
label values hv110_15 HV110   
label values hv110_16 HV110   
label values hv110_17 HV110   
label values hv110_18 HV110   
label values hv110_19 HV110   
label values hv110_20 HV110   
label values hv111_01 HV111   
label values hv111_02 HV111   
label values hv111_03 HV111   
label values hv111_04 HV111   
label values hv111_05 HV111   
label values hv111_06 HV111   
label values hv111_07 HV111   
label values hv111_08 HV111   
label values hv111_09 HV111   
label values hv111_10 HV111   
label values hv111_11 HV111   
label values hv111_12 HV111   
label values hv111_13 HV111   
label values hv111_14 HV111   
label values hv111_15 HV111   
label values hv111_16 HV111   
label values hv111_17 HV111   
label values hv111_18 HV111   
label values hv111_19 HV111   
label values hv111_20 HV111   
label values hv112_01 HV112   
label values hv112_02 HV112   
label values hv112_03 HV112   
label values hv112_04 HV112   
label values hv112_05 HV112   
label values hv112_06 HV112   
label values hv112_07 HV112   
label values hv112_08 HV112   
label values hv112_09 HV112   
label values hv112_10 HV112   
label values hv112_11 HV112   
label values hv112_12 HV112   
label values hv112_13 HV112   
label values hv112_14 HV112   
label values hv112_15 HV112   
label values hv112_16 HV112   
label values hv112_17 HV112   
label values hv112_18 HV112   
label values hv112_19 HV112   
label values hv112_20 HV112   
label values hv113_01 HV113   
label values hv113_02 HV113   
label values hv113_03 HV113   
label values hv113_04 HV113   
label values hv113_05 HV113   
label values hv113_06 HV113   
label values hv113_07 HV113   
label values hv113_08 HV113   
label values hv113_09 HV113   
label values hv113_10 HV113   
label values hv113_11 HV113   
label values hv113_12 HV113   
label values hv113_13 HV113   
label values hv113_14 HV113   
label values hv113_15 HV113   
label values hv113_16 HV113   
label values hv113_17 HV113   
label values hv113_18 HV113   
label values hv113_19 HV113   
label values hv113_20 HV113   
label values hv114_01 HV114   
label values hv114_02 HV114   
label values hv114_03 HV114   
label values hv114_04 HV114   
label values hv114_05 HV114   
label values hv114_06 HV114   
label values hv114_07 HV114   
label values hv114_08 HV114   
label values hv114_09 HV114   
label values hv114_10 HV114   
label values hv114_11 HV114   
label values hv114_12 HV114   
label values hv114_13 HV114   
label values hv114_14 HV114   
label values hv114_15 HV114   
label values hv114_16 HV114   
label values hv114_17 HV114   
label values hv114_18 HV114   
label values hv114_19 HV114   
label values hv114_20 HV114   
label values hv115_01 HV115   
label values hv115_02 HV115   
label values hv115_03 HV115   
label values hv115_04 HV115   
label values hv115_05 HV115   
label values hv115_06 HV115   
label values hv115_07 HV115   
label values hv115_08 HV115   
label values hv115_09 HV115   
label values hv115_10 HV115   
label values hv115_11 HV115   
label values hv115_12 HV115   
label values hv115_13 HV115   
label values hv115_14 HV115   
label values hv115_15 HV115   
label values hv115_16 HV115   
label values hv115_17 HV115   
label values hv115_18 HV115   
label values hv115_19 HV115   
label values hv115_20 HV115   
label values hv116_01 HV116   
label values hv116_02 HV116   
label values hv116_03 HV116   
label values hv116_04 HV116   
label values hv116_05 HV116   
label values hv116_06 HV116   
label values hv116_07 HV116   
label values hv116_08 HV116   
label values hv116_09 HV116   
label values hv116_10 HV116   
label values hv116_11 HV116   
label values hv116_12 HV116   
label values hv116_13 HV116   
label values hv116_14 HV116   
label values hv116_15 HV116   
label values hv116_16 HV116   
label values hv116_17 HV116   
label values hv116_18 HV116   
label values hv116_19 HV116   
label values hv116_20 HV116   
label values hv117_01 HV117   
label values hv117_02 HV117   
label values hv117_03 HV117   
label values hv117_04 HV117   
label values hv117_05 HV117   
label values hv117_06 HV117   
label values hv117_07 HV117   
label values hv117_08 HV117   
label values hv117_09 HV117   
label values hv117_10 HV117   
label values hv117_11 HV117   
label values hv117_12 HV117   
label values hv117_13 HV117   
label values hv117_14 HV117   
label values hv117_15 HV117   
label values hv117_16 HV117   
label values hv117_17 HV117   
label values hv117_18 HV117   
label values hv117_19 HV117   
label values hv117_20 HV117   
label values hv118_01 HV118   
label values hv118_02 HV118   
label values hv118_03 HV118   
label values hv118_04 HV118   
label values hv118_05 HV118   
label values hv118_06 HV118   
label values hv118_07 HV118   
label values hv118_08 HV118   
label values hv118_09 HV118   
label values hv118_10 HV118   
label values hv118_11 HV118   
label values hv118_12 HV118   
label values hv118_13 HV118   
label values hv118_14 HV118   
label values hv118_15 HV118   
label values hv118_16 HV118   
label values hv118_17 HV118   
label values hv118_18 HV118   
label values hv118_19 HV118   
label values hv118_20 HV118   
label values hv120_01 HV120   
label values hv120_02 HV120   
label values hv120_03 HV120   
label values hv120_04 HV120   
label values hv120_05 HV120   
label values hv120_06 HV120   
label values hv120_07 HV120   
label values hv120_08 HV120   
label values hv120_09 HV120   
label values hv120_10 HV120   
label values hv120_11 HV120   
label values hv120_12 HV120   
label values hv120_13 HV120   
label values hv120_14 HV120   
label values hv120_15 HV120   
label values hv120_16 HV120   
label values hv120_17 HV120   
label values hv120_18 HV120   
label values hv120_19 HV120   
label values hv120_20 HV120   
label values hv121_01 HV121   
label values hv121_02 HV121   
label values hv121_03 HV121   
label values hv121_04 HV121   
label values hv121_05 HV121   
label values hv121_06 HV121   
label values hv121_07 HV121   
label values hv121_08 HV121   
label values hv121_09 HV121   
label values hv121_10 HV121   
label values hv121_11 HV121   
label values hv121_12 HV121   
label values hv121_13 HV121   
label values hv121_14 HV121   
label values hv121_15 HV121   
label values hv121_16 HV121   
label values hv121_17 HV121   
label values hv121_18 HV121   
label values hv121_19 HV121   
label values hv121_20 HV121   
label values hv122_01 HV122   
label values hv122_02 HV122   
label values hv122_03 HV122   
label values hv122_04 HV122   
label values hv122_05 HV122   
label values hv122_06 HV122   
label values hv122_07 HV122   
label values hv122_08 HV122   
label values hv122_09 HV122   
label values hv122_10 HV122   
label values hv122_11 HV122   
label values hv122_12 HV122   
label values hv122_13 HV122   
label values hv122_14 HV122   
label values hv122_15 HV122   
label values hv122_16 HV122   
label values hv122_17 HV122   
label values hv122_18 HV122   
label values hv122_19 HV122   
label values hv122_20 HV122   
label values hv123_01 HV123   
label values hv123_02 HV123   
label values hv123_03 HV123   
label values hv123_04 HV123   
label values hv123_05 HV123   
label values hv123_06 HV123   
label values hv123_07 HV123   
label values hv123_08 HV123   
label values hv123_09 HV123   
label values hv123_10 HV123   
label values hv123_11 HV123   
label values hv123_12 HV123   
label values hv123_13 HV123   
label values hv123_14 HV123   
label values hv123_15 HV123   
label values hv123_16 HV123   
label values hv123_17 HV123   
label values hv123_18 HV123   
label values hv123_19 HV123   
label values hv123_20 HV123   
label values hv124_01 HV124   
label values hv124_02 HV124   
label values hv124_03 HV124   
label values hv124_04 HV124   
label values hv124_05 HV124   
label values hv124_06 HV124   
label values hv124_07 HV124   
label values hv124_08 HV124   
label values hv124_09 HV124   
label values hv124_10 HV124   
label values hv124_11 HV124   
label values hv124_12 HV124   
label values hv124_13 HV124   
label values hv124_14 HV124   
label values hv124_15 HV124   
label values hv124_16 HV124   
label values hv124_17 HV124   
label values hv124_18 HV124   
label values hv124_19 HV124   
label values hv124_20 HV124   
label values hv125_01 HV125   
label values hv125_02 HV125   
label values hv125_03 HV125   
label values hv125_04 HV125   
label values hv125_05 HV125   
label values hv125_06 HV125   
label values hv125_07 HV125   
label values hv125_08 HV125   
label values hv125_09 HV125   
label values hv125_10 HV125   
label values hv125_11 HV125   
label values hv125_12 HV125   
label values hv125_13 HV125   
label values hv125_14 HV125   
label values hv125_15 HV125   
label values hv125_16 HV125   
label values hv125_17 HV125   
label values hv125_18 HV125   
label values hv125_19 HV125   
label values hv125_20 HV125   
label values hv126_01 HV126   
label values hv126_02 HV126   
label values hv126_03 HV126   
label values hv126_04 HV126   
label values hv126_05 HV126   
label values hv126_06 HV126   
label values hv126_07 HV126   
label values hv126_08 HV126   
label values hv126_09 HV126   
label values hv126_10 HV126   
label values hv126_11 HV126   
label values hv126_12 HV126   
label values hv126_13 HV126   
label values hv126_14 HV126   
label values hv126_15 HV126   
label values hv126_16 HV126   
label values hv126_17 HV126   
label values hv126_18 HV126   
label values hv126_19 HV126   
label values hv126_20 HV126   
label values hv127_01 HV127   
label values hv127_02 HV127   
label values hv127_03 HV127   
label values hv127_04 HV127   
label values hv127_05 HV127   
label values hv127_06 HV127   
label values hv127_07 HV127   
label values hv127_08 HV127   
label values hv127_09 HV127   
label values hv127_10 HV127   
label values hv127_11 HV127   
label values hv127_12 HV127   
label values hv127_13 HV127   
label values hv127_14 HV127   
label values hv127_15 HV127   
label values hv127_16 HV127   
label values hv127_17 HV127   
label values hv127_18 HV127   
label values hv127_19 HV127   
label values hv127_20 HV127   
label values hv128_01 HV128   
label values hv128_02 HV128   
label values hv128_03 HV128   
label values hv128_04 HV128   
label values hv128_05 HV128   
label values hv128_06 HV128   
label values hv128_07 HV128   
label values hv128_08 HV128   
label values hv128_09 HV128   
label values hv128_10 HV128   
label values hv128_11 HV128   
label values hv128_12 HV128   
label values hv128_13 HV128   
label values hv128_14 HV128   
label values hv128_15 HV128   
label values hv128_16 HV128   
label values hv128_17 HV128   
label values hv128_18 HV128   
label values hv128_19 HV128   
label values hv128_20 HV128   
label values hv129_01 HV129   
label values hv129_02 HV129   
label values hv129_03 HV129   
label values hv129_04 HV129   
label values hv129_05 HV129   
label values hv129_06 HV129   
label values hv129_07 HV129   
label values hv129_08 HV129   
label values hv129_09 HV129   
label values hv129_10 HV129   
label values hv129_11 HV129   
label values hv129_12 HV129   
label values hv129_13 HV129   
label values hv129_14 HV129   
label values hv129_15 HV129   
label values hv129_16 HV129   
label values hv129_17 HV129   
label values hv129_18 HV129   
label values hv129_19 HV129   
label values hv129_20 HV129   
label values hv140_01 HV140   
label values hv140_02 HV140   
label values hv140_03 HV140   
label values hv140_04 HV140   
label values hv140_05 HV140   
label values hv140_06 HV140   
label values hv140_07 HV140   
label values hv140_08 HV140   
label values hv140_09 HV140   
label values hv140_10 HV140   
label values hv140_11 HV140   
label values hv140_12 HV140   
label values hv140_13 HV140   
label values hv140_14 HV140   
label values hv140_15 HV140   
label values hv140_16 HV140   
label values hv140_17 HV140   
label values hv140_18 HV140   
label values hv140_19 HV140   
label values hv140_20 HV140   
label values sh06_01  SH06    
label values sh06_02  SH06    
label values sh06_03  SH06    
label values sh06_04  SH06    
label values sh06_05  SH06    
label values sh06_06  SH06    
label values sh06_07  SH06    
label values sh06_08  SH06    
label values sh06_09  SH06    
label values sh06_10  SH06    
label values sh06_11  SH06    
label values sh06_12  SH06    
label values sh06_13  SH06    
label values sh06_14  SH06    
label values sh06_15  SH06    
label values sh06_16  SH06    
label values sh06_17  SH06    
label values sh06_18  SH06    
label values sh06_19  SH06    
label values sh06_20  SH06    
label values sh07_01  SH07    
label values sh07_02  SH07    
label values sh07_03  SH07    
label values sh07_04  SH07    
label values sh07_05  SH07    
label values sh07_06  SH07    
label values sh07_07  SH07    
label values sh07_08  SH07    
label values sh07_09  SH07    
label values sh07_10  SH07    
label values sh07_11  SH07    
label values sh07_12  SH07    
label values sh07_13  SH07    
label values sh07_14  SH07    
label values sh07_15  SH07    
label values sh07_16  SH07    
label values sh07_17  SH07    
label values sh07_18  SH07    
label values sh07_19  SH07    
label values sh07_20  SH07    
label values sh19a_01 SH19A   
label values sh19a_02 SH19A   
label values sh19a_03 SH19A   
label values sh19a_04 SH19A   
label values sh19a_05 SH19A   
label values sh19a_06 SH19A   
label values sh19a_07 SH19A   
label values sh19a_08 SH19A   
label values sh19a_09 SH19A   
label values sh19a_10 SH19A   
label values sh19a_11 SH19A   
label values sh19a_12 SH19A   
label values sh19a_13 SH19A   
label values sh19a_14 SH19A   
label values sh19a_15 SH19A   
label values sh19a_16 SH19A   
label values sh19a_17 SH19A   
label values sh19a_18 SH19A   
label values sh19a_19 SH19A   
label values sh19a_20 SH19A   
label values sh21a_01 SH21A   
label values sh21a_02 SH21A   
label values sh21a_03 SH21A   
label values sh21a_04 SH21A   
label values sh21a_05 SH21A   
label values sh21a_06 SH21A   
label values sh21a_07 SH21A   
label values sh21a_08 SH21A   
label values sh21a_09 SH21A   
label values sh21a_10 SH21A   
label values sh21a_11 SH21A   
label values sh21a_12 SH21A   
label values sh21a_13 SH21A   
label values sh21a_14 SH21A   
label values sh21a_15 SH21A   
label values sh21a_16 SH21A   
label values sh21a_17 SH21A   
label values sh21a_18 SH21A   
label values sh21a_19 SH21A   
label values sh21a_20 SH21A   
label values ha2_1    HA2     
label values ha2_2    HA2     
label values ha2_3    HA2     
label values ha2_4    HA2     
label values ha2_5    HA2     
label values ha3_1    HA3     
label values ha3_2    HA3     
label values ha3_3    HA3     
label values ha3_4    HA3     
label values ha3_5    HA3     
label values ha4_1    HA4     
label values ha4_2    HA4     
label values ha4_3    HA4     
label values ha4_4    HA4     
label values ha4_5    HA4     
label values ha5_1    HA5     
label values ha5_2    HA5     
label values ha5_3    HA5     
label values ha5_4    HA5     
label values ha5_5    HA5     
label values ha6_1    HA6     
label values ha6_2    HA6     
label values ha6_3    HA6     
label values ha6_4    HA6     
label values ha6_5    HA6     
label values ha11_1   HA11    
label values ha11_2   HA11    
label values ha11_3   HA11    
label values ha11_4   HA11    
label values ha11_5   HA11    
label values ha12_1   HA12    
label values ha12_2   HA12    
label values ha12_3   HA12    
label values ha12_4   HA12    
label values ha12_5   HA12    
label values ha12a_1  HA12A   
label values ha12a_2  HA12A   
label values ha12a_3  HA12A   
label values ha12a_4  HA12A   
label values ha12a_5  HA12A   
label values ha12b_1  HA12B   
label values ha12b_2  HA12B   
label values ha12b_3  HA12B   
label values ha12b_4  HA12B   
label values ha12b_5  HA12B   
label values ha13_1   HA13    
label values ha13_2   HA13    
label values ha13_3   HA13    
label values ha13_4   HA13    
label values ha13_5   HA13    
label values ha33_1   HA33    
label values ha33_2   HA33    
label values ha33_3   HA33    
label values ha33_4   HA33    
label values ha33_5   HA33    
label values ha35_1   HA35    
label values ha35_2   HA35    
label values ha35_3   HA35    
label values ha35_4   HA35    
label values ha35_5   HA35    
label values ha40_1   HA40    
label values ha40_2   HA40    
label values ha40_3   HA40    
label values ha40_4   HA40    
label values ha40_5   HA40    
label values ha41_1   HA41    
label values ha41_2   HA41    
label values ha41_3   HA41    
label values ha41_4   HA41    
label values ha41_5   HA41    
label values ha50_1   HA50    
label values ha50_2   HA50    
label values ha50_3   HA50    
label values ha50_4   HA50    
label values ha50_5   HA50    
label values ha51_1   HA51    
label values ha51_2   HA51    
label values ha51_3   HA51    
label values ha51_4   HA51    
label values ha51_5   HA51    
label values ha52_1   HA52    
label values ha52_2   HA52    
label values ha52_3   HA52    
label values ha52_4   HA52    
label values ha52_5   HA52    
label values ha53_1   HA53    
label values ha53_2   HA53    
label values ha53_3   HA53    
label values ha53_4   HA53    
label values ha53_5   HA53    
label values ha54_1   HA54    
label values ha54_2   HA54    
label values ha54_3   HA54    
label values ha54_4   HA54    
label values ha54_5   HA54    
label values ha55_1   HA55    
label values ha55_2   HA55    
label values ha55_3   HA55    
label values ha55_4   HA55    
label values ha55_5   HA55    
label values ha56_1   HA56    
label values ha56_2   HA56    
label values ha56_3   HA56    
label values ha56_4   HA56    
label values ha56_5   HA56    
label values ha57_1   HA57    
label values ha57_2   HA57    
label values ha57_3   HA57    
label values ha57_4   HA57    
label values ha57_5   HA57    
label values ha58_1   HA58    
label values ha58_2   HA58    
label values ha58_3   HA58    
label values ha58_4   HA58    
label values ha58_5   HA58    
label values ha60_1   HA60    
label values ha60_2   HA60    
label values ha60_3   HA60    
label values ha60_4   HA60    
label values ha60_5   HA60    
label values ha61_1   HA61    
label values ha61_2   HA61    
label values ha61_3   HA61    
label values ha61_4   HA61    
label values ha61_5   HA61    
label values ha63_1   HA63    
label values ha63_2   HA63    
label values ha63_3   HA63    
label values ha63_4   HA63    
label values ha63_5   HA63    
label values ha64_1   HA64    
label values ha64_2   HA64    
label values ha64_3   HA64    
label values ha64_4   HA64    
label values ha64_5   HA64    
label values ha65_1   HA65    
label values ha65_2   HA65    
label values ha65_3   HA65    
label values ha65_4   HA65    
label values ha65_5   HA65    
label values ha66_1   HA66    
label values ha66_2   HA66    
label values ha66_3   HA66    
label values ha66_4   HA66    
label values ha66_5   HA66    
label values ha67_1   HA67    
label values ha67_2   HA67    
label values ha67_3   HA67    
label values ha67_4   HA67    
label values ha67_5   HA67    
label values ha68_1   HA68    
label values ha68_2   HA68    
label values ha68_3   HA68    
label values ha68_4   HA68    
label values ha68_5   HA68    
label values hc2_1    HC2     
label values hc2_2    HC2     
label values hc2_3    HC2     
label values hc2_4    HC2     
label values hc2_5    HC2     
label values hc3_1    HC3     
label values hc3_2    HC3     
label values hc3_3    HC3     
label values hc3_4    HC3     
label values hc3_5    HC3     
label values hc4_1    HC4     
label values hc4_2    HC4     
label values hc4_3    HC4     
label values hc4_4    HC4     
label values hc4_5    HC4     
label values hc5_1    HC5     
label values hc5_2    HC5     
label values hc5_3    HC5     
label values hc5_4    HC5     
label values hc5_5    HC5     
label values hc6_1    HC6     
label values hc6_2    HC6     
label values hc6_3    HC6     
label values hc6_4    HC6     
label values hc6_5    HC6     
label values hc7_1    HC7     
label values hc7_2    HC7     
label values hc7_3    HC7     
label values hc7_4    HC7     
label values hc7_5    HC7     
label values hc8_1    HC8     
label values hc8_2    HC8     
label values hc8_3    HC8     
label values hc8_4    HC8     
label values hc8_5    HC8     
label values hc9_1    HC9     
label values hc9_2    HC9     
label values hc9_3    HC9     
label values hc9_4    HC9     
label values hc9_5    HC9     
label values hc10_1   HC10    
label values hc10_2   HC10    
label values hc10_3   HC10    
label values hc10_4   HC10    
label values hc10_5   HC10    
label values hc11_1   HC11    
label values hc11_2   HC11    
label values hc11_3   HC11    
label values hc11_4   HC11    
label values hc11_5   HC11    
label values hc12_1   HC12    
label values hc12_2   HC12    
label values hc12_3   HC12    
label values hc12_4   HC12    
label values hc12_5   HC12    
label values hc13_1   HC13    
label values hc13_2   HC13    
label values hc13_3   HC13    
label values hc13_4   HC13    
label values hc13_5   HC13    
label values hc15_1   HC15    
label values hc15_2   HC15    
label values hc15_3   HC15    
label values hc15_4   HC15    
label values hc15_5   HC15    
label values hc16_1   HC16    
label values hc16_2   HC16    
label values hc16_3   HC16    
label values hc16_4   HC16    
label values hc16_5   HC16    
label values hc27_1   HC27    
label values hc27_2   HC27    
label values hc27_3   HC27    
label values hc27_4   HC27    
label values hc27_5   HC27    
label values hc30_1   HC30    
label values hc30_2   HC30    
label values hc30_3   HC30    
label values hc30_4   HC30    
label values hc30_5   HC30    
label values hc31_1   HC31    
label values hc31_2   HC31    
label values hc31_3   HC31    
label values hc31_4   HC31    
label values hc31_5   HC31    
label values hc33_1   HC33    
label values hc33_2   HC33    
label values hc33_3   HC33    
label values hc33_4   HC33    
label values hc33_5   HC33    
label values hc51_1   HC51    
label values hc51_2   HC51    
label values hc51_3   HC51    
label values hc51_4   HC51    
label values hc51_5   HC51    
label values hc52_1   HC52    
label values hc52_2   HC52    
label values hc52_3   HC52    
label values hc52_4   HC52    
label values hc52_5   HC52    
label values hc53_1   HC53    
label values hc53_2   HC53    
label values hc53_3   HC53    
label values hc53_4   HC53    
label values hc53_5   HC53    
label values hc55_1   HC55    
label values hc55_2   HC55    
label values hc55_3   HC55    
label values hc55_4   HC55    
label values hc55_5   HC55    
label values hc56_1   HC56    
label values hc56_2   HC56    
label values hc56_3   HC56    
label values hc56_4   HC56    
label values hc56_5   HC56    
label values hc57_1   HC57    
label values hc57_2   HC57    
label values hc57_3   HC57    
label values hc57_4   HC57    
label values hc57_5   HC57    
label values hc58_1   HC58    
label values hc58_2   HC58    
label values hc58_3   HC58    
label values hc58_4   HC58    
label values hc58_5   HC58    
label values hc60_1   HC60    
label values hc60_2   HC60    
label values hc60_3   HC60    
label values hc60_4   HC60    
label values hc60_5   HC60    
label values hc61_1   HC61    
label values hc61_2   HC61    
label values hc61_3   HC61    
label values hc61_4   HC61    
label values hc61_5   HC61    
label values hc62_1   HC62    
label values hc62_2   HC62    
label values hc62_3   HC62    
label values hc62_4   HC62    
label values hc62_5   HC62    
label values hc68_1   HC68    
label values hc68_2   HC68    
label values hc68_3   HC68    
label values hc68_4   HC68    
label values hc68_5   HC68    
label values hc70_1   HC70    
label values hc70_2   HC70    
label values hc70_3   HC70    
label values hc70_4   HC70    
label values hc70_5   HC70    
label values hc71_1   HC71    
label values hc71_2   HC71    
label values hc71_3   HC71    
label values hc71_4   HC71    
label values hc71_5   HC71    
label values hc72_1   HC72    
label values hc72_2   HC72    
label values hc72_3   HC72    
label values hc72_4   HC72    
label values hc72_5   HC72    
label values hc73_1   HC73    
label values hc73_2   HC73    
label values hc73_3   HC73    
label values hc73_4   HC73    
label values hc73_5   HC73    
label values hb2_1    HB2     
label values hb2_2    HB2     
label values hb2_3    HB2     
label values hb2_4    HB2     
label values hb2_5    HB2     
label values hb2_6    HB2     
label values hb3_1    HB3     
label values hb3_2    HB3     
label values hb3_3    HB3     
label values hb3_4    HB3     
label values hb3_5    HB3     
label values hb3_6    HB3     
label values hb4_1    HB4     
label values hb4_2    HB4     
label values hb4_3    HB4     
label values hb4_4    HB4     
label values hb4_5    HB4     
label values hb4_6    HB4     
label values hb5_1    HB5     
label values hb5_2    HB5     
label values hb5_3    HB5     
label values hb5_4    HB5     
label values hb5_5    HB5     
label values hb5_6    HB5     
label values hb6_1    HB6     
label values hb6_2    HB6     
label values hb6_3    HB6     
label values hb6_4    HB6     
label values hb6_5    HB6     
label values hb6_6    HB6     
label values hb11_1   HB11    
label values hb11_2   HB11    
label values hb11_3   HB11    
label values hb11_4   HB11    
label values hb11_5   HB11    
label values hb11_6   HB11    
label values hb12_1   HB12    
label values hb12_2   HB12    
label values hb12_3   HB12    
label values hb12_4   HB12    
label values hb12_5   HB12    
label values hb12_6   HB12    
label values hb12a_1  HB12A   
label values hb12a_2  HB12A   
label values hb12a_3  HB12A   
label values hb12a_4  HB12A   
label values hb12a_5  HB12A   
label values hb12a_6  HB12A   
label values hb12b_1  HB12B   
label values hb12b_2  HB12B   
label values hb12b_3  HB12B   
label values hb12b_4  HB12B   
label values hb12b_5  HB12B   
label values hb12b_6  HB12B   
label values hb13_1   HB13    
label values hb13_2   HB13    
label values hb13_3   HB13    
label values hb13_4   HB13    
label values hb13_5   HB13    
label values hb13_6   HB13    
label values hb33_1   HB33    
label values hb33_2   HB33    
label values hb33_3   HB33    
label values hb33_4   HB33    
label values hb33_5   HB33    
label values hb33_6   HB33    
label values hb35_1   HB35    
label values hb35_2   HB35    
label values hb35_3   HB35    
label values hb35_4   HB35    
label values hb35_5   HB35    
label values hb35_6   HB35    
label values hb40_1   HB40    
label values hb40_2   HB40    
label values hb40_3   HB40    
label values hb40_4   HB40    
label values hb40_5   HB40    
label values hb40_6   HB40    
label values hb41_1   HB41    
label values hb41_2   HB41    
label values hb41_3   HB41    
label values hb41_4   HB41    
label values hb41_5   HB41    
label values hb41_6   HB41    
label values hb50_1   HB50    
label values hb50_2   HB50    
label values hb50_3   HB50    
label values hb50_4   HB50    
label values hb50_5   HB50    
label values hb50_6   HB50    
label values hb51_1   HB51    
label values hb51_2   HB51    
label values hb51_3   HB51    
label values hb51_4   HB51    
label values hb51_5   HB51    
label values hb51_6   HB51    
label values hb52_1   HB52    
label values hb52_2   HB52    
label values hb52_3   HB52    
label values hb52_4   HB52    
label values hb52_5   HB52    
label values hb52_6   HB52    
label values hb53_1   HB53    
label values hb53_2   HB53    
label values hb53_3   HB53    
label values hb53_4   HB53    
label values hb53_5   HB53    
label values hb53_6   HB53    
label values hb55_1   HB55    
label values hb55_2   HB55    
label values hb55_3   HB55    
label values hb55_4   HB55    
label values hb55_5   HB55    
label values hb55_6   HB55    
label values hb56_1   HB56    
label values hb56_2   HB56    
label values hb56_3   HB56    
label values hb56_4   HB56    
label values hb56_5   HB56    
label values hb56_6   HB56    
label values hb57_1   HB57    
label values hb57_2   HB57    
label values hb57_3   HB57    
label values hb57_4   HB57    
label values hb57_5   HB57    
label values hb57_6   HB57    
label values hb58_1   HB58    
label values hb58_2   HB58    
label values hb58_3   HB58    
label values hb58_4   HB58    
label values hb58_5   HB58    
label values hb58_6   HB58    
label values hb60_1   HB60    
label values hb60_2   HB60    
label values hb60_3   HB60    
label values hb60_4   HB60    
label values hb60_5   HB60    
label values hb60_6   HB60    
label values hb61_1   HB61    
label values hb61_2   HB61    
label values hb61_3   HB61    
label values hb61_4   HB61    
label values hb61_5   HB61    
label values hb61_6   HB61    
label values hb63_1   HB63    
label values hb63_2   HB63    
label values hb63_3   HB63    
label values hb63_4   HB63    
label values hb63_5   HB63    
label values hb63_6   HB63    
label values hb64_1   HB64    
label values hb64_2   HB64    
label values hb64_3   HB64    
label values hb64_4   HB64    
label values hb64_5   HB64    
label values hb64_6   HB64    
label values hb65_1   HB65    
label values hb65_2   HB65    
label values hb65_3   HB65    
label values hb65_4   HB65    
label values hb65_5   HB65    
label values hb65_6   HB65    
label values hb66_1   HB66    
label values hb66_2   HB66    
label values hb66_3   HB66    
label values hb66_4   HB66    
label values hb66_5   HB66    
label values hb66_6   HB66    
label values hb67_1   HB67    
label values hb67_2   HB67    
label values hb67_3   HB67    
label values hb67_4   HB67    
label values hb67_5   HB67    
label values hb67_6   HB67    
label values hb68_1   HB68    
label values hb68_2   HB68    
label values hb68_3   HB68    
label values hb68_4   HB68    
label values hb68_5   HB68    
label values hb68_6   HB68    
