infix using "C:\COUNTRIES\LS71\LSPR71FL.dct"

label variable hhid     "Case Identification"
label variable hvidx    "Line number"
label variable hv000    "Country code and phase"
label variable hv001    "Cluster number"
label variable hv002    "Household number"
label variable hv003    "Respondent's line number (answering Household questionnaire)"
label variable hv004    "Ultimate area unit"
label variable hv005    "Household sample weight (6 decimals)"
label variable hv006    "Month of interview"
label variable hv007    "Year of interview"
label variable hv008    "Date of interview (CMC)"
label variable hv009    "Number of household members"
label variable hv010    "Number of eligible women in household"
label variable hv011    "Number of eligible men in household"
label variable hv012    "Number of de jure members"
label variable hv013    "Number of de facto members"
label variable hv014    "Number of children 5 and under (de jure)"
label variable hv015    "Result of household interview"
label variable hv016    "Day of interview"
label variable hv017    "Number of visits"
label variable hv018    "Interviewer identification"
label variable hv019    "NA - Keyer identification"
label variable hv020    "Ever-married sample"
label variable hv021    "Primary sampling unit"
label variable hv022    "Sample strata for sampling errors"
label variable hv023    "Stratification used in sample design"
label variable hv024    "Region"
label variable hv025    "Type of place of residence"
label variable hv026    "NA - Place of residence"
label variable hv027    "Household selected for male interview"
label variable hv028    "Household weight for male subsample (6 decimals)"
label variable hv030    "Field supervisor"
label variable hv031    "NA - Field editor"
label variable hv032    "NA - Office editor"
label variable hv035    "Number of eligible children for height and weight"
label variable hv040    "Cluster altitude in meters"
label variable hv041    "Total adults measured"
label variable hv042    "Household selected for hemoglobin"
label variable hv044    "NA - Household selected for Domestic Violence module"
label variable hv201    "Source of drinking water"
label variable hv202    "NA - Source of non-drinking water"
label variable hv204    "Time to get to water source (minutes)"
label variable hv205    "Type of toilet facility"
label variable hv206    "Has electricity"
label variable hv207    "Has radio"
label variable hv208    "Has television"
label variable hv209    "Has refrigerator"
label variable hv210    "Has bicycle"
label variable hv211    "Has motorcycle/scooter"
label variable hv212    "Has car/truck"
label variable hv213    "Main floor material"
label variable hv214    "Main wall material"
label variable hv215    "Main roof material"
label variable hv216    "Number of rooms used for sleeping"
label variable hv217    "Relationship structure"
label variable hv218    "Line number of head of household"
label variable hv219    "Sex of head of household"
label variable hv220    "Age of head of household"
label variable hv221    "Has telephone (land-line)"
label variable hv225    "Share toilet with other households"
label variable hv226    "Type of cooking fuel"
label variable hv227    "NA - Has mosquito bed net for sleeping"
label variable hv228    "NA - Children under 5 slept under mosquito bed net last night"
label variable hv230a   "Place where household members wash their hands"
label variable hv230b   "Presence of water at hand washing place"
label variable hv232    "Items present: Soap or detergent"
label variable hv232b   "Items present: Ash, mud, sand"
label variable hv232c   "NA - Items present: CS"
label variable hv232d   "NA - Items present: CS"
label variable hv232e   "NA - Items present: CS"
label variable hv232y   "Items present: None"
label variable hv234    "NA - Result of salt test for iodine (PPM)"
label variable hv234a   "Result of salt test for iodine"
label variable hv235    "Location of source for water"
label variable hv236    "NA - Person fetching water"
label variable hv237    "Anything done to water to make safe to drink"
label variable hv237a   "Water usually treated by: boil"
label variable hv237b   "Water usually treated by: add bleach/chlorine"
label variable hv237c   "Water usually treated by: strain through a cloth"
label variable hv237d   "Water usually treated by: use water filter"
label variable hv237e   "Water usually treated by: solar disinfection"
label variable hv237f   "Water usually treated by: let it stand and settle"
label variable hv237g   "NA - Water usually treated by: CS"
label variable hv237h   "NA - Water usually treated by: CS"
label variable hv237i   "NA - Water usually treated by: CS"
label variable hv237j   "NA - Water usually treated by: CS"
label variable hv237k   "NA - Water usually treated by: CS"
label variable hv237x   "Water usually treated by: other"
label variable hv237z   "Water usually treated by: don't know"
label variable hv238    "Number of households sharing toilet"
label variable hv239    "NA - Food cooked on stove or open fire"
label variable hv240    "NA - Household has a chimney, hood or neither"
label variable hv241    "Food cooked in the house/ separate building/ outdoors"
label variable hv242    "Household has separate room used as kitchen"
label variable hv243a   "Has mobile telephone"
label variable hv243b   "Has watch"
label variable hv243c   "Has animal-drawn cart"
label variable hv243d   "NA - Has boat with a motor"
label variable hv244    "Owns land usable for agriculture"
label variable hv245    "Hectares of agricultural land (1 decimal)"
label variable hv246    "Owns livestock, herds or farm animals"
label variable hv246a   "Owns cattle"
label variable hv246b   "Owns cows/ bulls"
label variable hv246c   "Owns horses/ donkeys/ mules"
label variable hv246d   "Owns goats"
label variable hv246e   "Owns sheep"
label variable hv246f   "Owns chickens"
label variable hv246g   "Owns Bulls (CS)"
label variable hv246h   "Owns cows(CS)"
label variable hv246i   "Owns Improved chickens(CS)"
label variable hv246j   "Ordinary Pigs (CS)"
label variable hv246k   "Improved pigs (CS)"
label variable hv247    "Has bank account"
label variable hv252    "Frequency household members smoke inside the house"
label variable hv253    "NA - Has dwelling been sprayed against mosquitoes in last 12 months"
label variable hv253a   "NA - Dwelling sprayed by: government worker/program"
label variable hv253b   "NA - Dwelling sprayed by: private company"
label variable hv253c   "NA - Dwelling sprayed by: NGO"
label variable hv253d   "NA - Dwelling sprayed by: CS"
label variable hv253e   "NA - Dwelling sprayed by: CS"
label variable hv253f   "NA - Dwelling sprayed by: CS"
label variable hv253g   "NA - Dwelling sprayed by: CS"
label variable hv253h   "NA - Dwelling sprayed by: CS"
label variable hv253x   "NA - Dwelling sprayed by: other"
label variable hv253z   "NA - Dwelling sprayed by: don't know"
label variable hv270    "Wealth index"
label variable hv271    "Wealth index factor score (5 decimals)"
label variable hml1     "NA - Number of mosquito bed nets"
label variable hml1a    "NA - Number of mosquito bed nets with specific information"
label variable hml2     "NA - Number of children under mosquito bed net previous night"
label variable chl0     "NA - Number of de-jure children 5-14 for child labor module"
label variable shzone   "Ecological zone"
label variable sh110b   "Battery or generator"
label variable sh110c   "Solar panel"
label variable sh110i   "Bed/mattress"
label variable sh110j   "Computer"
label variable sh110k   "Internet access"
label variable sh122k   "Owns Rabbits"
label variable sh124    "Nearest health facility"
label variable sh125    "Mode of transport to nearest health facility"
label variable sh126h   "Time taken to nearest health facility in hours"
label variable sh126m   "Time taken to nearest health facility in minutes"
label variable hv101    "Relationship to head"
label variable hv102    "Usual resident"
label variable hv103    "Slept last night"
label variable hv104    "Sex of household member"
label variable hv105    "Age of household members"
label variable hv106    "Highest educational level attained"
label variable hv107    "Highest year of education completed"
label variable hv108    "Education completed in single years"
label variable hv109    "Educational attainment"
label variable hv110    "NA - Member still in school"
label variable hv111    "Mother alive"
label variable hv112    "Mother's line number"
label variable hv113    "Father alive"
label variable hv114    "Father's line number"
label variable hv115    "Current marital status"
label variable hv116    "Currently, formerly, never married"
label variable hv117    "Eligibility for female interview"
label variable hv118    "Eligibility for male interview"
label variable hv120    "Children eligibility for height/weight and hemoglobin"
label variable hv121    "Member attended school during current school year"
label variable hv122    "Educational level during current school year"
label variable hv123    "Grade of education during current school year"
label variable hv124    "Education in single years - current school year"
label variable hv125    "NA - Member attended school during previous school year"
label variable hv126    "NA - Educational level during previous school year"
label variable hv127    "NA - Grade of education during previous school year"
label variable hv128    "NA - Education in single years - previous school year"
label variable hv129    "NA - School attendance status"
label variable hv140    "Member has a birth certificate"
label variable idxh4    "Index to Household Schedule"
label variable sh06     "Country member is living in"
label variable sh07     "How long member has lived in country"
label variable sh19a    "Level of education attended"
label variable sh21a    "Level of education attended in current school year"
label variable ha0      "Index to Household Schedule"
label variable ha1      "Woman's age in years"
label variable ha2      "Woman's weight in kilograms (1 decimal)"
label variable ha3      "Woman's height in centimeters (1 decimal)"
label variable ha4      "Height/Age percentile"
label variable ha5      "Height/Age standard deviation"
label variable ha6      "Height/Age percent ref. median"
label variable ha11     "Weight/Height standard deviation (DHS)"
label variable ha12     "Weight/Height percent ref. median (DHS)"
label variable ha12a    "Weight/Height percent ref. median (Fog)"
label variable ha12b    "Weight/Height percent ref. median (WHO)"
label variable ha13     "Result of measurement - height/weight"
label variable ha32     "Date of birth (CMC)"
label variable ha33     "Completeness of HA32 information"
label variable ha35     "Smoking (cigarettes in last 24 hours)"
label variable ha40     "Body Mass Index"
label variable ha41     "Rohrer's index"
label variable ha50     "Under age 18"
label variable ha51     "Line number of parent/caretaker"
label variable ha52     "Read consent statement - hemoglobin"
label variable ha53     "Hemoglobin level (g/dl - 1 decimal)"
label variable ha54     "Currently pregnant"
label variable ha55     "Result of measurement - hemoglobin"
label variable ha56     "Hemoglobin level adjusted for altitude and smoking (g/dl - 1 decimal)"
label variable ha57     "Anemia level"
label variable ha58     "NA - Agrees to referral - anemia"
label variable ha60     "Marital status"
label variable ha61     "Read consent statement - HIV"
label variable ha62     "Bar code for HIV blood sample"
label variable ha63     "Result of measurement - HIV"
label variable ha64     "NA - Consent for additional tests"
label variable ha65     "Result of woman's individual interview"
label variable ha66     "Woman's highest educational level"
label variable ha67     "Woman's highest year of education"
label variable ha68     "Woman's highest educational level (for preliminary and final report)"
label variable ha69     "HIV weight (6 decimals)"
label variable ha70     "Interviewer that took blood for HIV testing"
label variable hc0      "Index to Household Schedule"
label variable hc1      "Child's age in months"
label variable hc2      "Child's weight in kilograms (1 decimal)"
label variable hc3      "Child's height in centimeters (1 decimal)"
label variable hc4      "Height/Age percentile"
label variable hc5      "Height/Age standard deviation"
label variable hc6      "Height/Age percent of ref. median"
label variable hc7      "Weight/Age percentile"
label variable hc8      "Weight/Age standard deviation"
label variable hc9      "Weight/Age percent of ref. median"
label variable hc10     "Weight/Height percentile"
label variable hc11     "Weight/Height standard deviation"
label variable hc12     "Weight/Height percent of ref. median"
label variable hc13     "Result of measurement - height/weight"
label variable hc15     "Height: lying or standing"
label variable hc16     "Day of birth"
label variable hc17     "Date measured (day)"
label variable hc18     "Date measured (month)"
label variable hc19     "Date measured (year)"
label variable hc27     "Sex"
label variable hc30     "Month of birth"
label variable hc31     "Year of birth"
label variable hc32     "Date of birth (CMC)"
label variable hc33     "Completeness of HC32 information"
label variable hc51     "Line number of parent/caretaker"
label variable hc52     "Read consent statement - hemoglobin"
label variable hc53     "Hemoglobin level (g/dl - 1 decimal)"
label variable hc55     "Result of measurement - hemoglobin"
label variable hc56     "Hemoglobin level adjusted for altitude (g/dl - 1 decimal)"
label variable hc57     "Anemia level"
label variable hc58     "NA - Agrees to referral - anemia"
label variable hc60     "Mother's line number (woman's questionnaire)"
label variable hc61     "Mother's highest educational level"
label variable hc62     "Mother's highest year of education"
label variable hc63     "Preceding birth interval (months)"
label variable hc64     "Birth order number"
label variable hc68     "Mother's highest educational level (for preliminary and final report)"
label variable hc70     "Height/Age standard deviation (new WHO)"
label variable hc71     "Weight/Age standard deviation (new WHO)"
label variable hc72     "Weight/Height standard deviation (new WHO)"
label variable hc73     "BMI standard deviation (new WHO)"
label variable hb0      "Index to Household Schedule"
label variable hb1      "Man's age in years"
label variable hb2      "Man's weight in kilograms (1 decimal)"
label variable hb3      "Man's height in centimeters (1 decimal)"
label variable hb4      "Height/Age percentile"
label variable hb5      "Height/Age standard deviation"
label variable hb6      "Height/Age percent ref. median"
label variable hb11     "Weight/Height standard deviation (DHS)"
label variable hb12     "Weight/Height percent ref. median (DHS)"
label variable hb12a    "Weight/Height percent ref. median (Fog)"
label variable hb12b    "Weight/Height percent ref. median (WHO)"
label variable hb13     "Result of measurement - height/weight"
label variable hb32     "Date of birth (CMC)"
label variable hb33     "Completeness of HB32 information"
label variable hb35     "Smoking (cigarettes in last 24 hours)"
label variable hb40     "Body Mass Index"
label variable hb41     "Rohrer's index"
label variable hb50     "Under age 18"
label variable hb51     "Line number of parent/caretaker"
label variable hb52     "Read consent statement - hemoglobin"
label variable hb53     "Hemoglobin level (g/dl - 1 decimal)"
label variable hb55     "Result of measurement - hemoglobin"
label variable hb56     "Hemoglobin level adjusted for altitude and smoking (g/dl - 1 decimal)"
label variable hb57     "Anemia level"
label variable hb58     "NA - Agrees to referral - anemia"
label variable hb60     "Marital status"
label variable hb61     "Read consent statement - HIV"
label variable hb62     "Bar code for HIV blood sample"
label variable hb63     "Result of measurement - HIV"
label variable hb64     "NA - Consent for additional tests"
label variable hb65     "Result of man's individual interview"
label variable hb66     "Man's highest educational level"
label variable hb67     "Man's highest year of education"
label variable hb68     "Man's highest educational level (for preliminary and final report)"
label variable hb69     "HIV weight (6 decimals)"
label variable hb70     "Interviewer that took blood for HIV testing"

#delimit ;
label define HV003   
     0 "Incomplete household"
;
label define HV015   
     1 "Completed"
     2 "No Household member/no competent member at home"
     3 "Entire Household absent for extended period of time"
     4 "Postponed"
     5 "Refused"
     6 "Dwelling vacant or address not a dwelling"
     7 "Dwelling destroyed"
     8 "Dwelling not found"
     9 "Other"
;
label define HV017   
     9 "Missing"
;
label define HV018   
   999 "Missing"
;
label define HV020   
     0 "All woman sample"
     1 "Ever married sample"
;
label define HV022   
     1 "Botha-bothe - Rural"
     2 "Botha-bothe - Urban"
     3 "Leribe - Rural"
     4 "Leribe - Urban"
     5 "Berea - Rural"
     6 "Berea - Urban"
     7 "Maseru - Rural"
     8 "Maseru - Urban"
     9 "Mafeteng - Rural"
    10 "Mafeteng - Urban"
    11 "Mohale's hoek - Rural"
    12 "Mohale's hoek - Urban"
    13 "Quthing - Rural"
    14 "Quthing - Urban"
    15 "Qacha's-nek - Rural"
    16 "Qacha's-nek - Urban"
    17 "Mokhotlong - Rural"
    18 "Mokhotlong - Urban"
    19 "Thaba Tseka - Rural"
    20 "Thaba Tseka - Urban"
;
label define HV023   
     1 "Botha-bothe - Rural"
     2 "Botha-bothe - Urban"
     3 "Leribe - Rural"
     4 "Leribe - Urban"
     5 "Berea - Rural"
     6 "Berea - Urban"
     7 "Maseru - Rural"
     8 "Maseru - Urban"
     9 "Mafeteng - Rural"
    10 "Mafeteng - Urban"
    11 "Mohale's hoek - Rural"
    12 "Mohale's hoek - Urban"
    13 "Quthing - Rural"
    14 "Quthing - Urban"
    15 "Qacha's-nek - Rural"
    16 "Qacha's-nek - Urban"
    17 "Mokhotlong - Rural"
    18 "Mokhotlong - Urban"
    19 "Thaba Tseka - Rural"
    20 "Thaba Tseka - Urban"
;
label define HV024   
     1 "Botha-bothe"
     2 "Leribe"
     3 "Berea"
     4 "Maseru"
     5 "Mafeteng"
     6 "Mohale's hoek"
     7 "Quthing"
     8 "Qacha's-nek"
     9 "Mokhotlong"
    10 "Thaba Tseka"
;
label define HV025   
     1 "Urban"
     2 "Rural"
;
label define HV026   
     0 "Capital, large city"
     1 "Small city"
     2 "Town"
     3 "Countryside"
;
label define HV027   
     0 "Not selected"
     1 "Men's survey"
     2 "Husband's survey"
;
label define HV030   
   999 "Missing"
;
label define HV040   
  9999 "Missing"
;
label define HV042   
     0 "Not selected"
     1 "Selected"
;
label define HV044   
     0 "Household not selected"
     1 "Household selected"
;
label define HV201   
    10 "PIPED WATER"
    11 "Piped into dwelling"
    12 "Piped to yard/plot"
    13 "Public tap/standpipe"
    14 "Neighbour's tap"
    20 "TUBE WELL WATER"
    21 "Tube well or borehole"
    30 "DUG WELL (OPEN/PROTECTED)"
    31 "Protected well"
    32 "Unprotected well"
    40 "SURFACE WATER"
    41 "Protected spring"
    42 "Unprotected spring"
    43 "River/dam/lake/ponds/stream/canal/irrigation channel"
    51 "Rainwater"
    61 "Tanker truck"
    62 "Cart with small tank"
    71 "Bottled water"
    96 "Other"
;
label define HV202   
    10 "PIPED WATER"
    11 "Piped into dwelling"
    12 "Piped to yard/plot"
    13 "Public tap/standpipe"
    20 "TUBE WELL WATER"
    21 "Tube well or borehole"
    30 "DUG WELL (OPEN/PROTECTED)"
    31 "Protected well"
    32 "Unprotected well"
    40 "SURFACE WATER"
    41 "Protected spring"
    42 "Unprotected spring"
    43 "River/dam/lake/ponds/stream/canal/irrigation channel"
    51 "Rainwater"
    61 "Tanker truck"
    62 "Cart with small tank"
    71 "Bottled water"
    96 "Other"
;
label define HV204   
   996 "On premises"
   998 "Don't know"
;
label define HV205   
    10 "FLUSH TOILET"
    11 "Flush to piped sewer system"
    12 "Flush to septic tank"
    13 "Flush to pit latrine"
    14 "Flush to somewhere else"
    15 "Flush, don't know where"
    20 "PIT TOILET LATRINE"
    21 "Ventilated Improved Pit latrine (VIP)"
    22 "Pit latrine with slab"
    23 "Pit latrine without slab/open pit"
    30 "NO FACILITY"
    31 "No facility/bush/field"
    41 "Composting toilet"
    42 "Bucket toilet"
    43 "Hanging toilet/latrine"
    96 "Other"
;
label define HV206   
     0 "No"
     1 "Yes"
;
label define HV207   
     0 "No"
     1 "Yes"
;
label define HV208   
     0 "No"
     1 "Yes"
;
label define HV209   
     0 "No"
     1 "Yes"
;
label define HV210   
     0 "No"
     1 "Yes"
;
label define HV211   
     0 "No"
     1 "Yes"
;
label define HV212   
     0 "No"
     1 "Yes"
;
label define HV213   
    10 "NATURAL"
    11 "Earth/mud/dung"
    20 "Rudimentary"
    21 "Wood planks"
    30 "FINISHED"
    31 "Parquet or polished wood"
    32 "Vinyl tile/vinyl carpet"
    33 "Ceramic tiles"
    34 "Cement"
    35 "Carpet"
    96 "Other"
;
label define HV214   
    10 "NATURAL"
    11 "Cane/tree trunks"
    12 "Sod"
    20 "Rudimentary"
    21 "Stone with mud"
    22 "Plywood"
    23 "Cardboard"
    24 "Reused wood"
    30 "FINISHED"
    31 "Cement"
    32 "Stone with lime/cement"
    33 "Bricks"
    34 "Cement blocks"
    35 "Wood planks/shingles/metal/corrugated"
    96 "Other"
;
label define HV215   
    10 "NATURAL"
    11 "Thatch/grass"
    12 "Sod"
    20 "RUDIMENTARY"
    21 "Wood planks"
    22 "Cardboard"
    30 "FINISHED"
    31 "Metal/corrugated"
    32 "Wood"
    33 "Asbestos/cement fiber"
    34 "Ceramic/clay tiles"
    35 "Cement"
    36 "Roofing shingles"
    96 "Other"
;
label define HV216   
    99 "Missing"
;
label define HV217   
     0 "No adults"
     1 "One adult"
     2 "Two adults, opposite sex"
     3 "Two adults, same sex"
     4 "Three+ related adults"
     5 "Unrelated adults"
;
label define HV219   
     1 "Male"
     2 "Female"
;
label define HV220   
    97 "97+"
    98 "Don't know"
;
label define HV221   
     0 "No"
     1 "Yes"
;
label define HV225   
     0 "No"
     1 "Yes"
;
label define HV226   
     1 "Electricity"
     2 "LPG"
     3 "Natural gas"
     4 "Biogas"
     5 "Kerosene"
     6 "Coal, lignite"
     7 "Charcoal"
     8 "Wood"
     9 "Straw/shrubs/grass"
    10 "Agricultural crop"
    11 "Animal dung"
    95 "No food cooked in house"
    96 "Other"
;
label define HV227   
     0 "No"
     1 "Yes"
;
label define HV228   
     0 "No"
     1 "All children"
     2 "Some children"
     3 "No net in household"
;
label define HV230A  
     1 "Observed"
     2 "Not observed: not in dwelling"
     3 "Not observed: no permission to see"
     4 "Not observed: other reason"
     5 "Not observed, no specific place"
;
label define HV230B  
     0 "Water not available"
     1 "Water is available"
;
label define HV232   
     0 "No"
     1 "Yes"
;
label define HV232B  
     0 "No"
     1 "Yes"
;
label define HV232C  
     0 "No"
     1 "Yes"
;
label define HV232D  
     0 "No"
     1 "Yes"
;
label define HV232E  
     0 "No"
     1 "Yes"
;
label define HV232Y  
     0 "No"
     1 "Yes: no cleansing agent observed"
;
label define HV234   
     0 "0 PPM (no iodine)"
     7 "Below 15 PPM"
    15 "15 PPM and above"
    30 "30 PPM"
   994 "Salt not tested"
   995 "No salt in household"
;
label define HV234A  
     0 "No iodine"
     1 "Iodine present"
     3 "No salt in household"
     6 "Salt not tested"
;
label define HV235   
     1 "In own dwelling"
     2 "In own yard/plot"
     3 "Elsewhere"
;
label define HV236   
     1 "Adult woman"
     2 "Adult man"
     3 "Female child under 15 years old"
     4 "Male child under 15 years old"
     6 "Other"
;
label define HV237   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237A  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237B  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237C  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237D  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237E  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237F  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237G  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237H  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237I  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237J  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237K  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237X  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237Z  
     0 "No"
     1 "Yes: don't know what is done to water"
     8 "Don't know"
;
label define HV238   
    95 "10 or more households"
    98 "Don't know"
;
label define HV239   
     1 "Open fire"
     2 "Open stove"
     3 "Closed stove with chimney"
     6 "Other"
;
label define HV240   
     0 "Neither chimney or hood"
     1 "Chimney"
     2 "Hood"
;
label define HV241   
     1 "In the house"
     2 "In a separate building"
     3 "Outdoors"
     6 "Other"
;
label define HV242   
     0 "No"
     1 "Yes"
;
label define HV243A  
     0 "No"
     1 "Yes"
;
label define HV243B  
     0 "No"
     1 "Yes"
;
label define HV243C  
     0 "No"
     1 "Yes"
;
label define HV243D  
     0 "No"
     1 "Yes"
;
label define HV244   
     0 "No"
     1 "Yes"
;
label define HV245   
   950 "95 or more"
   998 "Unknown"
;
label define HV246   
     0 "No"
     1 "Yes"
;
label define HV246A  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246B  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246C  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246D  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246E  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246F  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246G  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246H  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246I  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246J  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246K  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV247   
     0 "No"
     1 "Yes"
;
label define HV252   
     0 "Never"
     1 "Daily"
     2 "Weekly"
     3 "Monthly"
     4 "Less than monthly"
;
label define HV253   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV253A  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV253B  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV253C  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV253D  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV253E  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV253F  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV253G  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV253H  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV253X  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV253Z  
     0 "No"
     1 "Yes: don't know who sprayed the dwelling"
     8 "Don't know if it was sprayed"
;
label define HV270   
     1 "Poorest"
     2 "Poorer"
     3 "Middle"
     4 "Richer"
     5 "Richest"
;
label define HML1    
    98 "Don't know"
;
label define HML2    
    99 "Missing"
;
label define SHZONE  
     1 "Lowlands"
     2 "Foothills"
     3 "Mountains"
     4 "Senqu River Valley"
;
label define SH110B  
     1 "Yes"
     0 "No"
;
label define SH110C  
     1 "Yes"
     0 "No"
;
label define SH110I  
     1 "Yes"
     0 "No"
;
label define SH110J  
     1 "Yes"
     0 "No"
;
label define SH110K  
     1 "Yes"
     0 "No"
;
label define SH122K  
     0 "None"
    95 "More than 95"
    98 "Unknown"
;
label define SH124   
     1 "Abia (St Josephs)"
     2 "Auray health center"
     3 "Bafokeng"
     4 "Bathopele clinic"
     5 "Beautitude"
     6 "Berea govt hospital"
     7 "Berea private"
     8 "Bethany mission health center"
     9 "Bethel health center"
    10 "Bobete health center"
    11 "Boiketsiso health center"
    12 "Bongani Leseli nursing health center"
    13 "Bophelong private clinic"
    14 "Botha-Bothe govt hospital"
    15 "Bots'abelo leprosy hospital"
    16 "Carewell health center"
    17 "Caselin clinic"
    18 "Cehal private clinic"
    19 "Center for equal health access clinic"
    20 "City clinic"
    21 "Dilli-Dilli health center"
    22 "Domicilliary health center"
    23 "Dual clinic"
    24 "Emmanuel health center"
    25 "Emmaus health center"
    26 "Fatima/Ramabanta health center"
    27 "Fobane health center"
    28 "Gateway clinic (Queen ‘mamohato memorial hospital)"
    29 "Good shepherd health center"
    30 "Ha Lephoi health center"
    31 "Ha Makoae health center"
    32 "Ha Mokoto health center"
    33 "Ha Pita health center"
    34 "Ha Popa health center"
    35 "Ha Seng health center"
    36 "Ha TŠepo health center"
    37 "Ha-Tlali health center"
    38 "Hanson (private) clinic"
    39 "Health care clinic"
    40 "Hermitage health center"
    41 "Holy Cross health center"
    42 "Immaculate conception"
    43 "Jesse polyclinic"
    44 "Katleho clinic"
    45 "Katse health center"
    46 "Kena health center"
    47 "Khabo health center"
    48 "Khubetsoana health center"
    49 "Koali health center"
    50 "Kolberg/khohlontŠo"
    51 "Kolo health center"
    52 "Kolojane health center"
    53 "Korokoro health center (St. Joseph)"
    54 "Kuebunyane health center"
    55 "L&L family clinic"
    56 "Lebakeng health center"
    57 "Leco-op health center"
    58 "Lehlakeng health center"
    59 "Lejone health center"
    60 "Lenkotong clinic"
    61 "Leqele clinic"
    62 "Leseli (private)"
    63 "Leseli (thabaneng) clinic"
    64 "Lesotho college of education (LCE) clinic"
    65 "Lesotho Planned Parenthood Association (LPPA)"
    66 "LetŠeng diamond mine clinic"
    67 "Libibing health center"
    68 "Likalaneng health center"
    69 "Likotsi filter clinic"
    70 "Linakaneng health center"
    71 "Linakeng (BB) health center"
    72 "Linakeng health center (TT)"
    73 "Linotsing health center"
    74 "Liphiring health center"
    75 "Lisemelo health center"
    76 "Lithipeng health center"
    77 "Little Flower health center"
    78 "LitŠoeneng health center"
    79 "Loretto health center"
    80 "Louis Gerard health center"
    81 "Mabatho clinic"
    82 "Mabote filter clinic"
    83 "Machabeng hospital"
    84 "Mafeteng govt hospital"
    85 "Mafube clinic"
    86 "Mahlatsa health center"
    87 "Mahlompho clinic"
    88 "Mahobong health center"
    89 "Mahobong Holy Trinity health center"
    90 "Makhalanyane clinic"
    91 "Makoa private"
    92 "Makoanyane Military Hospital"
    93 "Malea-Lea health center"
    94 "Maluti hospital"
    95 "Manamaneng health center"
    96 "Manthati (ha seetsi) clinic"
    97 "Mapheleng health center"
    98 "Mapholaneng health center"
    99 "Maputsoe filter clinic"
   100 "Maputsoe SDA Health Center"
   101 "Maqhaka Health Center (HOLY FAMILY)"
   102 "Maqokho Health Center"
   103 "MarakabeI Health Center"
   104 "Maryland Health Center"
   105 "MasechabA CLINIC"
   106 "MasemousE Health Center"
   107 "Maseru children center of exellence"
   108 "MASERU CORRECTIONAL SERVICES CLINIC"
   109 "MASERU PRIVATE HOSPITAL"
   110 "MASERU SDA Health Center"
   111 "MASIANOKENG CLINIC"
   112 "MATEBENG Health Center"
   113 "MATELILE Health Center"
   114 "MATLAMENG Health Center"
   115 "MATSIENG Health Center"
   116 "MATUKENG Health Center"
   117 "MEDICAL ARTS CLINIC"
   118 "MELIKANE Health Center"
   119 "METHALANENG Health Center"
   120 "MOEKETSANE Health Center"
   121 "MOFOKA Health Center"
   122 "MOFUMAHALI OA ROSARI Health Center"
   123 "MOHALE Health Center"
   124 "MOHALEROE PRIVATE"
   125 "MOHALE’S HOEK CORRECTIONAL SERVICES"
   126 "MOHALINYANE Health Center"
   127 "MOHLANAPENG Health Center"
   128 "MOHLAPISO Health Center"
   129 "MOHLOMI MENTAL HOSPITAL"
   130 "MOKHOTLONG HOSPITAL"
   131 "MOLIKALIKO Health Center"
   132 "MOLOPI CLINIC"
   133 "MONTMARTRE Health Center"
   134 "MOOTSINYANE Health Center"
   135 "MORIFI Health Center"
   136 "MOTEBANG HOSPITAL"
   137 "MOTETE Health Center"
   138 "MOTSEKUOA Health Center"
   139 "MOUNT TABOR Health Center"
   140 "MPHAKI Health Center"
   141 "MPHARANE Health Center"
   142 "Mt OLIVET Health Center"
   143 "N.U.L. Health Center"
   144 "NAZARETH Health Center"
   145 "NGOAJANE/KHATIBE Health Center"
   146 "NKAU Health Center"
   147 "NOHANA Health Center"
   148 "NTŠEKHE HOSPITAL"
   149 "OSMAN (PRIVATE)"
   150 "OUR LADY OF LOURDES/MOSITI Health Center"
   151 "PABALLONG PRIVATE ART CENTRE"
   152 "PAKI Health Center"
   153 "PALAMA Health Center"
   154 "PARAY MISSION HOSPITAL"
   155 "PEKA Health Center"
   156 "PHAMONG Health Center"
   157 "PHELA-U-PHELISE CLINIC"
   158 "PILOT Health Center"
   159 "PONTMAIN Health Center"
   160 "PSHATLELLA Health Center"
   161 "QHOLAQHOE Health Center (MAKHUNOANE)"
   162 "QOALING FILTER CLINIC"
   163 "QUEEN ‘MAMOHATO MEMORIAL HOSPITAL"
   164 "QUTHING GovernmentHOSPITAL"
   165 "R.L.D.F. Health Center"
   166 "RAMPAI Health Center"
   167 "RANKAKALA Health Center"
   168 "RIBANENG Health Center"
   169 "ROSYM CLINIC"
   170 "SACRED HEART Health Center"
   171 "SAMARIA Health Center"
   172 "SCOTT MISSION HOSPITAL"
   173 "SEBEDIA Health Center"
   174 "SEBOCHE HOSPITAL"
   175 "SEETSA Health Center"
   176 "SEHLABA-THEBE Health Center"
   177 "SEHONG-HONG Health Center"
   178 "SEKAKE Health Center"
   179 "SEKAMANENG CLINIC"
   180 "SEKAMENG Health Center"
   181 "SEMENANYANA Health Center"
   182 "SEMONKONG Health Center"
   183 "SENKATANA CLINIC"
   184 "SEPINARE Health Center"
   185 "SESHOTE Health Center"
   186 "SHIFAa CLINIC"
   187 "SION Health Center"
   188 "SOS CLINIC"
   189 "SPRINGFIELD Health Center"
   190 "ST ANDREW Health Center"
   191 "ST ANNE Health Center"
   192 "ST BARNABAS Health Center (MASITE)"
   193 "ST BENEDICT Health Center"
   194 "ST BERNARD Health Center"
   195 "ST CLARE Health Center"
   196 "ST DAVID Health Center"
   197 "ST DENIS Health Center"
   198 "ST FRANCIS Health Center"
   199 "ST GABRIEL Health Center"
   200 "ST JAMES Health Center"
   201 "ST JAMES MISSION HOSPITAL"
   202 "ST JOSEPHS HOSPITAL"
   203 "ST LEO Health Center"
   204 "ST LEONARD Health Center"
   205 "ST MAGDALENA Health Center"
   206 "ST MARGRET Health Center"
   207 "ST MARTIN Health Center"
   208 "ST MATTHEWS Health Center"
   209 "ST MONICAS Health Center"
   210 "ST PAUL Health Center"
   211 "ST PETER CLAVER Health Center (TŠOENENG)"
   212 "ST PETER'S Health Center"
   213 "ST PETERS Health Center (MOTENG)"
   214 "ST RODRIGUE Health Center"
   215 "ST ROSE Health Center"
   216 "ST THERESA Health Center"
   217 "ST THERESA (BELA-BELA) Health Center"
   218 "TEBELLONG HOSPITAL"
   219 "THABA TŠOEU Health Center"
   220 "THABA-BOSIU Health Center"
   221 "THABA-PHAT?OA Health Center"
   222 "THABA-TSEKA Health Center"
   223 "THABANA-MORENA Health Center"
   224 "THAMAE Health Center"
   225 "THUSANANG Health Center"
   226 "TLHANYAKU Health Center"
   227 "TSATSANE Health Center"
   228 "TSIME Health Center"
   229 "TŠAKHOLO Health Center"
   230 "TŠENOLA PRIVATEC LINIC(MAMA'S)"
   231 "VILLA MARIA Health Center"
   232 "WILLIES CLINIC"
   233 "‘MALEFILOANE Health Center"
   234 "‘MAMOHAU MISSION HOSPITAL"
   235 "‘MUELA SITE Health Center"
   236 "‘NELESE CLINIC"
   996 "Other"
   998 "Don't know"
;
label define SH125   
     1 "Car/truck/bus/taxi"
     2 "Motorcycle/scooter"
     3 "Bicycle"
     4 "Horse/donkey/mule"
     5 "Scotch cart"
     6 "Walking"
     7 "Combination walking and bus/taxi"
    95 "Household doesn't use nearest health facility"
    98 "Household doesn't know nearest health facility"
    96 "Other"
;
label define SH126H  
    97 "Household doesn't know nearest health facility"
    98 "Don't know"
;
label define SH126M  
    97 "Household doesn't know nearest health facility"
    98 "Don't know"
;
label define HV101   
     1 "Head"
     2 "Wife or husband"
     3 "Son/daughter"
     4 "Son/daughter-in-law"
     5 "Grandchild"
     6 "Parent"
     7 "Parent-in-law"
     8 "Brother/sister"
     9 "Co-spouse"
    10 "Other relative"
    11 "Adopted/foster child"
    12 "Not related"
    13 "Niece/nephew by blood"
    14 "Niece/nephew by marriage"
    15 "Domestic employee"
    16 "Herdboy"
    98 "Don't know"
;
label define HV102   
     0 "No"
     1 "Yes"
;
label define HV103   
     0 "No"
     1 "Yes"
;
label define HV104   
     1 "Male"
     2 "Female"
;
label define HV105   
    95 "95+"
    98 "Don't know"
;
label define HV106   
     0 "No education, preschool"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "Don't know"
;
label define HV107   
    98 "Don't know"
;
label define HV108   
    97 "Inconsistent"
    98 "Don't know"
;
label define HV109   
     0 "No education"
     1 "Incomplete primary"
     2 "Complete primary"
     3 "Incomplete secondary"
     4 "Complete secondary"
     5 "Higher"
     8 "Don't know"
;
label define HV110   
     0 "No"
     1 "Yes"
;
label define HV111   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV112   
     0 "Mother not in household"
;
label define HV113   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV114   
     0 "Father not in household"
;
label define HV115   
     0 "Never married"
     1 "Married"
     2 "Living together"
     3 "Widowed"
     4 "Divorced"
     5 "Not living together"
;
label define HV116   
     0 "Never married"
     1 "Currently married"
     2 "Formerly/ever married"
;
label define HV117   
     0 "Not eligible"
     1 "Eligible"
;
label define HV118   
     0 "Not eligible"
     1 "Eligible"
;
label define HV120   
     0 "Not eligible"
     1 "Eligible"
;
label define HV121   
     0 "No"
     1 "Currently attending"
     2 "Attended at some time"
;
label define HV122   
     0 "No education, preschool"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "Don't know"
;
label define HV123   
    98 "Don't know"
;
label define HV124   
    97 "Inconsistent"
    98 "Don't know"
;
label define HV125   
     0 "No"
     1 "Yes"
;
label define HV126   
     0 "No education, preschool"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "Don't know"
;
label define HV127   
    98 "Don't know"
;
label define HV128   
    97 "Inconsistent"
    98 "Don't know"
;
label define HV129   
     0 "Never attended"
     1 "Entered school"
     2 "Advanced"
     3 "Repeating"
     4 "Dropout"
     5 "Left school 2+ years ago"
     8 "Don't know"
;
label define HV140   
     0 "Neither certificate or registered"
     1 "Has certificate"
     2 "Registered"
     8 "Don't know"
;
label define SH06    
     1 "Lesotho"
     2 "South Africa"
     3 "Other Country"
;
label define SH07    
     0 "Less than one year"
    98 "Don't know"
;
label define SH19A   
     0 "No education"
     1 "Primary"
     2 "After primary:vocational/tech.training"
     3 "Secondary/high"
     4 "After secondary:vocational/tech.training"
     5 "College"
     6 "Graduate/post graduate"
     8 "Don't know"
;
label define SH21A   
     0 "No education"
     1 "Primary"
     2 "After primary:vocational/tech.training"
     3 "Secondary/high"
     4 "After secondary:vocational/tech.training"
     5 "College"
     6 "Graduate/post graduate"
     8 "Don't know"
;
label define HA2     
  9994 "Not present"
  9995 "Refused"
  9996 "Other"
;
label define HA3     
  9994 "Not present"
  9995 "Refused"
  9996 "Other"
;
label define HA4     
  9998 "Flagged cases"
;
label define HA5     
  9998 "Flagged cases"
;
label define HA6     
 99998 "Flagged cases"
;
label define HA11    
  9998 "Flagged cases"
;
label define HA12    
 99998 "Flagged cases"
;
label define HA12A   
 99998 "Flagged cases"
;
label define HA12B   
 99998 "Flagged cases"
;
label define HA13    
     0 "Measured"
     3 "Not present"
     4 "Refused"
     6 "Other"
;
label define HA33    
     1 "Month and year - information complete"
     2 "Month and age - year imputed"
     3 "Year and age - month imputed"
     4 "Year and age - year ignored"
     5 "Year - age/month imputed"
     6 "Age - year/month imputed"
     7 "Month - age/year imputed"
     8 "None - all imputed"
;
label define HA35    
     0 "Doesn't smoke"
    80 "80+"
    94 "Smokes pipes, cigars, etc"
;
label define HA40    
  9998 "Flagged cases"
;
label define HA41    
  9998 "Flagged cases"
;
label define HA50    
     1 "Under age 18"
     2 "Age 18 or older"
;
label define HA51    
     0 "Not in household"
;
label define HA52    
     1 "Granted"
     2 "Parent/other responsible refused"
     3 "Respondent refused"
;
label define HA53    
   994 "Not present"
   995 "Refused"
   996 "Other"
;
label define HA54    
     0 "No/don't know"
     1 "Yes"
;
label define HA55    
     0 "Measured"
     3 "Not present"
     4 "Refused"
     6 "Other"
;
label define HA56    
   997 "Inconsistent"
;
label define HA57    
     1 "Severe"
     2 "Moderate"
     3 "Mild"
     4 "Not anemic"
;
label define HA58    
     0 "No"
     1 "Yes"
;
label define HA60    
     1 "Never in union"
     2 "Other"
;
label define HA61    
     1 "Granted"
     2 "Parent/other responsible refused"
     3 "Respondent refused"
     4 "Sample not tested/lost/not enough DBS"
;
label define HA63    
     1 "Blood taken"
     2 "Not present"
     3 "Refused"
     4 "Sample not tested/lost/damaged/insufficient"
     5 "Not enough DBS to complete protocol"
     6 "Other"
;
label define HA64    
     1 "Granted"
     2 "Parent/other responsible refused"
     3 "Respondent refused"
;
label define HA65    
     1 "Completed"
     2 "Not at home"
     3 "Postponed"
     4 "Refused"
     5 "Partly completed"
     6 "Incapacitated"
     7 "Other"
;
label define HA66    
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "Don't know"
;
label define HA67    
    98 "Don't know"
;
label define HA68    
     0 "No education"
     1 "Primary incomplete"
     2 "Primary complete"
     3 "Secondary"
     4 "More than secondary"
;
label define HA70    
   999 "Missing"
;
label define HC2     
  9994 "Not present"
  9995 "Refused"
  9996 "Other"
;
label define HC3     
  9994 "Not present"
  9995 "Refused"
  9996 "Other"
;
label define HC4     
  9998 "Flagged cases"
;
label define HC5     
  9998 "Flagged cases"
;
label define HC6     
 99998 "Flagged cases"
;
label define HC7     
  9998 "Flagged cases"
;
label define HC8     
  9998 "Flagged cases"
;
label define HC9     
 99998 "Flagged cases"
;
label define HC10    
  9998 "Flagged cases"
;
label define HC11    
  9998 "Flagged cases"
;
label define HC12    
 99998 "Flagged cases"
;
label define HC13    
     0 "Measured"
     3 "Not present"
     4 "Refused"
     6 "Other"
;
label define HC15    
     0 "Not measured"
     1 "Lying"
     2 "Standing"
;
label define HC16    
    97 "Inconsistent"
    98 "Don't know"
;
label define HC27    
     1 "Male"
     2 "Female"
;
label define HC30    
    97 "Inconsistent"
    98 "Don't know"
;
label define HC31    
  9997 "Inconsistent"
  9998 "Don't know"
;
label define HC33    
     1 "Month and year - information complete"
     2 "Month and age - year imputed"
     3 "Year and age - month imputed"
     6 "Age - year/month imputed"
     7 "Month - age/year imputed"
     8 "None - all imputed"
;
label define HC51    
     0 "Not in household"
;
label define HC52    
     1 "Granted"
     2 "Refused"
;
label define HC53    
   994 "Not present"
   995 "Refused"
   996 "Other"
;
label define HC55    
     0 "Measured"
     3 "Not present"
     4 "Refused"
     6 "Other"
;
label define HC56    
   997 "Inconsistent"
;
label define HC57    
     1 "Severe"
     2 "Moderate"
     3 "Mild"
     4 "Not anemic"
;
label define HC58    
     0 "No"
     1 "Yes"
;
label define HC60    
   993 "Mother not de facto"
   994 "Incomplete woman's interview"
   995 "Not in household"
;
label define HC61    
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "Don't know"
;
label define HC62    
    98 "Don't know"
;
label define HC63    
   999 "Missing"
;
label define HC64    
    99 "Missing"
;
label define HC68    
     0 "No education"
     1 "Primary incomplete"
     2 "Primary complete"
     3 "Secondary"
     4 "More than secondary"
;
label define HC70    
  9996 "Height out of plausible limits"
  9997 "Age in days out of plausible limits"
  9998 "Flagged cases"
;
label define HC71    
  9996 "Height out of plausible limits"
  9997 "Age in days out of plausible limits"
  9998 "Flagged cases"
;
label define HC72    
  9996 "Height out of plausible limits"
  9997 "Age in days out of plausible limits"
  9998 "Flagged cases"
;
label define HC73    
  9996 "Height out of plausible limits"
  9997 "Age in days out of plausible limits"
  9998 "Flagged cases"
;
label define HB2     
  9994 "Not present"
  9995 "Refused"
  9996 "Other"
;
label define HB3     
  9994 "Not present"
  9995 "Refused"
  9996 "Other"
;
label define HB4     
  9998 "Flagged cases"
;
label define HB5     
  9998 "Flagged cases"
;
label define HB6     
 99998 "Flagged cases"
;
label define HB11    
  9998 "Flagged cases"
;
label define HB12    
 99998 "Flagged cases"
;
label define HB12A   
 99998 "Flagged cases"
;
label define HB12B   
 99998 "Flagged cases"
;
label define HB13    
     0 "Measured"
     3 "Not present"
     4 "Refused"
     6 "Other"
;
label define HB33    
     1 "Month and year - information complete"
     2 "Month and age - year imputed"
     3 "Year and age - month imputed"
     4 "Year and age - year ignored"
     5 "Year - age/month imputed"
     6 "Age - year/month imputed"
     7 "Month - age/year imputed"
     8 "None - all imputed"
;
label define HB35    
     0 "Doesn't smoke"
    80 "80+"
    94 "Smokes pipes, cigars, etc"
;
label define HB40    
  9998 "Flagged cases"
;
label define HB41    
  9998 "Flagged cases"
;
label define HB50    
     1 "Under age 18"
     2 "Age 18 or older"
;
label define HB51    
     0 "Not in household"
;
label define HB52    
     1 "Granted"
     2 "Parent/other responsible refused"
     3 "Respondent refused"
;
label define HB53    
   994 "Not present"
   995 "Refused"
   996 "Other"
;
label define HB55    
     0 "Measured"
     3 "Not present"
     4 "Refused"
     6 "Other"
;
label define HB56    
   997 "Inconsistent"
;
label define HB57    
     1 "Severe"
     2 "Moderate"
     3 "Mild"
     4 "Not anemic"
;
label define HB58    
     0 "No"
     1 "Yes"
;
label define HB60    
     1 "Never in union"
     2 "Other"
;
label define HB61    
     1 "Granted"
     2 "Parent/other responsible refused"
     3 "Respondent refused"
     4 "Sample not tested/lost/not enough DBS"
;
label define HB63    
     1 "Blood taken"
     2 "Not present"
     3 "Refused"
     4 "Sample not tested/lost/damaged/insufficient"
     5 "Not enough DBS to complete protocol"
     6 "Other"
;
label define HB64    
     1 "Granted"
     2 "Parent/other responsible refused"
     3 "Respondent refused"
;
label define HB65    
     1 "Completed"
     2 "Not at home"
     3 "Postponed"
     4 "Refused"
     5 "Partly completed"
     6 "Incapacitated"
     7 "Other"
;
label define HB66    
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "Don't know"
;
label define HB67    
    98 "Don't know"
;
label define HB68    
     0 "No education"
     1 "Primary incomplete"
     2 "Primary complete"
     3 "Secondary"
     4 "More than secondary"
;
label define HB70    
   999 "Missing"
;

#delimit cr
label values hv003    HV003   
label values hv015    HV015   
label values hv020    HV020   
label values hv022    HV022   
label values hv023    HV023   
label values hv024    HV024   
label values hv025    HV025   
label values hv026    HV026   
label values hv027    HV027   
label values hv042    HV042   
label values hv044    HV044   
label values hv201    HV201   
label values hv202    HV202   
label values hv204    HV204   
label values hv205    HV205   
label values hv206    HV206   
label values hv207    HV207   
label values hv208    HV208   
label values hv209    HV209   
label values hv210    HV210   
label values hv211    HV211   
label values hv212    HV212   
label values hv213    HV213   
label values hv214    HV214   
label values hv215    HV215   
label values hv217    HV217   
label values hv219    HV219   
label values hv220    HV220   
label values hv221    HV221   
label values hv225    HV225   
label values hv226    HV226   
label values hv227    HV227   
label values hv228    HV228   
label values hv230a   HV230A  
label values hv230b   HV230B  
label values hv232    HV232   
label values hv232b   HV232B  
label values hv232c   HV232C  
label values hv232d   HV232D  
label values hv232e   HV232E  
label values hv232y   HV232Y  
label values hv234    HV234   
label values hv234a   HV234A  
label values hv235    HV235   
label values hv236    HV236   
label values hv237    HV237   
label values hv237a   HV237A  
label values hv237b   HV237B  
label values hv237c   HV237C  
label values hv237d   HV237D  
label values hv237e   HV237E  
label values hv237f   HV237F  
label values hv237g   HV237G  
label values hv237h   HV237H  
label values hv237i   HV237I  
label values hv237j   HV237J  
label values hv237k   HV237K  
label values hv237x   HV237X  
label values hv237z   HV237Z  
label values hv238    HV238   
label values hv239    HV239   
label values hv240    HV240   
label values hv241    HV241   
label values hv242    HV242   
label values hv243a   HV243A  
label values hv243b   HV243B  
label values hv243c   HV243C  
label values hv243d   HV243D  
label values hv244    HV244   
label values hv245    HV245   
label values hv246    HV246   
label values hv246a   HV246A  
label values hv246b   HV246B  
label values hv246c   HV246C  
label values hv246d   HV246D  
label values hv246e   HV246E  
label values hv246f   HV246F  
label values hv246g   HV246G  
label values hv246h   HV246H  
label values hv246i   HV246I  
label values hv246j   HV246J  
label values hv246k   HV246K  
label values hv247    HV247   
label values hv252    HV252   
label values hv253    HV253   
label values hv253a   HV253A  
label values hv253b   HV253B  
label values hv253c   HV253C  
label values hv253d   HV253D  
label values hv253e   HV253E  
label values hv253f   HV253F  
label values hv253g   HV253G  
label values hv253h   HV253H  
label values hv253x   HV253X  
label values hv253z   HV253Z  
label values hv270    HV270   
label values hml1     HML1    
label values shzone   SHZONE  
label values sh110b   SH110B  
label values sh110c   SH110C  
label values sh110i   SH110I  
label values sh110j   SH110J  
label values sh110k   SH110K  
label values sh122k   SH122K  
label values sh124    SH124   
label values sh125    SH125   
label values sh126h   SH126H  
label values sh126m   SH126M  
label values hv101    HV101   
label values hv102    HV102   
label values hv103    HV103   
label values hv104    HV104   
label values hv105    HV105   
label values hv106    HV106   
label values hv107    HV107   
label values hv108    HV108   
label values hv109    HV109   
label values hv110    HV110   
label values hv111    HV111   
label values hv112    HV112   
label values hv113    HV113   
label values hv114    HV114   
label values hv115    HV115   
label values hv116    HV116   
label values hv117    HV117   
label values hv118    HV118   
label values hv120    HV120   
label values hv121    HV121   
label values hv122    HV122   
label values hv123    HV123   
label values hv124    HV124   
label values hv125    HV125   
label values hv126    HV126   
label values hv127    HV127   
label values hv128    HV128   
label values hv129    HV129   
label values hv140    HV140   
label values sh06     SH06    
label values sh07     SH07    
label values sh19a    SH19A   
label values sh21a    SH21A   
label values ha2      HA2     
label values ha3      HA3     
label values ha4      HA4     
label values ha5      HA5     
label values ha6      HA6     
label values ha11     HA11    
label values ha12     HA12    
label values ha12a    HA12A   
label values ha12b    HA12B   
label values ha13     HA13    
label values ha33     HA33    
label values ha35     HA35    
label values ha40     HA40    
label values ha41     HA41    
label values ha50     HA50    
label values ha51     HA51    
label values ha52     HA52    
label values ha53     HA53    
label values ha54     HA54    
label values ha55     HA55    
label values ha56     HA56    
label values ha57     HA57    
label values ha58     HA58    
label values ha60     HA60    
label values ha61     HA61    
label values ha63     HA63    
label values ha64     HA64    
label values ha65     HA65    
label values ha66     HA66    
label values ha67     HA67    
label values ha68     HA68    
label values hc2      HC2     
label values hc3      HC3     
label values hc4      HC4     
label values hc5      HC5     
label values hc6      HC6     
label values hc7      HC7     
label values hc8      HC8     
label values hc9      HC9     
label values hc10     HC10    
label values hc11     HC11    
label values hc12     HC12    
label values hc13     HC13    
label values hc15     HC15    
label values hc16     HC16    
label values hc27     HC27    
label values hc30     HC30    
label values hc31     HC31    
label values hc33     HC33    
label values hc51     HC51    
label values hc52     HC52    
label values hc53     HC53    
label values hc55     HC55    
label values hc56     HC56    
label values hc57     HC57    
label values hc58     HC58    
label values hc60     HC60    
label values hc61     HC61    
label values hc62     HC62    
label values hc68     HC68    
label values hc70     HC70    
label values hc71     HC71    
label values hc72     HC72    
label values hc73     HC73    
label values hb2      HB2     
label values hb3      HB3     
label values hb4      HB4     
label values hb5      HB5     
label values hb6      HB6     
label values hb11     HB11    
label values hb12     HB12    
label values hb12a    HB12A   
label values hb12b    HB12B   
label values hb13     HB13    
label values hb33     HB33    
label values hb35     HB35    
label values hb40     HB40    
label values hb41     HB41    
label values hb50     HB50    
label values hb51     HB51    
label values hb52     HB52    
label values hb53     HB53    
label values hb55     HB55    
label values hb56     HB56    
label values hb57     HB57    
label values hb58     HB58    
label values hb60     HB60    
label values hb61     HB61    
label values hb63     HB63    
label values hb64     HB64    
label values hb65     HB65    
label values hb66     HB66    
label values hb67     HB67    
label values hb68     HB68    
