infix using "C:\COUNTRIES\LS61\LSHR61FL.dct"

label variable hhid     "Case Identification"
label variable hv000    "Country code and phase"
label variable hv001    "Cluster number"
label variable hv002    "Household number"
label variable hv003    "Respondent's line number"
label variable hv004    "Ultimate area unit"
label variable hv005    "Sample weight"
label variable hv006    "Month of interview"
label variable hv007    "Year of interview"
label variable hv008    "Date of interview (CMC)"
label variable hv009    "Number of household members"
label variable hv010    "Number of eligible women in HH"
label variable hv011    "Number of eligible men in HH"
label variable hv012    "Number of de jure members"
label variable hv013    "Number of de facto members"
label variable hv014    "Number of children 5 and under"
label variable hv015    "Result of household interview"
label variable hv016    "Day of interview"
label variable hv017    "Number of visits"
label variable hv018    "Interviewer identification"
label variable hv019    "NA - Keyer identification"
label variable hv020    "Ever-married sample"
label variable hv021    "Primary sampling unit"
label variable hv022    "Sample stratum number"
label variable hv023    "Sample domain"
label variable hv024    "Region"
label variable hv025    "Type of place of residence"
label variable hv026    "NA - Place of residence"
label variable hv027    "Selection for male/husb. int."
label variable hv028    "Sample weight for male subsamp"
label variable hv030    "Field supervisor"
label variable hv031    "NA - Field editor"
label variable hv032    "NA - Office editor"
label variable hv033    "NA - Ultimate area selection prob."
label variable hv035    "Number of eligible children for height & weight"
label variable hv040    "Cluster altitude in meters"
label variable hv041    "Total adults measured"
label variable hv042    "Selection for hemoglobin"
label variable hv043    "NA - Selection for women's status module"
label variable hv044    "NA - Selection for domestic violence module"
label variable hv201    "Source of drinking water"
label variable hv202    "Source of non-drinking water"
label variable hv204    "Time to get to water source"
label variable hv205    "Type of toilet facility"
label variable hv206    "Has electricity"
label variable hv207    "Has radio"
label variable hv208    "Has television"
label variable hv209    "Has refrigerator"
label variable hv210    "Has bicycle"
label variable hv211    "Has motorcycle/scooter"
label variable hv212    "Has car/truck"
label variable hv213    "Main floor material"
label variable hv214    "Main wall material"
label variable hv215    "Main roof material"
label variable hv216    "Rooms used for sleeping"
label variable hv217    "Relationship structure"
label variable hv218    "Line number of head of househ."
label variable hv219    "Sex of head of household"
label variable hv220    "Age of head of household"
label variable hv221    "Has a landline telephone"
label variable hv225    "Share toilet with other households"
label variable hv226    "Type of cooking fuel"
label variable hv227    "NA - Have bednet for sleeping"
label variable hv228    "NA - Children under 5 slept under bednet last night"
label variable hv234    "Test salt for Iodine"
label variable hv235    "Location of source for water"
label variable hv236    "Person fetching water"
label variable hv237    "Anything done to water to make safe to drink"
label variable hv237a   "Water usually treated by: boil"
label variable hv237b   "Water usually treated by: add bleach/chlorine"
label variable hv237c   "Water usually treated by: strain through a cloth"
label variable hv237d   "Water usually treated by: use water filter"
label variable hv237e   "Water usually treated by: solar disinfection"
label variable hv237f   "Water usually treated by: let it stand and settle"
label variable hv237g   "NA - Water usually treated by: CS"
label variable hv237h   "NA - Water usually treated by: CS"
label variable hv237i   "NA - Water usually treated by: CS"
label variable hv237j   "NA - Water usually treated by: CS"
label variable hv237k   "NA - Water usually treated by: CS"
label variable hv237x   "Water usually treated by: other"
label variable hv237z   "Water usually treated by: don't know"
label variable hv238    "Number of households sharing toilet"
label variable hv239    "Food cooked on stove or open fire"
label variable hv240    "Household has a chimney, hood or neither"
label variable hv241    "Food cooked in the house / in separate building / outdoors"
label variable hv242    "Household has separate room used as kitchen"
label variable hv243a   "Has a mobile telephone"
label variable hv243b   "Has a watch"
label variable hv243c   "Has an animal-drawn cart"
label variable hv243d   "NA - Has a boat with a motor"
label variable hv244    "Own land usable for agriculture"
label variable hv245    "Hectares for agricultural land"
label variable hv246    "Livestock, herds or farm animals"
label variable hv246a   "Cattle own"
label variable hv246b   "Cows, bulls own"
label variable hv246c   "Horses, donkeys, mules own"
label variable hv246d   "Goats own"
label variable hv246e   "Sheep own"
label variable hv246f   "Chickens own"
label variable hv246g   "CS own"
label variable hv246h   "Owns pigs (CS)"
label variable hv246i   "Owns improved pigs (CS)"
label variable hv246j   "Owns rabbits (CS)"
label variable hv246k   "NA - CS own"
label variable hv247    "Owns a bank account"
label variable hv248    "NA - Number of sick people 18-59"
label variable hv249    "NA - Member of the HH died last 12 months"
label variable hv250    "NA - Number of members who died last 12 months"
label variable hv251    "NA - Number of orphans and vulnerable children"
label variable hv270    "Wealth index"
label variable hv271    "Wealth index factor score (5 decimals)"
label variable hml1     "NA - Number of mosquito nets"
label variable hml1a    "NA - Number of mosquito nets with specific information"
label variable hml2     "NA - Number of children under bednet previous night"
label variable shzone   "Lesotho Ecological Zone"
label variable sh111b   "Battery or generator"
label variable sh111h   "Bed/mattress"
label variable sh111i   "Computer"
label variable sh111j   "Internet access"
label variable sh127r   "Region of health facility"
label variable sh127    "Nearest health facility"
label variable sh128    "Mode of transport to nearest health facility"
label variable sh129h   "Time taken to nearest health facility in hours"
label variable sh129m   "Time taken to nearest health facility in minutes"
label variable hvidx_01 "Line number"
label variable hvidx_02 "Line number"
label variable hvidx_03 "Line number"
label variable hvidx_04 "Line number"
label variable hvidx_05 "Line number"
label variable hvidx_06 "Line number"
label variable hvidx_07 "Line number"
label variable hvidx_08 "Line number"
label variable hvidx_09 "Line number"
label variable hvidx_10 "Line number"
label variable hvidx_11 "Line number"
label variable hvidx_12 "Line number"
label variable hvidx_13 "Line number"
label variable hvidx_14 "Line number"
label variable hvidx_15 "Line number"
label variable hvidx_16 "Line number"
label variable hvidx_17 "Line number"
label variable hvidx_18 "Line number"
label variable hvidx_19 "Line number"
label variable hvidx_20 "Line number"
label variable hvidx_21 "Line number"
label variable hv101_01 "Relationship to head"
label variable hv101_02 "Relationship to head"
label variable hv101_03 "Relationship to head"
label variable hv101_04 "Relationship to head"
label variable hv101_05 "Relationship to head"
label variable hv101_06 "Relationship to head"
label variable hv101_07 "Relationship to head"
label variable hv101_08 "Relationship to head"
label variable hv101_09 "Relationship to head"
label variable hv101_10 "Relationship to head"
label variable hv101_11 "Relationship to head"
label variable hv101_12 "Relationship to head"
label variable hv101_13 "Relationship to head"
label variable hv101_14 "Relationship to head"
label variable hv101_15 "Relationship to head"
label variable hv101_16 "Relationship to head"
label variable hv101_17 "Relationship to head"
label variable hv101_18 "Relationship to head"
label variable hv101_19 "Relationship to head"
label variable hv101_20 "Relationship to head"
label variable hv101_21 "Relationship to head"
label variable hv102_01 "Usual resident"
label variable hv102_02 "Usual resident"
label variable hv102_03 "Usual resident"
label variable hv102_04 "Usual resident"
label variable hv102_05 "Usual resident"
label variable hv102_06 "Usual resident"
label variable hv102_07 "Usual resident"
label variable hv102_08 "Usual resident"
label variable hv102_09 "Usual resident"
label variable hv102_10 "Usual resident"
label variable hv102_11 "Usual resident"
label variable hv102_12 "Usual resident"
label variable hv102_13 "Usual resident"
label variable hv102_14 "Usual resident"
label variable hv102_15 "Usual resident"
label variable hv102_16 "Usual resident"
label variable hv102_17 "Usual resident"
label variable hv102_18 "Usual resident"
label variable hv102_19 "Usual resident"
label variable hv102_20 "Usual resident"
label variable hv102_21 "Usual resident"
label variable hv103_01 "Slept last night"
label variable hv103_02 "Slept last night"
label variable hv103_03 "Slept last night"
label variable hv103_04 "Slept last night"
label variable hv103_05 "Slept last night"
label variable hv103_06 "Slept last night"
label variable hv103_07 "Slept last night"
label variable hv103_08 "Slept last night"
label variable hv103_09 "Slept last night"
label variable hv103_10 "Slept last night"
label variable hv103_11 "Slept last night"
label variable hv103_12 "Slept last night"
label variable hv103_13 "Slept last night"
label variable hv103_14 "Slept last night"
label variable hv103_15 "Slept last night"
label variable hv103_16 "Slept last night"
label variable hv103_17 "Slept last night"
label variable hv103_18 "Slept last night"
label variable hv103_19 "Slept last night"
label variable hv103_20 "Slept last night"
label variable hv103_21 "Slept last night"
label variable hv104_01 "Sex of household member"
label variable hv104_02 "Sex of household member"
label variable hv104_03 "Sex of household member"
label variable hv104_04 "Sex of household member"
label variable hv104_05 "Sex of household member"
label variable hv104_06 "Sex of household member"
label variable hv104_07 "Sex of household member"
label variable hv104_08 "Sex of household member"
label variable hv104_09 "Sex of household member"
label variable hv104_10 "Sex of household member"
label variable hv104_11 "Sex of household member"
label variable hv104_12 "Sex of household member"
label variable hv104_13 "Sex of household member"
label variable hv104_14 "Sex of household member"
label variable hv104_15 "Sex of household member"
label variable hv104_16 "Sex of household member"
label variable hv104_17 "Sex of household member"
label variable hv104_18 "Sex of household member"
label variable hv104_19 "Sex of household member"
label variable hv104_20 "Sex of household member"
label variable hv104_21 "Sex of household member"
label variable hv105_01 "Age of household members"
label variable hv105_02 "Age of household members"
label variable hv105_03 "Age of household members"
label variable hv105_04 "Age of household members"
label variable hv105_05 "Age of household members"
label variable hv105_06 "Age of household members"
label variable hv105_07 "Age of household members"
label variable hv105_08 "Age of household members"
label variable hv105_09 "Age of household members"
label variable hv105_10 "Age of household members"
label variable hv105_11 "Age of household members"
label variable hv105_12 "Age of household members"
label variable hv105_13 "Age of household members"
label variable hv105_14 "Age of household members"
label variable hv105_15 "Age of household members"
label variable hv105_16 "Age of household members"
label variable hv105_17 "Age of household members"
label variable hv105_18 "Age of household members"
label variable hv105_19 "Age of household members"
label variable hv105_20 "Age of household members"
label variable hv105_21 "Age of household members"
label variable hv106_01 "Highest educational level"
label variable hv106_02 "Highest educational level"
label variable hv106_03 "Highest educational level"
label variable hv106_04 "Highest educational level"
label variable hv106_05 "Highest educational level"
label variable hv106_06 "Highest educational level"
label variable hv106_07 "Highest educational level"
label variable hv106_08 "Highest educational level"
label variable hv106_09 "Highest educational level"
label variable hv106_10 "Highest educational level"
label variable hv106_11 "Highest educational level"
label variable hv106_12 "Highest educational level"
label variable hv106_13 "Highest educational level"
label variable hv106_14 "Highest educational level"
label variable hv106_15 "Highest educational level"
label variable hv106_16 "Highest educational level"
label variable hv106_17 "Highest educational level"
label variable hv106_18 "Highest educational level"
label variable hv106_19 "Highest educational level"
label variable hv106_20 "Highest educational level"
label variable hv106_21 "Highest educational level"
label variable hv107_01 "Highest year of education"
label variable hv107_02 "Highest year of education"
label variable hv107_03 "Highest year of education"
label variable hv107_04 "Highest year of education"
label variable hv107_05 "Highest year of education"
label variable hv107_06 "Highest year of education"
label variable hv107_07 "Highest year of education"
label variable hv107_08 "Highest year of education"
label variable hv107_09 "Highest year of education"
label variable hv107_10 "Highest year of education"
label variable hv107_11 "Highest year of education"
label variable hv107_12 "Highest year of education"
label variable hv107_13 "Highest year of education"
label variable hv107_14 "Highest year of education"
label variable hv107_15 "Highest year of education"
label variable hv107_16 "Highest year of education"
label variable hv107_17 "Highest year of education"
label variable hv107_18 "Highest year of education"
label variable hv107_19 "Highest year of education"
label variable hv107_20 "Highest year of education"
label variable hv107_21 "Highest year of education"
label variable hv108_01 "Education in single years"
label variable hv108_02 "Education in single years"
label variable hv108_03 "Education in single years"
label variable hv108_04 "Education in single years"
label variable hv108_05 "Education in single years"
label variable hv108_06 "Education in single years"
label variable hv108_07 "Education in single years"
label variable hv108_08 "Education in single years"
label variable hv108_09 "Education in single years"
label variable hv108_10 "Education in single years"
label variable hv108_11 "Education in single years"
label variable hv108_12 "Education in single years"
label variable hv108_13 "Education in single years"
label variable hv108_14 "Education in single years"
label variable hv108_15 "Education in single years"
label variable hv108_16 "Education in single years"
label variable hv108_17 "Education in single years"
label variable hv108_18 "Education in single years"
label variable hv108_19 "Education in single years"
label variable hv108_20 "Education in single years"
label variable hv108_21 "Education in single years"
label variable hv109_01 "Educational attainment"
label variable hv109_02 "Educational attainment"
label variable hv109_03 "Educational attainment"
label variable hv109_04 "Educational attainment"
label variable hv109_05 "Educational attainment"
label variable hv109_06 "Educational attainment"
label variable hv109_07 "Educational attainment"
label variable hv109_08 "Educational attainment"
label variable hv109_09 "Educational attainment"
label variable hv109_10 "Educational attainment"
label variable hv109_11 "Educational attainment"
label variable hv109_12 "Educational attainment"
label variable hv109_13 "Educational attainment"
label variable hv109_14 "Educational attainment"
label variable hv109_15 "Educational attainment"
label variable hv109_16 "Educational attainment"
label variable hv109_17 "Educational attainment"
label variable hv109_18 "Educational attainment"
label variable hv109_19 "Educational attainment"
label variable hv109_20 "Educational attainment"
label variable hv109_21 "Educational attainment"
label variable hv110_01 "NA - Member still in school"
label variable hv110_02 "NA - Member still in school"
label variable hv110_03 "NA - Member still in school"
label variable hv110_04 "NA - Member still in school"
label variable hv110_05 "NA - Member still in school"
label variable hv110_06 "NA - Member still in school"
label variable hv110_07 "NA - Member still in school"
label variable hv110_08 "NA - Member still in school"
label variable hv110_09 "NA - Member still in school"
label variable hv110_10 "NA - Member still in school"
label variable hv110_11 "NA - Member still in school"
label variable hv110_12 "NA - Member still in school"
label variable hv110_13 "NA - Member still in school"
label variable hv110_14 "NA - Member still in school"
label variable hv110_15 "NA - Member still in school"
label variable hv110_16 "NA - Member still in school"
label variable hv110_17 "NA - Member still in school"
label variable hv110_18 "NA - Member still in school"
label variable hv110_19 "NA - Member still in school"
label variable hv110_20 "NA - Member still in school"
label variable hv110_21 "NA - Member still in school"
label variable hv111_01 "Mother alive"
label variable hv111_02 "Mother alive"
label variable hv111_03 "Mother alive"
label variable hv111_04 "Mother alive"
label variable hv111_05 "Mother alive"
label variable hv111_06 "Mother alive"
label variable hv111_07 "Mother alive"
label variable hv111_08 "Mother alive"
label variable hv111_09 "Mother alive"
label variable hv111_10 "Mother alive"
label variable hv111_11 "Mother alive"
label variable hv111_12 "Mother alive"
label variable hv111_13 "Mother alive"
label variable hv111_14 "Mother alive"
label variable hv111_15 "Mother alive"
label variable hv111_16 "Mother alive"
label variable hv111_17 "Mother alive"
label variable hv111_18 "Mother alive"
label variable hv111_19 "Mother alive"
label variable hv111_20 "Mother alive"
label variable hv111_21 "Mother alive"
label variable hv112_01 "Mother's line number"
label variable hv112_02 "Mother's line number"
label variable hv112_03 "Mother's line number"
label variable hv112_04 "Mother's line number"
label variable hv112_05 "Mother's line number"
label variable hv112_06 "Mother's line number"
label variable hv112_07 "Mother's line number"
label variable hv112_08 "Mother's line number"
label variable hv112_09 "Mother's line number"
label variable hv112_10 "Mother's line number"
label variable hv112_11 "Mother's line number"
label variable hv112_12 "Mother's line number"
label variable hv112_13 "Mother's line number"
label variable hv112_14 "Mother's line number"
label variable hv112_15 "Mother's line number"
label variable hv112_16 "Mother's line number"
label variable hv112_17 "Mother's line number"
label variable hv112_18 "Mother's line number"
label variable hv112_19 "Mother's line number"
label variable hv112_20 "Mother's line number"
label variable hv112_21 "Mother's line number"
label variable hv113_01 "Father alive"
label variable hv113_02 "Father alive"
label variable hv113_03 "Father alive"
label variable hv113_04 "Father alive"
label variable hv113_05 "Father alive"
label variable hv113_06 "Father alive"
label variable hv113_07 "Father alive"
label variable hv113_08 "Father alive"
label variable hv113_09 "Father alive"
label variable hv113_10 "Father alive"
label variable hv113_11 "Father alive"
label variable hv113_12 "Father alive"
label variable hv113_13 "Father alive"
label variable hv113_14 "Father alive"
label variable hv113_15 "Father alive"
label variable hv113_16 "Father alive"
label variable hv113_17 "Father alive"
label variable hv113_18 "Father alive"
label variable hv113_19 "Father alive"
label variable hv113_20 "Father alive"
label variable hv113_21 "Father alive"
label variable hv114_01 "Father's line number"
label variable hv114_02 "Father's line number"
label variable hv114_03 "Father's line number"
label variable hv114_04 "Father's line number"
label variable hv114_05 "Father's line number"
label variable hv114_06 "Father's line number"
label variable hv114_07 "Father's line number"
label variable hv114_08 "Father's line number"
label variable hv114_09 "Father's line number"
label variable hv114_10 "Father's line number"
label variable hv114_11 "Father's line number"
label variable hv114_12 "Father's line number"
label variable hv114_13 "Father's line number"
label variable hv114_14 "Father's line number"
label variable hv114_15 "Father's line number"
label variable hv114_16 "Father's line number"
label variable hv114_17 "Father's line number"
label variable hv114_18 "Father's line number"
label variable hv114_19 "Father's line number"
label variable hv114_20 "Father's line number"
label variable hv114_21 "Father's line number"
label variable hv115_01 "Current marital status"
label variable hv115_02 "Current marital status"
label variable hv115_03 "Current marital status"
label variable hv115_04 "Current marital status"
label variable hv115_05 "Current marital status"
label variable hv115_06 "Current marital status"
label variable hv115_07 "Current marital status"
label variable hv115_08 "Current marital status"
label variable hv115_09 "Current marital status"
label variable hv115_10 "Current marital status"
label variable hv115_11 "Current marital status"
label variable hv115_12 "Current marital status"
label variable hv115_13 "Current marital status"
label variable hv115_14 "Current marital status"
label variable hv115_15 "Current marital status"
label variable hv115_16 "Current marital status"
label variable hv115_17 "Current marital status"
label variable hv115_18 "Current marital status"
label variable hv115_19 "Current marital status"
label variable hv115_20 "Current marital status"
label variable hv115_21 "Current marital status"
label variable hv116_01 "Currently, formerly, never m."
label variable hv116_02 "Currently, formerly, never m."
label variable hv116_03 "Currently, formerly, never m."
label variable hv116_04 "Currently, formerly, never m."
label variable hv116_05 "Currently, formerly, never m."
label variable hv116_06 "Currently, formerly, never m."
label variable hv116_07 "Currently, formerly, never m."
label variable hv116_08 "Currently, formerly, never m."
label variable hv116_09 "Currently, formerly, never m."
label variable hv116_10 "Currently, formerly, never m."
label variable hv116_11 "Currently, formerly, never m."
label variable hv116_12 "Currently, formerly, never m."
label variable hv116_13 "Currently, formerly, never m."
label variable hv116_14 "Currently, formerly, never m."
label variable hv116_15 "Currently, formerly, never m."
label variable hv116_16 "Currently, formerly, never m."
label variable hv116_17 "Currently, formerly, never m."
label variable hv116_18 "Currently, formerly, never m."
label variable hv116_19 "Currently, formerly, never m."
label variable hv116_20 "Currently, formerly, never m."
label variable hv116_21 "Currently, formerly, never m."
label variable hv117_01 "Eligibility for female interview"
label variable hv117_02 "Eligibility for female interview"
label variable hv117_03 "Eligibility for female interview"
label variable hv117_04 "Eligibility for female interview"
label variable hv117_05 "Eligibility for female interview"
label variable hv117_06 "Eligibility for female interview"
label variable hv117_07 "Eligibility for female interview"
label variable hv117_08 "Eligibility for female interview"
label variable hv117_09 "Eligibility for female interview"
label variable hv117_10 "Eligibility for female interview"
label variable hv117_11 "Eligibility for female interview"
label variable hv117_12 "Eligibility for female interview"
label variable hv117_13 "Eligibility for female interview"
label variable hv117_14 "Eligibility for female interview"
label variable hv117_15 "Eligibility for female interview"
label variable hv117_16 "Eligibility for female interview"
label variable hv117_17 "Eligibility for female interview"
label variable hv117_18 "Eligibility for female interview"
label variable hv117_19 "Eligibility for female interview"
label variable hv117_20 "Eligibility for female interview"
label variable hv117_21 "Eligibility for female interview"
label variable hv118_01 "Eligibility for male interview"
label variable hv118_02 "Eligibility for male interview"
label variable hv118_03 "Eligibility for male interview"
label variable hv118_04 "Eligibility for male interview"
label variable hv118_05 "Eligibility for male interview"
label variable hv118_06 "Eligibility for male interview"
label variable hv118_07 "Eligibility for male interview"
label variable hv118_08 "Eligibility for male interview"
label variable hv118_09 "Eligibility for male interview"
label variable hv118_10 "Eligibility for male interview"
label variable hv118_11 "Eligibility for male interview"
label variable hv118_12 "Eligibility for male interview"
label variable hv118_13 "Eligibility for male interview"
label variable hv118_14 "Eligibility for male interview"
label variable hv118_15 "Eligibility for male interview"
label variable hv118_16 "Eligibility for male interview"
label variable hv118_17 "Eligibility for male interview"
label variable hv118_18 "Eligibility for male interview"
label variable hv118_19 "Eligibility for male interview"
label variable hv118_20 "Eligibility for male interview"
label variable hv118_21 "Eligibility for male interview"
label variable hv120_01 "Children eligibility for height/weight and hemoglobin"
label variable hv120_02 "Children eligibility for height/weight and hemoglobin"
label variable hv120_03 "Children eligibility for height/weight and hemoglobin"
label variable hv120_04 "Children eligibility for height/weight and hemoglobin"
label variable hv120_05 "Children eligibility for height/weight and hemoglobin"
label variable hv120_06 "Children eligibility for height/weight and hemoglobin"
label variable hv120_07 "Children eligibility for height/weight and hemoglobin"
label variable hv120_08 "Children eligibility for height/weight and hemoglobin"
label variable hv120_09 "Children eligibility for height/weight and hemoglobin"
label variable hv120_10 "Children eligibility for height/weight and hemoglobin"
label variable hv120_11 "Children eligibility for height/weight and hemoglobin"
label variable hv120_12 "Children eligibility for height/weight and hemoglobin"
label variable hv120_13 "Children eligibility for height/weight and hemoglobin"
label variable hv120_14 "Children eligibility for height/weight and hemoglobin"
label variable hv120_15 "Children eligibility for height/weight and hemoglobin"
label variable hv120_16 "Children eligibility for height/weight and hemoglobin"
label variable hv120_17 "Children eligibility for height/weight and hemoglobin"
label variable hv120_18 "Children eligibility for height/weight and hemoglobin"
label variable hv120_19 "Children eligibility for height/weight and hemoglobin"
label variable hv120_20 "Children eligibility for height/weight and hemoglobin"
label variable hv120_21 "Children eligibility for height/weight and hemoglobin"
label variable hv121_01 "Member attended school during current school year"
label variable hv121_02 "Member attended school during current school year"
label variable hv121_03 "Member attended school during current school year"
label variable hv121_04 "Member attended school during current school year"
label variable hv121_05 "Member attended school during current school year"
label variable hv121_06 "Member attended school during current school year"
label variable hv121_07 "Member attended school during current school year"
label variable hv121_08 "Member attended school during current school year"
label variable hv121_09 "Member attended school during current school year"
label variable hv121_10 "Member attended school during current school year"
label variable hv121_11 "Member attended school during current school year"
label variable hv121_12 "Member attended school during current school year"
label variable hv121_13 "Member attended school during current school year"
label variable hv121_14 "Member attended school during current school year"
label variable hv121_15 "Member attended school during current school year"
label variable hv121_16 "Member attended school during current school year"
label variable hv121_17 "Member attended school during current school year"
label variable hv121_18 "Member attended school during current school year"
label variable hv121_19 "Member attended school during current school year"
label variable hv121_20 "Member attended school during current school year"
label variable hv121_21 "Member attended school during current school year"
label variable hv122_01 "Educational level during current school year"
label variable hv122_02 "Educational level during current school year"
label variable hv122_03 "Educational level during current school year"
label variable hv122_04 "Educational level during current school year"
label variable hv122_05 "Educational level during current school year"
label variable hv122_06 "Educational level during current school year"
label variable hv122_07 "Educational level during current school year"
label variable hv122_08 "Educational level during current school year"
label variable hv122_09 "Educational level during current school year"
label variable hv122_10 "Educational level during current school year"
label variable hv122_11 "Educational level during current school year"
label variable hv122_12 "Educational level during current school year"
label variable hv122_13 "Educational level during current school year"
label variable hv122_14 "Educational level during current school year"
label variable hv122_15 "Educational level during current school year"
label variable hv122_16 "Educational level during current school year"
label variable hv122_17 "Educational level during current school year"
label variable hv122_18 "Educational level during current school year"
label variable hv122_19 "Educational level during current school year"
label variable hv122_20 "Educational level during current school year"
label variable hv122_21 "Educational level during current school year"
label variable hv123_01 "Grade of education during current school year"
label variable hv123_02 "Grade of education during current school year"
label variable hv123_03 "Grade of education during current school year"
label variable hv123_04 "Grade of education during current school year"
label variable hv123_05 "Grade of education during current school year"
label variable hv123_06 "Grade of education during current school year"
label variable hv123_07 "Grade of education during current school year"
label variable hv123_08 "Grade of education during current school year"
label variable hv123_09 "Grade of education during current school year"
label variable hv123_10 "Grade of education during current school year"
label variable hv123_11 "Grade of education during current school year"
label variable hv123_12 "Grade of education during current school year"
label variable hv123_13 "Grade of education during current school year"
label variable hv123_14 "Grade of education during current school year"
label variable hv123_15 "Grade of education during current school year"
label variable hv123_16 "Grade of education during current school year"
label variable hv123_17 "Grade of education during current school year"
label variable hv123_18 "Grade of education during current school year"
label variable hv123_19 "Grade of education during current school year"
label variable hv123_20 "Grade of education during current school year"
label variable hv123_21 "Grade of education during current school year"
label variable hv124_01 "Education in single years - current school year"
label variable hv124_02 "Education in single years - current school year"
label variable hv124_03 "Education in single years - current school year"
label variable hv124_04 "Education in single years - current school year"
label variable hv124_05 "Education in single years - current school year"
label variable hv124_06 "Education in single years - current school year"
label variable hv124_07 "Education in single years - current school year"
label variable hv124_08 "Education in single years - current school year"
label variable hv124_09 "Education in single years - current school year"
label variable hv124_10 "Education in single years - current school year"
label variable hv124_11 "Education in single years - current school year"
label variable hv124_12 "Education in single years - current school year"
label variable hv124_13 "Education in single years - current school year"
label variable hv124_14 "Education in single years - current school year"
label variable hv124_15 "Education in single years - current school year"
label variable hv124_16 "Education in single years - current school year"
label variable hv124_17 "Education in single years - current school year"
label variable hv124_18 "Education in single years - current school year"
label variable hv124_19 "Education in single years - current school year"
label variable hv124_20 "Education in single years - current school year"
label variable hv124_21 "Education in single years - current school year"
label variable hv125_01 "NA - Member attended school during previous school year"
label variable hv125_02 "NA - Member attended school during previous school year"
label variable hv125_03 "NA - Member attended school during previous school year"
label variable hv125_04 "NA - Member attended school during previous school year"
label variable hv125_05 "NA - Member attended school during previous school year"
label variable hv125_06 "NA - Member attended school during previous school year"
label variable hv125_07 "NA - Member attended school during previous school year"
label variable hv125_08 "NA - Member attended school during previous school year"
label variable hv125_09 "NA - Member attended school during previous school year"
label variable hv125_10 "NA - Member attended school during previous school year"
label variable hv125_11 "NA - Member attended school during previous school year"
label variable hv125_12 "NA - Member attended school during previous school year"
label variable hv125_13 "NA - Member attended school during previous school year"
label variable hv125_14 "NA - Member attended school during previous school year"
label variable hv125_15 "NA - Member attended school during previous school year"
label variable hv125_16 "NA - Member attended school during previous school year"
label variable hv125_17 "NA - Member attended school during previous school year"
label variable hv125_18 "NA - Member attended school during previous school year"
label variable hv125_19 "NA - Member attended school during previous school year"
label variable hv125_20 "NA - Member attended school during previous school year"
label variable hv125_21 "NA - Member attended school during previous school year"
label variable hv126_01 "NA - Educational level during previous school year"
label variable hv126_02 "NA - Educational level during previous school year"
label variable hv126_03 "NA - Educational level during previous school year"
label variable hv126_04 "NA - Educational level during previous school year"
label variable hv126_05 "NA - Educational level during previous school year"
label variable hv126_06 "NA - Educational level during previous school year"
label variable hv126_07 "NA - Educational level during previous school year"
label variable hv126_08 "NA - Educational level during previous school year"
label variable hv126_09 "NA - Educational level during previous school year"
label variable hv126_10 "NA - Educational level during previous school year"
label variable hv126_11 "NA - Educational level during previous school year"
label variable hv126_12 "NA - Educational level during previous school year"
label variable hv126_13 "NA - Educational level during previous school year"
label variable hv126_14 "NA - Educational level during previous school year"
label variable hv126_15 "NA - Educational level during previous school year"
label variable hv126_16 "NA - Educational level during previous school year"
label variable hv126_17 "NA - Educational level during previous school year"
label variable hv126_18 "NA - Educational level during previous school year"
label variable hv126_19 "NA - Educational level during previous school year"
label variable hv126_20 "NA - Educational level during previous school year"
label variable hv126_21 "NA - Educational level during previous school year"
label variable hv127_01 "NA - Grade of education during previous school year"
label variable hv127_02 "NA - Grade of education during previous school year"
label variable hv127_03 "NA - Grade of education during previous school year"
label variable hv127_04 "NA - Grade of education during previous school year"
label variable hv127_05 "NA - Grade of education during previous school year"
label variable hv127_06 "NA - Grade of education during previous school year"
label variable hv127_07 "NA - Grade of education during previous school year"
label variable hv127_08 "NA - Grade of education during previous school year"
label variable hv127_09 "NA - Grade of education during previous school year"
label variable hv127_10 "NA - Grade of education during previous school year"
label variable hv127_11 "NA - Grade of education during previous school year"
label variable hv127_12 "NA - Grade of education during previous school year"
label variable hv127_13 "NA - Grade of education during previous school year"
label variable hv127_14 "NA - Grade of education during previous school year"
label variable hv127_15 "NA - Grade of education during previous school year"
label variable hv127_16 "NA - Grade of education during previous school year"
label variable hv127_17 "NA - Grade of education during previous school year"
label variable hv127_18 "NA - Grade of education during previous school year"
label variable hv127_19 "NA - Grade of education during previous school year"
label variable hv127_20 "NA - Grade of education during previous school year"
label variable hv127_21 "NA - Grade of education during previous school year"
label variable hv128_01 "NA - Education in single years - previous school year"
label variable hv128_02 "NA - Education in single years - previous school year"
label variable hv128_03 "NA - Education in single years - previous school year"
label variable hv128_04 "NA - Education in single years - previous school year"
label variable hv128_05 "NA - Education in single years - previous school year"
label variable hv128_06 "NA - Education in single years - previous school year"
label variable hv128_07 "NA - Education in single years - previous school year"
label variable hv128_08 "NA - Education in single years - previous school year"
label variable hv128_09 "NA - Education in single years - previous school year"
label variable hv128_10 "NA - Education in single years - previous school year"
label variable hv128_11 "NA - Education in single years - previous school year"
label variable hv128_12 "NA - Education in single years - previous school year"
label variable hv128_13 "NA - Education in single years - previous school year"
label variable hv128_14 "NA - Education in single years - previous school year"
label variable hv128_15 "NA - Education in single years - previous school year"
label variable hv128_16 "NA - Education in single years - previous school year"
label variable hv128_17 "NA - Education in single years - previous school year"
label variable hv128_18 "NA - Education in single years - previous school year"
label variable hv128_19 "NA - Education in single years - previous school year"
label variable hv128_20 "NA - Education in single years - previous school year"
label variable hv128_21 "NA - Education in single years - previous school year"
label variable hv129_01 "School attendance status"
label variable hv129_02 "School attendance status"
label variable hv129_03 "School attendance status"
label variable hv129_04 "School attendance status"
label variable hv129_05 "School attendance status"
label variable hv129_06 "School attendance status"
label variable hv129_07 "School attendance status"
label variable hv129_08 "School attendance status"
label variable hv129_09 "School attendance status"
label variable hv129_10 "School attendance status"
label variable hv129_11 "School attendance status"
label variable hv129_12 "School attendance status"
label variable hv129_13 "School attendance status"
label variable hv129_14 "School attendance status"
label variable hv129_15 "School attendance status"
label variable hv129_16 "School attendance status"
label variable hv129_17 "School attendance status"
label variable hv129_18 "School attendance status"
label variable hv129_19 "School attendance status"
label variable hv129_20 "School attendance status"
label variable hv129_21 "School attendance status"
label variable hv130_01 "NA - Member has been very sick for 3+ months last year"
label variable hv130_02 "NA - Member has been very sick for 3+ months last year"
label variable hv130_03 "NA - Member has been very sick for 3+ months last year"
label variable hv130_04 "NA - Member has been very sick for 3+ months last year"
label variable hv130_05 "NA - Member has been very sick for 3+ months last year"
label variable hv130_06 "NA - Member has been very sick for 3+ months last year"
label variable hv130_07 "NA - Member has been very sick for 3+ months last year"
label variable hv130_08 "NA - Member has been very sick for 3+ months last year"
label variable hv130_09 "NA - Member has been very sick for 3+ months last year"
label variable hv130_10 "NA - Member has been very sick for 3+ months last year"
label variable hv130_11 "NA - Member has been very sick for 3+ months last year"
label variable hv130_12 "NA - Member has been very sick for 3+ months last year"
label variable hv130_13 "NA - Member has been very sick for 3+ months last year"
label variable hv130_14 "NA - Member has been very sick for 3+ months last year"
label variable hv130_15 "NA - Member has been very sick for 3+ months last year"
label variable hv130_16 "NA - Member has been very sick for 3+ months last year"
label variable hv130_17 "NA - Member has been very sick for 3+ months last year"
label variable hv130_18 "NA - Member has been very sick for 3+ months last year"
label variable hv130_19 "NA - Member has been very sick for 3+ months last year"
label variable hv130_20 "NA - Member has been very sick for 3+ months last year"
label variable hv130_21 "NA - Member has been very sick for 3+ months last year"
label variable hv131_01 "NA - Mother has been very sick for 3+ months last year"
label variable hv131_02 "NA - Mother has been very sick for 3+ months last year"
label variable hv131_03 "NA - Mother has been very sick for 3+ months last year"
label variable hv131_04 "NA - Mother has been very sick for 3+ months last year"
label variable hv131_05 "NA - Mother has been very sick for 3+ months last year"
label variable hv131_06 "NA - Mother has been very sick for 3+ months last year"
label variable hv131_07 "NA - Mother has been very sick for 3+ months last year"
label variable hv131_08 "NA - Mother has been very sick for 3+ months last year"
label variable hv131_09 "NA - Mother has been very sick for 3+ months last year"
label variable hv131_10 "NA - Mother has been very sick for 3+ months last year"
label variable hv131_11 "NA - Mother has been very sick for 3+ months last year"
label variable hv131_12 "NA - Mother has been very sick for 3+ months last year"
label variable hv131_13 "NA - Mother has been very sick for 3+ months last year"
label variable hv131_14 "NA - Mother has been very sick for 3+ months last year"
label variable hv131_15 "NA - Mother has been very sick for 3+ months last year"
label variable hv131_16 "NA - Mother has been very sick for 3+ months last year"
label variable hv131_17 "NA - Mother has been very sick for 3+ months last year"
label variable hv131_18 "NA - Mother has been very sick for 3+ months last year"
label variable hv131_19 "NA - Mother has been very sick for 3+ months last year"
label variable hv131_20 "NA - Mother has been very sick for 3+ months last year"
label variable hv131_21 "NA - Mother has been very sick for 3+ months last year"
label variable hv132_01 "NA - Father has been very sick for 3+ months last year"
label variable hv132_02 "NA - Father has been very sick for 3+ months last year"
label variable hv132_03 "NA - Father has been very sick for 3+ months last year"
label variable hv132_04 "NA - Father has been very sick for 3+ months last year"
label variable hv132_05 "NA - Father has been very sick for 3+ months last year"
label variable hv132_06 "NA - Father has been very sick for 3+ months last year"
label variable hv132_07 "NA - Father has been very sick for 3+ months last year"
label variable hv132_08 "NA - Father has been very sick for 3+ months last year"
label variable hv132_09 "NA - Father has been very sick for 3+ months last year"
label variable hv132_10 "NA - Father has been very sick for 3+ months last year"
label variable hv132_11 "NA - Father has been very sick for 3+ months last year"
label variable hv132_12 "NA - Father has been very sick for 3+ months last year"
label variable hv132_13 "NA - Father has been very sick for 3+ months last year"
label variable hv132_14 "NA - Father has been very sick for 3+ months last year"
label variable hv132_15 "NA - Father has been very sick for 3+ months last year"
label variable hv132_16 "NA - Father has been very sick for 3+ months last year"
label variable hv132_17 "NA - Father has been very sick for 3+ months last year"
label variable hv132_18 "NA - Father has been very sick for 3+ months last year"
label variable hv132_19 "NA - Father has been very sick for 3+ months last year"
label variable hv132_20 "NA - Father has been very sick for 3+ months last year"
label variable hv132_21 "NA - Father has been very sick for 3+ months last year"
label variable hv133_01 "NA - Mother/father dead or been very sick for 3+ months"
label variable hv133_02 "NA - Mother/father dead or been very sick for 3+ months"
label variable hv133_03 "NA - Mother/father dead or been very sick for 3+ months"
label variable hv133_04 "NA - Mother/father dead or been very sick for 3+ months"
label variable hv133_05 "NA - Mother/father dead or been very sick for 3+ months"
label variable hv133_06 "NA - Mother/father dead or been very sick for 3+ months"
label variable hv133_07 "NA - Mother/father dead or been very sick for 3+ months"
label variable hv133_08 "NA - Mother/father dead or been very sick for 3+ months"
label variable hv133_09 "NA - Mother/father dead or been very sick for 3+ months"
label variable hv133_10 "NA - Mother/father dead or been very sick for 3+ months"
label variable hv133_11 "NA - Mother/father dead or been very sick for 3+ months"
label variable hv133_12 "NA - Mother/father dead or been very sick for 3+ months"
label variable hv133_13 "NA - Mother/father dead or been very sick for 3+ months"
label variable hv133_14 "NA - Mother/father dead or been very sick for 3+ months"
label variable hv133_15 "NA - Mother/father dead or been very sick for 3+ months"
label variable hv133_16 "NA - Mother/father dead or been very sick for 3+ months"
label variable hv133_17 "NA - Mother/father dead or been very sick for 3+ months"
label variable hv133_18 "NA - Mother/father dead or been very sick for 3+ months"
label variable hv133_19 "NA - Mother/father dead or been very sick for 3+ months"
label variable hv133_20 "NA - Mother/father dead or been very sick for 3+ months"
label variable hv133_21 "NA - Mother/father dead or been very sick for 3+ months"
label variable hv134_01 "NA - Both parents alive"
label variable hv134_02 "NA - Both parents alive"
label variable hv134_03 "NA - Both parents alive"
label variable hv134_04 "NA - Both parents alive"
label variable hv134_05 "NA - Both parents alive"
label variable hv134_06 "NA - Both parents alive"
label variable hv134_07 "NA - Both parents alive"
label variable hv134_08 "NA - Both parents alive"
label variable hv134_09 "NA - Both parents alive"
label variable hv134_10 "NA - Both parents alive"
label variable hv134_11 "NA - Both parents alive"
label variable hv134_12 "NA - Both parents alive"
label variable hv134_13 "NA - Both parents alive"
label variable hv134_14 "NA - Both parents alive"
label variable hv134_15 "NA - Both parents alive"
label variable hv134_16 "NA - Both parents alive"
label variable hv134_17 "NA - Both parents alive"
label variable hv134_18 "NA - Both parents alive"
label variable hv134_19 "NA - Both parents alive"
label variable hv134_20 "NA - Both parents alive"
label variable hv134_21 "NA - Both parents alive"
label variable hv135_01 "NA - Has brothers/sisters under 18 of the same father and mother"
label variable hv135_02 "NA - Has brothers/sisters under 18 of the same father and mother"
label variable hv135_03 "NA - Has brothers/sisters under 18 of the same father and mother"
label variable hv135_04 "NA - Has brothers/sisters under 18 of the same father and mother"
label variable hv135_05 "NA - Has brothers/sisters under 18 of the same father and mother"
label variable hv135_06 "NA - Has brothers/sisters under 18 of the same father and mother"
label variable hv135_07 "NA - Has brothers/sisters under 18 of the same father and mother"
label variable hv135_08 "NA - Has brothers/sisters under 18 of the same father and mother"
label variable hv135_09 "NA - Has brothers/sisters under 18 of the same father and mother"
label variable hv135_10 "NA - Has brothers/sisters under 18 of the same father and mother"
label variable hv135_11 "NA - Has brothers/sisters under 18 of the same father and mother"
label variable hv135_12 "NA - Has brothers/sisters under 18 of the same father and mother"
label variable hv135_13 "NA - Has brothers/sisters under 18 of the same father and mother"
label variable hv135_14 "NA - Has brothers/sisters under 18 of the same father and mother"
label variable hv135_15 "NA - Has brothers/sisters under 18 of the same father and mother"
label variable hv135_16 "NA - Has brothers/sisters under 18 of the same father and mother"
label variable hv135_17 "NA - Has brothers/sisters under 18 of the same father and mother"
label variable hv135_18 "NA - Has brothers/sisters under 18 of the same father and mother"
label variable hv135_19 "NA - Has brothers/sisters under 18 of the same father and mother"
label variable hv135_20 "NA - Has brothers/sisters under 18 of the same father and mother"
label variable hv135_21 "NA - Has brothers/sisters under 18 of the same father and mother"
label variable hv136_01 "NA - Brothers/sisters under 18 that don't live in household"
label variable hv136_02 "NA - Brothers/sisters under 18 that don't live in household"
label variable hv136_03 "NA - Brothers/sisters under 18 that don't live in household"
label variable hv136_04 "NA - Brothers/sisters under 18 that don't live in household"
label variable hv136_05 "NA - Brothers/sisters under 18 that don't live in household"
label variable hv136_06 "NA - Brothers/sisters under 18 that don't live in household"
label variable hv136_07 "NA - Brothers/sisters under 18 that don't live in household"
label variable hv136_08 "NA - Brothers/sisters under 18 that don't live in household"
label variable hv136_09 "NA - Brothers/sisters under 18 that don't live in household"
label variable hv136_10 "NA - Brothers/sisters under 18 that don't live in household"
label variable hv136_11 "NA - Brothers/sisters under 18 that don't live in household"
label variable hv136_12 "NA - Brothers/sisters under 18 that don't live in household"
label variable hv136_13 "NA - Brothers/sisters under 18 that don't live in household"
label variable hv136_14 "NA - Brothers/sisters under 18 that don't live in household"
label variable hv136_15 "NA - Brothers/sisters under 18 that don't live in household"
label variable hv136_16 "NA - Brothers/sisters under 18 that don't live in household"
label variable hv136_17 "NA - Brothers/sisters under 18 that don't live in household"
label variable hv136_18 "NA - Brothers/sisters under 18 that don't live in household"
label variable hv136_19 "NA - Brothers/sisters under 18 that don't live in household"
label variable hv136_20 "NA - Brothers/sisters under 18 that don't live in household"
label variable hv136_21 "NA - Brothers/sisters under 18 that don't live in household"
label variable hv137_01 "NA - Member has a blanket"
label variable hv137_02 "NA - Member has a blanket"
label variable hv137_03 "NA - Member has a blanket"
label variable hv137_04 "NA - Member has a blanket"
label variable hv137_05 "NA - Member has a blanket"
label variable hv137_06 "NA - Member has a blanket"
label variable hv137_07 "NA - Member has a blanket"
label variable hv137_08 "NA - Member has a blanket"
label variable hv137_09 "NA - Member has a blanket"
label variable hv137_10 "NA - Member has a blanket"
label variable hv137_11 "NA - Member has a blanket"
label variable hv137_12 "NA - Member has a blanket"
label variable hv137_13 "NA - Member has a blanket"
label variable hv137_14 "NA - Member has a blanket"
label variable hv137_15 "NA - Member has a blanket"
label variable hv137_16 "NA - Member has a blanket"
label variable hv137_17 "NA - Member has a blanket"
label variable hv137_18 "NA - Member has a blanket"
label variable hv137_19 "NA - Member has a blanket"
label variable hv137_20 "NA - Member has a blanket"
label variable hv137_21 "NA - Member has a blanket"
label variable hv138_01 "NA - Member has a pair of shoes"
label variable hv138_02 "NA - Member has a pair of shoes"
label variable hv138_03 "NA - Member has a pair of shoes"
label variable hv138_04 "NA - Member has a pair of shoes"
label variable hv138_05 "NA - Member has a pair of shoes"
label variable hv138_06 "NA - Member has a pair of shoes"
label variable hv138_07 "NA - Member has a pair of shoes"
label variable hv138_08 "NA - Member has a pair of shoes"
label variable hv138_09 "NA - Member has a pair of shoes"
label variable hv138_10 "NA - Member has a pair of shoes"
label variable hv138_11 "NA - Member has a pair of shoes"
label variable hv138_12 "NA - Member has a pair of shoes"
label variable hv138_13 "NA - Member has a pair of shoes"
label variable hv138_14 "NA - Member has a pair of shoes"
label variable hv138_15 "NA - Member has a pair of shoes"
label variable hv138_16 "NA - Member has a pair of shoes"
label variable hv138_17 "NA - Member has a pair of shoes"
label variable hv138_18 "NA - Member has a pair of shoes"
label variable hv138_19 "NA - Member has a pair of shoes"
label variable hv138_20 "NA - Member has a pair of shoes"
label variable hv138_21 "NA - Member has a pair of shoes"
label variable hv139_01 "NA - Member has 2+ sets of clothes"
label variable hv139_02 "NA - Member has 2+ sets of clothes"
label variable hv139_03 "NA - Member has 2+ sets of clothes"
label variable hv139_04 "NA - Member has 2+ sets of clothes"
label variable hv139_05 "NA - Member has 2+ sets of clothes"
label variable hv139_06 "NA - Member has 2+ sets of clothes"
label variable hv139_07 "NA - Member has 2+ sets of clothes"
label variable hv139_08 "NA - Member has 2+ sets of clothes"
label variable hv139_09 "NA - Member has 2+ sets of clothes"
label variable hv139_10 "NA - Member has 2+ sets of clothes"
label variable hv139_11 "NA - Member has 2+ sets of clothes"
label variable hv139_12 "NA - Member has 2+ sets of clothes"
label variable hv139_13 "NA - Member has 2+ sets of clothes"
label variable hv139_14 "NA - Member has 2+ sets of clothes"
label variable hv139_15 "NA - Member has 2+ sets of clothes"
label variable hv139_16 "NA - Member has 2+ sets of clothes"
label variable hv139_17 "NA - Member has 2+ sets of clothes"
label variable hv139_18 "NA - Member has 2+ sets of clothes"
label variable hv139_19 "NA - Member has 2+ sets of clothes"
label variable hv139_20 "NA - Member has 2+ sets of clothes"
label variable hv139_21 "NA - Member has 2+ sets of clothes"
label variable hv140_01 "NA - Member has a birth certificate"
label variable hv140_02 "NA - Member has a birth certificate"
label variable hv140_03 "NA - Member has a birth certificate"
label variable hv140_04 "NA - Member has a birth certificate"
label variable hv140_05 "NA - Member has a birth certificate"
label variable hv140_06 "NA - Member has a birth certificate"
label variable hv140_07 "NA - Member has a birth certificate"
label variable hv140_08 "NA - Member has a birth certificate"
label variable hv140_09 "NA - Member has a birth certificate"
label variable hv140_10 "NA - Member has a birth certificate"
label variable hv140_11 "NA - Member has a birth certificate"
label variable hv140_12 "NA - Member has a birth certificate"
label variable hv140_13 "NA - Member has a birth certificate"
label variable hv140_14 "NA - Member has a birth certificate"
label variable hv140_15 "NA - Member has a birth certificate"
label variable hv140_16 "NA - Member has a birth certificate"
label variable hv140_17 "NA - Member has a birth certificate"
label variable hv140_18 "NA - Member has a birth certificate"
label variable hv140_19 "NA - Member has a birth certificate"
label variable hv140_20 "NA - Member has a birth certificate"
label variable hv140_21 "NA - Member has a birth certificate"
label variable idxh4_01 "Index to household schedule"
label variable idxh4_02 "Index to household schedule"
label variable idxh4_03 "Index to household schedule"
label variable idxh4_04 "Index to household schedule"
label variable idxh4_05 "Index to household schedule"
label variable idxh4_06 "Index to household schedule"
label variable idxh4_07 "Index to household schedule"
label variable idxh4_08 "Index to household schedule"
label variable idxh4_09 "Index to household schedule"
label variable idxh4_10 "Index to household schedule"
label variable idxh4_11 "Index to household schedule"
label variable idxh4_12 "Index to household schedule"
label variable idxh4_13 "Index to household schedule"
label variable idxh4_14 "Index to household schedule"
label variable idxh4_15 "Index to household schedule"
label variable idxh4_16 "Index to household schedule"
label variable idxh4_17 "Index to household schedule"
label variable idxh4_18 "Index to household schedule"
label variable idxh4_19 "Index to household schedule"
label variable idxh4_20 "Index to household schedule"
label variable idxh4_21 "Index to household schedule"
label variable sh06_01  "Country member is living in"
label variable sh06_02  "Country member is living in"
label variable sh06_03  "Country member is living in"
label variable sh06_04  "Country member is living in"
label variable sh06_05  "Country member is living in"
label variable sh06_06  "Country member is living in"
label variable sh06_07  "Country member is living in"
label variable sh06_08  "Country member is living in"
label variable sh06_09  "Country member is living in"
label variable sh06_10  "Country member is living in"
label variable sh06_11  "Country member is living in"
label variable sh06_12  "Country member is living in"
label variable sh06_13  "Country member is living in"
label variable sh06_14  "Country member is living in"
label variable sh06_15  "Country member is living in"
label variable sh06_16  "Country member is living in"
label variable sh06_17  "Country member is living in"
label variable sh06_18  "Country member is living in"
label variable sh06_19  "Country member is living in"
label variable sh06_20  "Country member is living in"
label variable sh06_21  "Country member is living in"
label variable sh07_01  "How long member has lived in country"
label variable sh07_02  "How long member has lived in country"
label variable sh07_03  "How long member has lived in country"
label variable sh07_04  "How long member has lived in country"
label variable sh07_05  "How long member has lived in country"
label variable sh07_06  "How long member has lived in country"
label variable sh07_07  "How long member has lived in country"
label variable sh07_08  "How long member has lived in country"
label variable sh07_09  "How long member has lived in country"
label variable sh07_10  "How long member has lived in country"
label variable sh07_11  "How long member has lived in country"
label variable sh07_12  "How long member has lived in country"
label variable sh07_13  "How long member has lived in country"
label variable sh07_14  "How long member has lived in country"
label variable sh07_15  "How long member has lived in country"
label variable sh07_16  "How long member has lived in country"
label variable sh07_17  "How long member has lived in country"
label variable sh07_18  "How long member has lived in country"
label variable sh07_19  "How long member has lived in country"
label variable sh07_20  "How long member has lived in country"
label variable sh07_21  "How long member has lived in country"
label variable sh19a_01 "Level of education attended"
label variable sh19a_02 "Level of education attended"
label variable sh19a_03 "Level of education attended"
label variable sh19a_04 "Level of education attended"
label variable sh19a_05 "Level of education attended"
label variable sh19a_06 "Level of education attended"
label variable sh19a_07 "Level of education attended"
label variable sh19a_08 "Level of education attended"
label variable sh19a_09 "Level of education attended"
label variable sh19a_10 "Level of education attended"
label variable sh19a_11 "Level of education attended"
label variable sh19a_12 "Level of education attended"
label variable sh19a_13 "Level of education attended"
label variable sh19a_14 "Level of education attended"
label variable sh19a_15 "Level of education attended"
label variable sh19a_16 "Level of education attended"
label variable sh19a_17 "Level of education attended"
label variable sh19a_18 "Level of education attended"
label variable sh19a_19 "Level of education attended"
label variable sh19a_20 "Level of education attended"
label variable sh19a_21 "Level of education attended"
label variable sh21a_01 "Level of education attended in current school year"
label variable sh21a_02 "Level of education attended in current school year"
label variable sh21a_03 "Level of education attended in current school year"
label variable sh21a_04 "Level of education attended in current school year"
label variable sh21a_05 "Level of education attended in current school year"
label variable sh21a_06 "Level of education attended in current school year"
label variable sh21a_07 "Level of education attended in current school year"
label variable sh21a_08 "Level of education attended in current school year"
label variable sh21a_09 "Level of education attended in current school year"
label variable sh21a_10 "Level of education attended in current school year"
label variable sh21a_11 "Level of education attended in current school year"
label variable sh21a_12 "Level of education attended in current school year"
label variable sh21a_13 "Level of education attended in current school year"
label variable sh21a_14 "Level of education attended in current school year"
label variable sh21a_15 "Level of education attended in current school year"
label variable sh21a_16 "Level of education attended in current school year"
label variable sh21a_17 "Level of education attended in current school year"
label variable sh21a_18 "Level of education attended in current school year"
label variable sh21a_19 "Level of education attended in current school year"
label variable sh21a_20 "Level of education attended in current school year"
label variable sh21a_21 "Level of education attended in current school year"
label variable sh19aa_01 "Country specific education categories used in reports"
label variable sh19aa_02 "Country specific education categories used in reports"
label variable sh19aa_03 "Country specific education categories used in reports"
label variable sh19aa_04 "Country specific education categories used in reports"
label variable sh19aa_05 "Country specific education categories used in reports"
label variable sh19aa_06 "Country specific education categories used in reports"
label variable sh19aa_07 "Country specific education categories used in reports"
label variable sh19aa_08 "Country specific education categories used in reports"
label variable sh19aa_09 "Country specific education categories used in reports"
label variable sh19aa_10 "Country specific education categories used in reports"
label variable sh19aa_11 "Country specific education categories used in reports"
label variable sh19aa_12 "Country specific education categories used in reports"
label variable sh19aa_13 "Country specific education categories used in reports"
label variable sh19aa_14 "Country specific education categories used in reports"
label variable sh19aa_15 "Country specific education categories used in reports"
label variable sh19aa_16 "Country specific education categories used in reports"
label variable sh19aa_17 "Country specific education categories used in reports"
label variable sh19aa_18 "Country specific education categories used in reports"
label variable sh19aa_19 "Country specific education categories used in reports"
label variable sh19aa_20 "Country specific education categories used in reports"
label variable sh19aa_21 "Country specific education categories used in reports"
label variable ha0_1    "Index to household schedule"
label variable ha0_2    "Index to household schedule"
label variable ha0_3    "Index to household schedule"
label variable ha0_4    "Index to household schedule"
label variable ha0_5    "Index to household schedule"
label variable ha0_6    "Index to household schedule"
label variable ha0_7    "Index to household schedule"
label variable ha1_1    "Women's age in years"
label variable ha1_2    "Women's age in years"
label variable ha1_3    "Women's age in years"
label variable ha1_4    "Women's age in years"
label variable ha1_5    "Women's age in years"
label variable ha1_6    "Women's age in years"
label variable ha1_7    "Women's age in years"
label variable ha2_1    "Respondent's weight (kilos-1d)"
label variable ha2_2    "Respondent's weight (kilos-1d)"
label variable ha2_3    "Respondent's weight (kilos-1d)"
label variable ha2_4    "Respondent's weight (kilos-1d)"
label variable ha2_5    "Respondent's weight (kilos-1d)"
label variable ha2_6    "Respondent's weight (kilos-1d)"
label variable ha2_7    "Respondent's weight (kilos-1d)"
label variable ha3_1    "Respondent's height (cms-1d)"
label variable ha3_2    "Respondent's height (cms-1d)"
label variable ha3_3    "Respondent's height (cms-1d)"
label variable ha3_4    "Respondent's height (cms-1d)"
label variable ha3_5    "Respondent's height (cms-1d)"
label variable ha3_6    "Respondent's height (cms-1d)"
label variable ha3_7    "Respondent's height (cms-1d)"
label variable ha4_1    "Ht/A Percentile (resp.)"
label variable ha4_2    "Ht/A Percentile (resp.)"
label variable ha4_3    "Ht/A Percentile (resp.)"
label variable ha4_4    "Ht/A Percentile (resp.)"
label variable ha4_5    "Ht/A Percentile (resp.)"
label variable ha4_6    "Ht/A Percentile (resp.)"
label variable ha4_7    "Ht/A Percentile (resp.)"
label variable ha5_1    "Ht/A Standard deviations (resp"
label variable ha5_2    "Ht/A Standard deviations (resp"
label variable ha5_3    "Ht/A Standard deviations (resp"
label variable ha5_4    "Ht/A Standard deviations (resp"
label variable ha5_5    "Ht/A Standard deviations (resp"
label variable ha5_6    "Ht/A Standard deviations (resp"
label variable ha5_7    "Ht/A Standard deviations (resp"
label variable ha6_1    "Ht/A Percent ref. median (resp"
label variable ha6_2    "Ht/A Percent ref. median (resp"
label variable ha6_3    "Ht/A Percent ref. median (resp"
label variable ha6_4    "Ht/A Percent ref. median (resp"
label variable ha6_5    "Ht/A Percent ref. median (resp"
label variable ha6_6    "Ht/A Percent ref. median (resp"
label variable ha6_7    "Ht/A Percent ref. median (resp"
label variable ha11_1   "Wt/Ht Std deviations(resp) DHS"
label variable ha11_2   "Wt/Ht Std deviations(resp) DHS"
label variable ha11_3   "Wt/Ht Std deviations(resp) DHS"
label variable ha11_4   "Wt/Ht Std deviations(resp) DHS"
label variable ha11_5   "Wt/Ht Std deviations(resp) DHS"
label variable ha11_6   "Wt/Ht Std deviations(resp) DHS"
label variable ha11_7   "Wt/Ht Std deviations(resp) DHS"
label variable ha12_1   "Wt/Ht Percent ref. median (DHS"
label variable ha12_2   "Wt/Ht Percent ref. median (DHS"
label variable ha12_3   "Wt/Ht Percent ref. median (DHS"
label variable ha12_4   "Wt/Ht Percent ref. median (DHS"
label variable ha12_5   "Wt/Ht Percent ref. median (DHS"
label variable ha12_6   "Wt/Ht Percent ref. median (DHS"
label variable ha12_7   "Wt/Ht Percent ref. median (DHS"
label variable ha12a_1  "Wt/Ht Percent ref. median (Fog"
label variable ha12a_2  "Wt/Ht Percent ref. median (Fog"
label variable ha12a_3  "Wt/Ht Percent ref. median (Fog"
label variable ha12a_4  "Wt/Ht Percent ref. median (Fog"
label variable ha12a_5  "Wt/Ht Percent ref. median (Fog"
label variable ha12a_6  "Wt/Ht Percent ref. median (Fog"
label variable ha12a_7  "Wt/Ht Percent ref. median (Fog"
label variable ha12b_1  "Wt/Ht Percent ref. median (WHO"
label variable ha12b_2  "Wt/Ht Percent ref. median (WHO"
label variable ha12b_3  "Wt/Ht Percent ref. median (WHO"
label variable ha12b_4  "Wt/Ht Percent ref. median (WHO"
label variable ha12b_5  "Wt/Ht Percent ref. median (WHO"
label variable ha12b_6  "Wt/Ht Percent ref. median (WHO"
label variable ha12b_7  "Wt/Ht Percent ref. median (WHO"
label variable ha13_1   "Result of measurement of resp."
label variable ha13_2   "Result of measurement of resp."
label variable ha13_3   "Result of measurement of resp."
label variable ha13_4   "Result of measurement of resp."
label variable ha13_5   "Result of measurement of resp."
label variable ha13_6   "Result of measurement of resp."
label variable ha13_7   "Result of measurement of resp."
label variable ha32_1   "Date of birth (cmc)"
label variable ha32_2   "Date of birth (cmc)"
label variable ha32_3   "Date of birth (cmc)"
label variable ha32_4   "Date of birth (cmc)"
label variable ha32_5   "Date of birth (cmc)"
label variable ha32_6   "Date of birth (cmc)"
label variable ha32_7   "Date of birth (cmc)"
label variable ha33_1   "Completeness of information"
label variable ha33_2   "Completeness of information"
label variable ha33_3   "Completeness of information"
label variable ha33_4   "Completeness of information"
label variable ha33_5   "Completeness of information"
label variable ha33_6   "Completeness of information"
label variable ha33_7   "Completeness of information"
label variable ha35_1   "Smoking"
label variable ha35_2   "Smoking"
label variable ha35_3   "Smoking"
label variable ha35_4   "Smoking"
label variable ha35_5   "Smoking"
label variable ha35_6   "Smoking"
label variable ha35_7   "Smoking"
label variable ha40_1   "Body mass index for respondent"
label variable ha40_2   "Body mass index for respondent"
label variable ha40_3   "Body mass index for respondent"
label variable ha40_4   "Body mass index for respondent"
label variable ha40_5   "Body mass index for respondent"
label variable ha40_6   "Body mass index for respondent"
label variable ha40_7   "Body mass index for respondent"
label variable ha41_1   "Rohrer's index for respondent"
label variable ha41_2   "Rohrer's index for respondent"
label variable ha41_3   "Rohrer's index for respondent"
label variable ha41_4   "Rohrer's index for respondent"
label variable ha41_5   "Rohrer's index for respondent"
label variable ha41_6   "Rohrer's index for respondent"
label variable ha41_7   "Rohrer's index for respondent"
label variable ha50_1   "Under age 18"
label variable ha50_2   "Under age 18"
label variable ha50_3   "Under age 18"
label variable ha50_4   "Under age 18"
label variable ha50_5   "Under age 18"
label variable ha50_6   "Under age 18"
label variable ha50_7   "Under age 18"
label variable ha51_1   "Line no. of parent/caretaker"
label variable ha51_2   "Line no. of parent/caretaker"
label variable ha51_3   "Line no. of parent/caretaker"
label variable ha51_4   "Line no. of parent/caretaker"
label variable ha51_5   "Line no. of parent/caretaker"
label variable ha51_6   "Line no. of parent/caretaker"
label variable ha51_7   "Line no. of parent/caretaker"
label variable ha52_1   "Read consent statement"
label variable ha52_2   "Read consent statement"
label variable ha52_3   "Read consent statement"
label variable ha52_4   "Read consent statement"
label variable ha52_5   "Read consent statement"
label variable ha52_6   "Read consent statement"
label variable ha52_7   "Read consent statement"
label variable ha53_1   "Hemoglobin level (g/dl - 1 decimal)"
label variable ha53_2   "Hemoglobin level (g/dl - 1 decimal)"
label variable ha53_3   "Hemoglobin level (g/dl - 1 decimal)"
label variable ha53_4   "Hemoglobin level (g/dl - 1 decimal)"
label variable ha53_5   "Hemoglobin level (g/dl - 1 decimal)"
label variable ha53_6   "Hemoglobin level (g/dl - 1 decimal)"
label variable ha53_7   "Hemoglobin level (g/dl - 1 decimal)"
label variable ha54_1   "Currently pregnant"
label variable ha54_2   "Currently pregnant"
label variable ha54_3   "Currently pregnant"
label variable ha54_4   "Currently pregnant"
label variable ha54_5   "Currently pregnant"
label variable ha54_6   "Currently pregnant"
label variable ha54_7   "Currently pregnant"
label variable ha55_1   "Result of measuring (Hemoglobin)"
label variable ha55_2   "Result of measuring (Hemoglobin)"
label variable ha55_3   "Result of measuring (Hemoglobin)"
label variable ha55_4   "Result of measuring (Hemoglobin)"
label variable ha55_5   "Result of measuring (Hemoglobin)"
label variable ha55_6   "Result of measuring (Hemoglobin)"
label variable ha55_7   "Result of measuring (Hemoglobin)"
label variable ha56_1   "Hemoglobin level adjusted by altitude (g/dl - 1 decimal)"
label variable ha56_2   "Hemoglobin level adjusted by altitude (g/dl - 1 decimal)"
label variable ha56_3   "Hemoglobin level adjusted by altitude (g/dl - 1 decimal)"
label variable ha56_4   "Hemoglobin level adjusted by altitude (g/dl - 1 decimal)"
label variable ha56_5   "Hemoglobin level adjusted by altitude (g/dl - 1 decimal)"
label variable ha56_6   "Hemoglobin level adjusted by altitude (g/dl - 1 decimal)"
label variable ha56_7   "Hemoglobin level adjusted by altitude (g/dl - 1 decimal)"
label variable ha57_1   "Anemia level"
label variable ha57_2   "Anemia level"
label variable ha57_3   "Anemia level"
label variable ha57_4   "Anemia level"
label variable ha57_5   "Anemia level"
label variable ha57_6   "Anemia level"
label variable ha57_7   "Anemia level"
label variable ha58_1   "NA - Agrees to referral"
label variable ha58_2   "NA - Agrees to referral"
label variable ha58_3   "NA - Agrees to referral"
label variable ha58_4   "NA - Agrees to referral"
label variable ha58_5   "NA - Agrees to referral"
label variable ha58_6   "NA - Agrees to referral"
label variable ha58_7   "NA - Agrees to referral"
label variable ha60_1   "Marital status"
label variable ha60_2   "Marital status"
label variable ha60_3   "Marital status"
label variable ha60_4   "Marital status"
label variable ha60_5   "Marital status"
label variable ha60_6   "Marital status"
label variable ha60_7   "Marital status"
label variable ha61_1   "Read consent statement (HIV)"
label variable ha61_2   "Read consent statement (HIV)"
label variable ha61_3   "Read consent statement (HIV)"
label variable ha61_4   "Read consent statement (HIV)"
label variable ha61_5   "Read consent statement (HIV)"
label variable ha61_6   "Read consent statement (HIV)"
label variable ha61_7   "Read consent statement (HIV)"
label variable ha62_1   "Blood sample ID number"
label variable ha62_2   "Blood sample ID number"
label variable ha62_3   "Blood sample ID number"
label variable ha62_4   "Blood sample ID number"
label variable ha62_5   "Blood sample ID number"
label variable ha62_6   "Blood sample ID number"
label variable ha62_7   "Blood sample ID number"
label variable ha63_1   "Result of measuring (HIV)"
label variable ha63_2   "Result of measuring (HIV)"
label variable ha63_3   "Result of measuring (HIV)"
label variable ha63_4   "Result of measuring (HIV)"
label variable ha63_5   "Result of measuring (HIV)"
label variable ha63_6   "Result of measuring (HIV)"
label variable ha63_7   "Result of measuring (HIV)"
label variable ha64_1   "NA - Consent for additional tests"
label variable ha64_2   "NA - Consent for additional tests"
label variable ha64_3   "NA - Consent for additional tests"
label variable ha64_4   "NA - Consent for additional tests"
label variable ha64_5   "NA - Consent for additional tests"
label variable ha64_6   "NA - Consent for additional tests"
label variable ha64_7   "NA - Consent for additional tests"
label variable ha65_1   "Result of woman individual interview"
label variable ha65_2   "Result of woman individual interview"
label variable ha65_3   "Result of woman individual interview"
label variable ha65_4   "Result of woman individual interview"
label variable ha65_5   "Result of woman individual interview"
label variable ha65_6   "Result of woman individual interview"
label variable ha65_7   "Result of woman individual interview"
label variable ha66_1   "Woman's highest educational level"
label variable ha66_2   "Woman's highest educational level"
label variable ha66_3   "Woman's highest educational level"
label variable ha66_4   "Woman's highest educational level"
label variable ha66_5   "Woman's highest educational level"
label variable ha66_6   "Woman's highest educational level"
label variable ha66_7   "Woman's highest educational level"
label variable ha67_1   "Woman's highest year of education"
label variable ha67_2   "Woman's highest year of education"
label variable ha67_3   "Woman's highest year of education"
label variable ha67_4   "Woman's highest year of education"
label variable ha67_5   "Woman's highest year of education"
label variable ha67_6   "Woman's highest year of education"
label variable ha67_7   "Woman's highest year of education"
label variable ha68_1   "Highest educational level (CS for preliminary & final report)"
label variable ha68_2   "Highest educational level (CS for preliminary & final report)"
label variable ha68_3   "Highest educational level (CS for preliminary & final report)"
label variable ha68_4   "Highest educational level (CS for preliminary & final report)"
label variable ha68_5   "Highest educational level (CS for preliminary & final report)"
label variable ha68_6   "Highest educational level (CS for preliminary & final report)"
label variable ha68_7   "Highest educational level (CS for preliminary & final report)"
label variable ha69_1   "HIV weight (6 decimals)"
label variable ha69_2   "HIV weight (6 decimals)"
label variable ha69_3   "HIV weight (6 decimals)"
label variable ha69_4   "HIV weight (6 decimals)"
label variable ha69_5   "HIV weight (6 decimals)"
label variable ha69_6   "HIV weight (6 decimals)"
label variable ha69_7   "HIV weight (6 decimals)"
label variable hc0_1    "Index to household schedule"
label variable hc0_2    "Index to household schedule"
label variable hc0_3    "Index to household schedule"
label variable hc0_4    "Index to household schedule"
label variable hc0_5    "Index to household schedule"
label variable hc0_6    "Index to household schedule"
label variable hc1_1    "Age in months"
label variable hc1_2    "Age in months"
label variable hc1_3    "Age in months"
label variable hc1_4    "Age in months"
label variable hc1_5    "Age in months"
label variable hc1_6    "Age in months"
label variable hc2_1    "Weight in kilograms (1 dec.)"
label variable hc2_2    "Weight in kilograms (1 dec.)"
label variable hc2_3    "Weight in kilograms (1 dec.)"
label variable hc2_4    "Weight in kilograms (1 dec.)"
label variable hc2_5    "Weight in kilograms (1 dec.)"
label variable hc2_6    "Weight in kilograms (1 dec.)"
label variable hc3_1    "Height in centimeters (1 dec.)"
label variable hc3_2    "Height in centimeters (1 dec.)"
label variable hc3_3    "Height in centimeters (1 dec.)"
label variable hc3_4    "Height in centimeters (1 dec.)"
label variable hc3_5    "Height in centimeters (1 dec.)"
label variable hc3_6    "Height in centimeters (1 dec.)"
label variable hc4_1    "Ht/A Percentile"
label variable hc4_2    "Ht/A Percentile"
label variable hc4_3    "Ht/A Percentile"
label variable hc4_4    "Ht/A Percentile"
label variable hc4_5    "Ht/A Percentile"
label variable hc4_6    "Ht/A Percentile"
label variable hc5_1    "Ht/A Standard deviations"
label variable hc5_2    "Ht/A Standard deviations"
label variable hc5_3    "Ht/A Standard deviations"
label variable hc5_4    "Ht/A Standard deviations"
label variable hc5_5    "Ht/A Standard deviations"
label variable hc5_6    "Ht/A Standard deviations"
label variable hc6_1    "Ht/A Percent of ref. median"
label variable hc6_2    "Ht/A Percent of ref. median"
label variable hc6_3    "Ht/A Percent of ref. median"
label variable hc6_4    "Ht/A Percent of ref. median"
label variable hc6_5    "Ht/A Percent of ref. median"
label variable hc6_6    "Ht/A Percent of ref. median"
label variable hc7_1    "Wt/A Percentile"
label variable hc7_2    "Wt/A Percentile"
label variable hc7_3    "Wt/A Percentile"
label variable hc7_4    "Wt/A Percentile"
label variable hc7_5    "Wt/A Percentile"
label variable hc7_6    "Wt/A Percentile"
label variable hc8_1    "Wt/A Standard deviations"
label variable hc8_2    "Wt/A Standard deviations"
label variable hc8_3    "Wt/A Standard deviations"
label variable hc8_4    "Wt/A Standard deviations"
label variable hc8_5    "Wt/A Standard deviations"
label variable hc8_6    "Wt/A Standard deviations"
label variable hc9_1    "Wt/A Percent of ref. median"
label variable hc9_2    "Wt/A Percent of ref. median"
label variable hc9_3    "Wt/A Percent of ref. median"
label variable hc9_4    "Wt/A Percent of ref. median"
label variable hc9_5    "Wt/A Percent of ref. median"
label variable hc9_6    "Wt/A Percent of ref. median"
label variable hc10_1   "Wt/Ht Percentile"
label variable hc10_2   "Wt/Ht Percentile"
label variable hc10_3   "Wt/Ht Percentile"
label variable hc10_4   "Wt/Ht Percentile"
label variable hc10_5   "Wt/Ht Percentile"
label variable hc10_6   "Wt/Ht Percentile"
label variable hc11_1   "Wt/Ht Standard deviations"
label variable hc11_2   "Wt/Ht Standard deviations"
label variable hc11_3   "Wt/Ht Standard deviations"
label variable hc11_4   "Wt/Ht Standard deviations"
label variable hc11_5   "Wt/Ht Standard deviations"
label variable hc11_6   "Wt/Ht Standard deviations"
label variable hc12_1   "Wt/Ht Percent of ref. median"
label variable hc12_2   "Wt/Ht Percent of ref. median"
label variable hc12_3   "Wt/Ht Percent of ref. median"
label variable hc12_4   "Wt/Ht Percent of ref. median"
label variable hc12_5   "Wt/Ht Percent of ref. median"
label variable hc12_6   "Wt/Ht Percent of ref. median"
label variable hc13_1   "Result of measurement"
label variable hc13_2   "Result of measurement"
label variable hc13_3   "Result of measurement"
label variable hc13_4   "Result of measurement"
label variable hc13_5   "Result of measurement"
label variable hc13_6   "Result of measurement"
label variable hc15_1   "Height: lying or standing"
label variable hc15_2   "Height: lying or standing"
label variable hc15_3   "Height: lying or standing"
label variable hc15_4   "Height: lying or standing"
label variable hc15_5   "Height: lying or standing"
label variable hc15_6   "Height: lying or standing"
label variable hc16_1   "Day of birth of child"
label variable hc16_2   "Day of birth of child"
label variable hc16_3   "Day of birth of child"
label variable hc16_4   "Day of birth of child"
label variable hc16_5   "Day of birth of child"
label variable hc16_6   "Day of birth of child"
label variable hc17_1   "Date measured (day)"
label variable hc17_2   "Date measured (day)"
label variable hc17_3   "Date measured (day)"
label variable hc17_4   "Date measured (day)"
label variable hc17_5   "Date measured (day)"
label variable hc17_6   "Date measured (day)"
label variable hc18_1   "Date measured (month)"
label variable hc18_2   "Date measured (month)"
label variable hc18_3   "Date measured (month)"
label variable hc18_4   "Date measured (month)"
label variable hc18_5   "Date measured (month)"
label variable hc18_6   "Date measured (month)"
label variable hc19_1   "Date measured (year)"
label variable hc19_2   "Date measured (year)"
label variable hc19_3   "Date measured (year)"
label variable hc19_4   "Date measured (year)"
label variable hc19_5   "Date measured (year)"
label variable hc19_6   "Date measured (year)"
label variable hc27_1   "Sex"
label variable hc27_2   "Sex"
label variable hc27_3   "Sex"
label variable hc27_4   "Sex"
label variable hc27_5   "Sex"
label variable hc27_6   "Sex"
label variable hc30_1   "Month of birth of child"
label variable hc30_2   "Month of birth of child"
label variable hc30_3   "Month of birth of child"
label variable hc30_4   "Month of birth of child"
label variable hc30_5   "Month of birth of child"
label variable hc30_6   "Month of birth of child"
label variable hc31_1   "Year of birth of child"
label variable hc31_2   "Year of birth of child"
label variable hc31_3   "Year of birth of child"
label variable hc31_4   "Year of birth of child"
label variable hc31_5   "Year of birth of child"
label variable hc31_6   "Year of birth of child"
label variable hc32_1   "Date of birth (cmc)"
label variable hc32_2   "Date of birth (cmc)"
label variable hc32_3   "Date of birth (cmc)"
label variable hc32_4   "Date of birth (cmc)"
label variable hc32_5   "Date of birth (cmc)"
label variable hc32_6   "Date of birth (cmc)"
label variable hc33_1   "Completeness of information"
label variable hc33_2   "Completeness of information"
label variable hc33_3   "Completeness of information"
label variable hc33_4   "Completeness of information"
label variable hc33_5   "Completeness of information"
label variable hc33_6   "Completeness of information"
label variable hc51_1   "Line no. of parent/caretaker"
label variable hc51_2   "Line no. of parent/caretaker"
label variable hc51_3   "Line no. of parent/caretaker"
label variable hc51_4   "Line no. of parent/caretaker"
label variable hc51_5   "Line no. of parent/caretaker"
label variable hc51_6   "Line no. of parent/caretaker"
label variable hc52_1   "Read consent statement"
label variable hc52_2   "Read consent statement"
label variable hc52_3   "Read consent statement"
label variable hc52_4   "Read consent statement"
label variable hc52_5   "Read consent statement"
label variable hc52_6   "Read consent statement"
label variable hc53_1   "Hemoglobin level (g/dl - 1 decimal)"
label variable hc53_2   "Hemoglobin level (g/dl - 1 decimal)"
label variable hc53_3   "Hemoglobin level (g/dl - 1 decimal)"
label variable hc53_4   "Hemoglobin level (g/dl - 1 decimal)"
label variable hc53_5   "Hemoglobin level (g/dl - 1 decimal)"
label variable hc53_6   "Hemoglobin level (g/dl - 1 decimal)"
label variable hc55_1   "Result of measuring (Hemoglobin)"
label variable hc55_2   "Result of measuring (Hemoglobin)"
label variable hc55_3   "Result of measuring (Hemoglobin)"
label variable hc55_4   "Result of measuring (Hemoglobin)"
label variable hc55_5   "Result of measuring (Hemoglobin)"
label variable hc55_6   "Result of measuring (Hemoglobin)"
label variable hc56_1   "Hemoglobin level adjusted by altitude (g/dl - 1 decimal)"
label variable hc56_2   "Hemoglobin level adjusted by altitude (g/dl - 1 decimal)"
label variable hc56_3   "Hemoglobin level adjusted by altitude (g/dl - 1 decimal)"
label variable hc56_4   "Hemoglobin level adjusted by altitude (g/dl - 1 decimal)"
label variable hc56_5   "Hemoglobin level adjusted by altitude (g/dl - 1 decimal)"
label variable hc56_6   "Hemoglobin level adjusted by altitude (g/dl - 1 decimal)"
label variable hc57_1   "Anemia level"
label variable hc57_2   "Anemia level"
label variable hc57_3   "Anemia level"
label variable hc57_4   "Anemia level"
label variable hc57_5   "Anemia level"
label variable hc57_6   "Anemia level"
label variable hc58_1   "NA - Agrees to referral"
label variable hc58_2   "NA - Agrees to referral"
label variable hc58_3   "NA - Agrees to referral"
label variable hc58_4   "NA - Agrees to referral"
label variable hc58_5   "NA - Agrees to referral"
label variable hc58_6   "NA - Agrees to referral"
label variable hc60_1   "Mother's line number from woman's questionnaire"
label variable hc60_2   "Mother's line number from woman's questionnaire"
label variable hc60_3   "Mother's line number from woman's questionnaire"
label variable hc60_4   "Mother's line number from woman's questionnaire"
label variable hc60_5   "Mother's line number from woman's questionnaire"
label variable hc60_6   "Mother's line number from woman's questionnaire"
label variable hc61_1   "Mother's highest educational level"
label variable hc61_2   "Mother's highest educational level"
label variable hc61_3   "Mother's highest educational level"
label variable hc61_4   "Mother's highest educational level"
label variable hc61_5   "Mother's highest educational level"
label variable hc61_6   "Mother's highest educational level"
label variable hc62_1   "Mother's highest year of education"
label variable hc62_2   "Mother's highest year of education"
label variable hc62_3   "Mother's highest year of education"
label variable hc62_4   "Mother's highest year of education"
label variable hc62_5   "Mother's highest year of education"
label variable hc62_6   "Mother's highest year of education"
label variable hc63_1   "Preceding birth interval"
label variable hc63_2   "Preceding birth interval"
label variable hc63_3   "Preceding birth interval"
label variable hc63_4   "Preceding birth interval"
label variable hc63_5   "Preceding birth interval"
label variable hc63_6   "Preceding birth interval"
label variable hc64_1   "Birth order number"
label variable hc64_2   "Birth order number"
label variable hc64_3   "Birth order number"
label variable hc64_4   "Birth order number"
label variable hc64_5   "Birth order number"
label variable hc64_6   "Birth order number"
label variable hc68_1   "Highest educational level (CS for preliminary & final report)"
label variable hc68_2   "Highest educational level (CS for preliminary & final report)"
label variable hc68_3   "Highest educational level (CS for preliminary & final report)"
label variable hc68_4   "Highest educational level (CS for preliminary & final report)"
label variable hc68_5   "Highest educational level (CS for preliminary & final report)"
label variable hc68_6   "Highest educational level (CS for preliminary & final report)"
label variable hc70_1   "Ht/A Standard deviations (according to WHO)"
label variable hc70_2   "Ht/A Standard deviations (according to WHO)"
label variable hc70_3   "Ht/A Standard deviations (according to WHO)"
label variable hc70_4   "Ht/A Standard deviations (according to WHO)"
label variable hc70_5   "Ht/A Standard deviations (according to WHO)"
label variable hc70_6   "Ht/A Standard deviations (according to WHO)"
label variable hc71_1   "Wt/A Standard deviations (according to WHO)"
label variable hc71_2   "Wt/A Standard deviations (according to WHO)"
label variable hc71_3   "Wt/A Standard deviations (according to WHO)"
label variable hc71_4   "Wt/A Standard deviations (according to WHO)"
label variable hc71_5   "Wt/A Standard deviations (according to WHO)"
label variable hc71_6   "Wt/A Standard deviations (according to WHO)"
label variable hc72_1   "Wt/Ht Standard deviations (according to WHO)"
label variable hc72_2   "Wt/Ht Standard deviations (according to WHO)"
label variable hc72_3   "Wt/Ht Standard deviations (according to WHO)"
label variable hc72_4   "Wt/Ht Standard deviations (according to WHO)"
label variable hc72_5   "Wt/Ht Standard deviations (according to WHO)"
label variable hc72_6   "Wt/Ht Standard deviations (according to WHO)"
label variable hc73_1   "BMI Standard deviations (according to WHO)"
label variable hc73_2   "BMI Standard deviations (according to WHO)"
label variable hc73_3   "BMI Standard deviations (according to WHO)"
label variable hc73_4   "BMI Standard deviations (according to WHO)"
label variable hc73_5   "BMI Standard deviations (according to WHO)"
label variable hc73_6   "BMI Standard deviations (according to WHO)"
label variable hb0_1    "Index to household schedule"
label variable hb0_2    "Index to household schedule"
label variable hb0_3    "Index to household schedule"
label variable hb0_4    "Index to household schedule"
label variable hb0_5    "Index to household schedule"
label variable hb1_1    "Men's age in years"
label variable hb1_2    "Men's age in years"
label variable hb1_3    "Men's age in years"
label variable hb1_4    "Men's age in years"
label variable hb1_5    "Men's age in years"
label variable hb2_1    "Respondent's weight (kilos-1d)"
label variable hb2_2    "Respondent's weight (kilos-1d)"
label variable hb2_3    "Respondent's weight (kilos-1d)"
label variable hb2_4    "Respondent's weight (kilos-1d)"
label variable hb2_5    "Respondent's weight (kilos-1d)"
label variable hb3_1    "Respondent's height (cms-1d)"
label variable hb3_2    "Respondent's height (cms-1d)"
label variable hb3_3    "Respondent's height (cms-1d)"
label variable hb3_4    "Respondent's height (cms-1d)"
label variable hb3_5    "Respondent's height (cms-1d)"
label variable hb4_1    "Ht/A Percentile (resp.)"
label variable hb4_2    "Ht/A Percentile (resp.)"
label variable hb4_3    "Ht/A Percentile (resp.)"
label variable hb4_4    "Ht/A Percentile (resp.)"
label variable hb4_5    "Ht/A Percentile (resp.)"
label variable hb5_1    "Ht/A Standard deviations (resp"
label variable hb5_2    "Ht/A Standard deviations (resp"
label variable hb5_3    "Ht/A Standard deviations (resp"
label variable hb5_4    "Ht/A Standard deviations (resp"
label variable hb5_5    "Ht/A Standard deviations (resp"
label variable hb6_1    "Ht/A Percent ref. median (resp"
label variable hb6_2    "Ht/A Percent ref. median (resp"
label variable hb6_3    "Ht/A Percent ref. median (resp"
label variable hb6_4    "Ht/A Percent ref. median (resp"
label variable hb6_5    "Ht/A Percent ref. median (resp"
label variable hb11_1   "Wt/Ht Std deviations(resp) DHS"
label variable hb11_2   "Wt/Ht Std deviations(resp) DHS"
label variable hb11_3   "Wt/Ht Std deviations(resp) DHS"
label variable hb11_4   "Wt/Ht Std deviations(resp) DHS"
label variable hb11_5   "Wt/Ht Std deviations(resp) DHS"
label variable hb12_1   "Wt/Ht Percent ref. median (DHS"
label variable hb12_2   "Wt/Ht Percent ref. median (DHS"
label variable hb12_3   "Wt/Ht Percent ref. median (DHS"
label variable hb12_4   "Wt/Ht Percent ref. median (DHS"
label variable hb12_5   "Wt/Ht Percent ref. median (DHS"
label variable hb12a_1  "Wt/Ht Percent ref. median (Fog"
label variable hb12a_2  "Wt/Ht Percent ref. median (Fog"
label variable hb12a_3  "Wt/Ht Percent ref. median (Fog"
label variable hb12a_4  "Wt/Ht Percent ref. median (Fog"
label variable hb12a_5  "Wt/Ht Percent ref. median (Fog"
label variable hb12b_1  "Wt/Ht Percent ref. median (WHO"
label variable hb12b_2  "Wt/Ht Percent ref. median (WHO"
label variable hb12b_3  "Wt/Ht Percent ref. median (WHO"
label variable hb12b_4  "Wt/Ht Percent ref. median (WHO"
label variable hb12b_5  "Wt/Ht Percent ref. median (WHO"
label variable hb13_1   "Result of measurement of resp."
label variable hb13_2   "Result of measurement of resp."
label variable hb13_3   "Result of measurement of resp."
label variable hb13_4   "Result of measurement of resp."
label variable hb13_5   "Result of measurement of resp."
label variable hb32_1   "Date of birth (cmc)"
label variable hb32_2   "Date of birth (cmc)"
label variable hb32_3   "Date of birth (cmc)"
label variable hb32_4   "Date of birth (cmc)"
label variable hb32_5   "Date of birth (cmc)"
label variable hb33_1   "Completeness of information"
label variable hb33_2   "Completeness of information"
label variable hb33_3   "Completeness of information"
label variable hb33_4   "Completeness of information"
label variable hb33_5   "Completeness of information"
label variable hb35_1   "Smoking"
label variable hb35_2   "Smoking"
label variable hb35_3   "Smoking"
label variable hb35_4   "Smoking"
label variable hb35_5   "Smoking"
label variable hb40_1   "Body mass index for respondent"
label variable hb40_2   "Body mass index for respondent"
label variable hb40_3   "Body mass index for respondent"
label variable hb40_4   "Body mass index for respondent"
label variable hb40_5   "Body mass index for respondent"
label variable hb41_1   "Rohrer's index for respondent"
label variable hb41_2   "Rohrer's index for respondent"
label variable hb41_3   "Rohrer's index for respondent"
label variable hb41_4   "Rohrer's index for respondent"
label variable hb41_5   "Rohrer's index for respondent"
label variable hb50_1   "Under age 18"
label variable hb50_2   "Under age 18"
label variable hb50_3   "Under age 18"
label variable hb50_4   "Under age 18"
label variable hb50_5   "Under age 18"
label variable hb51_1   "Line no. of parent/caretaker"
label variable hb51_2   "Line no. of parent/caretaker"
label variable hb51_3   "Line no. of parent/caretaker"
label variable hb51_4   "Line no. of parent/caretaker"
label variable hb51_5   "Line no. of parent/caretaker"
label variable hb52_1   "Read consent statement"
label variable hb52_2   "Read consent statement"
label variable hb52_3   "Read consent statement"
label variable hb52_4   "Read consent statement"
label variable hb52_5   "Read consent statement"
label variable hb53_1   "Hemoglobin level (g/dl - 1 decimal)"
label variable hb53_2   "Hemoglobin level (g/dl - 1 decimal)"
label variable hb53_3   "Hemoglobin level (g/dl - 1 decimal)"
label variable hb53_4   "Hemoglobin level (g/dl - 1 decimal)"
label variable hb53_5   "Hemoglobin level (g/dl - 1 decimal)"
label variable hb55_1   "Result of measuring (Hemoglobin)"
label variable hb55_2   "Result of measuring (Hemoglobin)"
label variable hb55_3   "Result of measuring (Hemoglobin)"
label variable hb55_4   "Result of measuring (Hemoglobin)"
label variable hb55_5   "Result of measuring (Hemoglobin)"
label variable hb56_1   "Hemoglobin level adjusted by altitude (g/dl - 1 decimal)"
label variable hb56_2   "Hemoglobin level adjusted by altitude (g/dl - 1 decimal)"
label variable hb56_3   "Hemoglobin level adjusted by altitude (g/dl - 1 decimal)"
label variable hb56_4   "Hemoglobin level adjusted by altitude (g/dl - 1 decimal)"
label variable hb56_5   "Hemoglobin level adjusted by altitude (g/dl - 1 decimal)"
label variable hb57_1   "Anemia level"
label variable hb57_2   "Anemia level"
label variable hb57_3   "Anemia level"
label variable hb57_4   "Anemia level"
label variable hb57_5   "Anemia level"
label variable hb58_1   "NA - Agrees to referral"
label variable hb58_2   "NA - Agrees to referral"
label variable hb58_3   "NA - Agrees to referral"
label variable hb58_4   "NA - Agrees to referral"
label variable hb58_5   "NA - Agrees to referral"
label variable hb60_1   "Marital status"
label variable hb60_2   "Marital status"
label variable hb60_3   "Marital status"
label variable hb60_4   "Marital status"
label variable hb60_5   "Marital status"
label variable hb61_1   "Read consent statement (HIV)"
label variable hb61_2   "Read consent statement (HIV)"
label variable hb61_3   "Read consent statement (HIV)"
label variable hb61_4   "Read consent statement (HIV)"
label variable hb61_5   "Read consent statement (HIV)"
label variable hb62_1   "Blood sample ID number"
label variable hb62_2   "Blood sample ID number"
label variable hb62_3   "Blood sample ID number"
label variable hb62_4   "Blood sample ID number"
label variable hb62_5   "Blood sample ID number"
label variable hb63_1   "Result of measuring (HIV)"
label variable hb63_2   "Result of measuring (HIV)"
label variable hb63_3   "Result of measuring (HIV)"
label variable hb63_4   "Result of measuring (HIV)"
label variable hb63_5   "Result of measuring (HIV)"
label variable hb64_1   "NA - Consent for additional tests"
label variable hb64_2   "NA - Consent for additional tests"
label variable hb64_3   "NA - Consent for additional tests"
label variable hb64_4   "NA - Consent for additional tests"
label variable hb64_5   "NA - Consent for additional tests"
label variable hb65_1   "Result of man individual interview"
label variable hb65_2   "Result of man individual interview"
label variable hb65_3   "Result of man individual interview"
label variable hb65_4   "Result of man individual interview"
label variable hb65_5   "Result of man individual interview"
label variable hb66_1   "Man's highest educational level"
label variable hb66_2   "Man's highest educational level"
label variable hb66_3   "Man's highest educational level"
label variable hb66_4   "Man's highest educational level"
label variable hb66_5   "Man's highest educational level"
label variable hb67_1   "Man's highest year of education"
label variable hb67_2   "Man's highest year of education"
label variable hb67_3   "Man's highest year of education"
label variable hb67_4   "Man's highest year of education"
label variable hb67_5   "Man's highest year of education"
label variable hb68_1   "Highest educational level (CS for preliminary & final report)"
label variable hb68_2   "Highest educational level (CS for preliminary & final report)"
label variable hb68_3   "Highest educational level (CS for preliminary & final report)"
label variable hb68_4   "Highest educational level (CS for preliminary & final report)"
label variable hb68_5   "Highest educational level (CS for preliminary & final report)"
label variable hb69_1   "HIV weight (6 decimals)"
label variable hb69_2   "HIV weight (6 decimals)"
label variable hb69_3   "HIV weight (6 decimals)"
label variable hb69_4   "HIV weight (6 decimals)"
label variable hb69_5   "HIV weight (6 decimals)"

#delimit ;
label define HV015   
     1 "Completed"
     2 "HH present, no resp"
     3 "HH absent"
     4 "Postponed"
     5 "Refused"
     6 "Dwelling vacant"
     7 "Dwelling destroyed"
     8 "Dwelling not found"
     9 "Other"
;
label define HV020   
     0 "All woman sample"
     1 "Ever married sample"
;
label define HV022   
     1 "Butha-Bothe : Rural"
     2 "Butha-Bothe : Urban"
     3 "Leribe : Rural"
     4 "Leribe : Urban"
     5 "Berea : Rural"
     6 "Berea : Urban"
     7 "Maseru : Rural"
     8 "Maseru : Urban"
     9 "Mafeteng : Rural"
    10 "Mafeteng : Urban"
    11 "Mohale's Hoek : Rural"
    12 "Mohale's Hoek : Urban"
    13 "Quthing : Rural"
    14 "Quthing : Urban"
    15 "Qacha's Nek : Rural"
    16 "Qacha's Nek : Urban"
    17 "Mokhotlong : Rural"
    18 "Mokhotlong : Urban"
    19 "Thaba Tseka : Rural"
    20 "Thaba Tseka : Urban"
;
label define HV023   
     1 "Butha-Bothe : Rural"
     2 "Butha-Bothe : Urban"
     3 "Leribe : Rural"
     4 "Leribe : Urban"
     5 "Berea : Rural"
     6 "Berea : Urban"
     7 "Maseru : Rural"
     8 "Maseru : Urban"
     9 "Mafeteng : Rural"
    10 "Mafeteng : Urban"
    11 "Mohale's Hoek : Rural"
    12 "Mohale's Hoek : Urban"
    13 "Quthing : Rural"
    14 "Quthing : Urban"
    15 "Qacha's Nek : Rural"
    16 "Qacha's Nek : Urban"
    17 "Mokhotlong : Rural"
    18 "Mokhotlong : Urban"
    19 "Thaba Tseka : Rural"
    20 "Thaba Tseka : Urban"
;
label define HV024   
     1 "Butha-Bothe"
     2 "Leribe"
     3 "Berea"
     4 "Maseru"
     5 "Mafeteng"
     6 "Mohale's Hoek"
     7 "Quthing"
     8 "Qacha's-Nek"
     9 "Mokhotlong"
    10 "Thaba-Tseka"
;
label define HV025   
     1 "Urban"
     2 "Rural"
;
label define HV026   
     0 "Capital, large city"
     1 "Small city"
     2 "Town"
     3 "Countryside"
;
label define HV027   
     0 "Not selected"
     1 "Men's survey"
     2 "Husband's survey"
;
label define HV042   
     0 "Not selected"
     1 "Selected"
;
label define HV043   
     0 "Household not selected"
     1 "Household selected"
;
label define HV044   
     0 "Household not selected"
     1 "Household selected"
;
label define HV201   
    10 "PIPED WATER"
    11 "Piped into dwelling"
    12 "Piped to yard/plot"
    13 "Public tap/standpipe"
    20 "TUBE WELL WATER"
    21 "Tube well or borehole"
    30 "DUG WELL (OPEN/PROTECTED)"
    31 "Protected well"
    32 "Unprotected well"
    40 "SURFACE WATER"
    41 "Protected spring"
    42 "Unprotected spring"
    43 "River/stream"
    44 "Dam/lake/pond"
    51 "Rainwater"
    61 "Tanker truck"
    62 "Cart with small tank"
    71 "Bottled water"
    96 "Other"
;
label define HV202   
    10 "PIPED WATER"
    11 "Piped into dwelling"
    12 "Piped to yard/plot"
    13 "Public tap/standpipe"
    20 "TUBE WELL WATER"
    21 "Tube well or borehole"
    30 "DUG WELL (OPEN/PROTECTED)"
    31 "Protected well"
    32 "Unprotected well"
    40 "SURFACE WATER"
    41 "Protected spring"
    42 "Unprotected spring"
    43 "River/stream"
    44 "Dam/lake/pond"
    51 "Rainwater"
    61 "Tanker truck"
    62 "Cart with small tank"
    71 "Bottled water"
    96 "Other"
;
label define HV204   
   996 "On premises"
   998 "Don't know"
;
label define HV205   
    10 "Flush toilet"
    11 "Flush to piped sewer system"
    12 "Flush to septic tank"
    13 "Flush to pit latrine"
    14 "Flush to somewhere else"
    15 "Flush, don't know where"
    20 "Pit toilet latrine"
    21 "Pit latrine ventilated improved pit latrine"
    22 "Pit latrine with slab"
    23 "Pit latrine without slab/ open pit"
    30 "No facility"
    31 "No facility/bush/field"
    41 "Composting toilet"
    42 "Bucket toilet"
    96 "OTHER"
;
label define HV206   
     0 "No"
     1 "Yes"
;
label define HV207   
     0 "No"
     1 "Yes"
;
label define HV208   
     0 "No"
     1 "Yes"
;
label define HV209   
     0 "No"
     1 "Yes"
;
label define HV210   
     0 "No"
     1 "Yes"
;
label define HV211   
     0 "No"
     1 "Yes"
;
label define HV212   
     0 "No"
     1 "Yes"
;
label define HV213   
    10 "NATURAL"
    11 "Natural floor mud/earth"
    20 "RUDIMENTARY"
    21 "Rudimentary floor wood planks"
    30 "FINISHED"
    31 "Finished floor parquet or polished wood"
    32 "Vinyl or asphalt strips"
    33 "Ceramic tiles"
    34 "Brick tiles"
    35 "Cement"
    36 "Carpet"
    96 "OTHER"
;
label define HV214   
    10 "NATURAL"
    11 "Natural walls cane/tree trunks"
    12 "Sod"
    20 "RUDIMENTARY"
    21 "Rudimentary walls stone with mud"
    22 "Plywood"
    23 "Cardboard"
    24 "Reused wood"
    30 "FINISHED"
    31 "Finished walls cement"
    32 "Stone with lime/cement"
    33 "Bricks"
    34 "Cement blocks"
    35 "Wood planks/shingles"
    96 "OTHER"
;
label define HV215   
    10 "NATURAL"
    11 "Natural roofing thatch/grass"
    12 "Sod"
    20 "RUDIMENTARY"
    21 "Rudimentary roofing wood planks"
    22 "Cardboard"
    30 "FINISHED"
    31 "Finished roofing metal"
    32 "Wood"
    33 "Asbestos/cement fiber"
    34 "Ceramic tiles"
    35 "Cement"
    36 "Roofing tiles"
    96 "OTHER"
;
label define HV216   
    99 "Missing"
;
label define HV217   
     0 "No adults"
     1 "One adult"
     2 "Two adults, opp. sex"
     3 "Two adults, same sex"
     4 "Three+ related adult"
     5 "Unrelated adults"
;
label define HV219   
     1 "Male"
     2 "Female"
;
label define HV220   
    97 "97+"
    98 "DK"
;
label define HV221   
     0 "No"
     1 "Yes"
;
label define HV225   
     0 "No"
     1 "Yes"
;
label define HV226   
     1 "Electricity"
     2 "LPG"
     3 "Natural gas"
     4 "Biogas"
     5 "Kerosene"
     6 "Coal, lignite"
     7 "Charcoal"
     8 "Wood"
     9 "Straw / shrubs / grass"
    10 "Agricultural crop"
    11 "Animal dung"
    95 "No food cooked in HH"
    96 "Other"
;
label define HV227   
     0 "No"
     1 "Yes"
;
label define HV228   
     0 "No"
     1 "All children"
     2 "Some children"
     3 "No bednet in HH"
;
label define HV234   
     0 "0 PPM (No Iodine)"
     7 "Below 15 PPM"
    15 "15 PPM and above"
    30 "30 PPM"
   994 "Salt not tested"
   995 "No salt in household"
;
label define HV235   
     1 "In own dwelling"
     2 "In own yard/plot"
     3 "Elsewhere"
;
label define HV236   
     1 "Adult woman"
     2 "Adult man"
     3 "Female child under 15 years old"
     4 "Male child under 15 years old"
     6 "Other"
;
label define HV237   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237A  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237B  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237C  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237D  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237E  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237F  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237G  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237H  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237I  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237J  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237K  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237X  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237Z  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV238   
    95 "10 or more households"
    98 "Don't know"
;
label define HV239   
     1 "Open fire"
     2 "Open stove"
     3 "Closed stove with chimney"
     6 "Other"
;
label define HV240   
     0 "Neither chimney or hood"
     1 "Chimney"
     2 "Hood"
;
label define HV241   
     1 "In the house"
     2 "In a separate building"
     3 "Outdoors"
     6 "Other"
;
label define HV242   
     0 "No"
     1 "Yes"
;
label define HV243A  
     0 "No"
     1 "Yes"
;
label define HV243B  
     0 "No"
     1 "Yes"
;
label define HV243C  
     0 "No"
     1 "Yes"
;
label define HV243D  
     0 "No"
     1 "Yes"
;
label define HV244   
     0 "No"
     1 "Yes"
;
label define HV245   
    95 "More than 95"
    98 "Unknown"
;
label define HV246   
     0 "No"
     1 "Yes"
;
label define HV246A  
     0 "None"
    95 "More than 95"
    98 "Unknown"
;
label define HV246B  
     0 "None"
    95 "More than 95"
    98 "Unknown"
;
label define HV246C  
     0 "None"
    95 "More than 95"
    98 "Unknown"
;
label define HV246D  
     0 "None"
    95 "More than 95"
    98 "Unknown"
;
label define HV246E  
     0 "None"
    95 "More than 95"
    98 "Unknown"
;
label define HV246F  
     0 "None"
    95 "More than 95"
    98 "Unknown"
;
label define HV246G  
     0 "None"
    95 "More than 95"
    98 "Unknown"
;
label define HV246H  
     0 "None"
    95 "More than 95"
    98 "Unknown"
;
label define HV246I  
     0 "None"
    95 "More than 95"
    98 "Unknown"
;
label define HV246J  
     0 "None"
    95 "More than 95"
    98 "Unknown"
;
label define HV246K  
     0 "None"
    95 "More than 95"
    98 "Unknown"
;
label define HV247   
     0 "No"
     1 "Yes"
;
label define HV249   
     0 "No"
     1 "Yes"
     8 "DK"
     9 "Missing"
;
label define HV250   
     8 "DK"
;
label define HV270   
     1 "Poorest"
     2 "Poorer"
     3 "Middle"
     4 "Richer"
     5 "Richest"
;
label define HML1    
    98 "Don't know"
;
label define HML2    
    99 "Missing"
;
label define SHZONE  
     1 "Lowlands"
     2 "Foothills"
     3 "Mountains"
     4 "Senqu River Valley"
;
label define SH111B  
     1 "Yes"
     0 "No"
;
label define SH111H  
     1 "Yes"
     0 "No"
;
label define SH111I  
     1 "Yes"
     0 "No"
;
label define SH111J  
     1 "Yes"
     0 "No"
;
label define SH127R  
     1 "BOTHA-BOTHE"
     2 "LERIBE"
     3 "BEREA"
     4 "MASERU"
     5 "MAFETENG"
     6 "MOHALE'S HOEK"
     7 "QUTHING"
     8 "QACHA'S-NEK"
     9 "MOKHOTLONG"
    10 "THABA TSEKA"
;
label define SH127   
 11011 "BOTHA-BOTHE GOVT HOSPITAL"
 11022 "SEBOCHE HOSPITAL"
 12012 "ST PAUL H/C"
 12021 "LINAKENG H/C"
 12031 "MOTETE H/C"
 12041 "RAMPAI H/C"
 12052 "ST PETERS H/C (MOTENG)"
 12061 "BOIKETSISO H/C"
 12071 "QHOLAQHOE H/C (MAKHUNOANE)"
 12081 "TSIME H/C"
 12091 "NGOAJANE/KHATIBE H/C"
 12101 "‘MUELA SITE H/C"
 12118 "DUAL CLINIC"
 12128 "THUSANANG H/C"
 21011 "MOTEBANG HOSPITAL"
 21022 "‘MAMOHAU MISSION HOSPITAL"
 22012 "ST ROSE H/C"
 22022 "ST MONICAS H/C"
 22032 "PONTMAIN H/C"
 22042 "MARYLAND H/C"
 22052 "OUR LADY OF LOURDES/MOSITI  H/C"
 22062 "LOUIS GERARD H/C"
 22072 "ST ANNE H/C"
 22088 "SPRINGFIELD H/C"
 22091 "PEKA H/C"
 22102 "MAHOBONG HOLY TRINITY H/C"
 22111 "SEETSA H/C"
 22122 "ST MARGRET H/C"
 22131 "MATLAMENG H/C"
 22141 "LINOTSING H/C"
 22151 "MAHOBONG H/C"
 22161 "SESHOTE H/C"
 22171 "KHABO H/C"
 22184 "MAPUTSOE H/C"
 22194 "FOBANE H/C"
 22202 "LITTLE FLOWER H/C"
 22212 "ST DENIS H/C"
 22224 "EMMANUEL H/C"
 22231 "SEPINARE H/C"
 22241 "LEJONE H/C"
 22251 "PALAMA H/C"
 22271 "THABA-PHATSOA H/C"
 31011 "BEREA GOVT HOSPITAL"
 31024 "MALUTI HOSPITAL"
 32018 "WILLIES CLINIC"
 32022 "ST MAGDALENA H/C"
 32032 "ST DAVID H/C"
 32041 "MAHLATSA H/C"
 32058 "PABALLONG PRIVATE ART CENTRE"
 32062 "IMMACULATE CONCEPTION"
 32072 "SION H/C"
 32084 "MAPHELENG H/C"
 32092 "MAQHAKA H/C (HOLY FAMILY)"
 32102 "GOOD SHEPHARD H/C"
 32112 "BETHANY MISSION H/C"
 32122 "ST THERESA (BELA-BELA) H/C"
 32131 "PILOT H/C"
 32152 "SEBEDIA H/C"
 32167 "KOLOJANE H/C"
 32171 "KOALI H/C"
 32188 "MBEYA -T.Y. PRIVATE CLINIC"
 32191 "KHUBETSOANA H/C"
 32208 "SEKAMANENG CLINIC"
 32218 "TŠENOLA PRIVATE CLINIC (MAMA'S)"
 35011 "MABOTE FILTER CLINIC"
 41013 "SCOTT MISSION HOSPITAL"
 41028 "MASERU PRIVATE HOSPITAL"
 41032 "ST JOSEPHS HOSPITAL"
 41041 "MAKOANYANE MILITARY HOSP"
 42038 "CAREWELL H/C"
 42048 "SOS H/C"
 42052 "LORETTO H/C"
 42068 "MASIANOKENG H/C"
 42071 "DOMICILLIARY H/C"
 42087 "THABA-BOSIU H/C"
 42099 "MATUKENG H/C"
 42102 "ST LEO RCC"
 42118 "MASECHABA CLINIC"
 42121 "R.L.D.F. H/C"
 42141 "THAMAE H/C"
 42154 "MASERU SDA H/C"
 42162 "PAKI H/C"
 42178 "MAHLOMPHO CLINIC"
 42188 "SEKAMANENG CLINIC"
 42198 "MAFUBE CLINIC"
 42208 "‘NELESE CLINIC"
 42211 "MATSIENG H/C"
 42218 "LEBONE CLINIC"
 42222 "ST RODRIGUE H/C"
 42232 "ST PETER CLAVER H/C (TŠOENENG)"
 42246 "ST BARNABAS H/C (MASITE)"
 42253 "MOFOKA H/C"
 42271 "SEMONKONG H/C"
 42282 "ST LEONARD H/C"
 42291 "HA SENG H/C"
 42306 "MARAKABEI H/C"
 42311 "LIKALANENG H/C"
 42322 "FATIMA/RAMABANTA H/C"
 42332 "ST BERNARD H/C"
 42342 "KOROKORO H/C (ST. JOSEPH)"
 42351 "HA-TLALI H/C"
 42362 "ST BENEDICT H/C"
 42372 "NAZARETH H/C"
 42378 "N.U.L. CLINIC"
 42381 "MASERU CHILDREN CENTER OF EXELLENCE (BAYLOR)"
 42391 "SENKATANA"
 42408 "ROSYM"
 42418 "MAKHALANYANE H/C"
 42428 "BATHOPELE H/C"
 42431 "MASERU CORRECTIONAL SERVICES H/C"
 42448 "LEQELE CLINIC"
 42458 "HEALTH CARE H/C"
 42461 "MOHALE H/C"
 42478 "LEHLAKENG H/C"
 42488 "MOLOPI CLINIC"
 42498 "MABATHO CLINIC"
 42508 "KATLEHO CLINIC"
 43011 "Q.E. II HOSPITAL"
 44011 "MOHLOMI MENTAL HOSPITAL"
 44021 "BOTS'ABELO LEPROSY HOSPITAL"
 45011 "QOALING FILTER CLINIC"
 45021 "LIKOTSI FILTER CLINIC"
 51011 "MAFETENG GOVT HOSPITAL"
 52015 "MOUNT TABOR H/C"
 52021 "TŠAKHOLO H/C"
 52031 "THABANA-MORENA H/C"
 52041 "LECO-OP H/C"
 52052 "MT OLIVET H/C"
 52062 "SAMARIA H/C"
 52071 "THABA TŠOEU H/C"
 52081 "LITŠOENENG H/C"
 52091 "SEKAMENG CLINIC"
 52101 "MALEA-LEA H/C"
 52113 "MATELILE H/C"
 52122 "EMMAUS H/C"
 52132 "MOTSEKUOA H/C"
 52147 "KENA H/C"
 52151 "MASEMOUSE H/C"
 52163 "KOLO H/C"
 52172 "ST ANDREW H/C"
 52183 "RIBANENG H/C"
 52198 "LESELI (THABANENG) CLINIC"
 52208 "MANTHATI (HA SEETSI) H/C"
 61011 "NTŠEKHE HOSPITAL"
 62011 "PHAMONG H/C"
 62021 "MPHARANE H/C"
 62032 "HOLY CROSS H/C"
 62041 "LIPHIRING H/C"
 62052 "BETHEL H/C"
 62061 "MOHALINYANE H/C"
 62071 "MOOTSINYANE H/C"
 62081 "LITHIPENG H/C"
 62092 "HA TŠEPO H/C"
 62101 "MORIFI H/C"
 62111 "NOHANA H/C"
 62121 "NKAU H/C"
 62131 "KUEBUNYANE H/C"
 62142 "MOFUMAHALI OA ROSARI  H/C"
 62161 "MOHALE’S HOEK CORRECTIONAL  SERVICES CLINIC"
 71011 "QUTHING GOVT HOSPITAL"
 72011 "TSATSANE H/C"
 72021 "MPHAKI H/C"
 72032 "ST GABRIEL H/C"
 72042 "ST MATTHEWS H/C"
 72052 "VILLA MARIA H/C"
 72061 "DILLI-DILLI H/C"
 72071 "HA MAKOAE H/C"
 72081 "MAQOKHO H/C"
 72108 "LINEO CLINIC"
 81011 "MACHABENG HOSPITAL"
 81023 "TEBELLONG HOSPITAL"
 82011 "SEHLABA-THEBE H/C"
 82022 "ST FRANCIS H/C"
 82031 "MELIKANE H/C"
 82042 "HERMITAGE H/C"
 82051 "RANKAKALA H/C"
 82061 "MATEBENG H/C"
 82073 "SEKAKE H/C"
 82082 "SACRED HEART H/C"
 82091 "LEBAKENG H/C"
 82101 "MOHLAPISO H/C"
 82118 "BOPHELONG PRIVATE"
 91011 "MOKHOTLONG HOSPITAL"
 92011 "LIBIBING H/C"
 92027 "MAPHOLANENG H/C"
 92032 "ST JAMES H/C"
 92042 "ST PETER'S H/C"
 92051 "‘MALEFILOANE H/C"
 92061 "MOLIKALIKO H/C"
 92072 "ST MARTIN H/C"
 92081 "LINAKANENG H/C"
 92091 "MOEKETSANE H/C"
 92101 "TLHANYAKU H/C"
 92118 "NALELI CLINIC"
 92128 "LETŠENG DIAMOND MINE CLINIC"
101012 "PARAY MISSION HOSPITAL"
101026 "ST JAMES MISSION  HOSPITAL"
102011 "KATSE H/C"
102023 "MOHLANAPENG H/C"
102032 "ST THERESA H/C"
102041 "THABA-TSEKA H/C"
102058 "MOHLAKENG CLINIC"
102061 "LINAKENG H/C"
102071 "HA MOKOTO H/C"
102082 "MONTMARTRE H/C"
102092 "AURAY H/C"
102106 "HA LEPHOI H/C"
102116 "HA POPA H/C"
102121 "SEHONG-HONG H/C"
102131 "BOBETE H/C"
102141 "MANAMANENG H/C"
102151 "METHALANENG H/C"
102161 "KOLBERG/KHOHLONTŠO"
102171 "SEMENANYANA H/C"
999996 "Other facility"
999998 "Facility not known"
;
label define SH128   
     1 "CAR/TRUCK/BUS/TAXI"
     2 "MOTORCYCLE/SCOOTER"
     3 "BICYCLE"
     4 "HORSE/DONKEY/MULE"
     5 "SCOTCH CART"
     6 "WALKING"
    96 "OTHER"
;
label define SH129H  
    98 "Don't know"
;
label define SH129M  
    98 "Don't know"
;
label define HV101   
     1 "Head"
     2 "Wife or husband"
     3 "Son/daughter"
     4 "Son/daughter-in-law"
     5 "Grandchild"
     6 "Parent"
     7 "Parent-in-law"
     8 "Brother/sister"
    10 "Other relative"
    11 "Adopted/foster child"
    12 "Not related"
    15 "Domestic employee (CS)"
    16 "Herdboy (CS)"
    98 "DK"
;
label define HV102   
     0 "No"
     1 "Yes"
;
label define HV103   
     0 "No"
     1 "Yes"
;
label define HV104   
     1 "Male"
     2 "Female"
;
label define HV105   
    96 "96+"
    98 "DK"
;
label define HV106   
     0 "No education, preschool"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "DK"
;
label define HV107   
    98 "DK"
;
label define HV108   
    97 "Inconsistent"
    98 "DK"
;
label define HV109   
     0 "No education"
     1 "Incomplete primary"
     2 "Complete primary"
     3 "Incomplete secondary"
     4 "Complete secondary"
     5 "Higher"
     8 "DK"
;
label define HV110   
     0 "No"
     1 "Yes"
;
label define HV111   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define HV112   
     0 "Mother not in HH"
;
label define HV113   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define HV114   
     0 "Father not in HH"
;
label define HV115   
     0 "Never married"
     1 "Married"
     2 "Living together"
     3 "Widowed"
     4 "Divorced"
     5 "Not living together"
;
label define HV116   
     0 "Never married"
     1 "Currently married"
     2 "Formerly/ever marr."
;
label define HV117   
     0 "Not eligible"
     1 "Eligible"
;
label define HV118   
     0 "Not eligible"
     1 "Eligible"
;
label define HV120   
     0 "Not eligible"
     1 "Eligible"
;
label define HV121   
     0 "No"
     1 "Currently attending"
     2 "Attended at some time"
;
label define HV122   
     0 "No education, preschool"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "DK"
;
label define HV123   
    98 "DK"
;
label define HV124   
    97 "Inconsistent"
    98 "DK"
;
label define HV125   
     0 "No"
     1 "Yes"
;
label define HV126   
     0 "No education, preschool"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "DK"
;
label define HV127   
    98 "DK"
;
label define HV128   
    97 "Inconsistent"
    98 "DK"
;
label define HV129   
     0 "Never attended"
     1 "Entered school"
     2 "Advanced"
     3 "Repeating"
     4 "Dropout"
     5 "Left school 2+ years ago"
     8 "DK"
;
label define HV130   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define HV131   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define HV132   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define HV133   
     0 "No"
     1 "Yes"
;
label define HV134   
     0 "No"
     1 "Yes"
;
label define HV135   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define HV136   
     0 "No"
     1 "Yes"
;
label define HV137   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define HV138   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define HV139   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define HV140   
     0 "Neither certificate or registered"
     1 "Has certificate"
     2 "Registered"
     8 "DK"
;
label define SH06    
     1 "Lesotho"
     2 "South Africa"
     3 "Other Country"
;
label define SH07    
     0 "Less than one year"
    98 "Don't know"
;
label define SH19A   
     0 "No education"
     1 "Primary"
     2 "After primary :vocational/tech.training"
     3 "Secondary/high"
     4 "After secondary:vocational/tech.training"
     5 "College"
     6 "Graduate/post graduate"
     8 "Don't know"
;
label define SH21A   
     0 "No education"
     1 "Primary"
     2 "After primary:vocational/tech.training"
     3 "Secondary/high"
     4 "After secondary:vocational/tech.training"
     5 "College"
     6 "Graduate/post graduate"
     8 "Don't know"
;
label define SH19AA  
     0 "No education"
     1 "Primary incomplete"
     2 "Primary complete"
     3 "Secondary+"
     8 "Don't know"
;
label define HA2     
  9994 "Not present"
  9995 "Refused"
  9996 "Other"
;
label define HA3     
  9994 "Not present"
  9995 "Refused"
  9996 "Other"
;
label define HA4     
  9998 "Flagged cases"
;
label define HA5     
  9998 "Flagged cases"
;
label define HA6     
 99998 "Flagged cases"
;
label define HA11    
  9998 "Flagged cases"
;
label define HA12    
 99998 "Flagged cases"
;
label define HA12A   
 99998 "Flagged cases"
;
label define HA12B   
 99998 "Flagged cases"
;
label define HA13    
     0 "Measured"
     3 "Not present"
     4 "Refused"
     6 "Other"
;
label define HA33    
     1 "Month and year"
     2 "Month and age -y imp"
     3 "Year and age - m imp"
     4 "Y & age - y ignored"
     5 "Year - a, m imp"
     6 "Age - y, m imp"
     7 "Month - a, y imp"
     8 "None - all imp"
;
label define HA35    
     0 "Doesn't smoke"
    80 "80+"
    94 "Smokes pipes, cigars, etc"
;
label define HA40    
  9998 "Flagged cases"
;
label define HA41    
  9998 "Flagged cases"
;
label define HA50    
     1 "Under age 18"
     2 "Age 18 or older"
;
label define HA51    
     0 "Not in household"
;
label define HA52    
     1 "Granted"
     2 "Parent/Other responsible refused"
     3 "Respondent refused"
     4 "Not present"
;
label define HA53    
   999 "Missing"
;
label define HA54    
     0 "No/don't know"
     1 "Yes"
;
label define HA55    
     0 "Measured"
     3 "Not present"
     4 "Refused"
     6 "Other"
;
label define HA56    
   999 "Missing"
;
label define HA57    
     1 "Severe"
     2 "Moderate"
     3 "Mild"
     4 "Not anemic"
;
label define HA58    
     0 "No"
     1 "Yes"
;
label define HA60    
     1 "Never in union"
     2 "Other"
;
label define HA61    
     1 "Granted"
     2 "Parent/Other responsible refused"
     3 "Respondent refused"
     4 "Sample not tested/lost/not enough DBS"
     5 "Not present"
;
label define HA63    
     1 "Blood taken"
     2 "Not present"
     3 "Refused"
     4 "Sample not tested/lost"
     5 "Not enough DBS to complete protocol"
     6 "Other"
;
label define HA64    
     1 "Granted"
     2 "Parent/Other responsible refused"
     3 "Respondent refused"
;
label define HA65    
     1 "Completed"
     2 "Not at home"
     3 "Postponed"
     4 "Refused"
     5 "Partly completed"
     6 "Incapacitated"
     7 "Other"
;
label define HA66    
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "Don't know"
;
label define HA67    
    99 "Missing"
;
label define HA68    
     0 "No education"
     1 "PRIMARY"
     2 "AFTER PRIMARY :VOCATIONAL/TECH.TRAINING"
     3 "SECONDARY/HIGH"
     4 "AFTER SECONDARY:VOCATIONAL/TECH.TRAINING"
     5 "COLLEGE"
     6 "GRADUATE/POST GRADUATE"
     8 "DON'T KNOW"
;
label define HC2     
  9994 "Not present"
  9995 "Refused"
  9996 "Other"
;
label define HC3     
  9994 "Not present"
  9995 "Refused"
  9996 "Other"
;
label define HC4     
  9998 "Flagged cases"
;
label define HC5     
  9998 "Flagged cases"
;
label define HC6     
 99998 "Flagged cases"
;
label define HC7     
  9998 "Flagged cases"
;
label define HC8     
  9998 "Flagged cases"
;
label define HC9     
 99998 "Flagged cases"
;
label define HC10    
  9998 "Flagged cases"
;
label define HC11    
  9998 "Flagged cases"
;
label define HC12    
 99998 "Flagged cases"
;
label define HC13    
     0 "Measured"
     3 "Not present"
     4 "Refused"
     6 "Other"
;
label define HC15    
     1 "Lying"
     2 "Standing"
;
label define HC16    
    99 "Missing"
;
label define HC27    
     1 "Male"
     2 "Female"
;
label define HC30    
    97 "Inconsistent"
    98 "DK"
;
label define HC31    
  9997 "Inconsistent"
  9998 "DK"
;
label define HC33    
     1 "Month and year"
     2 "Month and age"
     3 "Year and age"
     4 "Year"
     6 "Age"
     7 "Month"
     8 "None"
;
label define HC51    
     0 "Not in household"
;
label define HC52    
     1 "Granted"
     2 "Refused"
;
label define HC53    
   999 "Missing"
;
label define HC55    
     0 "Measured"
     3 "Not present"
     4 "Refused"
     6 "Other"
;
label define HC56    
   999 "Missing"
;
label define HC57    
     1 "Severe"
     2 "Moderate"
     3 "Mild"
     4 "Not anemic"
;
label define HC58    
     0 "No"
     1 "Yes"
;
label define HC60    
   993 "Mother not de facto"
   994 "Incomplete woman's interview"
   995 "Not in household"
;
label define HC61    
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "Don't know"
;
label define HC62    
    99 "Missing"
;
label define HC63    
   999 "Missing"
;
label define HC64    
    99 "Missing"
;
label define HC68    
     0 "No Education"
     1 "Primary"
     2 "After Primary :Vocational/Tech.training"
     3 "Secondary/High"
     4 "After Secondary:Vocational/Tech.training"
     5 "College"
     6 "Graduate/Post Graduate"
     8 "Don't know"
;
label define HC70    
  9996 "Height out of plausible limits"
  9997 "Age in days out of plausible limits"
  9998 "Flagged cases"
;
label define HC71    
  9996 "Height out of plausible limits"
  9997 "Age in days out of plausible limits"
  9998 "Flagged cases"
;
label define HC72    
  9996 "Height out of plausible limits"
  9997 "Age in days out of plausible limits"
  9998 "Flagged cases"
;
label define HC73    
  9996 "Height out of plausible limits"
  9997 "Age in days out of plausible limits"
  9998 "Flagged cases"
;
label define HB2     
  9994 "Not present"
  9995 "Refused"
  9996 "Other"
;
label define HB3     
  9994 "Not present"
  9995 "Refused"
  9996 "Other"
;
label define HB4     
  9998 "Flagged cases"
;
label define HB5     
  9998 "Flagged cases"
;
label define HB6     
 99998 "Flagged cases"
;
label define HB11    
  9998 "Flagged cases"
;
label define HB12    
 99998 "Flagged cases"
;
label define HB12A   
 99998 "Flagged cases"
;
label define HB12B   
 99998 "Flagged cases"
;
label define HB13    
     0 "Measured"
     3 "Not present"
     4 "Refused"
     6 "Other"
;
label define HB33    
     1 "Month and year"
     2 "Month and age -y imp"
     3 "Year and age - m imp"
     4 "Y & age - y ignored"
     5 "Year - a, m imp"
     6 "Age - y, m imp"
     7 "Month - a, y imp"
     8 "None - all imp"
;
label define HB35    
     0 "Doesn't smoke"
    80 "80+"
    94 "Smokes pipes, cigars, etc"
    98 "Don't know"
;
label define HB40    
  9998 "Flagged cases"
;
label define HB41    
  9998 "Flagged cases"
;
label define HB50    
     1 "Under age 18"
     2 "Age 18 or older"
;
label define HB51    
     0 "Not in household"
;
label define HB52    
     1 "Granted"
     2 "Parent/Other responsible refused"
     3 "Respondent refused"
     4 "Not present"
;
label define HB53    
   999 "Missing"
;
label define HB55    
     0 "Measured"
     3 "Not present"
     4 "Refused"
     6 "Other"
;
label define HB56    
   999 "Missing"
;
label define HB57    
     1 "Severe"
     2 "Moderate"
     3 "Mild"
     4 "Not anemic"
;
label define HB58    
     0 "No"
     1 "Yes"
;
label define HB60    
     1 "Never in union"
     2 "Other"
;
label define HB61    
     1 "Granted"
     2 "Parent/Other responsible refused"
     3 "Respondent refused"
     4 "Sample not tested/lost/not enough DBS"
     5 "Not present"
;
label define HB63    
     1 "Blood taken"
     2 "Not present"
     3 "Refused"
     4 "Sample not tested/lost"
     5 "Not enough DBS to complete protocol"
     6 "Other"
;
label define HB64    
     1 "Granted"
     2 "Parent/Other responsible refused"
     3 "Respondent refused"
;
label define HB65    
     1 "Completed"
     2 "Not at home"
     3 "Postponed"
     4 "Refused"
     5 "Partly completed"
     6 "Incapacitated"
     7 "Other"
;
label define HB66    
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "Don't know"
;
label define HB67    
    99 "Missing"
;
label define HB68    
     0 "No education"
     1 "PRIMARY"
     2 "AFTER PRIMARY :VOCATIONAL/TECH.TRAINING"
     3 "SECONDARY/HIGH"
     4 "AFTER SECONDARY:VOCATIONAL/TECH.TRAINING"
     5 "COLLEGE"
     6 "GRADUATE/POST GRADUATE"
     8 "DON'T KNOW"
;

#delimit cr
label values hv015    HV015   
label values hv020    HV020   
label values hv022    HV022   
label values hv023    HV023   
label values hv024    HV024   
label values hv025    HV025   
label values hv026    HV026   
label values hv027    HV027   
label values hv042    HV042   
label values hv043    HV043   
label values hv044    HV044   
label values hv201    HV201   
label values hv202    HV202   
label values hv204    HV204   
label values hv205    HV205   
label values hv206    HV206   
label values hv207    HV207   
label values hv208    HV208   
label values hv209    HV209   
label values hv210    HV210   
label values hv211    HV211   
label values hv212    HV212   
label values hv213    HV213   
label values hv214    HV214   
label values hv215    HV215   
label values hv217    HV217   
label values hv219    HV219   
label values hv220    HV220   
label values hv221    HV221   
label values hv225    HV225   
label values hv226    HV226   
label values hv227    HV227   
label values hv228    HV228   
label values hv234    HV234   
label values hv235    HV235   
label values hv236    HV236   
label values hv237    HV237   
label values hv237a   HV237A  
label values hv237b   HV237B  
label values hv237c   HV237C  
label values hv237d   HV237D  
label values hv237e   HV237E  
label values hv237f   HV237F  
label values hv237g   HV237G  
label values hv237h   HV237H  
label values hv237i   HV237I  
label values hv237j   HV237J  
label values hv237k   HV237K  
label values hv237x   HV237X  
label values hv237z   HV237Z  
label values hv238    HV238   
label values hv239    HV239   
label values hv240    HV240   
label values hv241    HV241   
label values hv242    HV242   
label values hv243a   HV243A  
label values hv243b   HV243B  
label values hv243c   HV243C  
label values hv243d   HV243D  
label values hv244    HV244   
label values hv245    HV245   
label values hv246    HV246   
label values hv246a   HV246A  
label values hv246b   HV246B  
label values hv246c   HV246C  
label values hv246d   HV246D  
label values hv246e   HV246E  
label values hv246f   HV246F  
label values hv246g   HV246G  
label values hv246h   HV246H  
label values hv246i   HV246I  
label values hv246j   HV246J  
label values hv246k   HV246K  
label values hv247    HV247   
label values hv249    HV249   
label values hv250    HV250   
label values hv270    HV270   
label values hml1     HML1    
label values shzone   SHZONE  
label values sh111b   SH111B  
label values sh111h   SH111H  
label values sh111i   SH111I  
label values sh111j   SH111J  
label values sh127r   SH127R  
label values sh127    SH127   
label values sh128    SH128   
label values sh129h   SH129H  
label values sh129m   SH129M  
label values hv101_01 HV101   
label values hv101_02 HV101   
label values hv101_03 HV101   
label values hv101_04 HV101   
label values hv101_05 HV101   
label values hv101_06 HV101   
label values hv101_07 HV101   
label values hv101_08 HV101   
label values hv101_09 HV101   
label values hv101_10 HV101   
label values hv101_11 HV101   
label values hv101_12 HV101   
label values hv101_13 HV101   
label values hv101_14 HV101   
label values hv101_15 HV101   
label values hv101_16 HV101   
label values hv101_17 HV101   
label values hv101_18 HV101   
label values hv101_19 HV101   
label values hv101_20 HV101   
label values hv101_21 HV101   
label values hv102_01 HV102   
label values hv102_02 HV102   
label values hv102_03 HV102   
label values hv102_04 HV102   
label values hv102_05 HV102   
label values hv102_06 HV102   
label values hv102_07 HV102   
label values hv102_08 HV102   
label values hv102_09 HV102   
label values hv102_10 HV102   
label values hv102_11 HV102   
label values hv102_12 HV102   
label values hv102_13 HV102   
label values hv102_14 HV102   
label values hv102_15 HV102   
label values hv102_16 HV102   
label values hv102_17 HV102   
label values hv102_18 HV102   
label values hv102_19 HV102   
label values hv102_20 HV102   
label values hv102_21 HV102   
label values hv103_01 HV103   
label values hv103_02 HV103   
label values hv103_03 HV103   
label values hv103_04 HV103   
label values hv103_05 HV103   
label values hv103_06 HV103   
label values hv103_07 HV103   
label values hv103_08 HV103   
label values hv103_09 HV103   
label values hv103_10 HV103   
label values hv103_11 HV103   
label values hv103_12 HV103   
label values hv103_13 HV103   
label values hv103_14 HV103   
label values hv103_15 HV103   
label values hv103_16 HV103   
label values hv103_17 HV103   
label values hv103_18 HV103   
label values hv103_19 HV103   
label values hv103_20 HV103   
label values hv103_21 HV103   
label values hv104_01 HV104   
label values hv104_02 HV104   
label values hv104_03 HV104   
label values hv104_04 HV104   
label values hv104_05 HV104   
label values hv104_06 HV104   
label values hv104_07 HV104   
label values hv104_08 HV104   
label values hv104_09 HV104   
label values hv104_10 HV104   
label values hv104_11 HV104   
label values hv104_12 HV104   
label values hv104_13 HV104   
label values hv104_14 HV104   
label values hv104_15 HV104   
label values hv104_16 HV104   
label values hv104_17 HV104   
label values hv104_18 HV104   
label values hv104_19 HV104   
label values hv104_20 HV104   
label values hv104_21 HV104   
label values hv105_01 HV105   
label values hv105_02 HV105   
label values hv105_03 HV105   
label values hv105_04 HV105   
label values hv105_05 HV105   
label values hv105_06 HV105   
label values hv105_07 HV105   
label values hv105_08 HV105   
label values hv105_09 HV105   
label values hv105_10 HV105   
label values hv105_11 HV105   
label values hv105_12 HV105   
label values hv105_13 HV105   
label values hv105_14 HV105   
label values hv105_15 HV105   
label values hv105_16 HV105   
label values hv105_17 HV105   
label values hv105_18 HV105   
label values hv105_19 HV105   
label values hv105_20 HV105   
label values hv105_21 HV105   
label values hv106_01 HV106   
label values hv106_02 HV106   
label values hv106_03 HV106   
label values hv106_04 HV106   
label values hv106_05 HV106   
label values hv106_06 HV106   
label values hv106_07 HV106   
label values hv106_08 HV106   
label values hv106_09 HV106   
label values hv106_10 HV106   
label values hv106_11 HV106   
label values hv106_12 HV106   
label values hv106_13 HV106   
label values hv106_14 HV106   
label values hv106_15 HV106   
label values hv106_16 HV106   
label values hv106_17 HV106   
label values hv106_18 HV106   
label values hv106_19 HV106   
label values hv106_20 HV106   
label values hv106_21 HV106   
label values hv107_01 HV107   
label values hv107_02 HV107   
label values hv107_03 HV107   
label values hv107_04 HV107   
label values hv107_05 HV107   
label values hv107_06 HV107   
label values hv107_07 HV107   
label values hv107_08 HV107   
label values hv107_09 HV107   
label values hv107_10 HV107   
label values hv107_11 HV107   
label values hv107_12 HV107   
label values hv107_13 HV107   
label values hv107_14 HV107   
label values hv107_15 HV107   
label values hv107_16 HV107   
label values hv107_17 HV107   
label values hv107_18 HV107   
label values hv107_19 HV107   
label values hv107_20 HV107   
label values hv107_21 HV107   
label values hv108_01 HV108   
label values hv108_02 HV108   
label values hv108_03 HV108   
label values hv108_04 HV108   
label values hv108_05 HV108   
label values hv108_06 HV108   
label values hv108_07 HV108   
label values hv108_08 HV108   
label values hv108_09 HV108   
label values hv108_10 HV108   
label values hv108_11 HV108   
label values hv108_12 HV108   
label values hv108_13 HV108   
label values hv108_14 HV108   
label values hv108_15 HV108   
label values hv108_16 HV108   
label values hv108_17 HV108   
label values hv108_18 HV108   
label values hv108_19 HV108   
label values hv108_20 HV108   
label values hv108_21 HV108   
label values hv109_01 HV109   
label values hv109_02 HV109   
label values hv109_03 HV109   
label values hv109_04 HV109   
label values hv109_05 HV109   
label values hv109_06 HV109   
label values hv109_07 HV109   
label values hv109_08 HV109   
label values hv109_09 HV109   
label values hv109_10 HV109   
label values hv109_11 HV109   
label values hv109_12 HV109   
label values hv109_13 HV109   
label values hv109_14 HV109   
label values hv109_15 HV109   
label values hv109_16 HV109   
label values hv109_17 HV109   
label values hv109_18 HV109   
label values hv109_19 HV109   
label values hv109_20 HV109   
label values hv109_21 HV109   
label values hv110_01 HV110   
label values hv110_02 HV110   
label values hv110_03 HV110   
label values hv110_04 HV110   
label values hv110_05 HV110   
label values hv110_06 HV110   
label values hv110_07 HV110   
label values hv110_08 HV110   
label values hv110_09 HV110   
label values hv110_10 HV110   
label values hv110_11 HV110   
label values hv110_12 HV110   
label values hv110_13 HV110   
label values hv110_14 HV110   
label values hv110_15 HV110   
label values hv110_16 HV110   
label values hv110_17 HV110   
label values hv110_18 HV110   
label values hv110_19 HV110   
label values hv110_20 HV110   
label values hv110_21 HV110   
label values hv111_01 HV111   
label values hv111_02 HV111   
label values hv111_03 HV111   
label values hv111_04 HV111   
label values hv111_05 HV111   
label values hv111_06 HV111   
label values hv111_07 HV111   
label values hv111_08 HV111   
label values hv111_09 HV111   
label values hv111_10 HV111   
label values hv111_11 HV111   
label values hv111_12 HV111   
label values hv111_13 HV111   
label values hv111_14 HV111   
label values hv111_15 HV111   
label values hv111_16 HV111   
label values hv111_17 HV111   
label values hv111_18 HV111   
label values hv111_19 HV111   
label values hv111_20 HV111   
label values hv111_21 HV111   
label values hv112_01 HV112   
label values hv112_02 HV112   
label values hv112_03 HV112   
label values hv112_04 HV112   
label values hv112_05 HV112   
label values hv112_06 HV112   
label values hv112_07 HV112   
label values hv112_08 HV112   
label values hv112_09 HV112   
label values hv112_10 HV112   
label values hv112_11 HV112   
label values hv112_12 HV112   
label values hv112_13 HV112   
label values hv112_14 HV112   
label values hv112_15 HV112   
label values hv112_16 HV112   
label values hv112_17 HV112   
label values hv112_18 HV112   
label values hv112_19 HV112   
label values hv112_20 HV112   
label values hv112_21 HV112   
label values hv113_01 HV113   
label values hv113_02 HV113   
label values hv113_03 HV113   
label values hv113_04 HV113   
label values hv113_05 HV113   
label values hv113_06 HV113   
label values hv113_07 HV113   
label values hv113_08 HV113   
label values hv113_09 HV113   
label values hv113_10 HV113   
label values hv113_11 HV113   
label values hv113_12 HV113   
label values hv113_13 HV113   
label values hv113_14 HV113   
label values hv113_15 HV113   
label values hv113_16 HV113   
label values hv113_17 HV113   
label values hv113_18 HV113   
label values hv113_19 HV113   
label values hv113_20 HV113   
label values hv113_21 HV113   
label values hv114_01 HV114   
label values hv114_02 HV114   
label values hv114_03 HV114   
label values hv114_04 HV114   
label values hv114_05 HV114   
label values hv114_06 HV114   
label values hv114_07 HV114   
label values hv114_08 HV114   
label values hv114_09 HV114   
label values hv114_10 HV114   
label values hv114_11 HV114   
label values hv114_12 HV114   
label values hv114_13 HV114   
label values hv114_14 HV114   
label values hv114_15 HV114   
label values hv114_16 HV114   
label values hv114_17 HV114   
label values hv114_18 HV114   
label values hv114_19 HV114   
label values hv114_20 HV114   
label values hv114_21 HV114   
label values hv115_01 HV115   
label values hv115_02 HV115   
label values hv115_03 HV115   
label values hv115_04 HV115   
label values hv115_05 HV115   
label values hv115_06 HV115   
label values hv115_07 HV115   
label values hv115_08 HV115   
label values hv115_09 HV115   
label values hv115_10 HV115   
label values hv115_11 HV115   
label values hv115_12 HV115   
label values hv115_13 HV115   
label values hv115_14 HV115   
label values hv115_15 HV115   
label values hv115_16 HV115   
label values hv115_17 HV115   
label values hv115_18 HV115   
label values hv115_19 HV115   
label values hv115_20 HV115   
label values hv115_21 HV115   
label values hv116_01 HV116   
label values hv116_02 HV116   
label values hv116_03 HV116   
label values hv116_04 HV116   
label values hv116_05 HV116   
label values hv116_06 HV116   
label values hv116_07 HV116   
label values hv116_08 HV116   
label values hv116_09 HV116   
label values hv116_10 HV116   
label values hv116_11 HV116   
label values hv116_12 HV116   
label values hv116_13 HV116   
label values hv116_14 HV116   
label values hv116_15 HV116   
label values hv116_16 HV116   
label values hv116_17 HV116   
label values hv116_18 HV116   
label values hv116_19 HV116   
label values hv116_20 HV116   
label values hv116_21 HV116   
label values hv117_01 HV117   
label values hv117_02 HV117   
label values hv117_03 HV117   
label values hv117_04 HV117   
label values hv117_05 HV117   
label values hv117_06 HV117   
label values hv117_07 HV117   
label values hv117_08 HV117   
label values hv117_09 HV117   
label values hv117_10 HV117   
label values hv117_11 HV117   
label values hv117_12 HV117   
label values hv117_13 HV117   
label values hv117_14 HV117   
label values hv117_15 HV117   
label values hv117_16 HV117   
label values hv117_17 HV117   
label values hv117_18 HV117   
label values hv117_19 HV117   
label values hv117_20 HV117   
label values hv117_21 HV117   
label values hv118_01 HV118   
label values hv118_02 HV118   
label values hv118_03 HV118   
label values hv118_04 HV118   
label values hv118_05 HV118   
label values hv118_06 HV118   
label values hv118_07 HV118   
label values hv118_08 HV118   
label values hv118_09 HV118   
label values hv118_10 HV118   
label values hv118_11 HV118   
label values hv118_12 HV118   
label values hv118_13 HV118   
label values hv118_14 HV118   
label values hv118_15 HV118   
label values hv118_16 HV118   
label values hv118_17 HV118   
label values hv118_18 HV118   
label values hv118_19 HV118   
label values hv118_20 HV118   
label values hv118_21 HV118   
label values hv120_01 HV120   
label values hv120_02 HV120   
label values hv120_03 HV120   
label values hv120_04 HV120   
label values hv120_05 HV120   
label values hv120_06 HV120   
label values hv120_07 HV120   
label values hv120_08 HV120   
label values hv120_09 HV120   
label values hv120_10 HV120   
label values hv120_11 HV120   
label values hv120_12 HV120   
label values hv120_13 HV120   
label values hv120_14 HV120   
label values hv120_15 HV120   
label values hv120_16 HV120   
label values hv120_17 HV120   
label values hv120_18 HV120   
label values hv120_19 HV120   
label values hv120_20 HV120   
label values hv120_21 HV120   
label values hv121_01 HV121   
label values hv121_02 HV121   
label values hv121_03 HV121   
label values hv121_04 HV121   
label values hv121_05 HV121   
label values hv121_06 HV121   
label values hv121_07 HV121   
label values hv121_08 HV121   
label values hv121_09 HV121   
label values hv121_10 HV121   
label values hv121_11 HV121   
label values hv121_12 HV121   
label values hv121_13 HV121   
label values hv121_14 HV121   
label values hv121_15 HV121   
label values hv121_16 HV121   
label values hv121_17 HV121   
label values hv121_18 HV121   
label values hv121_19 HV121   
label values hv121_20 HV121   
label values hv121_21 HV121   
label values hv122_01 HV122   
label values hv122_02 HV122   
label values hv122_03 HV122   
label values hv122_04 HV122   
label values hv122_05 HV122   
label values hv122_06 HV122   
label values hv122_07 HV122   
label values hv122_08 HV122   
label values hv122_09 HV122   
label values hv122_10 HV122   
label values hv122_11 HV122   
label values hv122_12 HV122   
label values hv122_13 HV122   
label values hv122_14 HV122   
label values hv122_15 HV122   
label values hv122_16 HV122   
label values hv122_17 HV122   
label values hv122_18 HV122   
label values hv122_19 HV122   
label values hv122_20 HV122   
label values hv122_21 HV122   
label values hv123_01 HV123   
label values hv123_02 HV123   
label values hv123_03 HV123   
label values hv123_04 HV123   
label values hv123_05 HV123   
label values hv123_06 HV123   
label values hv123_07 HV123   
label values hv123_08 HV123   
label values hv123_09 HV123   
label values hv123_10 HV123   
label values hv123_11 HV123   
label values hv123_12 HV123   
label values hv123_13 HV123   
label values hv123_14 HV123   
label values hv123_15 HV123   
label values hv123_16 HV123   
label values hv123_17 HV123   
label values hv123_18 HV123   
label values hv123_19 HV123   
label values hv123_20 HV123   
label values hv123_21 HV123   
label values hv124_01 HV124   
label values hv124_02 HV124   
label values hv124_03 HV124   
label values hv124_04 HV124   
label values hv124_05 HV124   
label values hv124_06 HV124   
label values hv124_07 HV124   
label values hv124_08 HV124   
label values hv124_09 HV124   
label values hv124_10 HV124   
label values hv124_11 HV124   
label values hv124_12 HV124   
label values hv124_13 HV124   
label values hv124_14 HV124   
label values hv124_15 HV124   
label values hv124_16 HV124   
label values hv124_17 HV124   
label values hv124_18 HV124   
label values hv124_19 HV124   
label values hv124_20 HV124   
label values hv124_21 HV124   
label values hv125_01 HV125   
label values hv125_02 HV125   
label values hv125_03 HV125   
label values hv125_04 HV125   
label values hv125_05 HV125   
label values hv125_06 HV125   
label values hv125_07 HV125   
label values hv125_08 HV125   
label values hv125_09 HV125   
label values hv125_10 HV125   
label values hv125_11 HV125   
label values hv125_12 HV125   
label values hv125_13 HV125   
label values hv125_14 HV125   
label values hv125_15 HV125   
label values hv125_16 HV125   
label values hv125_17 HV125   
label values hv125_18 HV125   
label values hv125_19 HV125   
label values hv125_20 HV125   
label values hv125_21 HV125   
label values hv126_01 HV126   
label values hv126_02 HV126   
label values hv126_03 HV126   
label values hv126_04 HV126   
label values hv126_05 HV126   
label values hv126_06 HV126   
label values hv126_07 HV126   
label values hv126_08 HV126   
label values hv126_09 HV126   
label values hv126_10 HV126   
label values hv126_11 HV126   
label values hv126_12 HV126   
label values hv126_13 HV126   
label values hv126_14 HV126   
label values hv126_15 HV126   
label values hv126_16 HV126   
label values hv126_17 HV126   
label values hv126_18 HV126   
label values hv126_19 HV126   
label values hv126_20 HV126   
label values hv126_21 HV126   
label values hv127_01 HV127   
label values hv127_02 HV127   
label values hv127_03 HV127   
label values hv127_04 HV127   
label values hv127_05 HV127   
label values hv127_06 HV127   
label values hv127_07 HV127   
label values hv127_08 HV127   
label values hv127_09 HV127   
label values hv127_10 HV127   
label values hv127_11 HV127   
label values hv127_12 HV127   
label values hv127_13 HV127   
label values hv127_14 HV127   
label values hv127_15 HV127   
label values hv127_16 HV127   
label values hv127_17 HV127   
label values hv127_18 HV127   
label values hv127_19 HV127   
label values hv127_20 HV127   
label values hv127_21 HV127   
label values hv128_01 HV128   
label values hv128_02 HV128   
label values hv128_03 HV128   
label values hv128_04 HV128   
label values hv128_05 HV128   
label values hv128_06 HV128   
label values hv128_07 HV128   
label values hv128_08 HV128   
label values hv128_09 HV128   
label values hv128_10 HV128   
label values hv128_11 HV128   
label values hv128_12 HV128   
label values hv128_13 HV128   
label values hv128_14 HV128   
label values hv128_15 HV128   
label values hv128_16 HV128   
label values hv128_17 HV128   
label values hv128_18 HV128   
label values hv128_19 HV128   
label values hv128_20 HV128   
label values hv128_21 HV128   
label values hv129_01 HV129   
label values hv129_02 HV129   
label values hv129_03 HV129   
label values hv129_04 HV129   
label values hv129_05 HV129   
label values hv129_06 HV129   
label values hv129_07 HV129   
label values hv129_08 HV129   
label values hv129_09 HV129   
label values hv129_10 HV129   
label values hv129_11 HV129   
label values hv129_12 HV129   
label values hv129_13 HV129   
label values hv129_14 HV129   
label values hv129_15 HV129   
label values hv129_16 HV129   
label values hv129_17 HV129   
label values hv129_18 HV129   
label values hv129_19 HV129   
label values hv129_20 HV129   
label values hv129_21 HV129   
label values hv130_01 HV130   
label values hv130_02 HV130   
label values hv130_03 HV130   
label values hv130_04 HV130   
label values hv130_05 HV130   
label values hv130_06 HV130   
label values hv130_07 HV130   
label values hv130_08 HV130   
label values hv130_09 HV130   
label values hv130_10 HV130   
label values hv130_11 HV130   
label values hv130_12 HV130   
label values hv130_13 HV130   
label values hv130_14 HV130   
label values hv130_15 HV130   
label values hv130_16 HV130   
label values hv130_17 HV130   
label values hv130_18 HV130   
label values hv130_19 HV130   
label values hv130_20 HV130   
label values hv130_21 HV130   
label values hv131_01 HV131   
label values hv131_02 HV131   
label values hv131_03 HV131   
label values hv131_04 HV131   
label values hv131_05 HV131   
label values hv131_06 HV131   
label values hv131_07 HV131   
label values hv131_08 HV131   
label values hv131_09 HV131   
label values hv131_10 HV131   
label values hv131_11 HV131   
label values hv131_12 HV131   
label values hv131_13 HV131   
label values hv131_14 HV131   
label values hv131_15 HV131   
label values hv131_16 HV131   
label values hv131_17 HV131   
label values hv131_18 HV131   
label values hv131_19 HV131   
label values hv131_20 HV131   
label values hv131_21 HV131   
label values hv132_01 HV132   
label values hv132_02 HV132   
label values hv132_03 HV132   
label values hv132_04 HV132   
label values hv132_05 HV132   
label values hv132_06 HV132   
label values hv132_07 HV132   
label values hv132_08 HV132   
label values hv132_09 HV132   
label values hv132_10 HV132   
label values hv132_11 HV132   
label values hv132_12 HV132   
label values hv132_13 HV132   
label values hv132_14 HV132   
label values hv132_15 HV132   
label values hv132_16 HV132   
label values hv132_17 HV132   
label values hv132_18 HV132   
label values hv132_19 HV132   
label values hv132_20 HV132   
label values hv132_21 HV132   
label values hv133_01 HV133   
label values hv133_02 HV133   
label values hv133_03 HV133   
label values hv133_04 HV133   
label values hv133_05 HV133   
label values hv133_06 HV133   
label values hv133_07 HV133   
label values hv133_08 HV133   
label values hv133_09 HV133   
label values hv133_10 HV133   
label values hv133_11 HV133   
label values hv133_12 HV133   
label values hv133_13 HV133   
label values hv133_14 HV133   
label values hv133_15 HV133   
label values hv133_16 HV133   
label values hv133_17 HV133   
label values hv133_18 HV133   
label values hv133_19 HV133   
label values hv133_20 HV133   
label values hv133_21 HV133   
label values hv134_01 HV134   
label values hv134_02 HV134   
label values hv134_03 HV134   
label values hv134_04 HV134   
label values hv134_05 HV134   
label values hv134_06 HV134   
label values hv134_07 HV134   
label values hv134_08 HV134   
label values hv134_09 HV134   
label values hv134_10 HV134   
label values hv134_11 HV134   
label values hv134_12 HV134   
label values hv134_13 HV134   
label values hv134_14 HV134   
label values hv134_15 HV134   
label values hv134_16 HV134   
label values hv134_17 HV134   
label values hv134_18 HV134   
label values hv134_19 HV134   
label values hv134_20 HV134   
label values hv134_21 HV134   
label values hv135_01 HV135   
label values hv135_02 HV135   
label values hv135_03 HV135   
label values hv135_04 HV135   
label values hv135_05 HV135   
label values hv135_06 HV135   
label values hv135_07 HV135   
label values hv135_08 HV135   
label values hv135_09 HV135   
label values hv135_10 HV135   
label values hv135_11 HV135   
label values hv135_12 HV135   
label values hv135_13 HV135   
label values hv135_14 HV135   
label values hv135_15 HV135   
label values hv135_16 HV135   
label values hv135_17 HV135   
label values hv135_18 HV135   
label values hv135_19 HV135   
label values hv135_20 HV135   
label values hv135_21 HV135   
label values hv136_01 HV136   
label values hv136_02 HV136   
label values hv136_03 HV136   
label values hv136_04 HV136   
label values hv136_05 HV136   
label values hv136_06 HV136   
label values hv136_07 HV136   
label values hv136_08 HV136   
label values hv136_09 HV136   
label values hv136_10 HV136   
label values hv136_11 HV136   
label values hv136_12 HV136   
label values hv136_13 HV136   
label values hv136_14 HV136   
label values hv136_15 HV136   
label values hv136_16 HV136   
label values hv136_17 HV136   
label values hv136_18 HV136   
label values hv136_19 HV136   
label values hv136_20 HV136   
label values hv136_21 HV136   
label values hv137_01 HV137   
label values hv137_02 HV137   
label values hv137_03 HV137   
label values hv137_04 HV137   
label values hv137_05 HV137   
label values hv137_06 HV137   
label values hv137_07 HV137   
label values hv137_08 HV137   
label values hv137_09 HV137   
label values hv137_10 HV137   
label values hv137_11 HV137   
label values hv137_12 HV137   
label values hv137_13 HV137   
label values hv137_14 HV137   
label values hv137_15 HV137   
label values hv137_16 HV137   
label values hv137_17 HV137   
label values hv137_18 HV137   
label values hv137_19 HV137   
label values hv137_20 HV137   
label values hv137_21 HV137   
label values hv138_01 HV138   
label values hv138_02 HV138   
label values hv138_03 HV138   
label values hv138_04 HV138   
label values hv138_05 HV138   
label values hv138_06 HV138   
label values hv138_07 HV138   
label values hv138_08 HV138   
label values hv138_09 HV138   
label values hv138_10 HV138   
label values hv138_11 HV138   
label values hv138_12 HV138   
label values hv138_13 HV138   
label values hv138_14 HV138   
label values hv138_15 HV138   
label values hv138_16 HV138   
label values hv138_17 HV138   
label values hv138_18 HV138   
label values hv138_19 HV138   
label values hv138_20 HV138   
label values hv138_21 HV138   
label values hv139_01 HV139   
label values hv139_02 HV139   
label values hv139_03 HV139   
label values hv139_04 HV139   
label values hv139_05 HV139   
label values hv139_06 HV139   
label values hv139_07 HV139   
label values hv139_08 HV139   
label values hv139_09 HV139   
label values hv139_10 HV139   
label values hv139_11 HV139   
label values hv139_12 HV139   
label values hv139_13 HV139   
label values hv139_14 HV139   
label values hv139_15 HV139   
label values hv139_16 HV139   
label values hv139_17 HV139   
label values hv139_18 HV139   
label values hv139_19 HV139   
label values hv139_20 HV139   
label values hv139_21 HV139   
label values hv140_01 HV140   
label values hv140_02 HV140   
label values hv140_03 HV140   
label values hv140_04 HV140   
label values hv140_05 HV140   
label values hv140_06 HV140   
label values hv140_07 HV140   
label values hv140_08 HV140   
label values hv140_09 HV140   
label values hv140_10 HV140   
label values hv140_11 HV140   
label values hv140_12 HV140   
label values hv140_13 HV140   
label values hv140_14 HV140   
label values hv140_15 HV140   
label values hv140_16 HV140   
label values hv140_17 HV140   
label values hv140_18 HV140   
label values hv140_19 HV140   
label values hv140_20 HV140   
label values hv140_21 HV140   
label values sh06_01  SH06    
label values sh06_02  SH06    
label values sh06_03  SH06    
label values sh06_04  SH06    
label values sh06_05  SH06    
label values sh06_06  SH06    
label values sh06_07  SH06    
label values sh06_08  SH06    
label values sh06_09  SH06    
label values sh06_10  SH06    
label values sh06_11  SH06    
label values sh06_12  SH06    
label values sh06_13  SH06    
label values sh06_14  SH06    
label values sh06_15  SH06    
label values sh06_16  SH06    
label values sh06_17  SH06    
label values sh06_18  SH06    
label values sh06_19  SH06    
label values sh06_20  SH06    
label values sh06_21  SH06    
label values sh07_01  SH07    
label values sh07_02  SH07    
label values sh07_03  SH07    
label values sh07_04  SH07    
label values sh07_05  SH07    
label values sh07_06  SH07    
label values sh07_07  SH07    
label values sh07_08  SH07    
label values sh07_09  SH07    
label values sh07_10  SH07    
label values sh07_11  SH07    
label values sh07_12  SH07    
label values sh07_13  SH07    
label values sh07_14  SH07    
label values sh07_15  SH07    
label values sh07_16  SH07    
label values sh07_17  SH07    
label values sh07_18  SH07    
label values sh07_19  SH07    
label values sh07_20  SH07    
label values sh07_21  SH07    
label values sh19a_01 SH19A   
label values sh19a_02 SH19A   
label values sh19a_03 SH19A   
label values sh19a_04 SH19A   
label values sh19a_05 SH19A   
label values sh19a_06 SH19A   
label values sh19a_07 SH19A   
label values sh19a_08 SH19A   
label values sh19a_09 SH19A   
label values sh19a_10 SH19A   
label values sh19a_11 SH19A   
label values sh19a_12 SH19A   
label values sh19a_13 SH19A   
label values sh19a_14 SH19A   
label values sh19a_15 SH19A   
label values sh19a_16 SH19A   
label values sh19a_17 SH19A   
label values sh19a_18 SH19A   
label values sh19a_19 SH19A   
label values sh19a_20 SH19A   
label values sh19a_21 SH19A   
label values sh21a_01 SH21A   
label values sh21a_02 SH21A   
label values sh21a_03 SH21A   
label values sh21a_04 SH21A   
label values sh21a_05 SH21A   
label values sh21a_06 SH21A   
label values sh21a_07 SH21A   
label values sh21a_08 SH21A   
label values sh21a_09 SH21A   
label values sh21a_10 SH21A   
label values sh21a_11 SH21A   
label values sh21a_12 SH21A   
label values sh21a_13 SH21A   
label values sh21a_14 SH21A   
label values sh21a_15 SH21A   
label values sh21a_16 SH21A   
label values sh21a_17 SH21A   
label values sh21a_18 SH21A   
label values sh21a_19 SH21A   
label values sh21a_20 SH21A   
label values sh21a_21 SH21A   
label values sh19aa_01 SH19AA  
label values sh19aa_02 SH19AA  
label values sh19aa_03 SH19AA  
label values sh19aa_04 SH19AA  
label values sh19aa_05 SH19AA  
label values sh19aa_06 SH19AA  
label values sh19aa_07 SH19AA  
label values sh19aa_08 SH19AA  
label values sh19aa_09 SH19AA  
label values sh19aa_10 SH19AA  
label values sh19aa_11 SH19AA  
label values sh19aa_12 SH19AA  
label values sh19aa_13 SH19AA  
label values sh19aa_14 SH19AA  
label values sh19aa_15 SH19AA  
label values sh19aa_16 SH19AA  
label values sh19aa_17 SH19AA  
label values sh19aa_18 SH19AA  
label values sh19aa_19 SH19AA  
label values sh19aa_20 SH19AA  
label values sh19aa_21 SH19AA  
label values ha2_1    HA2     
label values ha2_2    HA2     
label values ha2_3    HA2     
label values ha2_4    HA2     
label values ha2_5    HA2     
label values ha2_6    HA2     
label values ha2_7    HA2     
label values ha3_1    HA3     
label values ha3_2    HA3     
label values ha3_3    HA3     
label values ha3_4    HA3     
label values ha3_5    HA3     
label values ha3_6    HA3     
label values ha3_7    HA3     
label values ha4_1    HA4     
label values ha4_2    HA4     
label values ha4_3    HA4     
label values ha4_4    HA4     
label values ha4_5    HA4     
label values ha4_6    HA4     
label values ha4_7    HA4     
label values ha5_1    HA5     
label values ha5_2    HA5     
label values ha5_3    HA5     
label values ha5_4    HA5     
label values ha5_5    HA5     
label values ha5_6    HA5     
label values ha5_7    HA5     
label values ha6_1    HA6     
label values ha6_2    HA6     
label values ha6_3    HA6     
label values ha6_4    HA6     
label values ha6_5    HA6     
label values ha6_6    HA6     
label values ha6_7    HA6     
label values ha11_1   HA11    
label values ha11_2   HA11    
label values ha11_3   HA11    
label values ha11_4   HA11    
label values ha11_5   HA11    
label values ha11_6   HA11    
label values ha11_7   HA11    
label values ha12_1   HA12    
label values ha12_2   HA12    
label values ha12_3   HA12    
label values ha12_4   HA12    
label values ha12_5   HA12    
label values ha12_6   HA12    
label values ha12_7   HA12    
label values ha12a_1  HA12A   
label values ha12a_2  HA12A   
label values ha12a_3  HA12A   
label values ha12a_4  HA12A   
label values ha12a_5  HA12A   
label values ha12a_6  HA12A   
label values ha12a_7  HA12A   
label values ha12b_1  HA12B   
label values ha12b_2  HA12B   
label values ha12b_3  HA12B   
label values ha12b_4  HA12B   
label values ha12b_5  HA12B   
label values ha12b_6  HA12B   
label values ha12b_7  HA12B   
label values ha13_1   HA13    
label values ha13_2   HA13    
label values ha13_3   HA13    
label values ha13_4   HA13    
label values ha13_5   HA13    
label values ha13_6   HA13    
label values ha13_7   HA13    
label values ha33_1   HA33    
label values ha33_2   HA33    
label values ha33_3   HA33    
label values ha33_4   HA33    
label values ha33_5   HA33    
label values ha33_6   HA33    
label values ha33_7   HA33    
label values ha35_1   HA35    
label values ha35_2   HA35    
label values ha35_3   HA35    
label values ha35_4   HA35    
label values ha35_5   HA35    
label values ha35_6   HA35    
label values ha35_7   HA35    
label values ha40_1   HA40    
label values ha40_2   HA40    
label values ha40_3   HA40    
label values ha40_4   HA40    
label values ha40_5   HA40    
label values ha40_6   HA40    
label values ha40_7   HA40    
label values ha41_1   HA41    
label values ha41_2   HA41    
label values ha41_3   HA41    
label values ha41_4   HA41    
label values ha41_5   HA41    
label values ha41_6   HA41    
label values ha41_7   HA41    
label values ha50_1   HA50    
label values ha50_2   HA50    
label values ha50_3   HA50    
label values ha50_4   HA50    
label values ha50_5   HA50    
label values ha50_6   HA50    
label values ha50_7   HA50    
label values ha51_1   HA51    
label values ha51_2   HA51    
label values ha51_3   HA51    
label values ha51_4   HA51    
label values ha51_5   HA51    
label values ha51_6   HA51    
label values ha51_7   HA51    
label values ha52_1   HA52    
label values ha52_2   HA52    
label values ha52_3   HA52    
label values ha52_4   HA52    
label values ha52_5   HA52    
label values ha52_6   HA52    
label values ha52_7   HA52    
label values ha54_1   HA54    
label values ha54_2   HA54    
label values ha54_3   HA54    
label values ha54_4   HA54    
label values ha54_5   HA54    
label values ha54_6   HA54    
label values ha54_7   HA54    
label values ha55_1   HA55    
label values ha55_2   HA55    
label values ha55_3   HA55    
label values ha55_4   HA55    
label values ha55_5   HA55    
label values ha55_6   HA55    
label values ha55_7   HA55    
label values ha57_1   HA57    
label values ha57_2   HA57    
label values ha57_3   HA57    
label values ha57_4   HA57    
label values ha57_5   HA57    
label values ha57_6   HA57    
label values ha57_7   HA57    
label values ha58_1   HA58    
label values ha58_2   HA58    
label values ha58_3   HA58    
label values ha58_4   HA58    
label values ha58_5   HA58    
label values ha58_6   HA58    
label values ha58_7   HA58    
label values ha60_1   HA60    
label values ha60_2   HA60    
label values ha60_3   HA60    
label values ha60_4   HA60    
label values ha60_5   HA60    
label values ha60_6   HA60    
label values ha60_7   HA60    
label values ha61_1   HA61    
label values ha61_2   HA61    
label values ha61_3   HA61    
label values ha61_4   HA61    
label values ha61_5   HA61    
label values ha61_6   HA61    
label values ha61_7   HA61    
label values ha63_1   HA63    
label values ha63_2   HA63    
label values ha63_3   HA63    
label values ha63_4   HA63    
label values ha63_5   HA63    
label values ha63_6   HA63    
label values ha63_7   HA63    
label values ha64_1   HA64    
label values ha64_2   HA64    
label values ha64_3   HA64    
label values ha64_4   HA64    
label values ha64_5   HA64    
label values ha64_6   HA64    
label values ha64_7   HA64    
label values ha65_1   HA65    
label values ha65_2   HA65    
label values ha65_3   HA65    
label values ha65_4   HA65    
label values ha65_5   HA65    
label values ha65_6   HA65    
label values ha65_7   HA65    
label values ha66_1   HA66    
label values ha66_2   HA66    
label values ha66_3   HA66    
label values ha66_4   HA66    
label values ha66_5   HA66    
label values ha66_6   HA66    
label values ha66_7   HA66    
label values ha68_1   HA68    
label values ha68_2   HA68    
label values ha68_3   HA68    
label values ha68_4   HA68    
label values ha68_5   HA68    
label values ha68_6   HA68    
label values ha68_7   HA68    
label values hc2_1    HC2     
label values hc2_2    HC2     
label values hc2_3    HC2     
label values hc2_4    HC2     
label values hc2_5    HC2     
label values hc2_6    HC2     
label values hc3_1    HC3     
label values hc3_2    HC3     
label values hc3_3    HC3     
label values hc3_4    HC3     
label values hc3_5    HC3     
label values hc3_6    HC3     
label values hc4_1    HC4     
label values hc4_2    HC4     
label values hc4_3    HC4     
label values hc4_4    HC4     
label values hc4_5    HC4     
label values hc4_6    HC4     
label values hc5_1    HC5     
label values hc5_2    HC5     
label values hc5_3    HC5     
label values hc5_4    HC5     
label values hc5_5    HC5     
label values hc5_6    HC5     
label values hc6_1    HC6     
label values hc6_2    HC6     
label values hc6_3    HC6     
label values hc6_4    HC6     
label values hc6_5    HC6     
label values hc6_6    HC6     
label values hc7_1    HC7     
label values hc7_2    HC7     
label values hc7_3    HC7     
label values hc7_4    HC7     
label values hc7_5    HC7     
label values hc7_6    HC7     
label values hc8_1    HC8     
label values hc8_2    HC8     
label values hc8_3    HC8     
label values hc8_4    HC8     
label values hc8_5    HC8     
label values hc8_6    HC8     
label values hc9_1    HC9     
label values hc9_2    HC9     
label values hc9_3    HC9     
label values hc9_4    HC9     
label values hc9_5    HC9     
label values hc9_6    HC9     
label values hc10_1   HC10    
label values hc10_2   HC10    
label values hc10_3   HC10    
label values hc10_4   HC10    
label values hc10_5   HC10    
label values hc10_6   HC10    
label values hc11_1   HC11    
label values hc11_2   HC11    
label values hc11_3   HC11    
label values hc11_4   HC11    
label values hc11_5   HC11    
label values hc11_6   HC11    
label values hc12_1   HC12    
label values hc12_2   HC12    
label values hc12_3   HC12    
label values hc12_4   HC12    
label values hc12_5   HC12    
label values hc12_6   HC12    
label values hc13_1   HC13    
label values hc13_2   HC13    
label values hc13_3   HC13    
label values hc13_4   HC13    
label values hc13_5   HC13    
label values hc13_6   HC13    
label values hc15_1   HC15    
label values hc15_2   HC15    
label values hc15_3   HC15    
label values hc15_4   HC15    
label values hc15_5   HC15    
label values hc15_6   HC15    
label values hc27_1   HC27    
label values hc27_2   HC27    
label values hc27_3   HC27    
label values hc27_4   HC27    
label values hc27_5   HC27    
label values hc27_6   HC27    
label values hc30_1   HC30    
label values hc30_2   HC30    
label values hc30_3   HC30    
label values hc30_4   HC30    
label values hc30_5   HC30    
label values hc30_6   HC30    
label values hc31_1   HC31    
label values hc31_2   HC31    
label values hc31_3   HC31    
label values hc31_4   HC31    
label values hc31_5   HC31    
label values hc31_6   HC31    
label values hc33_1   HC33    
label values hc33_2   HC33    
label values hc33_3   HC33    
label values hc33_4   HC33    
label values hc33_5   HC33    
label values hc33_6   HC33    
label values hc51_1   HC51    
label values hc51_2   HC51    
label values hc51_3   HC51    
label values hc51_4   HC51    
label values hc51_5   HC51    
label values hc51_6   HC51    
label values hc52_1   HC52    
label values hc52_2   HC52    
label values hc52_3   HC52    
label values hc52_4   HC52    
label values hc52_5   HC52    
label values hc52_6   HC52    
label values hc55_1   HC55    
label values hc55_2   HC55    
label values hc55_3   HC55    
label values hc55_4   HC55    
label values hc55_5   HC55    
label values hc55_6   HC55    
label values hc57_1   HC57    
label values hc57_2   HC57    
label values hc57_3   HC57    
label values hc57_4   HC57    
label values hc57_5   HC57    
label values hc57_6   HC57    
label values hc58_1   HC58    
label values hc58_2   HC58    
label values hc58_3   HC58    
label values hc58_4   HC58    
label values hc58_5   HC58    
label values hc58_6   HC58    
label values hc60_1   HC60    
label values hc60_2   HC60    
label values hc60_3   HC60    
label values hc60_4   HC60    
label values hc60_5   HC60    
label values hc60_6   HC60    
label values hc61_1   HC61    
label values hc61_2   HC61    
label values hc61_3   HC61    
label values hc61_4   HC61    
label values hc61_5   HC61    
label values hc61_6   HC61    
label values hc68_1   HC68    
label values hc68_2   HC68    
label values hc68_3   HC68    
label values hc68_4   HC68    
label values hc68_5   HC68    
label values hc68_6   HC68    
label values hc70_1   HC70    
label values hc70_2   HC70    
label values hc70_3   HC70    
label values hc70_4   HC70    
label values hc70_5   HC70    
label values hc70_6   HC70    
label values hc71_1   HC71    
label values hc71_2   HC71    
label values hc71_3   HC71    
label values hc71_4   HC71    
label values hc71_5   HC71    
label values hc71_6   HC71    
label values hc72_1   HC72    
label values hc72_2   HC72    
label values hc72_3   HC72    
label values hc72_4   HC72    
label values hc72_5   HC72    
label values hc72_6   HC72    
label values hc73_1   HC73    
label values hc73_2   HC73    
label values hc73_3   HC73    
label values hc73_4   HC73    
label values hc73_5   HC73    
label values hc73_6   HC73    
label values hb2_1    HB2     
label values hb2_2    HB2     
label values hb2_3    HB2     
label values hb2_4    HB2     
label values hb2_5    HB2     
label values hb3_1    HB3     
label values hb3_2    HB3     
label values hb3_3    HB3     
label values hb3_4    HB3     
label values hb3_5    HB3     
label values hb4_1    HB4     
label values hb4_2    HB4     
label values hb4_3    HB4     
label values hb4_4    HB4     
label values hb4_5    HB4     
label values hb5_1    HB5     
label values hb5_2    HB5     
label values hb5_3    HB5     
label values hb5_4    HB5     
label values hb5_5    HB5     
label values hb6_1    HB6     
label values hb6_2    HB6     
label values hb6_3    HB6     
label values hb6_4    HB6     
label values hb6_5    HB6     
label values hb11_1   HB11    
label values hb11_2   HB11    
label values hb11_3   HB11    
label values hb11_4   HB11    
label values hb11_5   HB11    
label values hb12_1   HB12    
label values hb12_2   HB12    
label values hb12_3   HB12    
label values hb12_4   HB12    
label values hb12_5   HB12    
label values hb12a_1  HB12A   
label values hb12a_2  HB12A   
label values hb12a_3  HB12A   
label values hb12a_4  HB12A   
label values hb12a_5  HB12A   
label values hb12b_1  HB12B   
label values hb12b_2  HB12B   
label values hb12b_3  HB12B   
label values hb12b_4  HB12B   
label values hb12b_5  HB12B   
label values hb13_1   HB13    
label values hb13_2   HB13    
label values hb13_3   HB13    
label values hb13_4   HB13    
label values hb13_5   HB13    
label values hb33_1   HB33    
label values hb33_2   HB33    
label values hb33_3   HB33    
label values hb33_4   HB33    
label values hb33_5   HB33    
label values hb35_1   HB35    
label values hb35_2   HB35    
label values hb35_3   HB35    
label values hb35_4   HB35    
label values hb35_5   HB35    
label values hb40_1   HB40    
label values hb40_2   HB40    
label values hb40_3   HB40    
label values hb40_4   HB40    
label values hb40_5   HB40    
label values hb41_1   HB41    
label values hb41_2   HB41    
label values hb41_3   HB41    
label values hb41_4   HB41    
label values hb41_5   HB41    
label values hb50_1   HB50    
label values hb50_2   HB50    
label values hb50_3   HB50    
label values hb50_4   HB50    
label values hb50_5   HB50    
label values hb51_1   HB51    
label values hb51_2   HB51    
label values hb51_3   HB51    
label values hb51_4   HB51    
label values hb51_5   HB51    
label values hb52_1   HB52    
label values hb52_2   HB52    
label values hb52_3   HB52    
label values hb52_4   HB52    
label values hb52_5   HB52    
label values hb55_1   HB55    
label values hb55_2   HB55    
label values hb55_3   HB55    
label values hb55_4   HB55    
label values hb55_5   HB55    
label values hb57_1   HB57    
label values hb57_2   HB57    
label values hb57_3   HB57    
label values hb57_4   HB57    
label values hb57_5   HB57    
label values hb58_1   HB58    
label values hb58_2   HB58    
label values hb58_3   HB58    
label values hb58_4   HB58    
label values hb58_5   HB58    
label values hb60_1   HB60    
label values hb60_2   HB60    
label values hb60_3   HB60    
label values hb60_4   HB60    
label values hb60_5   HB60    
label values hb61_1   HB61    
label values hb61_2   HB61    
label values hb61_3   HB61    
label values hb61_4   HB61    
label values hb61_5   HB61    
label values hb63_1   HB63    
label values hb63_2   HB63    
label values hb63_3   HB63    
label values hb63_4   HB63    
label values hb63_5   HB63    
label values hb64_1   HB64    
label values hb64_2   HB64    
label values hb64_3   HB64    
label values hb64_4   HB64    
label values hb64_5   HB64    
label values hb65_1   HB65    
label values hb65_2   HB65    
label values hb65_3   HB65    
label values hb65_4   HB65    
label values hb65_5   HB65    
label values hb66_1   HB66    
label values hb66_2   HB66    
label values hb66_3   HB66    
label values hb66_4   HB66    
label values hb66_5   HB66    
label values hb68_1   HB68    
label values hb68_2   HB68    
label values hb68_3   HB68    
label values hb68_4   HB68    
label values hb68_5   HB68    
