infix using "C:\COUNTRIES\LS61\LSPR61FL.dct"

label variable hhid     "Case Identification"
label variable hvidx    "Line number"
label variable hv000    "Country code and phase"
label variable hv001    "Cluster number"
label variable hv002    "Household number"
label variable hv003    "Respondent's line number"
label variable hv004    "Ultimate area unit"
label variable hv005    "Sample weight"
label variable hv006    "Month of interview"
label variable hv007    "Year of interview"
label variable hv008    "Date of interview (CMC)"
label variable hv009    "Number of household members"
label variable hv010    "Number of eligible women in HH"
label variable hv011    "Number of eligible men in HH"
label variable hv012    "Number of de jure members"
label variable hv013    "Number of de facto members"
label variable hv014    "Number of children 5 and under"
label variable hv015    "Result of household interview"
label variable hv016    "Day of interview"
label variable hv017    "Number of visits"
label variable hv018    "Interviewer identification"
label variable hv019    "NA - Keyer identification"
label variable hv020    "Ever-married sample"
label variable hv021    "Primary sampling unit"
label variable hv022    "Sample stratum number"
label variable hv023    "Sample domain"
label variable hv024    "Region"
label variable hv025    "Type of place of residence"
label variable hv026    "NA - Place of residence"
label variable hv027    "Selection for male/husb. int."
label variable hv028    "Sample weight for male subsamp"
label variable hv030    "Field supervisor"
label variable hv031    "NA - Field editor"
label variable hv032    "NA - Office editor"
label variable hv033    "NA - Ultimate area selection prob."
label variable hv035    "Number of eligible children for height & weight"
label variable hv040    "Cluster altitude in meters"
label variable hv041    "Total adults measured"
label variable hv042    "Selection for hemoglobin"
label variable hv043    "NA - Selection for women's status module"
label variable hv044    "NA - Selection for domestic violence module"
label variable hv201    "Source of drinking water"
label variable hv202    "Source of non-drinking water"
label variable hv204    "Time to get to water source"
label variable hv205    "Type of toilet facility"
label variable hv206    "Has electricity"
label variable hv207    "Has radio"
label variable hv208    "Has television"
label variable hv209    "Has refrigerator"
label variable hv210    "Has bicycle"
label variable hv211    "Has motorcycle/scooter"
label variable hv212    "Has car/truck"
label variable hv213    "Main floor material"
label variable hv214    "Main wall material"
label variable hv215    "Main roof material"
label variable hv216    "Rooms used for sleeping"
label variable hv217    "Relationship structure"
label variable hv218    "Line number of head of househ."
label variable hv219    "Sex of head of household"
label variable hv220    "Age of head of household"
label variable hv221    "Has a landline telephone"
label variable hv225    "Share toilet with other households"
label variable hv226    "Type of cooking fuel"
label variable hv227    "NA - Have bednet for sleeping"
label variable hv228    "NA - Children under 5 slept under bednet last night"
label variable hv234    "Test salt for Iodine"
label variable hv235    "Location of source for water"
label variable hv236    "Person fetching water"
label variable hv237    "Anything done to water to make safe to drink"
label variable hv237a   "Water usually treated by: boil"
label variable hv237b   "Water usually treated by: add bleach/chlorine"
label variable hv237c   "Water usually treated by: strain through a cloth"
label variable hv237d   "Water usually treated by: use water filter"
label variable hv237e   "Water usually treated by: solar disinfection"
label variable hv237f   "Water usually treated by: let it stand and settle"
label variable hv237g   "NA - Water usually treated by: CS"
label variable hv237h   "NA - Water usually treated by: CS"
label variable hv237i   "NA - Water usually treated by: CS"
label variable hv237j   "NA - Water usually treated by: CS"
label variable hv237k   "NA - Water usually treated by: CS"
label variable hv237x   "Water usually treated by: other"
label variable hv237z   "Water usually treated by: don't know"
label variable hv238    "Number of households sharing toilet"
label variable hv239    "Food cooked on stove or open fire"
label variable hv240    "Household has a chimney, hood or neither"
label variable hv241    "Food cooked in the house / in separate building / outdoors"
label variable hv242    "Household has separate room used as kitchen"
label variable hv243a   "Has a mobile telephone"
label variable hv243b   "Has a watch"
label variable hv243c   "Has an animal-drawn cart"
label variable hv243d   "NA - Has a boat with a motor"
label variable hv244    "Own land usable for agriculture"
label variable hv245    "Hectares for agricultural land"
label variable hv246    "Livestock, herds or farm animals"
label variable hv246a   "Cattle own"
label variable hv246b   "Cows, bulls own"
label variable hv246c   "Horses, donkeys, mules own"
label variable hv246d   "Goats own"
label variable hv246e   "Sheep own"
label variable hv246f   "Chickens own"
label variable hv246g   "CS own"
label variable hv246h   "Owns pigs (CS)"
label variable hv246i   "Owns improved pigs (CS)"
label variable hv246j   "Owns rabbits (CS)"
label variable hv246k   "NA - CS own"
label variable hv247    "Owns a bank account"
label variable hv248    "NA - Number of sick people 18-59"
label variable hv249    "NA - Member of the HH died last 12 months"
label variable hv250    "NA - Number of members who died last 12 months"
label variable hv251    "NA - Number of orphans and vulnerable children"
label variable hv270    "Wealth index"
label variable hv271    "Wealth index factor score (5 decimals)"
label variable hml1     "NA - Number of mosquito nets"
label variable hml1a    "NA - Number of mosquito nets with specific information"
label variable hml2     "NA - Number of children under bednet previous night"
label variable shzone   "Lesotho Ecological Zone"
label variable sh111b   "Battery or generator"
label variable sh111h   "Bed/mattress"
label variable sh111i   "Computer"
label variable sh111j   "Internet access"
label variable sh127r   "Region of health facility"
label variable sh127    "Nearest health facility"
label variable sh128    "Mode of transport to nearest health facility"
label variable sh129h   "Time taken to nearest health facility in hours"
label variable sh129m   "Time taken to nearest health facility in minutes"
label variable hv101    "Relationship to head"
label variable hv102    "Usual resident"
label variable hv103    "Slept last night"
label variable hv104    "Sex of household member"
label variable hv105    "Age of household members"
label variable hv106    "Highest educational level"
label variable hv107    "Highest year of education"
label variable hv108    "Education in single years"
label variable hv109    "Educational attainment"
label variable hv110    "NA - Member still in school"
label variable hv111    "Mother alive"
label variable hv112    "Mother's line number"
label variable hv113    "Father alive"
label variable hv114    "Father's line number"
label variable hv115    "Current marital status"
label variable hv116    "Currently, formerly, never m."
label variable hv117    "Eligibility for female interview"
label variable hv118    "Eligibility for male interview"
label variable hv120    "Children eligibility for height/weight and hemoglobin"
label variable hv121    "Member attended school during current school year"
label variable hv122    "Educational level during current school year"
label variable hv123    "Grade of education during current school year"
label variable hv124    "Education in single years - current school year"
label variable hv125    "NA - Member attended school during previous school year"
label variable hv126    "NA - Educational level during previous school year"
label variable hv127    "NA - Grade of education during previous school year"
label variable hv128    "NA - Education in single years - previous school year"
label variable hv129    "School attendance status"
label variable hv130    "NA - Member has been very sick for 3+ months last year"
label variable hv131    "NA - Mother has been very sick for 3+ months last year"
label variable hv132    "NA - Father has been very sick for 3+ months last year"
label variable hv133    "NA - Mother/father dead or been very sick for 3+ months"
label variable hv134    "NA - Both parents alive"
label variable hv135    "NA - Has brothers/sisters under 18 of the same father and mother"
label variable hv136    "NA - Brothers/sisters under 18 that don't live in household"
label variable hv137    "NA - Member has a blanket"
label variable hv138    "NA - Member has a pair of shoes"
label variable hv139    "NA - Member has 2+ sets of clothes"
label variable hv140    "NA - Member has a birth certificate"
label variable idxh4    "Index to household schedule"
label variable sh06     "Country member is living in"
label variable sh07     "How long member has lived in country"
label variable sh19a    "Level of education attended"
label variable sh21a    "Level of education attended in current school year"
label variable sh19aa   "Country specific education categories used in reports"
label variable ha0      "Index to household schedule"
label variable ha1      "Women's age in years"
label variable ha2      "Respondent's weight (kilos-1d)"
label variable ha3      "Respondent's height (cms-1d)"
label variable ha4      "Ht/A Percentile (resp.)"
label variable ha5      "Ht/A Standard deviations (resp"
label variable ha6      "Ht/A Percent ref. median (resp"
label variable ha11     "Wt/Ht Std deviations(resp) DHS"
label variable ha12     "Wt/Ht Percent ref. median (DHS"
label variable ha12a    "Wt/Ht Percent ref. median (Fog"
label variable ha12b    "Wt/Ht Percent ref. median (WHO"
label variable ha13     "Result of measurement of resp."
label variable ha32     "Date of birth (cmc)"
label variable ha33     "Completeness of information"
label variable ha35     "Smoking"
label variable ha40     "Body mass index for respondent"
label variable ha41     "Rohrer's index for respondent"
label variable ha50     "Under age 18"
label variable ha51     "Line no. of parent/caretaker"
label variable ha52     "Read consent statement"
label variable ha53     "Hemoglobin level (g/dl - 1 decimal)"
label variable ha54     "Currently pregnant"
label variable ha55     "Result of measuring (Hemoglobin)"
label variable ha56     "Hemoglobin level adjusted by altitude (g/dl - 1 decimal)"
label variable ha57     "Anemia level"
label variable ha58     "NA - Agrees to referral"
label variable ha60     "Marital status"
label variable ha61     "Read consent statement (HIV)"
label variable ha62     "Blood sample ID number"
label variable ha63     "Result of measuring (HIV)"
label variable ha64     "NA - Consent for additional tests"
label variable ha65     "Result of woman individual interview"
label variable ha66     "Woman's highest educational level"
label variable ha67     "Woman's highest year of education"
label variable ha68     "Highest educational level (CS for preliminary & final report)"
label variable ha69     "HIV weight (6 decimals)"
label variable hc0      "Index to household schedule"
label variable hc1      "Age in months"
label variable hc2      "Weight in kilograms (1 dec.)"
label variable hc3      "Height in centimeters (1 dec.)"
label variable hc4      "Ht/A Percentile"
label variable hc5      "Ht/A Standard deviations"
label variable hc6      "Ht/A Percent of ref. median"
label variable hc7      "Wt/A Percentile"
label variable hc8      "Wt/A Standard deviations"
label variable hc9      "Wt/A Percent of ref. median"
label variable hc10     "Wt/Ht Percentile"
label variable hc11     "Wt/Ht Standard deviations"
label variable hc12     "Wt/Ht Percent of ref. median"
label variable hc13     "Result of measurement"
label variable hc15     "Height: lying or standing"
label variable hc16     "Day of birth of child"
label variable hc17     "Date measured (day)"
label variable hc18     "Date measured (month)"
label variable hc19     "Date measured (year)"
label variable hc27     "Sex"
label variable hc30     "Month of birth of child"
label variable hc31     "Year of birth of child"
label variable hc32     "Date of birth (cmc)"
label variable hc33     "Completeness of information"
label variable hc51     "Line no. of parent/caretaker"
label variable hc52     "Read consent statement"
label variable hc53     "Hemoglobin level (g/dl - 1 decimal)"
label variable hc55     "Result of measuring (Hemoglobin)"
label variable hc56     "Hemoglobin level adjusted by altitude (g/dl - 1 decimal)"
label variable hc57     "Anemia level"
label variable hc58     "NA - Agrees to referral"
label variable hc60     "Mother's line number from woman's questionnaire"
label variable hc61     "Mother's highest educational level"
label variable hc62     "Mother's highest year of education"
label variable hc63     "Preceding birth interval"
label variable hc64     "Birth order number"
label variable hc68     "Highest educational level (CS for preliminary & final report)"
label variable hc70     "Ht/A Standard deviations (according to WHO)"
label variable hc71     "Wt/A Standard deviations (according to WHO)"
label variable hc72     "Wt/Ht Standard deviations (according to WHO)"
label variable hc73     "BMI Standard deviations (according to WHO)"
label variable hb0      "Index to household schedule"
label variable hb1      "Men's age in years"
label variable hb2      "Respondent's weight (kilos-1d)"
label variable hb3      "Respondent's height (cms-1d)"
label variable hb4      "Ht/A Percentile (resp.)"
label variable hb5      "Ht/A Standard deviations (resp"
label variable hb6      "Ht/A Percent ref. median (resp"
label variable hb11     "Wt/Ht Std deviations(resp) DHS"
label variable hb12     "Wt/Ht Percent ref. median (DHS"
label variable hb12a    "Wt/Ht Percent ref. median (Fog"
label variable hb12b    "Wt/Ht Percent ref. median (WHO"
label variable hb13     "Result of measurement of resp."
label variable hb32     "Date of birth (cmc)"
label variable hb33     "Completeness of information"
label variable hb35     "Smoking"
label variable hb40     "Body mass index for respondent"
label variable hb41     "Rohrer's index for respondent"
label variable hb50     "Under age 18"
label variable hb51     "Line no. of parent/caretaker"
label variable hb52     "Read consent statement"
label variable hb53     "Hemoglobin level (g/dl - 1 decimal)"
label variable hb55     "Result of measuring (Hemoglobin)"
label variable hb56     "Hemoglobin level adjusted by altitude (g/dl - 1 decimal)"
label variable hb57     "Anemia level"
label variable hb58     "NA - Agrees to referral"
label variable hb60     "Marital status"
label variable hb61     "Read consent statement (HIV)"
label variable hb62     "Blood sample ID number"
label variable hb63     "Result of measuring (HIV)"
label variable hb64     "NA - Consent for additional tests"
label variable hb65     "Result of man individual interview"
label variable hb66     "Man's highest educational level"
label variable hb67     "Man's highest year of education"
label variable hb68     "Highest educational level (CS for preliminary & final report)"
label variable hb69     "HIV weight (6 decimals)"

#delimit ;
label define HV015   
     1 "Completed"
     2 "HH present, no resp"
     3 "HH absent"
     4 "Postponed"
     5 "Refused"
     6 "Dwelling vacant"
     7 "Dwelling destroyed"
     8 "Dwelling not found"
     9 "Other"
;
label define HV020   
     0 "All woman sample"
     1 "Ever married sample"
;
label define HV022   
     1 "Butha-Bothe : Rural"
     2 "Butha-Bothe : Urban"
     3 "Leribe : Rural"
     4 "Leribe : Urban"
     5 "Berea : Rural"
     6 "Berea : Urban"
     7 "Maseru : Rural"
     8 "Maseru : Urban"
     9 "Mafeteng : Rural"
    10 "Mafeteng : Urban"
    11 "Mohale's Hoek : Rural"
    12 "Mohale's Hoek : Urban"
    13 "Quthing : Rural"
    14 "Quthing : Urban"
    15 "Qacha's Nek : Rural"
    16 "Qacha's Nek : Urban"
    17 "Mokhotlong : Rural"
    18 "Mokhotlong : Urban"
    19 "Thaba Tseka : Rural"
    20 "Thaba Tseka : Urban"
;
label define HV023   
     1 "Butha-Bothe : Rural"
     2 "Butha-Bothe : Urban"
     3 "Leribe : Rural"
     4 "Leribe : Urban"
     5 "Berea : Rural"
     6 "Berea : Urban"
     7 "Maseru : Rural"
     8 "Maseru : Urban"
     9 "Mafeteng : Rural"
    10 "Mafeteng : Urban"
    11 "Mohale's Hoek : Rural"
    12 "Mohale's Hoek : Urban"
    13 "Quthing : Rural"
    14 "Quthing : Urban"
    15 "Qacha's Nek : Rural"
    16 "Qacha's Nek : Urban"
    17 "Mokhotlong : Rural"
    18 "Mokhotlong : Urban"
    19 "Thaba Tseka : Rural"
    20 "Thaba Tseka : Urban"
;
label define HV024   
     1 "Butha-Bothe"
     2 "Leribe"
     3 "Berea"
     4 "Maseru"
     5 "Mafeteng"
     6 "Mohale's Hoek"
     7 "Quthing"
     8 "Qacha's-Nek"
     9 "Mokhotlong"
    10 "Thaba-Tseka"
;
label define HV025   
     1 "Urban"
     2 "Rural"
;
label define HV026   
     0 "Capital, large city"
     1 "Small city"
     2 "Town"
     3 "Countryside"
;
label define HV027   
     0 "Not selected"
     1 "Men's survey"
     2 "Husband's survey"
;
label define HV042   
     0 "Not selected"
     1 "Selected"
;
label define HV043   
     0 "Household not selected"
     1 "Household selected"
;
label define HV044   
     0 "Household not selected"
     1 "Household selected"
;
label define HV201   
    10 "PIPED WATER"
    11 "Piped into dwelling"
    12 "Piped to yard/plot"
    13 "Public tap/standpipe"
    20 "TUBE WELL WATER"
    21 "Tube well or borehole"
    30 "DUG WELL (OPEN/PROTECTED)"
    31 "Protected well"
    32 "Unprotected well"
    40 "SURFACE WATER"
    41 "Protected spring"
    42 "Unprotected spring"
    43 "River/stream"
    44 "Dam/lake/pond"
    51 "Rainwater"
    61 "Tanker truck"
    62 "Cart with small tank"
    71 "Bottled water"
    96 "Other"
;
label define HV202   
    10 "PIPED WATER"
    11 "Piped into dwelling"
    12 "Piped to yard/plot"
    13 "Public tap/standpipe"
    20 "TUBE WELL WATER"
    21 "Tube well or borehole"
    30 "DUG WELL (OPEN/PROTECTED)"
    31 "Protected well"
    32 "Unprotected well"
    40 "SURFACE WATER"
    41 "Protected spring"
    42 "Unprotected spring"
    43 "River/stream"
    44 "Dam/lake/pond"
    51 "Rainwater"
    61 "Tanker truck"
    62 "Cart with small tank"
    71 "Bottled water"
    96 "Other"
;
label define HV204   
   996 "On premises"
   998 "Don't know"
;
label define HV205   
    10 "Flush toilet"
    11 "Flush to piped sewer system"
    12 "Flush to septic tank"
    13 "Flush to pit latrine"
    14 "Flush to somewhere else"
    15 "Flush, don't know where"
    20 "Pit toilet latrine"
    21 "Pit latrine ventilated improved pit latrine"
    22 "Pit latrine with slab"
    23 "Pit latrine without slab/ open pit"
    30 "No facility"
    31 "No facility/bush/field"
    41 "Composting toilet"
    42 "Bucket toilet"
    96 "OTHER"
;
label define HV206   
     0 "No"
     1 "Yes"
;
label define HV207   
     0 "No"
     1 "Yes"
;
label define HV208   
     0 "No"
     1 "Yes"
;
label define HV209   
     0 "No"
     1 "Yes"
;
label define HV210   
     0 "No"
     1 "Yes"
;
label define HV211   
     0 "No"
     1 "Yes"
;
label define HV212   
     0 "No"
     1 "Yes"
;
label define HV213   
    10 "NATURAL"
    11 "Natural floor mud/earth"
    20 "RUDIMENTARY"
    21 "Rudimentary floor wood planks"
    30 "FINISHED"
    31 "Finished floor parquet or polished wood"
    32 "Vinyl or asphalt strips"
    33 "Ceramic tiles"
    34 "Brick tiles"
    35 "Cement"
    36 "Carpet"
    96 "OTHER"
;
label define HV214   
    10 "NATURAL"
    11 "Natural walls cane/tree trunks"
    12 "Sod"
    20 "RUDIMENTARY"
    21 "Rudimentary walls stone with mud"
    22 "Plywood"
    23 "Cardboard"
    24 "Reused wood"
    30 "FINISHED"
    31 "Finished walls cement"
    32 "Stone with lime/cement"
    33 "Bricks"
    34 "Cement blocks"
    35 "Wood planks/shingles"
    96 "OTHER"
;
label define HV215   
    10 "NATURAL"
    11 "Natural roofing thatch/grass"
    12 "Sod"
    20 "RUDIMENTARY"
    21 "Rudimentary roofing wood planks"
    22 "Cardboard"
    30 "FINISHED"
    31 "Finished roofing metal"
    32 "Wood"
    33 "Asbestos/cement fiber"
    34 "Ceramic tiles"
    35 "Cement"
    36 "Roofing tiles"
    96 "OTHER"
;
label define HV216   
    99 "Missing"
;
label define HV217   
     0 "No adults"
     1 "One adult"
     2 "Two adults, opp. sex"
     3 "Two adults, same sex"
     4 "Three+ related adult"
     5 "Unrelated adults"
;
label define HV219   
     1 "Male"
     2 "Female"
;
label define HV220   
    97 "97+"
    98 "DK"
;
label define HV221   
     0 "No"
     1 "Yes"
;
label define HV225   
     0 "No"
     1 "Yes"
;
label define HV226   
     1 "Electricity"
     2 "LPG"
     3 "Natural gas"
     4 "Biogas"
     5 "Kerosene"
     6 "Coal, lignite"
     7 "Charcoal"
     8 "Wood"
     9 "Straw / shrubs / grass"
    10 "Agricultural crop"
    11 "Animal dung"
    95 "No food cooked in HH"
    96 "Other"
;
label define HV227   
     0 "No"
     1 "Yes"
;
label define HV228   
     0 "No"
     1 "All children"
     2 "Some children"
     3 "No bednet in HH"
;
label define HV234   
     0 "0 PPM (No Iodine)"
     7 "Below 15 PPM"
    15 "15 PPM and above"
    30 "30 PPM"
   994 "Salt not tested"
   995 "No salt in household"
;
label define HV235   
     1 "In own dwelling"
     2 "In own yard/plot"
     3 "Elsewhere"
;
label define HV236   
     1 "Adult woman"
     2 "Adult man"
     3 "Female child under 15 years old"
     4 "Male child under 15 years old"
     6 "Other"
;
label define HV237   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237A  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237B  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237C  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237D  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237E  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237F  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237G  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237H  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237I  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237J  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237K  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237X  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237Z  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV238   
    95 "10 or more households"
    98 "Don't know"
;
label define HV239   
     1 "Open fire"
     2 "Open stove"
     3 "Closed stove with chimney"
     6 "Other"
;
label define HV240   
     0 "Neither chimney or hood"
     1 "Chimney"
     2 "Hood"
;
label define HV241   
     1 "In the house"
     2 "In a separate building"
     3 "Outdoors"
     6 "Other"
;
label define HV242   
     0 "No"
     1 "Yes"
;
label define HV243A  
     0 "No"
     1 "Yes"
;
label define HV243B  
     0 "No"
     1 "Yes"
;
label define HV243C  
     0 "No"
     1 "Yes"
;
label define HV243D  
     0 "No"
     1 "Yes"
;
label define HV244   
     0 "No"
     1 "Yes"
;
label define HV245   
    95 "More than 95"
    98 "Unknown"
;
label define HV246   
     0 "No"
     1 "Yes"
;
label define HV246A  
     0 "None"
    95 "More than 95"
    98 "Unknown"
;
label define HV246B  
     0 "None"
    95 "More than 95"
    98 "Unknown"
;
label define HV246C  
     0 "None"
    95 "More than 95"
    98 "Unknown"
;
label define HV246D  
     0 "None"
    95 "More than 95"
    98 "Unknown"
;
label define HV246E  
     0 "None"
    95 "More than 95"
    98 "Unknown"
;
label define HV246F  
     0 "None"
    95 "More than 95"
    98 "Unknown"
;
label define HV246G  
     0 "None"
    95 "More than 95"
    98 "Unknown"
;
label define HV246H  
     0 "None"
    95 "More than 95"
    98 "Unknown"
;
label define HV246I  
     0 "None"
    95 "More than 95"
    98 "Unknown"
;
label define HV246J  
     0 "None"
    95 "More than 95"
    98 "Unknown"
;
label define HV246K  
     0 "None"
    95 "More than 95"
    98 "Unknown"
;
label define HV247   
     0 "No"
     1 "Yes"
;
label define HV249   
     0 "No"
     1 "Yes"
     8 "DK"
     9 "Missing"
;
label define HV250   
     8 "DK"
;
label define HV270   
     1 "Poorest"
     2 "Poorer"
     3 "Middle"
     4 "Richer"
     5 "Richest"
;
label define HML1    
    98 "Don't know"
;
label define HML2    
    99 "Missing"
;
label define SHZONE  
     1 "Lowlands"
     2 "Foothills"
     3 "Mountains"
     4 "Senqu River Valley"
;
label define SH111B  
     1 "Yes"
     0 "No"
;
label define SH111H  
     1 "Yes"
     0 "No"
;
label define SH111I  
     1 "Yes"
     0 "No"
;
label define SH111J  
     1 "Yes"
     0 "No"
;
label define SH127R  
     1 "BOTHA-BOTHE"
     2 "LERIBE"
     3 "BEREA"
     4 "MASERU"
     5 "MAFETENG"
     6 "MOHALE'S HOEK"
     7 "QUTHING"
     8 "QACHA'S-NEK"
     9 "MOKHOTLONG"
    10 "THABA TSEKA"
;
label define SH127   
 11011 "BOTHA-BOTHE GOVT HOSPITAL"
 11022 "SEBOCHE HOSPITAL"
 12012 "ST PAUL H/C"
 12021 "LINAKENG H/C"
 12031 "MOTETE H/C"
 12041 "RAMPAI H/C"
 12052 "ST PETERS H/C (MOTENG)"
 12061 "BOIKETSISO H/C"
 12071 "QHOLAQHOE H/C (MAKHUNOANE)"
 12081 "TSIME H/C"
 12091 "NGOAJANE/KHATIBE H/C"
 12101 "‘MUELA SITE H/C"
 12118 "DUAL CLINIC"
 12128 "THUSANANG H/C"
 21011 "MOTEBANG HOSPITAL"
 21022 "‘MAMOHAU MISSION HOSPITAL"
 22012 "ST ROSE H/C"
 22022 "ST MONICAS H/C"
 22032 "PONTMAIN H/C"
 22042 "MARYLAND H/C"
 22052 "OUR LADY OF LOURDES/MOSITI  H/C"
 22062 "LOUIS GERARD H/C"
 22072 "ST ANNE H/C"
 22088 "SPRINGFIELD H/C"
 22091 "PEKA H/C"
 22102 "MAHOBONG HOLY TRINITY H/C"
 22111 "SEETSA H/C"
 22122 "ST MARGRET H/C"
 22131 "MATLAMENG H/C"
 22141 "LINOTSING H/C"
 22151 "MAHOBONG H/C"
 22161 "SESHOTE H/C"
 22171 "KHABO H/C"
 22184 "MAPUTSOE H/C"
 22194 "FOBANE H/C"
 22202 "LITTLE FLOWER H/C"
 22212 "ST DENIS H/C"
 22224 "EMMANUEL H/C"
 22231 "SEPINARE H/C"
 22241 "LEJONE H/C"
 22251 "PALAMA H/C"
 22271 "THABA-PHATSOA H/C"
 31011 "BEREA GOVT HOSPITAL"
 31024 "MALUTI HOSPITAL"
 32018 "WILLIES CLINIC"
 32022 "ST MAGDALENA H/C"
 32032 "ST DAVID H/C"
 32041 "MAHLATSA H/C"
 32058 "PABALLONG PRIVATE ART CENTRE"
 32062 "IMMACULATE CONCEPTION"
 32072 "SION H/C"
 32084 "MAPHELENG H/C"
 32092 "MAQHAKA H/C (HOLY FAMILY)"
 32102 "GOOD SHEPHARD H/C"
 32112 "BETHANY MISSION H/C"
 32122 "ST THERESA (BELA-BELA) H/C"
 32131 "PILOT H/C"
 32152 "SEBEDIA H/C"
 32167 "KOLOJANE H/C"
 32171 "KOALI H/C"
 32188 "MBEYA -T.Y. PRIVATE CLINIC"
 32191 "KHUBETSOANA H/C"
 32208 "SEKAMANENG CLINIC"
 32218 "TŠENOLA PRIVATE CLINIC (MAMA'S)"
 35011 "MABOTE FILTER CLINIC"
 41013 "SCOTT MISSION HOSPITAL"
 41028 "MASERU PRIVATE HOSPITAL"
 41032 "ST JOSEPHS HOSPITAL"
 41041 "MAKOANYANE MILITARY HOSP"
 42038 "CAREWELL H/C"
 42048 "SOS H/C"
 42052 "LORETTO H/C"
 42068 "MASIANOKENG H/C"
 42071 "DOMICILLIARY H/C"
 42087 "THABA-BOSIU H/C"
 42099 "MATUKENG H/C"
 42102 "ST LEO RCC"
 42118 "MASECHABA CLINIC"
 42121 "R.L.D.F. H/C"
 42141 "THAMAE H/C"
 42154 "MASERU SDA H/C"
 42162 "PAKI H/C"
 42178 "MAHLOMPHO CLINIC"
 42188 "SEKAMANENG CLINIC"
 42198 "MAFUBE CLINIC"
 42208 "‘NELESE CLINIC"
 42211 "MATSIENG H/C"
 42218 "LEBONE CLINIC"
 42222 "ST RODRIGUE H/C"
 42232 "ST PETER CLAVER H/C (TŠOENENG)"
 42246 "ST BARNABAS H/C (MASITE)"
 42253 "MOFOKA H/C"
 42271 "SEMONKONG H/C"
 42282 "ST LEONARD H/C"
 42291 "HA SENG H/C"
 42306 "MARAKABEI H/C"
 42311 "LIKALANENG H/C"
 42322 "FATIMA/RAMABANTA H/C"
 42332 "ST BERNARD H/C"
 42342 "KOROKORO H/C (ST. JOSEPH)"
 42351 "HA-TLALI H/C"
 42362 "ST BENEDICT H/C"
 42372 "NAZARETH H/C"
 42378 "N.U.L. CLINIC"
 42381 "MASERU CHILDREN CENTER OF EXELLENCE (BAYLOR)"
 42391 "SENKATANA"
 42408 "ROSYM"
 42418 "MAKHALANYANE H/C"
 42428 "BATHOPELE H/C"
 42431 "MASERU CORRECTIONAL SERVICES H/C"
 42448 "LEQELE CLINIC"
 42458 "HEALTH CARE H/C"
 42461 "MOHALE H/C"
 42478 "LEHLAKENG H/C"
 42488 "MOLOPI CLINIC"
 42498 "MABATHO CLINIC"
 42508 "KATLEHO CLINIC"
 43011 "Q.E. II HOSPITAL"
 44011 "MOHLOMI MENTAL HOSPITAL"
 44021 "BOTS'ABELO LEPROSY HOSPITAL"
 45011 "QOALING FILTER CLINIC"
 45021 "LIKOTSI FILTER CLINIC"
 51011 "MAFETENG GOVT HOSPITAL"
 52015 "MOUNT TABOR H/C"
 52021 "TŠAKHOLO H/C"
 52031 "THABANA-MORENA H/C"
 52041 "LECO-OP H/C"
 52052 "MT OLIVET H/C"
 52062 "SAMARIA H/C"
 52071 "THABA TŠOEU H/C"
 52081 "LITŠOENENG H/C"
 52091 "SEKAMENG CLINIC"
 52101 "MALEA-LEA H/C"
 52113 "MATELILE H/C"
 52122 "EMMAUS H/C"
 52132 "MOTSEKUOA H/C"
 52147 "KENA H/C"
 52151 "MASEMOUSE H/C"
 52163 "KOLO H/C"
 52172 "ST ANDREW H/C"
 52183 "RIBANENG H/C"
 52198 "LESELI (THABANENG) CLINIC"
 52208 "MANTHATI (HA SEETSI) H/C"
 61011 "NTŠEKHE HOSPITAL"
 62011 "PHAMONG H/C"
 62021 "MPHARANE H/C"
 62032 "HOLY CROSS H/C"
 62041 "LIPHIRING H/C"
 62052 "BETHEL H/C"
 62061 "MOHALINYANE H/C"
 62071 "MOOTSINYANE H/C"
 62081 "LITHIPENG H/C"
 62092 "HA TŠEPO H/C"
 62101 "MORIFI H/C"
 62111 "NOHANA H/C"
 62121 "NKAU H/C"
 62131 "KUEBUNYANE H/C"
 62142 "MOFUMAHALI OA ROSARI  H/C"
 62161 "MOHALE’S HOEK CORRECTIONAL  SERVICES CLINIC"
 71011 "QUTHING GOVT HOSPITAL"
 72011 "TSATSANE H/C"
 72021 "MPHAKI H/C"
 72032 "ST GABRIEL H/C"
 72042 "ST MATTHEWS H/C"
 72052 "VILLA MARIA H/C"
 72061 "DILLI-DILLI H/C"
 72071 "HA MAKOAE H/C"
 72081 "MAQOKHO H/C"
 72108 "LINEO CLINIC"
 81011 "MACHABENG HOSPITAL"
 81023 "TEBELLONG HOSPITAL"
 82011 "SEHLABA-THEBE H/C"
 82022 "ST FRANCIS H/C"
 82031 "MELIKANE H/C"
 82042 "HERMITAGE H/C"
 82051 "RANKAKALA H/C"
 82061 "MATEBENG H/C"
 82073 "SEKAKE H/C"
 82082 "SACRED HEART H/C"
 82091 "LEBAKENG H/C"
 82101 "MOHLAPISO H/C"
 82118 "BOPHELONG PRIVATE"
 91011 "MOKHOTLONG HOSPITAL"
 92011 "LIBIBING H/C"
 92027 "MAPHOLANENG H/C"
 92032 "ST JAMES H/C"
 92042 "ST PETER'S H/C"
 92051 "‘MALEFILOANE H/C"
 92061 "MOLIKALIKO H/C"
 92072 "ST MARTIN H/C"
 92081 "LINAKANENG H/C"
 92091 "MOEKETSANE H/C"
 92101 "TLHANYAKU H/C"
 92118 "NALELI CLINIC"
 92128 "LETŠENG DIAMOND MINE CLINIC"
101012 "PARAY MISSION HOSPITAL"
101026 "ST JAMES MISSION  HOSPITAL"
102011 "KATSE H/C"
102023 "MOHLANAPENG H/C"
102032 "ST THERESA H/C"
102041 "THABA-TSEKA H/C"
102058 "MOHLAKENG CLINIC"
102061 "LINAKENG H/C"
102071 "HA MOKOTO H/C"
102082 "MONTMARTRE H/C"
102092 "AURAY H/C"
102106 "HA LEPHOI H/C"
102116 "HA POPA H/C"
102121 "SEHONG-HONG H/C"
102131 "BOBETE H/C"
102141 "MANAMANENG H/C"
102151 "METHALANENG H/C"
102161 "KOLBERG/KHOHLONTŠO"
102171 "SEMENANYANA H/C"
999996 "Other facility"
999998 "Facility not known"
;
label define SH128   
     1 "CAR/TRUCK/BUS/TAXI"
     2 "MOTORCYCLE/SCOOTER"
     3 "BICYCLE"
     4 "HORSE/DONKEY/MULE"
     5 "SCOTCH CART"
     6 "WALKING"
    96 "OTHER"
;
label define SH129H  
    98 "Don't know"
;
label define SH129M  
    98 "Don't know"
;
label define HV101   
     1 "Head"
     2 "Wife or husband"
     3 "Son/daughter"
     4 "Son/daughter-in-law"
     5 "Grandchild"
     6 "Parent"
     7 "Parent-in-law"
     8 "Brother/sister"
    10 "Other relative"
    11 "Adopted/foster child"
    12 "Not related"
    15 "Domestic employee (CS)"
    16 "Herdboy (CS)"
    98 "DK"
;
label define HV102   
     0 "No"
     1 "Yes"
;
label define HV103   
     0 "No"
     1 "Yes"
;
label define HV104   
     1 "Male"
     2 "Female"
;
label define HV105   
    96 "96+"
    98 "DK"
;
label define HV106   
     0 "No education, preschool"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "DK"
;
label define HV107   
    98 "DK"
;
label define HV108   
    97 "Inconsistent"
    98 "DK"
;
label define HV109   
     0 "No education"
     1 "Incomplete primary"
     2 "Complete primary"
     3 "Incomplete secondary"
     4 "Complete secondary"
     5 "Higher"
     8 "DK"
;
label define HV110   
     0 "No"
     1 "Yes"
;
label define HV111   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define HV112   
     0 "Mother not in HH"
;
label define HV113   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define HV114   
     0 "Father not in HH"
;
label define HV115   
     0 "Never married"
     1 "Married"
     2 "Living together"
     3 "Widowed"
     4 "Divorced"
     5 "Not living together"
;
label define HV116   
     0 "Never married"
     1 "Currently married"
     2 "Formerly/ever marr."
;
label define HV117   
     0 "Not eligible"
     1 "Eligible"
;
label define HV118   
     0 "Not eligible"
     1 "Eligible"
;
label define HV120   
     0 "Not eligible"
     1 "Eligible"
;
label define HV121   
     0 "No"
     1 "Currently attending"
     2 "Attended at some time"
;
label define HV122   
     0 "No education, preschool"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "DK"
;
label define HV123   
    98 "DK"
;
label define HV124   
    97 "Inconsistent"
    98 "DK"
;
label define HV125   
     0 "No"
     1 "Yes"
;
label define HV126   
     0 "No education, preschool"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "DK"
;
label define HV127   
    98 "DK"
;
label define HV128   
    97 "Inconsistent"
    98 "DK"
;
label define HV129   
     0 "Never attended"
     1 "Entered school"
     2 "Advanced"
     3 "Repeating"
     4 "Dropout"
     5 "Left school 2+ years ago"
     8 "DK"
;
label define HV130   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define HV131   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define HV132   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define HV133   
     0 "No"
     1 "Yes"
;
label define HV134   
     0 "No"
     1 "Yes"
;
label define HV135   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define HV136   
     0 "No"
     1 "Yes"
;
label define HV137   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define HV138   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define HV139   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define HV140   
     0 "Neither certificate or registered"
     1 "Has certificate"
     2 "Registered"
     8 "DK"
;
label define SH06    
     1 "Lesotho"
     2 "South Africa"
     3 "Other Country"
;
label define SH07    
     0 "Less than one year"
    98 "Don't know"
;
label define SH19A   
     0 "No education"
     1 "Primary"
     2 "After primary :vocational/tech.training"
     3 "Secondary/high"
     4 "After secondary:vocational/tech.training"
     5 "College"
     6 "Graduate/post graduate"
     8 "Don't know"
;
label define SH21A   
     0 "No education"
     1 "Primary"
     2 "After primary:vocational/tech.training"
     3 "Secondary/high"
     4 "After secondary:vocational/tech.training"
     5 "College"
     6 "Graduate/post graduate"
     8 "Don't know"
;
label define SH19AA  
     0 "No education"
     1 "Primary incomplete"
     2 "Primary complete"
     3 "Secondary+"
     8 "Don't know"
;
label define HA2     
  9994 "Not present"
  9995 "Refused"
  9996 "Other"
;
label define HA3     
  9994 "Not present"
  9995 "Refused"
  9996 "Other"
;
label define HA4     
  9998 "Flagged cases"
;
label define HA5     
  9998 "Flagged cases"
;
label define HA6     
 99998 "Flagged cases"
;
label define HA11    
  9998 "Flagged cases"
;
label define HA12    
 99998 "Flagged cases"
;
label define HA12A   
 99998 "Flagged cases"
;
label define HA12B   
 99998 "Flagged cases"
;
label define HA13    
     0 "Measured"
     3 "Not present"
     4 "Refused"
     6 "Other"
;
label define HA33    
     1 "Month and year"
     2 "Month and age -y imp"
     3 "Year and age - m imp"
     4 "Y & age - y ignored"
     5 "Year - a, m imp"
     6 "Age - y, m imp"
     7 "Month - a, y imp"
     8 "None - all imp"
;
label define HA35    
     0 "Doesn't smoke"
    80 "80+"
    94 "Smokes pipes, cigars, etc"
;
label define HA40    
  9998 "Flagged cases"
;
label define HA41    
  9998 "Flagged cases"
;
label define HA50    
     1 "Under age 18"
     2 "Age 18 or older"
;
label define HA51    
     0 "Not in household"
;
label define HA52    
     1 "Granted"
     2 "Parent/Other responsible refused"
     3 "Respondent refused"
     4 "Not present"
;
label define HA53    
   999 "Missing"
;
label define HA54    
     0 "No/don't know"
     1 "Yes"
;
label define HA55    
     0 "Measured"
     3 "Not present"
     4 "Refused"
     6 "Other"
;
label define HA56    
   999 "Missing"
;
label define HA57    
     1 "Severe"
     2 "Moderate"
     3 "Mild"
     4 "Not anemic"
;
label define HA58    
     0 "No"
     1 "Yes"
;
label define HA60    
     1 "Never in union"
     2 "Other"
;
label define HA61    
     1 "Granted"
     2 "Parent/Other responsible refused"
     3 "Respondent refused"
     4 "Sample not tested/lost/not enough DBS"
     5 "Not present"
;
label define HA63    
     1 "Blood taken"
     2 "Not present"
     3 "Refused"
     4 "Sample not tested/lost"
     5 "Not enough DBS to complete protocol"
     6 "Other"
;
label define HA64    
     1 "Granted"
     2 "Parent/Other responsible refused"
     3 "Respondent refused"
;
label define HA65    
     1 "Completed"
     2 "Not at home"
     3 "Postponed"
     4 "Refused"
     5 "Partly completed"
     6 "Incapacitated"
     7 "Other"
;
label define HA66    
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "Don't know"
;
label define HA67    
    99 "Missing"
;
label define HA68    
     0 "No education"
     1 "PRIMARY"
     2 "AFTER PRIMARY :VOCATIONAL/TECH.TRAINING"
     3 "SECONDARY/HIGH"
     4 "AFTER SECONDARY:VOCATIONAL/TECH.TRAINING"
     5 "COLLEGE"
     6 "GRADUATE/POST GRADUATE"
     8 "DON'T KNOW"
;
label define HC2     
  9994 "Not present"
  9995 "Refused"
  9996 "Other"
;
label define HC3     
  9994 "Not present"
  9995 "Refused"
  9996 "Other"
;
label define HC4     
  9998 "Flagged cases"
;
label define HC5     
  9998 "Flagged cases"
;
label define HC6     
 99998 "Flagged cases"
;
label define HC7     
  9998 "Flagged cases"
;
label define HC8     
  9998 "Flagged cases"
;
label define HC9     
 99998 "Flagged cases"
;
label define HC10    
  9998 "Flagged cases"
;
label define HC11    
  9998 "Flagged cases"
;
label define HC12    
 99998 "Flagged cases"
;
label define HC13    
     0 "Measured"
     3 "Not present"
     4 "Refused"
     6 "Other"
;
label define HC15    
     1 "Lying"
     2 "Standing"
;
label define HC16    
    99 "Missing"
;
label define HC27    
     1 "Male"
     2 "Female"
;
label define HC30    
    97 "Inconsistent"
    98 "DK"
;
label define HC31    
  9997 "Inconsistent"
  9998 "DK"
;
label define HC33    
     1 "Month and year"
     2 "Month and age"
     3 "Year and age"
     4 "Year"
     6 "Age"
     7 "Month"
     8 "None"
;
label define HC51    
     0 "Not in household"
;
label define HC52    
     1 "Granted"
     2 "Refused"
;
label define HC53    
   999 "Missing"
;
label define HC55    
     0 "Measured"
     3 "Not present"
     4 "Refused"
     6 "Other"
;
label define HC56    
   999 "Missing"
;
label define HC57    
     1 "Severe"
     2 "Moderate"
     3 "Mild"
     4 "Not anemic"
;
label define HC58    
     0 "No"
     1 "Yes"
;
label define HC60    
   993 "Mother not de facto"
   994 "Incomplete woman's interview"
   995 "Not in household"
;
label define HC61    
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "Don't know"
;
label define HC62    
    99 "Missing"
;
label define HC63    
   999 "Missing"
;
label define HC64    
    99 "Missing"
;
label define HC68    
     0 "No Education"
     1 "Primary"
     2 "After Primary :Vocational/Tech.training"
     3 "Secondary/High"
     4 "After Secondary:Vocational/Tech.training"
     5 "College"
     6 "Graduate/Post Graduate"
     8 "Don't know"
;
label define HC70    
  9996 "Height out of plausible limits"
  9997 "Age in days out of plausible limits"
  9998 "Flagged cases"
;
label define HC71    
  9996 "Height out of plausible limits"
  9997 "Age in days out of plausible limits"
  9998 "Flagged cases"
;
label define HC72    
  9996 "Height out of plausible limits"
  9997 "Age in days out of plausible limits"
  9998 "Flagged cases"
;
label define HC73    
  9996 "Height out of plausible limits"
  9997 "Age in days out of plausible limits"
  9998 "Flagged cases"
;
label define HB2     
  9994 "Not present"
  9995 "Refused"
  9996 "Other"
;
label define HB3     
  9994 "Not present"
  9995 "Refused"
  9996 "Other"
;
label define HB4     
  9998 "Flagged cases"
;
label define HB5     
  9998 "Flagged cases"
;
label define HB6     
 99998 "Flagged cases"
;
label define HB11    
  9998 "Flagged cases"
;
label define HB12    
 99998 "Flagged cases"
;
label define HB12A   
 99998 "Flagged cases"
;
label define HB12B   
 99998 "Flagged cases"
;
label define HB13    
     0 "Measured"
     3 "Not present"
     4 "Refused"
     6 "Other"
;
label define HB33    
     1 "Month and year"
     2 "Month and age -y imp"
     3 "Year and age - m imp"
     4 "Y & age - y ignored"
     5 "Year - a, m imp"
     6 "Age - y, m imp"
     7 "Month - a, y imp"
     8 "None - all imp"
;
label define HB35    
     0 "Doesn't smoke"
    80 "80+"
    94 "Smokes pipes, cigars, etc"
    98 "Don't know"
;
label define HB40    
  9998 "Flagged cases"
;
label define HB41    
  9998 "Flagged cases"
;
label define HB50    
     1 "Under age 18"
     2 "Age 18 or older"
;
label define HB51    
     0 "Not in household"
;
label define HB52    
     1 "Granted"
     2 "Parent/Other responsible refused"
     3 "Respondent refused"
     4 "Not present"
;
label define HB53    
   999 "Missing"
;
label define HB55    
     0 "Measured"
     3 "Not present"
     4 "Refused"
     6 "Other"
;
label define HB56    
   999 "Missing"
;
label define HB57    
     1 "Severe"
     2 "Moderate"
     3 "Mild"
     4 "Not anemic"
;
label define HB58    
     0 "No"
     1 "Yes"
;
label define HB60    
     1 "Never in union"
     2 "Other"
;
label define HB61    
     1 "Granted"
     2 "Parent/Other responsible refused"
     3 "Respondent refused"
     4 "Sample not tested/lost/not enough DBS"
     5 "Not present"
;
label define HB63    
     1 "Blood taken"
     2 "Not present"
     3 "Refused"
     4 "Sample not tested/lost"
     5 "Not enough DBS to complete protocol"
     6 "Other"
;
label define HB64    
     1 "Granted"
     2 "Parent/Other responsible refused"
     3 "Respondent refused"
;
label define HB65    
     1 "Completed"
     2 "Not at home"
     3 "Postponed"
     4 "Refused"
     5 "Partly completed"
     6 "Incapacitated"
     7 "Other"
;
label define HB66    
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "Don't know"
;
label define HB67    
    99 "Missing"
;
label define HB68    
     0 "No education"
     1 "PRIMARY"
     2 "AFTER PRIMARY :VOCATIONAL/TECH.TRAINING"
     3 "SECONDARY/HIGH"
     4 "AFTER SECONDARY:VOCATIONAL/TECH.TRAINING"
     5 "COLLEGE"
     6 "GRADUATE/POST GRADUATE"
     8 "DON'T KNOW"
;

#delimit cr
label values hv015    HV015   
label values hv020    HV020   
label values hv022    HV022   
label values hv023    HV023   
label values hv024    HV024   
label values hv025    HV025   
label values hv026    HV026   
label values hv027    HV027   
label values hv042    HV042   
label values hv043    HV043   
label values hv044    HV044   
label values hv201    HV201   
label values hv202    HV202   
label values hv204    HV204   
label values hv205    HV205   
label values hv206    HV206   
label values hv207    HV207   
label values hv208    HV208   
label values hv209    HV209   
label values hv210    HV210   
label values hv211    HV211   
label values hv212    HV212   
label values hv213    HV213   
label values hv214    HV214   
label values hv215    HV215   
label values hv217    HV217   
label values hv219    HV219   
label values hv220    HV220   
label values hv221    HV221   
label values hv225    HV225   
label values hv226    HV226   
label values hv227    HV227   
label values hv228    HV228   
label values hv234    HV234   
label values hv235    HV235   
label values hv236    HV236   
label values hv237    HV237   
label values hv237a   HV237A  
label values hv237b   HV237B  
label values hv237c   HV237C  
label values hv237d   HV237D  
label values hv237e   HV237E  
label values hv237f   HV237F  
label values hv237g   HV237G  
label values hv237h   HV237H  
label values hv237i   HV237I  
label values hv237j   HV237J  
label values hv237k   HV237K  
label values hv237x   HV237X  
label values hv237z   HV237Z  
label values hv238    HV238   
label values hv239    HV239   
label values hv240    HV240   
label values hv241    HV241   
label values hv242    HV242   
label values hv243a   HV243A  
label values hv243b   HV243B  
label values hv243c   HV243C  
label values hv243d   HV243D  
label values hv244    HV244   
label values hv245    HV245   
label values hv246    HV246   
label values hv246a   HV246A  
label values hv246b   HV246B  
label values hv246c   HV246C  
label values hv246d   HV246D  
label values hv246e   HV246E  
label values hv246f   HV246F  
label values hv246g   HV246G  
label values hv246h   HV246H  
label values hv246i   HV246I  
label values hv246j   HV246J  
label values hv246k   HV246K  
label values hv247    HV247   
label values hv249    HV249   
label values hv250    HV250   
label values hv270    HV270   
label values hml1     HML1    
label values shzone   SHZONE  
label values sh111b   SH111B  
label values sh111h   SH111H  
label values sh111i   SH111I  
label values sh111j   SH111J  
label values sh127r   SH127R  
label values sh127    SH127   
label values sh128    SH128   
label values sh129h   SH129H  
label values sh129m   SH129M  
label values hv101    HV101   
label values hv102    HV102   
label values hv103    HV103   
label values hv104    HV104   
label values hv105    HV105   
label values hv106    HV106   
label values hv107    HV107   
label values hv108    HV108   
label values hv109    HV109   
label values hv110    HV110   
label values hv111    HV111   
label values hv112    HV112   
label values hv113    HV113   
label values hv114    HV114   
label values hv115    HV115   
label values hv116    HV116   
label values hv117    HV117   
label values hv118    HV118   
label values hv120    HV120   
label values hv121    HV121   
label values hv122    HV122   
label values hv123    HV123   
label values hv124    HV124   
label values hv125    HV125   
label values hv126    HV126   
label values hv127    HV127   
label values hv128    HV128   
label values hv129    HV129   
label values hv130    HV130   
label values hv131    HV131   
label values hv132    HV132   
label values hv133    HV133   
label values hv134    HV134   
label values hv135    HV135   
label values hv136    HV136   
label values hv137    HV137   
label values hv138    HV138   
label values hv139    HV139   
label values hv140    HV140   
label values sh06     SH06    
label values sh07     SH07    
label values sh19a    SH19A   
label values sh21a    SH21A   
label values sh19aa   SH19AA  
label values ha2      HA2     
label values ha3      HA3     
label values ha4      HA4     
label values ha5      HA5     
label values ha6      HA6     
label values ha11     HA11    
label values ha12     HA12    
label values ha12a    HA12A   
label values ha12b    HA12B   
label values ha13     HA13    
label values ha33     HA33    
label values ha35     HA35    
label values ha40     HA40    
label values ha41     HA41    
label values ha50     HA50    
label values ha51     HA51    
label values ha52     HA52    
label values ha54     HA54    
label values ha55     HA55    
label values ha57     HA57    
label values ha58     HA58    
label values ha60     HA60    
label values ha61     HA61    
label values ha63     HA63    
label values ha64     HA64    
label values ha65     HA65    
label values ha66     HA66    
label values ha68     HA68    
label values hc2      HC2     
label values hc3      HC3     
label values hc4      HC4     
label values hc5      HC5     
label values hc6      HC6     
label values hc7      HC7     
label values hc8      HC8     
label values hc9      HC9     
label values hc10     HC10    
label values hc11     HC11    
label values hc12     HC12    
label values hc13     HC13    
label values hc15     HC15    
label values hc27     HC27    
label values hc30     HC30    
label values hc31     HC31    
label values hc33     HC33    
label values hc51     HC51    
label values hc52     HC52    
label values hc55     HC55    
label values hc57     HC57    
label values hc58     HC58    
label values hc60     HC60    
label values hc61     HC61    
label values hc68     HC68    
label values hc70     HC70    
label values hc71     HC71    
label values hc72     HC72    
label values hc73     HC73    
label values hb2      HB2     
label values hb3      HB3     
label values hb4      HB4     
label values hb5      HB5     
label values hb6      HB6     
label values hb11     HB11    
label values hb12     HB12    
label values hb12a    HB12A   
label values hb12b    HB12B   
label values hb13     HB13    
label values hb33     HB33    
label values hb35     HB35    
label values hb40     HB40    
label values hb41     HB41    
label values hb50     HB50    
label values hb51     HB51    
label values hb52     HB52    
label values hb55     HB55    
label values hb57     HB57    
label values hb58     HB58    
label values hb60     HB60    
label values hb61     HB61    
label values hb63     HB63    
label values hb64     HB64    
label values hb65     HB65    
label values hb66     HB66    
label values hb68     HB68    
