infix using "C:\COUNTRIES\LS71\LSMR71FL.dct"

label variable mcaseid  "Case Identification"
label variable mv000    "Country code and phase"
label variable mv001    "Cluster number"
label variable mv002    "Household number"
label variable mv003    "Respondent's line number"
label variable mv004    "Ultimate area unit"
label variable mv005    "Men's sample weight (6 decimals)"
label variable mv006    "Month of interview"
label variable mv007    "Year of interview"
label variable mv008    "Date of interview (CMC)"
label variable mv009    "Month of birth"
label variable mv010    "Year of birth"
label variable mv011    "Date of birth (CMC)"
label variable mv012    "Current age"
label variable mv013    "Age in 5-year groups"
label variable mv014    "Completeness of age information"
label variable mv015    "Result of interview"
label variable mv016    "Day of interview"
label variable mv021    "Primary sampling unit"
label variable mv022    "Sample stratum number"
label variable mv023    "Sample domain"
label variable mv024    "Region"
label variable mv025    "Type of place of residence"
label variable mv026    "NA - De facto place of residence"
label variable mv027    "Number of visits"
label variable mv028    "Interviewer identification"
label variable mv029    "NA - Keyer identification"
label variable mv030    "NA - Field supervisor"
label variable mv031    "NA - Field editor"
label variable mv032    "NA - Office editor"
label variable mv034_1  "Line number of wife/partner"
label variable mv034_2  "Line number of wife/partner"
label variable mv034_3  "Line number of wife/partner"
label variable mv034_4  "Line number of wife/partner"
label variable mv034_5  "Line number of wife/partner"
label variable mv034_6  "Line number of wife/partner"
label variable mv034_7  "Line number of wife/partner"
label variable mv034_8  "Line number of wife/partner"
label variable mv034a_1 "NA - Wife or partner"
label variable mv034a_2 "NA - Wife or partner"
label variable mv034a_3 "NA - Wife or partner"
label variable mv034a_4 "NA - Wife or partner"
label variable mv034a_5 "NA - Wife or partner"
label variable mv034a_6 "NA - Wife or partner"
label variable mv034a_7 "NA - Wife or partner"
label variable mv034a_8 "NA - Wife or partner"
label variable mv034b_1 "Age of wife/partner"
label variable mv034b_2 "Age of wife/partner"
label variable mv034b_3 "Age of wife/partner"
label variable mv034b_4 "Age of wife/partner"
label variable mv034b_5 "Age of wife/partner"
label variable mv034b_6 "Age of wife/partner"
label variable mv034b_7 "Age of wife/partner"
label variable mv034b_8 "Age of wife/partner"
label variable mv035    "Number of wives/partners"
label variable mv801    "Time interview started (hhmm - 24 hour clock)"
label variable mv802    "Time interview ended (hhmm - 24 hour clock)"
label variable mv803    "Length of interview in minutes"
label variable mv101    "Region"
label variable mv102    "Type of place of residence"
label variable mv103    "NA - Childhood place of residence***"
label variable mv104    "NA - Years lived in place of residence"
label variable mv105    "NA - Type of place of previous residence"
label variable mv106    "Educational level"
label variable mv107    "Highest year of education (at level in MV106)"
label variable mv130    "Religion"
label variable mv131    "NA - Ethnicity"
label variable mv133    "Total number of years of education"
label variable mv134    "NA - De facto place of residence"
label variable mv135    "Usual resident or visitor"
label variable mv136    "Number of household members (total listed)"
label variable mv138    "Number of eligible men in household (de facto)"
label variable mv149    "Educational attainment"
label variable mv150    "Relationship to household head"
label variable mv151    "Sex of household head"
label variable mv152    "Age of household head"
label variable mv155    "Literacy"
label variable mv156    "NA - Ever participated in a literacy program (excluding primary school)"
label variable mv157    "Frequency of reading newspaper or magazine"
label variable mv158    "Frequency of listening to radio"
label variable mv159    "Frequency of watching television"
label variable mv167    "Times away from home in last 12 months"
label variable mv168    "Away for more than one month in last 12 months"
label variable mv190    "Wealth index"
label variable mv191    "Wealth index factor score (5 decimals)"
label variable mv201    "Total children ever born"
label variable mv202    "Sons at home"
label variable mv203    "Daughters at home"
label variable mv204    "Sons elsewhere"
label variable mv205    "Daughters elsewhere"
label variable mv206    "Sons who have died"
label variable mv207    "Daughters who have died"
label variable mv212    "Age of respondent at 1st birth"
label variable mv213    "Partner currently pregnant"
label variable mv217    "Knowledge of ovulatory cycle"
label variable mv218    "Number of living children"
label variable mv225    "NA - Most recent pregnancy wanted***"
label variable mv245    "Number of women fathered children with"
label variable mv246    "NA - Married to mother when first child was born***"
label variable mv247    "Age of most recent child"
label variable mv248    "Antenatal check-ups for the mother of most recent child"
label variable mv249    "Respondent present during check-ups for most recent child"
label variable mv250    "Place of birth of most recent child"
label variable mv251    "NA - Reason for not delivering most recent child in health facility"
label variable mv252    "Amount a child should drink, when that child has diarrhea"
label variable mv301    "Knowledge of any contraceptive method"
label variable mv302    "NA - Ever use of any contraceptive method"
label variable m304a_01 "Type of contraceptive method"
label variable m304a_02 "Type of contraceptive method"
label variable m304a_03 "Type of contraceptive method"
label variable m304a_04 "Type of contraceptive method"
label variable m304a_05 "Type of contraceptive method"
label variable m304a_06 "Type of contraceptive method"
label variable m304a_07 "Type of contraceptive method"
label variable m304a_08 "Type of contraceptive method"
label variable m304a_09 "Type of contraceptive method"
label variable m304a_10 "Type of contraceptive method"
label variable m304a_11 "Type of contraceptive method"
label variable m304a_12 "Type of contraceptive method"
label variable m304a_13 "Type of contraceptive method"
label variable m304a_14 "Type of contraceptive method"
label variable m304a_15 "Type of contraceptive method"
label variable m304a_16 "Type of contraceptive method"
label variable m304a_17 "Type of contraceptive method"
label variable m304a_18 "Type of contraceptive method"
label variable m304a_19 "Type of contraceptive method"
label variable m304a_20 "Type of contraceptive method"
label variable mv304_01 "Knows contraceptive method"
label variable mv304_02 "Knows contraceptive method"
label variable mv304_03 "Knows contraceptive method"
label variable mv304_04 "Knows contraceptive method"
label variable mv304_05 "Knows contraceptive method"
label variable mv304_06 "Knows contraceptive method"
label variable mv304_07 "Knows contraceptive method"
label variable mv304_08 "Knows contraceptive method"
label variable mv304_09 "Knows contraceptive method"
label variable mv304_10 "Knows contraceptive method"
label variable mv304_11 "Knows contraceptive method"
label variable mv304_12 "Knows contraceptive method"
label variable mv304_13 "Knows contraceptive method"
label variable mv304_14 "Knows contraceptive method"
label variable mv304_15 "Knows contraceptive method"
label variable mv304_16 "Knows contraceptive method"
label variable mv304_17 "Knows contraceptive method"
label variable mv304_18 "Knows contraceptive method"
label variable mv304_19 "Knows contraceptive method"
label variable mv304_20 "Knows contraceptive method"
label variable mv305_01 "Ever used contraceptive method"
label variable mv305_02 "Ever used contraceptive method"
label variable mv305_03 "Ever used contraceptive method"
label variable mv305_04 "Ever used contraceptive method"
label variable mv305_05 "Ever used contraceptive method"
label variable mv305_06 "Ever used contraceptive method"
label variable mv305_07 "Ever used contraceptive method"
label variable mv305_08 "Ever used contraceptive method"
label variable mv305_09 "Ever used contraceptive method"
label variable mv305_10 "Ever used contraceptive method"
label variable mv305_11 "Ever used contraceptive method"
label variable mv305_12 "Ever used contraceptive method"
label variable mv305_13 "Ever used contraceptive method"
label variable mv305_14 "Ever used contraceptive method"
label variable mv305_15 "Ever used contraceptive method"
label variable mv305_16 "Ever used contraceptive method"
label variable mv305_17 "Ever used contraceptive method"
label variable mv305_18 "Ever used contraceptive method"
label variable mv305_19 "Ever used contraceptive method"
label variable mv305_20 "Ever used contraceptive method"
label variable mv307_01 "Contraceptive method currently used"
label variable mv307_02 "Contraceptive method currently used"
label variable mv307_03 "Contraceptive method currently used"
label variable mv307_04 "Contraceptive method currently used"
label variable mv307_05 "Contraceptive method currently used"
label variable mv307_06 "Contraceptive method currently used"
label variable mv307_07 "Contraceptive method currently used"
label variable mv307_08 "Contraceptive method currently used"
label variable mv307_09 "Contraceptive method currently used"
label variable mv307_10 "Contraceptive method currently used"
label variable mv307_11 "Contraceptive method currently used"
label variable mv307_12 "Contraceptive method currently used"
label variable mv307_13 "Contraceptive method currently used"
label variable mv307_14 "Contraceptive method currently used"
label variable mv307_15 "Contraceptive method currently used"
label variable mv307_16 "Contraceptive method currently used"
label variable mv307_17 "Contraceptive method currently used"
label variable mv307_18 "Contraceptive method currently used"
label variable mv307_19 "Contraceptive method currently used"
label variable mv307_20 "Contraceptive method currently used"
label variable mv312    "Current contraceptive method"
label variable mv313    "Current contraceptive by method type"
label variable mv323a   "NA - Brand of condom used"
label variable mv325b   "NA - Cost of condoms (in CURRENCY) last time obtained"
label variable mv372a   "NA - Interviewer shown condom package"
label variable mv384a   "On radio heard about Family Planning in the last few months"
label variable mv384b   "On TV saw about Family Planning in the last few months"
label variable mv384c   "In newspaper read about Family Planning in the last few months"
label variable mv395    "Discussed Family Planning with health worker in last few months"
label variable mv396    "NA - Possible for a breastfeeding woman to get pregnant"
label variable mv3a09b  "NA - Number of condoms did get last time"
label variable mv3b17   "Source of condoms"
label variable mv3b25a  "Contraception is woman's business, man should not worry"
label variable mv3b25b  "Women who use contraception become promiscuous"
label variable mv463a   "Smokes cigarettes"
label variable mv463b   "Smokes pipe"
label variable mv463c   "Uses chewing tobacco"
label variable mv463d   "Uses snuff"
label variable mv463e   "NA - Smokes CS"
label variable mv463f   "NA - Smokes CS"
label variable mv463g   "NA - Smokes CS"
label variable mv463x   "Smokes other"
label variable mv463z   "Smokes nothing"
label variable mv464    "Number of cigarettes in last 24 hours"
label variable mv474    "Heard of tuberculosis or TB"
label variable mv474a   "Tuberculosis spread by: air through coughing or sneezing"
label variable mv474b   "Tuberculosis spread by: sharing utensils"
label variable mv474c   "Tuberculosis spread by: touching a person with TB"
label variable mv474d   "Tuberculosis spread by: food"
label variable mv474e   "Tuberculosis spread by: sexual contact"
label variable mv474f   "Tuberculosis spread by: mosquito bites"
label variable mv474g   "NA - Tuberculosis spread by: CS"
label variable mv474h   "NA - Tuberculosis spread by: CS"
label variable mv474i   "NA - Tuberculosis spread by: CS"
label variable mv474j   "NA - Tuberculosis spread by: CS"
label variable mv474x   "Tuberculosis spread by: other"
label variable mv474z   "Don't know how tuberculosis is spread"
label variable mv475    "Tuberculosis can be cured"
label variable mv476    "Would want tuberculosis infection in family to remain secret"
label variable mv477    "Number of injections in last 12 months"
label variable mv478    "Number of injections administered by a health worker"
label variable mv479    "NA - Place where given injection by health worker"
label variable mv480    "Syringe and needle from new, unopened package"
label variable mv481    "Covered by health insurance"
label variable mv481a   "Health insurance type: mutual/community organization"
label variable mv481b   "Health insurance type: provided by employer"
label variable mv481c   "NA - Health insurance type: social security"
label variable mv481d   "Health insurance type: private/commercially purchased"
label variable mv481e   "NA - Health insurance type: CS"
label variable mv481f   "NA - Health insurance type: CS"
label variable mv481g   "NA - Health insurance type: CS"
label variable mv481h   "NA - Health insurance type: CS"
label variable mv481x   "Health insurance type: other"
label variable mv482a   "NA - Arrange care of biological children under age 18***"
label variable mv482b   "NA - Primary caregiver of children under age 18***"
label variable mv482c   "NA - Arrange care of non-biological children < 18***"
label variable mv483    "Respondent circumcised"
label variable mv483a   "Age at circumcision"
label variable mv483b   "NA - Who performed the circumcision"
label variable mv483c   "NA - Place where circumcision was done"
label variable mv501    "Current marital status"
label variable mv502    "Currently/formerly/never in union"
label variable mv503    "Number of unions"
label variable mv504    "Currently residing with wife/partner"
label variable mv505    "Number of wives/partners"
label variable mv507    "Month of first cohabitation"
label variable mv508    "Year of first cohabitation"
label variable mv509    "Date of first cohabitation (CMC)"
label variable mv510    "Completeness of date information in MV509"
label variable mv511    "Age at first cohabitation"
label variable mv512    "Years since first cohabitation"
label variable mv513    "Cohabitation duration (grouped)"
label variable mv525    "Age at first sex"
label variable mv527    "Time since last sex"
label variable mv528    "Time since last sex (in days)"
label variable mv529    "Time since last sex (in months)"
label variable mv531    "Age at first sex (imputed)"
label variable mv532    "Flag for MV531"
label variable mv535    "Ever been married or in union"
label variable mv536    "Recent sexual activity"
label variable mv541    "NA - Intends to wait until marriage to have sex"
label variable mv602    "Fertility preference"
label variable mv603    "Preferred waiting time for birth of a/another child"
label variable mv604    "Preferred waiting time for birth of a/another child (grouped)"
label variable mv605    "Desire for more children"
label variable mv613    "Ideal number of children"
label variable mv614    "Ideal number of children (grouped)"
label variable mv616    "Desired time for future birth"
label variable mv621    "NA - Wife's desire for children***"
label variable mv627    "Ideal number of boys"
label variable mv628    "Ideal number of girls"
label variable mv629    "Ideal number of either sex"
label variable mv631    "NA - Problem if wife became pregnant***"
label variable mv633a   "NA - Wife justified refusing sex: husband has STI"
label variable mv633b   "Wife justified refusing sex: husband has other women"
label variable mv633c   "NA - Wife justified refusing sex: recent birth"
label variable mv633d   "NA - Wife justified refusing sex: tired, not in mood"
label variable mv633e   "NA - Wife justified refusing sex: CS reason"
label variable mv633f   "NA - Wife justified refusing sex: CS reason"
label variable mv633g   "NA - Wife justified refusing sex: CS reason"
label variable mv634a   "NA - Wife refuses to have sex, husband has right to: get angry"
label variable mv634b   "NA - Wife refuses to have sex, husband has right to: refuse financial support"
label variable mv634c   "NA - Wife refuses to have sex, husband has right to: use force for sex"
label variable mv634d   "NA - Wife refuses to have sex, husband has right to: have sex with another women"
label variable mv714    "Currently working"
label variable mv714a   "Have a job, but currently absent"
label variable mv716    "Occupation"
label variable mv717    "Occupation (grouped)"
label variable mv719    "NA - Works for family, others, self"
label variable mv721    "NA - Works at home or away"
label variable mv731    "Worked in last 12 months"
label variable mv732    "Employment all year/seasonal"
label variable mv739    "Person who usually decides how to spend respondent's earnings"
label variable mv740    "NA - Type of land where respondent works"
label variable mv741    "Type of earnings from respondent's work"
label variable mv743a   "Person who should have greater say: respondent's health care"
label variable mv743b   "Person who should have greater say: large household purchases"
label variable mv743c   "NA - Person who should have greater say: daily household purchases"
label variable mv743d   "NA - Person who should have greater say: visits to family or relatives"
label variable mv743e   "NA - Person who should have greater say: food to be cooked each day"
label variable mv743f   "NA - Person who should have greater say: deciding what to do with money wife ear"
label variable mv743g   "NA - Person who should have greater say: deciding how many children to have"
label variable mv744a   "Beating justified: wife goes out without telling husband"
label variable mv744b   "Beating justified: wife neglects the children"
label variable mv744c   "Beating justified: wife argues with husband"
label variable mv744d   "Beating justified: wife refuses to have sex with husband"
label variable mv744e   "Beating justified: wife burns food"
label variable mv745a   "Owns a house alone or jointly"
label variable mv745b   "Owns land alone or jointly"
label variable mv747a   "NA - Childbearing is a woman's concern"
label variable mv747b   "NA - Important for mother/child health to get assistance at delivery"
label variable mv750    "Ever heard of a Sexually Transmitted Infection (STI)"
label variable mv751    "Ever heard of AIDS"
label variable mv754bp  "NA - Reduce risk of getting HIV: do not have sex at all"
label variable mv754cp  "Reduce risk of getting HIV: always use condoms during sex"
label variable mv754dp  "Reduce risk of getting HIV: have 1 sex partner only, who has no other partners"
label variable mv754jp  "Can get HIV from mosquito bites"
label variable mv754wp  "Can get HIV by sharing food with person who has AIDS"
label variable mv756    "A healthy looking person can have HIV"
label variable mv761    "Condom used during last sex with most recent partner"
label variable mv761b   "Condom used during last sex with 2nd to most recent partner"
label variable mv761c   "Condom used during last sex with 3rd to most recent partner"
label variable mv762aa  "Source for condoms: government hospital"
label variable mv762ab  "Source for condoms: (Public) Government Health center"
label variable mv762ac  "Source for condoms: (Public) Government Health Post"
label variable mv762ad  "Source for condoms: (Public) Family Planning Clinic"
label variable mv762ae  "Source for condoms: Other Public Sector"
label variable mv762af  "Source for condoms: (Private) Lesotho Planned Parenthood"
label variable mv762ag  "Source for condoms: (Private) PSI/New Start Center"
label variable mv762ah  "Source for condoms: (Private) CHAL hospital"
label variable mv762ai  "Source for condoms: (Private) CHAL health center"
label variable mv762aj  "Source for condoms: private hospital/clinic"
label variable mv762ak  "Source for condoms: (Private) CHAL health post"
label variable mv762al  "Source for condoms: private doctor"
label variable mv762am  "Source for condoms: pharmacy"
label variable mv762an  "Source for condoms: (Private) Red Cross Health Center"
label variable mv762ao  "Source for condoms: (Private) CBD"
label variable mv762ap  "Source for condoms: (Private) Village Health Worker"
label variable mv762aq  "Source for condoms: (Private) Support Groups"
label variable mv762ar  "Source for condoms: Facility Outside Lesotho"
label variable mv762as  "Source for condoms: (Private) Other"
label variable mv762at  "Source for condoms: (Other) Shop"
label variable mv762au  "Source for condoms: (Other) Church"
label variable mv762av  "Source for condoms: (Other) Peer educators"
label variable mv762aw  "Source for condoms: (Other) Friend/relative"
label variable mv762ax  "Source for condoms: other"
label variable mv762az  "Don't know any source for condoms"
label variable mv762ba  "Source for female condoms: government hospital"
label variable mv762bb  "Source for female condoms: (Public) Government Health center"
label variable mv762bc  "Source for female condoms: (Public) Government Health Post"
label variable mv762bd  "Source for female condoms: (Public) Family Planning Clinic"
label variable mv762be  "Source for female condoms: Other Public Sector"
label variable mv762bf  "Source for female condoms: (Private) Lesotho Planned Parenthood"
label variable mv762bg  "Source for female condoms: (Private) PSI/New Start Center"
label variable mv762bh  "Source for female condoms: (Private) CHAL hospital"
label variable mv762bi  "Source for female condoms: (Private) CHAL health center"
label variable mv762bj  "Source for female condoms: private hospital/clinic"
label variable mv762bk  "Source for female condoms: (Private) CHAL health post"
label variable mv762bl  "Source for female condoms: private doctor"
label variable mv762bm  "Source for female condoms: pharmacy"
label variable mv762bn  "Source for female condoms: (Private) Red Cross Health Center"
label variable mv762bo  "Source for female condoms: (Private) CBD"
label variable mv762bp  "Source for female condoms: (Private) Village Health Worker"
label variable mv762bq  "Source for female condoms: (Private) Support Groups"
label variable mv762br  "Source for female condoms: Facility Outside Lesotho"
label variable mv762bs  "Source for female condoms: (Private) Other"
label variable mv762bt  "Source for female condoms: (Other) Shop"
label variable mv762bu  "Source for female condoms: (Other) Church"
label variable mv762bv  "Source for female condoms: (Other) Peer educators"
label variable mv762bw  "Source for female condoms: (Other) Friend/relative"
label variable mv762bx  "Source for female condoms: other"
label variable mv762bz  "Don't know any source for female condoms"
label variable mv763a   "Had any STI in last 12 months"
label variable mv763b   "Had genital sore/ulcer in last 12 months"
label variable mv763c   "Had genital discharge in last 12 months"
label variable mv763d   "NA - Had CS STI in last 12 months"
label variable mv763e   "NA - Had CS STI in last 12 months"
label variable mv763f   "NA - Had CS STI in last 12 months"
label variable mv763g   "NA - Had CS STI in last 12 months"
label variable mv766a   "Number of sex partners, excluding spouse, in last 12 months"
label variable mv766b   "Number of sex partners, including spouse, in last 12 months"
label variable mv767a   "Relationship with most recent sex partner"
label variable mv767b   "Relationship with 2nd to most recent sex partner"
label variable mv767c   "Relationship with 3rd to most recent sex partner"
label variable mv768a   "NA - Length of time had sex relations with most recent partner"
label variable mv768b   "NA - Length of time had sex relations with 2nd to most recent partner"
label variable mv768c   "NA - Length of time had sex relations with 3rd to most recent partner"
label variable mv769    "Can get a condom"
label variable mv769a   "Can get a female condom"
label variable mv770    "Sought advice/treatment for last STI infection"
label variable mv770a   "Sought STI advice/treatment from: government hospital"
label variable mv770b   "Sought STI advice/treatment from: (Public) Government Health center"
label variable mv770c   "Sought STI advice/treatment from: (Public) Government Health Post"
label variable mv770d   "Sought STI advice/treatment from: (Public) Family Planning Clinic"
label variable mv770e   "Sought STI advice/treatment from: Other Public Sector"
label variable mv770f   "Sought STI advice/treatment from: (Private) Lesotho Planned Parenthood"
label variable mv770g   "Sought STI advice/treatment from: (Private) PSI/New Start Center"
label variable mv770h   "Sought STI advice/treatment from: (Private) CHAL hospital"
label variable mv770i   "Sought STI advice/treatment from: (Private) CHAL health center"
label variable mv770j   "Sought STI advice/treatment from: private hospital/clinic"
label variable mv770k   "Sought STI advice/treatment from: (Private) CHAL health post"
label variable mv770l   "Sought STI advice/treatment from: private doctor"
label variable mv770m   "Sought STI advice/treatment from: pharmacy"
label variable mv770n   "Sought STI advice/treatment from: (Private) Red Cross Health Center"
label variable mv770o   "NA - Sought STI advice/treatment from: CS Private"
label variable mv770p   "Sought STI advice/treatment from: (Private) Village Health Worker"
label variable mv770q   "Sought STI advice/treatment from: (Private) Support Groups"
label variable mv770r   "Sought STI advice/treatment from: Facility Outside Lesotho"
label variable mv770s   "Sought STI advice/treatment from: (Private) Other"
label variable mv770t   "Sought STI advice/treatment from: (Other) Shop"
label variable mv770u   "Sought STI advice/treatment from: (Other) Church"
label variable mv770v   "Sought STI advice/treatment from: (Other) Traditional healer"
label variable mv770w   "Sought STI advice/treatment from: (Other) Friend/relative"
label variable mv770x   "Sought STI advice/treatment from: other"
label variable mv774a   "HIV transmitted during pregnancy"
label variable mv774b   "HIV transmitted during delivery"
label variable mv774c   "HIV transmitted by breastfeeding"
label variable mv775    "NA - Knows someone who has, or is suspected of having, HIV"
label variable mv777    "Would want HIV infection in family to remain secret"
label variable mv778    "Willing to care for relative with AIDS"
label variable mv779    "A female teacher infected with HIV, but is not sick, should be allowed to contin"
label variable mv780    "Children should be taught about condoms to avoid AIDS"
label variable mv781    "Ever been tested for HIV"
label variable mv783    "Know a place to get HIV test"
label variable mv784a   "Place for HIV test: government hospital"
label variable mv784b   "Place for HIV test: (Public) Government Health Center"
label variable mv784c   "Place for HIV test: (Public) Government Health Post"
label variable mv784d   "Place for HIV test: (Public) Family Planning Clinic"
label variable mv784e   "NA - Place for HIV test: CS public"
label variable mv784f   "NA - Place for HIV test: CS public"
label variable mv784g   "NA - Place for HIV test: CS public"
label variable mv784h   "NA - Place for HIV test: CS public"
label variable mv784i   "Place for HIV test: Other Public Sector"
label variable mv784j   "Place for HIV test: private hospital/clinic"
label variable mv784k   "Place for HIV test: (Private) Lesotho Planned Parenthood"
label variable mv784l   "Place for HIV test: private doctor"
label variable mv784m   "Place for HIV test:  Pharmacy"
label variable mv784n   "Place for HIV test: (Private) PSI/New Start Center"
label variable mv784o   "Place for HIV test: (Private) CHAL hospital"
label variable mv784p   "Place for HIV test: (Private) CHAL health center"
label variable mv784q   "Place for HIV test: (Private) CHAL health post"
label variable mv784r   "Place for HIV test: (Private) Red Cross Health Center"
label variable mv784s   "Place for HIV test: (Private) Village Health Worker"
label variable mv784t   "Place for HIV test: (Private) Support Groups"
label variable mv784u   "Place for HIV test: Facility Outside Lesotho"
label variable mv784v   "Place for HIV test: Other private"
label variable mv784x   "Place for HIV test: other"
label variable mv785    "Heard about other STIs"
label variable mv791    "Have ever paid anyone in exchange for sex"
label variable mv793    "Paid for sex in last 12 months"
label variable mv793a   "Condom used last time paid for sex in last 12 months"
label variable mv793b   "Condom used every time paid for sex in last 12 months"
label variable mv820    "NA - Condom used at first sex"
label variable mv822    "Wife justified asking husband to use condom if he has STI"
label variable mv823    "Can get HIV by witchcraft or supernatural means"
label variable mv824    "Drugs to avoid HIV transmission to baby during pregnancy"
label variable mv825    "Would buy vegetables from vendor with HIV"
label variable mv826    "NA - Last time tested for HIV"
label variable mv826a   "Months ago most recent HIV test"
label variable mv827    "NA - Last HIV test: on your own, offered or required"
label variable mv828    "Received result from last HIV test"
label variable mv829    "Place where last HIV test was taken"
label variable mv832b   "Time since last sex with 2nd to most recent partner"
label variable mv832c   "Time since last sex with 3rd to most recent partner"
label variable mv833a   "Used condom every time had sex with most recent partner in last 12 months"
label variable mv833b   "Used condom every time had sex with 2nd to most recent partner in last 12 months"
label variable mv833c   "Used condom every time had sex with 3rd to most recent partner in last 12 months"
label variable mv834a   "Age of most recent partner"
label variable mv834b   "Age of 2nd to most recent partner"
label variable mv834c   "Age of 3rd to most recent partner"
label variable mv835a   "NA - Alcohol consumption at last sex with most recent partner"
label variable mv835b   "NA - Alcohol consumption at last sex with 2nd to most recent partner"
label variable mv835c   "NA - Alcohol consumption at last sex with 3rd to most recent partner"
label variable mv836    "Total lifetime number of sex partners"
label variable mv837    "NA - Heard of drugs to help HIV infected people live longer"
label variable mv844    "NA - Knows someone denied health services for having, or suspected of having, HI"
label variable mv845    "NA - Knows someone denied social event for having, or suspected of having, HIV; "
label variable mv846    "NA - Knows someone verbally abused for having, or suspected of having, HIV; in l"
label variable mv847    "NA - People with HIV should be ashamed of themselves"
label variable mv848    "NA - People with HIV should be blamed for bringing disease to community"
label variable mv849    "NA - Children 12-14 should be taught to wait for sex until marriage"
label variable mv851a   "NA - Young men should wait for sex until marriage"
label variable mv851b   "NA - Most young men wait for sex until marriage"
label variable mv851c   "NA - Unmarried sexually active men should have only one partner"
label variable mv851d   "NA - Most unmarried sexually active men have only one partner"
label variable mv851e   "NA - Married men should only have sex with their wives"
label variable mv851f   "NA - Most married men only have sex with their wives"
label variable mv851g   "NA - Young women should wait for sex until marriage"
label variable mv851h   "NA - Most young women wait for sex until marriage"
label variable mv851i   "NA - Unmarried sexually active women should have only one partner"
label variable mv851j   "NA - Most unmarried sexually active women have only one partner"
label variable mv851k   "NA - Married women should only have sex with their husbands"
label variable mv851l   "NA - Most married women only have sex with their husbands"
label variable mv852a   "How long ago first had sex with most recent partner"
label variable mv852b   "How long ago first had sex with 2nd most recent partner"
label variable mv852c   "How long ago first had sex with 3rd most recent partner"
label variable mv853a   "Times in last 12 months had sex with most recent partner"
label variable mv853b   "Times in last 12 months had sex with 2nd most recent partner"
label variable mv853c   "Times in last 12 months had sex with 3rd most recent partner"
label variable mv854a   "Concurrent sexual partners"
label variable mv854b   "Cumulative concurrent sexual partners"
label variable smzone   "Lesotho Ecological Zone"
label variable smlangin "Language of interview"
label variable smlangrs "Language of respondent"
label variable sminterp "Interpreter used"
label variable sm101b   "Respondent's consent to BP measurement"
label variable sm101ca  "Factors that could affect BP measurement : Eaten"
label variable sm101cb  "Factors that could affect BP measurement : Had caffeinated drink"
label variable sm101cc  "Factors that could affect BP measurement : Smoked"
label variable sm101d   "Arm circumference"
label variable sm101e   "Model and cuff size"
label variable smbp1s   "1st BP measurement : Systolic"
label variable smbp1d   "1st BP measurement : Diastolic"
label variable smbp2s   "2nd BP measurement : Systolic"
label variable smbp2d   "2nd BP measurement : Diastolic"
label variable smbp3s   "3rd BP measurement : Diastolic"
label variable smbp3d   "3rd BP measurement : Systolic"
label variable smbpaves "Blood pressure Averaged : Systolic"
label variable smbpaved "Blood pressure Averaged : Diastolic"
label variable smbpref  "Blood pressure referral reading"
label variable sm105    "Highest educational level (country specific)"
label variable sm106    "Highest grade at that level (country specific)"
label variable sm117    "Duration of last trip away of 1 month+"
label variable sm118    "Destination of last time away from home"
label variable sm120    "Reason for visit"
label variable sm122    "Times away from home for more than 3 months, in last 5 yrs"
label variable sm123    "Destination of last time away from home for 3+ months"
label variable sm124    "Reason for visit of 3+ months"
label variable sm125    "Times away from home for more than 3 months, in last 5 years"
label variable sm302d   "Saw FP billboard, poster, pamphlet last month"
label variable sm404    "Partner living with respondent"
label variable sm404a   "Reason partner living elsewhere"
label variable sm707a   "Can AIDS be cured"
label variable sm707ba  "Ways of curing AIDS: Modern drugs/antiretrovirals"
label variable sm707bb  "Ways of curing AIDS:Herbs"
label variable sm707bc  "Ways of curing AIDS:Prayer/God"
label variable sm707bx  "Ways of curing AIDS:Other"
label variable sm707bz  "Ways of curing AIDS:Don't know"
label variable sm717aa  "Reason why people do not go for HIV test: Already know status"
label variable sm717ab  "Reason why people do not go for HIV test: Feel they are not at risk"
label variable sm717ac  "Reason why people do not go for HIV test: Fear of results"
label variable sm717ad  "Reason why people do not go for HIV test: Fear of stigma/discrimination"
label variable sm717ae  "Reason why people do not go for HIV test: Fear of death"
label variable sm717af  "Reason why people do not go for HIV test: Fear of depression"
label variable sm717ag  "Reason why people do not go for HIV test: Don't know where to get HTC"
label variable sm717ah  "Reason why people do not go for HIV test: Fear of getting infected during test"
label variable sm717ai  "Reason why people do not go for HIV test: Fear of partners' reaction"
label variable sm717aj  "Reason why people do not go for HIV test: Lack of knowledge/ignorance"
label variable sm717ak  "Reason why people do not go for HIV test: Fatalism/no cure"
label variable sm717al  "Reason why people do not go for HIV test: Too expensive"
label variable sm717ax  "Reason why people do not go for HIV test: Other reason"
label variable sm717az  "Reason why people do not go for HIV test: Don't know"
label variable sm717c   "Main reason has not been tested for HIV"
label variable sm801aa  "Symptoms since aged 15 : Cough for two weeks +"
label variable sm801ab  "Symptoms since aged 15 : Fever for two weeks +"
label variable sm801ac  "Symptoms since aged 15 : Sweating at night"
label variable sm801ad  "Symptoms since aged 15 : weight loss"
label variable sm801c   "Sought consultation or treatment for symptoms"
label variable sm801d   "Main reason did not seek treatment"
label variable sm801e   "Source of advice or treatment for last STD"
label variable sm801f   "How soon after symptoms sought treatment"
label variable sm801g   "Told had TB during first visit by health professional"
label variable sm801h   "Given medicine to treat TB"
label variable sm801i   "How long told to take medicine"
label variable sm801j   "Went elsewhere for advice or treatment after diagnosis of TB"
label variable sm801k   "Other source for advice/treatment"
label variable sm804a   "Would be willing to work with someone previously treated for TB"
label variable sm804ba  "Signs or symptoms of TB :Coughing"
label variable sm804bb  "Signs or symptoms of TB :Coughing with sputum"
label variable sm804bc  "Signs or symptoms of TB :Coughing for several weeks"
label variable sm804bd  "Signs or symptoms of TB :Fever"
label variable sm804be  "Signs or symptoms of TB :Blood in sputum"
label variable sm804bf  "Signs or symptoms of TB :Loss of appetite"
label variable sm804bg  "Signs or symptoms of TB :Night sweating"
label variable sm804bh  "Signs or symptoms of TB :Pain in chest or back"
label variable sm804bi  "Signs or symptoms of TB :Tiredness/fatigue"
label variable sm804bj  "Signs or symptoms of TB :Weight loss"
label variable sm804bx  "Signs or symptoms of TB :Other"
label variable sm804by  "Signs or symptoms of TB :No symptoms"
label variable sm804bz  "Signs or symptoms of TB :Don't know"
label variable sm804ca  "Causes of TB :Microbes/germs/bacteria"
label variable sm804cb  "Causes of TB :Inherited"
label variable sm804cc  "Causes of TB :Lifestyle"
label variable sm804cd  "Causes of TB :Smoking"
label variable sm804ce  "Causes of TB :Alcohol drinking"
label variable sm804cf  "Causes of TB :Exposure to cold temp."
label variable sm804cg  "Causes of TB :Dust/pollution"
label variable sm804cx  "Causes of TB :Other"
label variable sm804cz  "Causes of TB :Don't know"
label variable sm805a   "Respondent traditionally circumcised"
label variable sm805b   "Age at traditional circumcision"
label variable sm805c   "Respondent medically circumcised"
label variable sm805d   "Age at medical circumcision"
label variable sm812a   "Heard of diabetes"
label variable sm812aaa "Knows symptom of diabetes:Frequent urination"
label variable sm812aab "Knows symptom of diabetes:Feeling very thirsty"
label variable sm812aac "Knows symptom of diabetes:Feeling very hungry"
label variable sm812aad "Knows symptom of diabetes:Extreme fatigue"
label variable sm812aae "Knows symptom of diabetes:;Blurry vision"
label variable sm812aaf "Knows symptom of diabetes:Cuts/bruises slow to heal"
label variable sm812aag "Knows symptom of diabetes:Weight loss"
label variable sm812aah "Knows symptom of diabetes:Pain/tingling/numbness in hands and feet"
label variable sm812aax "Knows symptom of diabetes:Other"
label variable sm812aaz "Knows symptom of diabetes:Don't know"
label variable sm812b   "Ever diagnosed with diabetes"
label variable sm812c   "Taking medication for diabetes"
label variable sm812d   "How takes medicine for diabetes"
label variable sm812e   "Ever had blood pressure checked"
label variable sm812f   "When last had blood pressure checked"
label variable sm812g   "Person who checked blood pressure"
label variable sm812h   "Ever diagnosed with high blood pressure by doctor or nurse"
label variable sm812ia  "Action taken to lower BP : take medicine"
label variable sm812ib  "Action taken to lower BP : Control weight"
label variable sm812ic  "Action taken to lower BP : Cut down salt"
label variable sm812id  "Action taken to lower BP : Exercise"
label variable sm812ie  "Action taken to lower BP : Cut down alcohol"
label variable sm812if  "Action taken to lower BP : Stop smoking"
label variable sm812ig  "Action taken to lower BP : Traditional medicine/herbs"
label variable sm812j   "Ever heard of breast cancer"
label variable sm812k   "Who is affected by breast cancer"

#delimit ;
label define MV013   
     1 "15-19"
     2 "20-24"
     3 "25-29"
     4 "30-34"
     5 "35-39"
     6 "40-44"
     7 "45-49"
     8 "50-54"
     9 "55-59"
    10 "60-64"
;
label define MV014   
     1 "Month and year - information complete"
     2 "Month and age - year imputed"
     3 "Year and age - month imputed"
     4 "Year and age - year ignored"
     5 "Year - age/month imputed"
     6 "Age - year/month imputed"
     7 "Month - age/year imputed"
     8 "None - all imputed"
;
label define MV015   
     1 "Completed"
     2 "Not at home"
     3 "Postponed"
     4 "Refused"
     5 "Partly completed"
     6 "Incapacitated"
     7 "Other"
;
label define MV022   
     1 "Botha-bothe - Rural"
     2 "Botha-bothe - Urban"
     3 "Leribe - Rural"
     4 "Leribe - Urban"
     5 "Berea - Rural"
     6 "Berea - Urban"
     7 "Maseru - Rural"
     8 "Maseru - Urban"
     9 "Mafeteng - Rural"
    10 "Mafeteng - Urban"
    11 "Mohale's hoek - Rural"
    12 "Mohale's hoek - Urban"
    13 "Quthing - Rural"
    14 "Quthing - Urban"
    15 "Qacha's-nek - Rural"
    16 "Qacha's-nek - Urban"
    17 "Mokhotlong - Rural"
    18 "Mokhotlong - Urban"
    19 "Thaba Tseka - Rural"
    20 "Thaba Tseka - Urban"
;
label define MV023   
     1 "Botha-bothe - Rural"
     2 "Botha-bothe - Urban"
     3 "Leribe - Rural"
     4 "Leribe - Urban"
     5 "Berea - Rural"
     6 "Berea - Urban"
     7 "Maseru - Rural"
     8 "Maseru - Urban"
     9 "Mafeteng - Rural"
    10 "Mafeteng - Urban"
    11 "Mohale's hoek - Rural"
    12 "Mohale's hoek - Urban"
    13 "Quthing - Rural"
    14 "Quthing - Urban"
    15 "Qacha's-nek - Rural"
    16 "Qacha's-nek - Urban"
    17 "Mokhotlong - Rural"
    18 "Mokhotlong - Urban"
    19 "Thaba Tseka - Rural"
    20 "Thaba Tseka - Urban"
;
label define MV024   
     1 "Botha-bothe"
     2 "Leribe"
     3 "Berea"
     4 "Maseru"
     5 "Mafeteng"
     6 "Mohale's hoek"
     7 "Quthing"
     8 "Qacha's-nek"
     9 "Mokhotlong"
    10 "Thaba Tseka"
;
label define MV025   
     1 "Urban"
     2 "Rural"
;
label define MV026   
     0 "Capital, large city"
     1 "Small city"
     2 "Town"
     3 "Countryside"
;
label define MV027   
     9 "Missing"
;
label define MV028   
   999 "Missing"
;
label define MV029   
    99 "Missing"
;
label define MV030   
   999 "Missing"
;
label define MV031   
   999 "Missing"
;
label define MV032   
    99 "Missing"
;
label define MV034   
     0 "Wife not in household"
;
label define MV034A  
     1 "Wife"
     2 "Partner"
;
label define MV034B  
    99 "Missing"
;
label define MV035   
     0 "No wives/partners"
;
label define MV801   
  9999 "Missing"
;
label define MV802   
  9999 "Missing"
;
label define MV803   
    95 "95+"
    96 "2+ visits"
    97 "Inconsistent"
;
label define MV101   
     1 "Botha-bothe"
     2 "Leribe"
     3 "Berea"
     4 "Maseru"
     5 "Mafeteng"
     6 "Mohale's hoek"
     7 "Quthing"
     8 "Qacha's-nek"
     9 "Mokhotlong"
    10 "Thaba Tseka"
;
label define MV102   
     1 "Urban"
     2 "Rural"
;
label define MV103   
     0 "Capital, large city"
     1 "City"
     2 "Town"
     3 "Countryside"
     4 "Abroad"
;
label define MV104   
    95 "Always"
    96 "Visitor"
    97 "Inconsistent"
    98 "Don't know"
;
label define MV105   
     0 "Capital, large city"
     1 "City"
     2 "Town"
     3 "Countryside"
     4 "Abroad"
;
label define MV106   
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
;
label define MV107   
     0 "No years completed at level MV106"
;
label define MV130   
     1 "Roman Catholic church"
     2 "Lesotho Evangelical church"
     3 "Methodist"
     4 "Anglican Church"
     5 "Seventh Day Adventist"
     6 "Pentecostal"
     7 "Other Christian"
     8 "Islam"
     9 "Hindu"
    10 "No religion"
    96 "Other"
;
label define MV131   
   999 "Missing"
;
label define MV133   
    97 "Inconsistent"
;
label define MV134   
     0 "Capital, large city"
     1 "Small city"
     2 "Town"
     3 "Countryside"
;
label define MV135   
     1 "Usual resident"
     2 "Visitor"
;
label define MV149   
     0 "No education"
     1 "Incomplete primary"
     2 "Complete primary"
     3 "Incomplete secondary"
     4 "Complete secondary"
     5 "Higher"
;
label define MV150   
     1 "Head"
     2 "Wife or husband"
     3 "Son/daughter"
     4 "Son/daughter-in-law"
     5 "Grandchild"
     6 "Parent"
     7 "Parent-in-law"
     8 "Brother/sister"
     9 "Co-spouse"
    10 "Other relative"
    11 "Adopted/foster child"
    12 "Not related"
    13 "Niece/nephew by blood"
    14 "Niece/nephew by marriage"
    15 "Domestic employee"
    16 "Herdboy"
    98 "Don't know"
;
label define MV151   
     1 "Male"
     2 "Female"
;
label define MV152   
    97 "97+"
    98 "Don't know"
;
label define MV155   
     0 "Cannot read at all"
     1 "Able to read only parts of sentence"
     2 "Able to read whole sentence"
     3 "No card with required language"
     4 "Blind/visually impaired"
;
label define MV156   
     0 "No"
     1 "Yes"
;
label define MV157   
     0 "Not at all"
     1 "Less than once a week"
     2 "At least once a week"
     3 "Almost every day"
;
label define MV158   
     0 "Not at all"
     1 "Less than once a week"
     2 "At least once a week"
     3 "Almost every day"
;
label define MV159   
     0 "Not at all"
     1 "Less than once a week"
     2 "At least once a week"
     3 "Almost every day"
;
label define MV167   
     0 "None"
    90 "90+"
    97 "Inconsistent"
    98 "Don't know"
;
label define MV168   
     0 "No"
     1 "Yes"
;
label define MV190   
     1 "Poorest"
     2 "Poorer"
     3 "Middle"
     4 "Richer"
     5 "Richest"
;
label define MV212   
    99 "Missing"
;
label define MV213   
     0 "No"
     1 "Yes"
     8 "Unsure"
;
label define MV217   
     1 "During her period"
     2 "After period ended"
     3 "Middle of the cycle"
     4 "Before period begins"
     5 "At any time"
     6 "Other"
     8 "Don't know"
;
label define MV225   
     1 "Then"
     2 "Later"
     3 "Not at all"
;
label define MV245   
    99 "Missing"
;
label define MV246   
     0 "No"
     1 "Yes"
;
label define MV247   
    99 "Missing"
;
label define MV248   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV249   
     0 "Not present"
     1 "Present"
;
label define MV250   
     1 "Hospital, health facility"
     2 "Other"
;
label define MV251   
     1 "Cost too much"
     2 "Facility closed"
     3 "Too far/no transportation"
     4 "Don't trust facility/poor quality service"
     5 "No female provider"
     6 "Not the first child"
     7 "Mother did not think it necessary"
     8 "Respondent did not think it necessary"
     9 "Family did not think it necessary"
    96 "Other"
    98 "Don't know"
;
label define MV252   
     0 "Nothing to drink"
     2 "Less than usual/much less"
     3 "Somewhat less"
     4 "About the same"
     5 "More"
     8 "Don't know"
;
label define MV301   
     0 "Knows no method"
     1 "Knows only folkloric method"
     2 "Knows only traditional method"
     3 "Knows modern method"
;
label define MV302   
     0 "Never used"
     1 "Used only folkloric method"
     2 "Used only traditional method"
     3 "Used modern method"
;
label define M304A   
     1 "Modern method"
     2 "Traditional method"
     3 "Folkloric method"
;
label define MV304   
     0 "No"
     1 "Yes"
     7 "Not in contraception table, but as a current method"
     8 "Not asked"
;
label define MV305   
     0 "No"
     1 "Yes"
;
label define MV307   
     0 "No"
     1 "Yes"
;
label define MV312   
     0 "Not using"
     1 "Pill"
     2 "IUD"
     3 "Injections"
     4 "Diaphragm"
     5 "Condom"
     6 "Female Sterilization"
     7 "Male Sterilization"
     8 "Periodic Abstinence"
     9 "Withdrawal"
    10 "Other"
    11 "Implants/Norplant"
    12 "Abstinence"
    13 "Lactational amenorrhea (LAM)"
    14 "Female condom"
    15 "Foam or jelly"
    17 "Other modern method"
    18 "Survey Specific method 2"
    19 "Survey Specific method 3"
    20 "Survey Specific method 4"
    98 "Don't know"
;
label define MV313   
     0 "No method"
     1 "Folkloric method"
     2 "Traditional method"
     3 "Modern method"
     8 "Don't know"
;
label define MV323A  
    96 "Other"
    98 "Don't know"
;
label define MV325B  
9999995 "Free"
9999998 "Don't know"
;
label define MV372A  
     0 "Package not seen"
     1 "Package seen"
;
label define MV384A  
     0 "No"
     1 "Yes"
;
label define MV384B  
     0 "No"
     1 "Yes"
;
label define MV384C  
     0 "No"
     1 "Yes"
;
label define MV395   
     0 "No"
     1 "Yes"
     2 "Depends"
     8 "Don't know"
;
label define MV396   
     0 "No"
     1 "Yes"
     2 "Depends"
     8 "Don't know"
;
label define MV3A09B 
   998 "Don't know"
;
label define MV3B17  
    10 "PUBLIC SECTOR"
    11 "Government Hospital"
    12 "Government Health center"
    13 "Government Health post"
    14 "Family Planning Clinic"
    16 "Other Public Sector"
    20 "PRIVATE SECTOR"
    21 "Private Hospital/clinic"
    22 "Pharmacy"
    23 "Private Doctor"
    24 "PSI/New Start Center"
    25 "Lesotho Planned parenthood"
    26 "Other Private medical sector"
    30 "NGO/OTHER MEDICAL"
    31 "CHAL Hospital"
    32 "CHAL Health center"
    33 "CHAL Health post"
    34 "RED Cross Health Center"
    35 "CBD"
    36 "Village health worker"
    37 "Support groups"
    38 "Facility outside Lesotho"
    40 "Other"
    41 "Shop"
    42 "Church"
    43 "Peer educators"
    44 "Friend/relative"
    96 "Other"
;
label define MV3B25A 
     0 "Disagree"
     1 "Agree"
     8 "Don't know"
;
label define MV3B25B 
     0 "Disagree"
     1 "Agree"
     8 "Don't know"
;
label define MV463A  
     0 "No"
     1 "Yes"
;
label define MV463B  
     0 "No"
     1 "Yes"
;
label define MV463C  
     0 "No"
     1 "Yes"
;
label define MV463D  
     0 "No"
     1 "Yes"
;
label define MV463E  
     0 "No"
     1 "Yes"
;
label define MV463F  
     0 "No"
     1 "Yes"
;
label define MV463G  
     0 "No"
     1 "Yes"
;
label define MV463X  
     0 "No"
     1 "Yes"
;
label define MV463Z  
     0 "No"
     1 "Yes, smokes nothing"
;
label define MV464   
    98 "DK"
;
label define MV474   
     0 "No"
     1 "Yes"
;
label define MV474A  
     0 "No"
     1 "Yes"
;
label define MV474B  
     0 "No"
     1 "Yes"
;
label define MV474C  
     0 "No"
     1 "Yes"
;
label define MV474D  
     0 "No"
     1 "Yes"
;
label define MV474E  
     0 "No"
     1 "Yes"
;
label define MV474F  
     0 "No"
     1 "Yes"
;
label define MV474G  
     0 "No"
     1 "Yes"
;
label define MV474H  
     0 "No"
     1 "Yes"
;
label define MV474I  
     0 "No"
     1 "Yes"
;
label define MV474J  
     0 "No"
     1 "Yes"
;
label define MV474X  
     0 "No"
     1 "Yes"
;
label define MV474Z  
     0 "No"
     1 "Yes"
;
label define MV475   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV476   
     0 "No"
     1 "Yes, remain a secret"
     8 "Don't know/not sure/depends"
;
label define MV477   
     0 "None"
    90 "90+"
    98 "Don't know"
;
label define MV478   
     0 "None"
    90 "90+"
    98 "Don't know"
;
label define MV479   
    10 "PUBLIC SECTOR"
    20 "PRIVATE SECTOR"
    30 "Other"
    96 "Other"
;
label define MV480   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV481   
     0 "No"
     1 "Yes"
;
label define MV481A  
     0 "No"
     1 "Yes"
;
label define MV481B  
     0 "No"
     1 "Yes"
;
label define MV481C  
     0 "No"
     1 "Yes"
;
label define MV481D  
     0 "No"
     1 "Yes"
;
label define MV481E  
     0 "No"
     1 "Yes"
;
label define MV481F  
     0 "No"
     1 "Yes"
;
label define MV481G  
     0 "No"
     1 "Yes"
;
label define MV481H  
     0 "No"
     1 "Yes"
;
label define MV481X  
     0 "No"
     1 "Yes"
;
label define MV482A  
     0 "No"
     1 "Yes"
     8 "Unsure"
;
label define MV482B  
     0 "No"
     1 "Yes"
;
label define MV482C  
     0 "No"
     1 "Yes"
     8 "Unsure"
;
label define MV483   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV483A  
    95 "During childhood <5 years"
    98 "Don't know"
;
label define MV483B  
     1 "Traditional practitioner / family friend"
     2 "Health worker / professional"
    96 "Other"
    98 "Don't know"
;
label define MV483C  
     1 "Health facility"
     2 "Home of a health worker / professional"
     3 "Circumcision done at home"
     4 "Ritual site"
    96 "Other home / place"
    98 "Don't know"
;
label define MV501   
     0 "Never in union"
     1 "Married"
     2 "Living with partner"
     3 "Widowed"
     4 "Divorced"
     5 "No longer living together/separated"
;
label define MV502   
     0 "Never in union"
     1 "Currently in union/living with a woman"
     2 "Formerly in union/living with a woman"
;
label define MV503   
     1 "Once"
     2 "More than once"
;
label define MV504   
     1 "Living with him"
     2 "Staying elsewhere"
;
label define MV505   
    99 "Missing"
;
label define MV510   
     1 "Month and year - information complete"
     2 "Month and age - year imputed"
     3 "Year and age - month imputed"
     5 "Year - age/month imputed"
     6 "Age - year/month imputed"
     7 "Month - age/year imputed"
     8 "None - all imputed"
;
label define MV513   
     0 "Never married"
     1 "0-4"
     2 "5-9"
     3 "10-14"
     4 "15-19"
     5 "20-24"
     6 "25-29"
     7 "30+"
;
label define MV525   
     0 "Not had sex"
    96 "At first union"
    97 "Inconsistent"
    98 "Don't know"
;
label define MV527   
   100 "<1 day ago"
   101 "Days: 1"
   199 "Days: number missing"
   201 "Weeks: 1"
   299 "Weeks: number missing"
   301 "Months: 1"
   399 "Months: number missing"
   401 "Years: 1"
   499 "Years: number missing"
   995 "Within last 4 weeks"
   996 "Before last birth"
   997 "Inconsistent"
   998 "Don't know"
;
label define MV528   
    31 "31+ days"
    95 "Within last 4 weeks"
    96 "Before last birth"
    97 "Inconsistent"
    98 "Don't know"
;
label define MV529   
   995 "Within last 4 weeks"
   996 "Before last birth"
   997 "Inconsistent"
   998 "Don't know"
;
label define MV531   
     0 "Not had sex"
    97 "Inconsistent"
    98 "Don't know"
;
label define MV532   
     0 "No flag"
     1 "After interview"
     2 "After conception >= 1 year"
     3 "After conception < 1 year"
     4 "At marriage, but never married"
     5 "At marriage, but after conception"
     6 "After marriage"
;
label define MV535   
     0 "No"
     1 "Formerly married"
     2 "Formerly lived with a woman"
     3 "Both, formerly married and lived with a woman"
;
label define MV536   
     0 "Never had sex"
     1 "Active in last 4 weeks"
     3 "Not active in last 4 weeks"
;
label define MV541   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV602   
     1 "Have another"
     2 "Undecided"
     3 "No more"
     4 "Sterilized (respondent or partner(s))"
     5 "Declared infecund (respondent or partner(s))"
     6 "Never had sex"
     7 "Man declared infecund"
     8 "Man has no partner"
;
label define MV603   
   100 "Wanted now"
   101 "Months: 1"
   199 "Months: number missing"
   201 "Years: 1"
   299 "Years: number missing"
   993 "After marriage"
   994 "Soon, now"
   996 "Other, non-numeric"
   997 "Inconsistent"
   998 "Don't know"
;
label define MV604   
     0 "<12 months"
     1 "1 year"
     2 "2 years"
     3 "3 years"
     4 "4 years"
     5 "5 years"
     6 "6+ years"
     7 "Non-numeric"
     8 "Don't know"
;
label define MV605   
     1 "Wants within 2 years"
     2 "Wants after 2+ years"
     3 "Wants, unsure timing"
     4 "Undecided"
     5 "Wants no more"
     6 "Sterilized (respondent or partner(s))"
     7 "Declared infecund (respondent or partner(s))"
     8 "Never had sex"
;
label define MV613   
    96 "Non-numeric response"
    98 "Don't know"
;
label define MV614   
     6 "6+"
     7 "Non-numeric response"
;
label define MV616   
   100 "Wanted now"
   101 "Months: 1"
   199 "Months: number missing"
   201 "Years: 1"
   299 "Years: number missing"
   993 "After marriage"
   994 "Soon/now"
   995 "Can't get pregnant"
   996 "Other"
   998 "Don't know"
;
label define MV621   
     1 "Both want same"
     2 "Wife wants more"
     3 "Wife wants fewer"
     8 "Don't know"
;
label define MV627   
    96 "Other"
    98 "Don't know"
;
label define MV628   
    96 "Other"
    98 "Don't know"
;
label define MV629   
    96 "Other"
    98 "Don't know"
;
label define MV631   
     1 "Big problem"
     2 "Small problem"
     3 "No problem"
     4 "Says she can't get pregnant/not having sex"
;
label define MV633A  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV633B  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV633C  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV633D  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV633E  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV633F  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV633G  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV634A  
     0 "No"
     1 "Yes"
     8 "Don't know, depends"
;
label define MV634B  
     0 "No"
     1 "Yes"
     8 "Don't know, depends"
;
label define MV634C  
     0 "No"
     1 "Yes"
     8 "Don't know, depends"
;
label define MV634D  
     0 "No"
     1 "Yes"
     8 "Don't know, depends"
;
label define MV714   
     0 "No"
     1 "Yes"
;
label define MV714A  
     0 "No"
     1 "Yes"
;
label define MV716   
     0 "Not employed"
     1 "[1110]Legislators and senior government officials"
     2 "[1141]Senior officials of political party organisations"
     3 "[1142]Senior officials of employers,worker and other"
     4 "[1210]Directors and chief executives"
     5 "[1213]Finance and administration managers"
     6 "[1225]Production and operations managers in restaurants and hotels"
     7 "[1228]Production and operations managers in personal care, cleaning and related services"
     8 "[1229]Production and operations managers not  elsewhere classified"
     9 "[1231]Finance and administration managers"
    10 "[1232]Personnel and Industrial relations managers"
    11 "[1235]Supply and distribution manager"
    12 "[1239]Other specialist managers not elsewhere classified"
    13 "[1311]Managers of small enterprises in agriculture,hunting,forestry and fishing"
    14 "[1314]Managers of small enterprises in wholesale and retail trade"
    15 "[1316]Managers of small enterprises in transport,storage and communications"
    16 "[1317]Managers of small enterprises of business services enterprises"
    17 "[1319]Managers of small enterprises not elsewhere classified"
    18 "[2112]Meteorologists"
    19 "[2131]Computer system designers,analysts and programmers"
    20 "[2139]Other specialist managers not elsewhere classified"
    21 "[2141]Architects, town and traffic planners"
    22 "[2142]Civil engineers"
    23 "[2145]Mechanical engineers"
    24 "[2147]Mining engineers, metallurgists and related professionals"
    25 "[2148]Cartographers and surveyors"
    26 "[2149]Architects,engineers and related professionals not elsewhere classified"
    27 "[2221]Medical doctors"
    28 "[2222]Dentists"
    29 "[2229]Health professionals (except nursing) not elsewhere classified"
    30 "[2230]Nursing and midwifery professionals"
    31 "[2310]College, university and higher education teaching professionals."
    32 "[2320]Secondary education teaching professionals"
    33 "[2331]Primary education teaching professionals"
    34 "[2351]Education methods specialists"
    35 "[2359]Other teaching professionals not elsewhere classified"
    36 "[2411]Accountant"
    37 "[2412]Personnel and careers professionals"
    38 "[2421]Lawyers"
    39 "[2422]Judges"
    40 "[2429]Legal professionals not elsewhere classified"
    41 "[2432]Librarians and related information professional"
    42 "[2446]Social work professionals"
    43 "[2451]Author,journalists and other writers"
    44 "[2453]Composers,musicians and singers"
    45 "[2455]Film,stage and related actors and directors"
    46 "[2460]Religious professionals"
    47 "[2470]Public service administrative professional"
    48 "[3113]Electrical engineering technicians"
    49 "[3115]Mechanical engineering technicians"
    50 "[3119]Physical and engineering science technicians not elsewhere classified"
    51 "[3131]Photographers and image and sound recording equipment operators"
    52 "[3132]Broadcasting and telecommunications equipment operators"
    53 "[3152]Safety,health and quality inspectors"
    54 "[3213]Farming and forestry advisers"
    55 "[3221]Medical assistants"
    56 "[3222]Hygienists,health and environmental officers"
    57 "[3223]Dieticians and nutritionists"
    58 "[3227]Veterinary assistants"
    59 "[3229]Health associate professionals (except nursing) not elsewhere classified"
    60 "[3231]Nursing associate professionals"
    61 "[3232]Midwifery associate professionals"
    62 "[3320]Pre-primary education teaching associate professionals"
    63 "[3330]Special education teaching associate professionals"
    64 "[3340]Other teaching associate professionals"
    65 "[3340]Other teaching associate professionals"
    66 "[3411]Securities and finance dealers and brokers"
    67 "[3412]Insurance representatives"
    68 "[3414]Travel consultants and organisers"
    69 "[3421]Trade brokers"
    70 "[3429]Business services agents and trade broker not elsewhere classified"
    71 "[3431]Administrative secretaries and related associate professions"
    72 "[3433]Bookkeepers"
    73 "[3434]Statistical, mathematical and related associate professionals"
    74 "[3441]Customs and border inspectors"
    75 "[3449]Customs, tax and related government associate professionals not elsewhere classified"
    76 "[3450]Police inspectors and detectives"
    77 "[3460]Social work associate professionals"
    78 "[3470]Artists,entertainment and sports associate professionals"
    79 "[3471]Decorators and commercial designer"
    80 "[3473]Street ,night-club and related musicians,singers and dancers"
    81 "[3474]Trade brokers"
    82 "[4111]Stenographers and typists"
    83 "[4112]Word-processors and related operators"
    84 "[4113]Data entry operators"
    85 "[4115]Secretaries"
    86 "[4121]Accounting & Book-keeping Clerks"
    87 "[4122]Statistical and finance clerks"
    88 "[4131]Stock clerks"
    89 "[4132]Production clerks"
    90 "[4190]Other office clerks"
    91 "[4211]Cashiers and tickets clerks"
    92 "[4212]Tellers and other counter clerks"
    93 "[4213]Pawnbrokers and money-lenders"
    94 "[4214]Pawnbrokers and money-lenders"
    95 "[4221]Travel agency and related clerks"
    96 "[4222]Receptionists and information clerk"
    97 "[4223]Telephone switchboard operators"
    98 "[5111]Travel attendants and travel stewards"
    99 "[5122]Cooks"
   100 "[5123]Waiters, waitresses and bartenders"
   101 "[5131]Child-care workers"
   102 "[5132]Institution-based personal care workers"
   103 "[5133]Home-based personal care workers"
   104 "[5141]Hairdressers, barbers, beauticians and related workers"
   105 "[5143]Undertakers and embalmers"
   106 "[5161]Fire-fighters"
   107 "[5162]Police officers"
   108 "[5163]Prison guards"
   109 "[5169]Protective services workers not elsewhere classified"
   110 "[5210]Fashion and other models"
   111 "[5220]Shops, stall and market salespersons and demonstrators"
   112 "[6111]Farm-hands and labourers"
   113 "[6112]Gardeners, horticultural and nursery growers"
   114 "[6121]Dairy and livestock producers"
   115 "[6122]Poultry producers"
   116 "[6122]Gardeners, horticultural and nursery growers"
   117 "[6122]Poultry producers"
   118 "[6129]Animal producers and related workers not elsewhere classified"
   119 "[6130]Crop and animal producers"
   120 "[6141]Forestry workers and loggers"
   121 "[6151]Aquatic life cultivation worker"
   122 "[7000]Craft  and related worker"
   123 "[7100]Craft  and related worker"
   124 "[7111]Miners and quarry workers"
   125 "[7113]Stone splitters, cutters and carvers"
   126 "[7121]Builders"
   127 "[7122]Bricklayers and stonemasons"
   128 "[7124]Carpenters and joiners"
   129 "[7129]Building frame and related trades workers not elsewhere classified"
   130 "[7131]Roofers"
   131 "[7132]Floor layers and tile setters"
   132 "[7133]Plasterers"
   133 "[7133]Tailors, dressmakers and hatters"
   134 "[7136]Plumbers and pipe fitters"
   135 "[7139]Building finishers and related trade works elsewhere classified"
   136 "[7141]Painters and related workers"
   137 "[7143]Building structure cleaners"
   138 "[7211]Metal moulders and coremakers"
   139 "[7212]Welders and flame cutters"
   140 "[7231]Motor vehicle machine and fitters"
   141 "[7233]Agricultural-industrial -machinery mechanics and fitters"
   142 "[7241]Electrical mechanics fitters and services"
   143 "[7244]Telegraph and telephone installers and services"
   144 "[7245]Electrical line installers;[repairer and cable jointers"
   145 "[7312]Musical-instrument makers and tuners"
   146 "[7321]Abrasive wheel formers, potters and related workers"
   147 "[7324]Glass,ceramic and related decorative painters"
   148 "[7331]Handicraft workers in wood and related materials"
   149 "[7341] compositors, typesetters and related workers"
   150 "[7343]Abrasive wheel formers, potters and related workers"
   151 "[7344]Photographic and related workers"
   152 "[7411]Butchers,fishmongers"
   153 "[7411]Butchers, fishmongers and related food preparers"
   154 "[7412]Bakers, pastry-cooks and confectionery makers"
   155 "[7415]Food and beverage testers and graders"
   156 "[7416]Tobacco preparers and tobacco product makers"
   157 "[7424]Basketry weavers, brush makers and related workers"
   158 "[7432]Weavers,knitters and related workers"
   159 "[7433]Tailors, dressmakers and hatters"
   160 "[7436]Sewers, embroiderers and related workers"
   161 "[7442]Shoe-makers and related workers"
   162 "[8111]Mining plant operators"
   163 "[8112]Mineral-ore and stone-processing--plant operators"
   164 "[8113]Well drillers and borers and related workers"
   165 "[8139]Glass,ceramic and related plant operator not elsewhere classified"
   166 "[8163]Incinerator, water-treatment and related plant operators"
   167 "[8263]Sewing-machine operators"
   168 "[8273]Production clerks"
   169 "[8278]Brewers, wine and other beverage machine operators"
   170 "[8281]Mechanical-machinery assemblers"
   171 "[8290]Other machine operators not elsewhere classified"
   172 "[8300]Motor vehicle drivers"
   173 "[8311]Locomotive engine drivers"
   174 "[8312]Railway brakers, signallers and shunters"
   175 "[8321]Motorcycle drivers"
   176 "[8322]Car, taxi and van drivers"
   177 "[8323]Bus and tram drivers"
   178 "[8324]Commercial vehicle drivers"
   179 "[8333]Crane,hoist and related plant operator"
   180 "[8334]Lifting-truck operators"
   181 "[8340]Ship' deck crew and related workers"
   182 "[8549]Paralegal training"
   183 "[9111]Street vendors"
   184 "[9113]Door-to-door and telephone salespersons"
   185 "[9120]Shoe cleaning and other street services elementary occupations"
   186 "[9131]Domestic helpers and cleaners"
   187 "[9132]Helpers and cleaners in offices,hotels and other establishments"
   188 "[9133]Domestic helpers and cleaners"
   189 "[9141]Building caretakers"
   190 "[9142]Vehicle ,window and related cleaners"
   191 "[9151]Messengers, package and luggage porters and deliverers"
   192 "[9152]Doorkeepers, watchpersons and related workers"
   193 "[9153]Vending-machine money collectors,meter readers and related workers"
   194 "[9153]Vending-machine money collectors,meter readers and related workers"
   195 "[9153]Vending-machine money collectors, meter readers and related workers"
   196 "[9161]Garbage collectors"
   197 "[9162]Sweepers and related labourers"
   198 "[9211]Farm-hands and labourers"
   199 "[9212]Forestry labourers"
   200 "[9311]Mining and quarrying labourers"
   201 "[9312]Construction and maintenance labourers: roads, dams and similar constructions"
   202 "[9313]Building construction labourers"
   203 "[9320]Manufacturing labourers"
   204 "[9330]Transport labourers and freight handlers"
   205 "Military (rank not specified)"
   996 "[9996]Other occupation"
   999 "[9999]Not categorized"
;
label define MV717   
     0 "Not working"
     1 "Professional/technical/managerial"
     2 "Clerical"
     3 "Sales"
     4 "Agriculture - self employed"
     5 "Agriculture - employee"
     6 "Household and domestic"
     7 "Services"
     8 "Skilled manual"
     9 "Unskilled manual"
    98 "Don't know"
;
label define MV719   
     1 "For family member"
     2 "For someone else"
     3 "Self-employed"
;
label define MV721   
     1 "At home"
     2 "Away"
;
label define MV731   
     0 "No"
     1 "In the past year"
     2 "Currently working"
;
label define MV732   
     1 "All year"
     2 "Seasonal"
     3 "Occasional"
;
label define MV739   
     1 "Respondent alone"
     2 "Respondent and wife/partner"
     3 "Respondent and other person"
     4 "Wife/partner alone"
     5 "Someone else"
;
label define MV740   
     0 "Own land"
     1 "Family land"
     2 "Someone else's land"
     3 "Rented land"
     8 "Don't know"
;
label define MV741   
     0 "Not paid"
     1 "Cash only"
     2 "Cash and in-kind"
     3 "In-kind only"
;
label define MV743A  
     1 "Respondent alone"
     2 "Respondent and wife/partner"
     3 "Respondent and other person"
     4 "Wife/partner alone"
     5 "Someone else"
     6 "Other"
     8 "Don't know/depends"
;
label define MV743B  
     1 "Respondent alone"
     2 "Respondent and wife/partner"
     3 "Respondent and other person"
     4 "Wife/partner alone"
     5 "Someone else"
     6 "Other"
     8 "Don't know/depends"
;
label define MV743C  
     1 "Respondent alone"
     2 "Respondent and wife/partner"
     3 "Respondent and other person"
     4 "Wife/partner alone"
     5 "Someone else"
     6 "Decision not made/not applicable"
     8 "Don't know/depends"
;
label define MV743D  
     1 "Respondent alone"
     2 "Respondent and wife/partner"
     3 "Respondent and other person"
     4 "Wife/partner alone"
     5 "Someone else"
     6 "Decision not made/not applicable"
     8 "Don't know/depends"
;
label define MV743E  
     1 "Respondent alone"
     2 "Respondent and wife/partner"
     3 "Respondent and other person"
     4 "Wife/partner alone"
     5 "Someone else"
     6 "Decision not made/not applicable"
     8 "Don't know/depends"
;
label define MV743F  
     1 "Respondent alone"
     2 "Respondent and wife/partner"
     3 "Respondent and other person"
     4 "Wife/partner alone"
     5 "Someone else"
     6 "Decision not made/not applicable"
     8 "Don't know/depends"
;
label define MV743G  
     1 "Respondent alone"
     2 "Respondent and wife/partner"
     3 "Respondent and other person"
     4 "Wife/partner alone"
     5 "Someone else"
     6 "Decision not made/not applicable"
     8 "Don't know/depends"
;
label define MV744A  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV744B  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV744C  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV744D  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV744E  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV745A  
     0 "Does not own"
     1 "Alone only"
     2 "Jointly only"
     3 "Both alone and jointly"
;
label define MV745B  
     0 "Does not own"
     1 "Alone only"
     2 "Jointly only"
     3 "Both alone and jointly"
;
label define MV747A  
     0 "Disagree"
     1 "Agree"
     8 "Don't know"
;
label define MV747B  
     0 "Disagree"
     1 "Agree"
     8 "Don't know"
;
label define MV750   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV751   
     0 "No"
     1 "Yes"
;
label define MV754BP 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV754CP 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV754DP 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV754JP 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV754WP 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV756   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV761   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV761B  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV761C  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV762AA 
     0 "No"
     1 "Yes"
;
label define MV762AB 
     0 "No"
     1 "Yes"
;
label define MV762AC 
     0 "No"
     1 "Yes"
;
label define MV762AD 
     0 "No"
     1 "Yes"
;
label define MV762AE 
     0 "No"
     1 "Yes"
;
label define MV762AF 
     0 "No"
     1 "Yes"
;
label define MV762AG 
     0 "No"
     1 "Yes"
;
label define MV762AH 
     0 "No"
     1 "Yes"
;
label define MV762AI 
     0 "No"
     1 "Yes"
;
label define MV762AJ 
     0 "No"
     1 "Yes"
;
label define MV762AK 
     0 "No"
     1 "Yes"
;
label define MV762AL 
     0 "No"
     1 "Yes"
;
label define MV762AM 
     0 "No"
     1 "Yes"
;
label define MV762AN 
     0 "No"
     1 "Yes"
;
label define MV762AO 
     0 "No"
     1 "Yes"
;
label define MV762AP 
     0 "No"
     1 "Yes"
;
label define MV762AQ 
     0 "No"
     1 "Yes"
;
label define MV762AR 
     0 "No"
     1 "Yes"
;
label define MV762AS 
     0 "No"
     1 "Yes"
;
label define MV762AT 
     0 "No"
     1 "Yes"
;
label define MV762AU 
     0 "No"
     1 "Yes"
;
label define MV762AV 
     0 "No"
     1 "Yes"
;
label define MV762AW 
     0 "No"
     1 "Yes"
;
label define MV762AX 
     0 "No"
     1 "Yes"
;
label define MV762AZ 
     0 "No: source known"
     1 "Yes: no source known"
;
label define MV762BA 
     0 "No"
     1 "Yes"
;
label define MV762BB 
     0 "No"
     1 "Yes"
;
label define MV762BC 
     0 "No"
     1 "Yes"
;
label define MV762BD 
     0 "No"
     1 "Yes"
;
label define MV762BE 
     0 "No"
     1 "Yes"
;
label define MV762BF 
     0 "No"
     1 "Yes"
;
label define MV762BG 
     0 "No"
     1 "Yes"
;
label define MV762BH 
     0 "No"
     1 "Yes"
;
label define MV762BI 
     0 "No"
     1 "Yes"
;
label define MV762BJ 
     0 "No"
     1 "Yes"
;
label define MV762BK 
     0 "No"
     1 "Yes"
;
label define MV762BL 
     0 "No"
     1 "Yes"
;
label define MV762BM 
     0 "No"
     1 "Yes"
;
label define MV762BN 
     0 "No"
     1 "Yes"
;
label define MV762BO 
     0 "No"
     1 "Yes"
;
label define MV762BP 
     0 "No"
     1 "Yes"
;
label define MV762BQ 
     0 "No"
     1 "Yes"
;
label define MV762BR 
     0 "No"
     1 "Yes"
;
label define MV762BS 
     0 "No"
     1 "Yes"
;
label define MV762BT 
     0 "No"
     1 "Yes"
;
label define MV762BU 
     0 "No"
     1 "Yes"
;
label define MV762BV 
     0 "No"
     1 "Yes"
;
label define MV762BW 
     0 "No"
     1 "Yes"
;
label define MV762BX 
     0 "No"
     1 "Yes"
;
label define MV762BZ 
     0 "No: source known"
     1 "Yes: no source known"
;
label define MV763A  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV763B  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV763C  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV763D  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV763E  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV763F  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV763G  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV766A  
    95 "95+"
    98 "Don't know"
;
label define MV766B  
    95 "95+"
    98 "Don't know"
;
label define MV767A  
     1 "Spouse"
     2 "Girlfriend/fiance"
     3 "Other friend"
     4 "Casual acquaintance"
     5 "Relative"
     6 "Commercial sex worker"
     7 "Live-in partner"
    96 "Other"
;
label define MV767B  
     1 "Spouse"
     2 "Girlfriend/fiance"
     3 "Other friend"
     4 "Casual acquaintance"
     5 "Relative"
     6 "Commercial sex worker"
     7 "Live-in partner"
    96 "Other"
;
label define MV767C  
     1 "Spouse"
     2 "Girlfriend/fiance"
     3 "Other friend"
     4 "Casual acquaintance"
     5 "Relative"
     6 "Commercial sex worker"
     7 "Live-in partner"
    96 "Other"
;
label define MV768A  
   101 "Days: 1"
   199 "Days: number missing"
   201 "Months: 1"
   299 "Months: number missing"
   301 "Years: 1"
   399 "Years: number missing"
;
label define MV768B  
   101 "Days: 1"
   199 "Days: number missing"
   201 "Months: 1"
   299 "Months: number missing"
   301 "Years: 1"
   399 "Years: number missing"
;
label define MV768C  
   101 "Days: 1"
   199 "Days: number missing"
   201 "Months: 1"
   299 "Months: number missing"
   301 "Years: 1"
   399 "Years: number missing"
;
label define MV769   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV769A  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV770   
     0 "No"
     1 "Yes"
;
label define MV770A  
     0 "No"
     1 "Yes"
;
label define MV770B  
     0 "No"
     1 "Yes"
;
label define MV770C  
     0 "No"
     1 "Yes"
;
label define MV770D  
     0 "No"
     1 "Yes"
;
label define MV770E  
     0 "No"
     1 "Yes"
;
label define MV770F  
     0 "No"
     1 "Yes"
;
label define MV770G  
     0 "No"
     1 "Yes"
;
label define MV770H  
     0 "No"
     1 "Yes"
;
label define MV770I  
     0 "No"
     1 "Yes"
;
label define MV770J  
     0 "No"
     1 "Yes"
;
label define MV770K  
     0 "No"
     1 "Yes"
;
label define MV770L  
     0 "No"
     1 "Yes"
;
label define MV770M  
     0 "No"
     1 "Yes"
;
label define MV770N  
     0 "No"
     1 "Yes"
;
label define MV770O  
     0 "No"
     1 "Yes"
;
label define MV770P  
     0 "No"
     1 "Yes"
;
label define MV770Q  
     0 "No"
     1 "Yes"
;
label define MV770R  
     0 "No"
     1 "Yes"
;
label define MV770S  
     0 "No"
     1 "Yes"
;
label define MV770T  
     0 "No"
     1 "Yes"
;
label define MV770U  
     0 "No"
     1 "Yes"
;
label define MV770V  
     0 "No"
     1 "Yes"
;
label define MV770W  
     0 "No"
     1 "Yes"
;
label define MV770X  
     0 "No"
     1 "Yes"
;
label define MV774A  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV774B  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV774C  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV775   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV777   
     0 "No"
     1 "Yes"
     8 "Don't know/not sure/depends"
;
label define MV778   
     0 "No"
     1 "Yes"
     8 "Don't know/not sure/depends"
;
label define MV779   
     0 "No"
     1 "Yes"
     8 "Don't know/not sure/depends"
;
label define MV780   
     0 "No"
     1 "Yes"
     8 "Don't know/not sure/depends"
;
label define MV781   
     0 "No"
     1 "Yes"
;
label define MV783   
     0 "No"
     1 "Yes"
;
label define MV784A  
     0 "No"
     1 "Yes"
;
label define MV784B  
     0 "No"
     1 "Yes"
;
label define MV784C  
     0 "No"
     1 "Yes"
;
label define MV784D  
     0 "No"
     1 "Yes"
;
label define MV784E  
     0 "No"
     1 "Yes"
;
label define MV784F  
     0 "No"
     1 "Yes"
;
label define MV784G  
     0 "No"
     1 "Yes"
;
label define MV784H  
     0 "No"
     1 "Yes"
;
label define MV784I  
     0 "No"
     1 "Yes"
;
label define MV784J  
     0 "No"
     1 "Yes"
;
label define MV784K  
     0 "No"
     1 "Yes"
;
label define MV784L  
     0 "No"
     1 "Yes"
;
label define MV784M  
     0 "No"
     1 "Yes"
;
label define MV784N  
     0 "No"
     1 "Yes"
;
label define MV784O  
     0 "No"
     1 "Yes"
;
label define MV784P  
     0 "No"
     1 "Yes"
;
label define MV784Q  
     0 "No"
     1 "Yes"
;
label define MV784R  
     0 "No"
     1 "Yes"
;
label define MV784S  
     0 "No"
     1 "Yes"
;
label define MV784T  
     0 "No"
     1 "Yes"
;
label define MV784U  
     0 "No"
     1 "Yes"
;
label define MV784V  
     0 "No"
     1 "Yes"
;
label define MV784X  
     0 "No"
     1 "Yes"
;
label define MV785   
     0 "No"
     1 "Yes"
;
label define MV791   
     0 "No"
     1 "Yes"
;
label define MV793   
     0 "No"
     1 "Yes"
;
label define MV793A  
     0 "No"
     1 "Yes"
;
label define MV793B  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV820   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV822   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV823   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV824   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV825   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV826   
     1 "Less than 12 months"
     2 "12-23 months"
     3 "2 years or more"
;
label define MV826A  
    95 "Two or more years"
    98 "Don't know"
;
label define MV827   
     1 "Asked for the test"
     2 "Offered and accepted"
     3 "Required"
;
label define MV828   
     0 "No"
     1 "Yes"
;
label define MV829   
    10 "PUBLIC SECTOR"
    11 "Public sector govt. hospital"
    12 "Government Health center"
    13 "Government Health post"
    14 "Family Planning Clinic"
    16 "Other Public Sector"
    20 "PRIVATE SECTOR"
    21 "Private hospital/clinic"
    22 "Private Doctor"
    23 "Pharmacy"
    24 "Lesotho Planned Parenthood"
    25 "PSI/New start center"
    26 "Other private medical sector"
    30 "NGO/OTHER MEDICAL"
    31 "CHAL Hospital"
    32 "CHAL Health Center"
    33 "CHAL Health Post"
    34 "Red Cross Health Center"
    35 "Village Health Worker"
    36 "Support Groups"
    37 "Facility outside Lesotho"
    96 "Other"
;
label define MV832B  
   100 "<1 day ago"
   101 "Days: 1"
   199 "Days: number missing"
   201 "Weeks: 1"
   299 "Weeks: number missing"
   301 "Months: 1"
   399 "Months: number missing"
   401 "Years: 1"
   995 "Within last 4 weeks"
   996 "Before last birth"
   997 "Inconsistent"
   998 "Don't know"
;
label define MV832C  
   100 "<1 day ago"
   101 "Days: 1"
   199 "Days: number missing"
   201 "Weeks: 1"
   299 "Weeks: number missing"
   301 "Months: 1"
   399 "Months: number missing"
   401 "Years: 1"
   995 "Within last 4 weeks"
   996 "Before last birth"
   997 "Inconsistent"
   998 "Don't know"
;
label define MV833A  
     0 "No"
     1 "Yes"
;
label define MV833B  
     0 "No"
     1 "Yes"
;
label define MV833C  
     0 "No"
     1 "Yes"
;
label define MV834A  
    95 "95+"
    98 "Don't know"
;
label define MV834B  
    95 "95+"
    98 "Don't know"
;
label define MV834C  
    95 "95+"
    98 "Don't know"
;
label define MV835A  
     0 "No"
     1 "Respondent drunk only"
     2 "Partner drunk only"
     3 "Both drunk"
     4 "Neither drunk but consumed alcohol"
;
label define MV835B  
     0 "No"
     1 "Respondent drunk only"
     2 "Partner drunk only"
     3 "Both drunk"
     4 "Neither drunk but consumed alcohol"
;
label define MV835C  
     0 "No"
     1 "Respondent drunk only"
     2 "Partner drunk only"
     3 "Both drunk"
     4 "Neither drunk but consumed alcohol"
;
label define MV836   
    95 "95+"
    98 "Don't know"
;
label define MV837   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV844   
     0 "No"
     1 "Yes"
     8 "Don't know anyone with AIDS"
;
label define MV845   
     0 "No"
     1 "Yes"
;
label define MV846   
     0 "No"
     1 "Yes"
;
label define MV847   
     0 "Disagree"
     1 "Agree"
     8 "Don't know/no opinion"
;
label define MV848   
     0 "Disagree"
     1 "Agree"
     8 "Don't know/no opinion"
;
label define MV849   
     0 "No"
     1 "Yes"
     8 "Don't know/depends"
;
label define MV851A  
     0 "No"
     1 "Yes"
     8 "Don't know/not sure/depends"
;
label define MV851B  
     0 "No"
     1 "Yes"
     8 "Don't know/not sure/depends"
;
label define MV851C  
     0 "No"
     1 "Yes"
     8 "Don't know/not sure/depends"
;
label define MV851D  
     0 "No"
     1 "Yes"
     8 "Don't know/not sure/depends"
;
label define MV851E  
     0 "No"
     1 "Yes"
     8 "Don't know/not sure/depends"
;
label define MV851F  
     0 "No"
     1 "Yes"
     8 "Don't know/not sure/depends"
;
label define MV851G  
     0 "No"
     1 "Yes"
     8 "Don't know/not sure/depends"
;
label define MV851H  
     0 "No"
     1 "Yes"
     8 "Don't know/not sure/depends"
;
label define MV851I  
     0 "No"
     1 "Yes"
     8 "Don't know/not sure/depends"
;
label define MV851J  
     0 "No"
     1 "Yes"
     8 "Don't know/not sure/depends"
;
label define MV851K  
     0 "No"
     1 "Yes"
     8 "Don't know/not sure/depends"
;
label define MV851L  
     0 "No"
     1 "Yes"
     8 "Don't know/not sure/depends"
;
label define MV852A  
   100 "Days: 0"
   101 "Days: 1"
   199 "Days: number missing"
   201 "Weeks: 1"
   299 "Weeks: number missing"
   301 "Months: 1"
   399 "Months: number missing"
   401 "Years: 1"
   499 "Years: number missing"
;
label define MV852B  
   101 "Days: 1"
   199 "Days: number missing"
   201 "Weeks: 1"
   299 "Weeks: number missing"
   301 "Months: 1"
   399 "Months: number missing"
   401 "Years: 1"
   499 "Years: number missing"
;
label define MV852C  
   101 "Days: 1"
   199 "Days: number missing"
   201 "Weeks: 1"
   299 "Weeks: number missing"
   301 "Months: 1"
   399 "Months: number missing"
   401 "Years: 1"
   499 "Years: number missing"
;
label define MV853A  
    95 "95+"
    98 "Don't know"
;
label define MV853B  
    95 "95+"
    98 "Don't know"
;
label define MV853C  
    95 "95+"
    98 "Don't know"
;
label define MV854A  
     0 "No"
     1 "Yes"
;
label define MV854B  
     0 "No"
     1 "Yes"
;
label define SMZONE  
     1 "Lowlands"
     2 "Foothills"
     3 "Mountains"
     4 "Senqu River Valley"
;
label define SMLANGIN
     2 "Sesotho"
     1 "English"
     6 "Other"
;
label define SMLANGRS
     2 "Sesotho"
     1 "English"
     6 "Other"
;
label define SMINTERP
     1 "Yes"
     0 "No"
;
label define SM101B  
     0 "Respondent does not agree"
     1 "Respondent agrees"
     3 "Not in male sub-sample"
;
label define SM101CA 
     1 "Yes"
     0 "No"
;
label define SM101CB 
     1 "Yes"
     0 "No"
;
label define SM101CC 
     1 "Yes"
     0 "No"
;
label define SM101E  
     1 "SMALL: 17 CM ? 22 CM"
     2 "MEDIUM: 23 CM ? 32 CM"
     3 "LARGE: 33 CM ? 42 CM"
;
label define SMBP1S  
   994 "Refused"
   995 "Technical problems"
   996 "Other"
;
label define SMBP1D  
   994 "Refused"
   995 "Technical problems"
   996 "Other"
;
label define SMBP2S  
   994 "Refused"
   995 "Technical problems"
   996 "Other"
;
label define SMBP2D  
   994 "Refused"
   995 "Technical problems"
   996 "Other"
;
label define SMBP3S  
   994 "Refused"
   995 "Technical problems"
   996 "Other"
;
label define SMBP3D  
   994 "Refused"
   995 "Technical problems"
   996 "Other"
;
label define SMBPAVES
   994 "Refused"
   995 "Technical problems"
   996 "Other"
;
label define SMBPAVED
   994 "Refused"
   995 "Technical problems"
   996 "Other"
;
label define SMBPREF 
     1 "Systolic <=129 and Diastolic <= 84"
     2 "Systolic 130-139 and/or Diastolic 85-89"
     3 "Systolic 140-159 and/or Diastolic 90-99"
     4 "Systolic 160-179 and/or Diastolic 100-109"
     5 "Systolic 180-209 and/or Diastolic 110-119"
     6 "Systolic >=210 and/or Diastolic >=120"
     9 "Other result"
;
label define SM105   
     0 "No education"
     1 "Primary"
     2 "Post Primary :Vocational/Tech.training"
     3 "Secondary/Higher"
     4 "Post secondary:Vocational/tech.training"
     5 "College"
     6 "Graduate/Post Graduate"
;
label define SM106   
     0 "Grade 0"
     1 "Grade 1"
     2 "Grade 2"
     3 "Grade 3"
     4 "Grade 4"
     5 "Grade 5"
     6 "Grade 6"
     7 "Grade 7"
     8 "Grade 8"
;
label define SM117   
    95 "12 OR MORE MONTHS"
;
label define SM118   
     1 "Elsewhere in Lesotho"
     2 "South Africa"
     3 "Other"
;
label define SM120   
     1 "Work"
     2 "School/university"
     3 "Family/marriage"
     4 "Access health or other services"
     6 "Other"
;
label define SM122   
     0 "None"
;
label define SM123   
     1 "Elsewhere in Lesotho"
     2 "South Africa"
     3 "Other"
;
label define SM124   
     1 "Work"
     2 "School/university"
     3 "Family/marriage"
     4 "Access health or other services"
     6 "Other"
;
label define SM302D  
     1 "Yes"
     0 "No"
;
label define SM404   
     1 "Living with him"
     2 "Staying elsewhere in Lesotho"
     3 "Staying elsewhere outside Lesotho"
;
label define SM404A  
     1 "Work"
     2 "Other reason"
     3 "Don't know"
;
label define SM707A  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SM707BA 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SM707BB 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SM707BC 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SM707BX 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SM707BZ 
     0 "No, knows a way"
     1 "Yes, does not know any way"
     8 "Don't know"
;
label define SM717AA 
     0 "No"
     1 "Yes"
;
label define SM717AB 
     0 "No"
     1 "Yes"
;
label define SM717AC 
     0 "No"
     1 "Yes"
;
label define SM717AD 
     0 "No"
     1 "Yes"
;
label define SM717AE 
     0 "No"
     1 "Yes"
;
label define SM717AF 
     0 "No"
     1 "Yes"
;
label define SM717AG 
     0 "No"
     1 "Yes"
;
label define SM717AH 
     0 "No"
     1 "Yes"
;
label define SM717AI 
     0 "No"
     1 "Yes"
;
label define SM717AJ 
     0 "No"
     1 "Yes"
;
label define SM717AK 
     0 "No"
     1 "Yes"
;
label define SM717AL 
     0 "No"
     1 "Yes"
;
label define SM717AX 
     0 "No"
     1 "Yes"
;
label define SM717AZ 
     0 "No"
     1 "Yes"
;
label define SM717C  
     1 "ALREADY KNOW STATUS"
     2 "NOT AT RISK"
     3 "FEAR OF RESULTS"
     4 "FEAR OF STIGMA/DISCRIMINATION"
     5 "FEAR OF DEATH"
     6 "FEAR OF DEPRESSION"
     7 "DON'T KNOW WHERE TO GET HTC"
     8 "FEAR OF GETTING INFECTED DURING TEST"
     9 "FEAR OF PARTNERS' REACTION"
    10 "LACK OF KNOWLEDGE/IGNORANCE"
    11 "FATALISM/NO CURE"
    12 "TOO EXPENSIVE"
    96 "OTHER REASON"
    98 "DON'T KNOW"
;
label define SM801AA 
     1 "Yes"
     0 "No"
;
label define SM801AB 
     1 "Yes"
     0 "No"
;
label define SM801AC 
     1 "Yes"
     0 "No"
;
label define SM801AD 
     1 "Yes"
     0 "No"
;
label define SM801C  
     1 "Yes"
     0 "No"
;
label define SM801D  
     1 "Symptoms harmless"
     2 "Cost"
     3 "Distance"
     4 "Embarrassed"
     5 "Long queue"
     6 "Other"
;
label define SM801E  
    11 "Government hospital"
    12 "Government health center"
    13 "Government health post"
    16 "Other public sector"
    21 "Private hospital/clinic"
    22 "Pharmacy"
    23 "Private doctor"
    26 "Other private medical sector"
    31 "CHAL hospital"
    32 "CHAL health center"
    41 "Red cross health center"
    51 "Village health worker"
    52 "Support groups"
    61 "Facility outside Lesotho"
    71 "Shop"
    72 "Church"
    73 "Friends/relatives"
    74 "Traditional healer"
    96 "Other"
;
label define SM801F  
   100 " Same day"
   101 " 1 Day"
   201 " 1 Week"
   301 " 1 Month"
   998 "Don't know"
;
label define SM801G  
     1 "Yes"
     0 "No"
;
label define SM801H  
     1 "Yes"
     0 "No"
;
label define SM801I  
    96 "8 years or more"
    98 "Don't know"
;
label define SM801J  
     1 "Yes"
     0 "No"
;
label define SM801K  
    11 "Government hospital"
    12 "Govt. health center"
    13 "Govt. health post"
    16 "Other public sector"
    21 "Private hospital/clinic"
    22 "Pharmacy"
    23 "Private doctor"
    26 "Other private medical sector"
    31 "CHAL hospital"
    32 "CHAL health center"
    41 "Red cross health center"
    51 "Village health worker"
    52 "Support groups"
    61 "Facility outside Lesotho"
    71 "Shop"
    72 "Church"
    73 "Friends/relatives"
    74 "Traditional healer"
    96 "Other"
;
label define SM804A  
     1 "Yes"
     0 "No"
;
label define SM804BA 
     0 "No"
     1 "Yes"
;
label define SM804BB 
     0 "No"
     1 "Yes"
;
label define SM804BC 
     0 "No"
     1 "Yes"
;
label define SM804BD 
     0 "No"
     1 "Yes"
;
label define SM804BE 
     0 "No"
     1 "Yes"
;
label define SM804BF 
     0 "No"
     1 "Yes"
;
label define SM804BG 
     0 "No"
     1 "Yes"
;
label define SM804BH 
     0 "No"
     1 "Yes"
;
label define SM804BI 
     0 "No"
     1 "Yes"
;
label define SM804BJ 
     0 "No"
     1 "Yes"
;
label define SM804BX 
     0 "No"
     1 "Yes"
;
label define SM804BY 
     0 "No"
     1 "Yes"
;
label define SM804BZ 
     0 "No"
     1 "Yes"
;
label define SM804CA 
     0 "No"
     1 "Yes"
;
label define SM804CB 
     0 "No"
     1 "Yes"
;
label define SM804CC 
     0 "No"
     1 "Yes"
;
label define SM804CD 
     0 "No"
     1 "Yes"
;
label define SM804CE 
     0 "No"
     1 "Yes"
;
label define SM804CF 
     0 "No"
     1 "Yes"
;
label define SM804CG 
     0 "No"
     1 "Yes"
;
label define SM804CX 
     0 "No"
     1 "Yes"
;
label define SM804CZ 
     0 "No"
     1 "Yes"
;
label define SM805A  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SM805B  
    96 "During childhood (< 5 years)"
    98 "Don't know"
;
label define SM805C  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SM805D  
    96 "During childhood (< 5 years)"
    98 "Don't know"
;
label define SM812A  
     1 "Yes"
     0 "No"
;
label define SM812AAA
     1 "Yes"
     0 "No"
;
label define SM812AAB
     1 "Yes"
     0 "No"
;
label define SM812AAC
     1 "Yes"
     0 "No"
;
label define SM812AAD
     1 "Yes"
     0 "No"
;
label define SM812AAE
     1 "Yes"
     0 "No"
;
label define SM812AAF
     1 "Yes"
     0 "No"
;
label define SM812AAG
     1 "Yes"
     0 "No"
;
label define SM812AAH
     1 "Yes"
     0 "No"
;
label define SM812AAX
     1 "Yes"
     0 "No"
;
label define SM812AAZ
     1 "Yes"
     0 "No"
;
label define SM812B  
     1 "Yes"
     0 "No"
;
label define SM812C  
     1 "Yes"
     0 "No"
;
label define SM812D  
     1 "Injected"
     2 "Orally"
     3 "BOTH INJECTED AND ORALLY"
;
label define SM812E  
     1 "Yes"
     0 "No"
;
label define SM812F  
     1 "LESS THAN 6 MONTHS AGO"
     2 "6 - 11 MONTHS AGO"
     3 "1 - 5 YEARS AGO"
     4 "MORE THAN 5 YEARS AGO"
     8 "DON'T KNOW"
;
label define SM812G  
     1 "Doctor/nurse"
     2 "Pharmacist"
     3 "Self"
     6 "Other"
     8 "Don't know"
;
label define SM812H  
     0 "No"
     1 "Yes"
;
label define SM812IA 
     0 "No"
     1 "Yes"
     3 "Does not apply"
;
label define SM812IB 
     0 "No"
     1 "Yes"
     3 "Does not apply"
;
label define SM812IC 
     0 "No"
     1 "Yes"
     3 "Does not apply"
;
label define SM812ID 
     0 "No"
     1 "Yes"
     3 "Does not apply"
;
label define SM812IE 
     0 "No"
     1 "Yes"
     3 "Does not apply"
;
label define SM812IF 
     0 "No"
     1 "Yes"
     3 "Does not apply"
;
label define SM812IG 
     1 "Yes"
     0 "No"
     3 "Does not apply"
;
label define SM812J  
     1 "Yes"
     0 "No"
;
label define SM812K  
     1 "Women only"
     2 "Men only"
     3 "Both"
;

#delimit cr
label values mv013    MV013   
label values mv014    MV014   
label values mv015    MV015   
label values mv022    MV022   
label values mv023    MV023   
label values mv024    MV024   
label values mv025    MV025   
label values mv026    MV026   
label values mv034_1  MV034   
label values mv034_2  MV034   
label values mv034_3  MV034   
label values mv034_4  MV034   
label values mv034_5  MV034   
label values mv034_6  MV034   
label values mv034_7  MV034   
label values mv034_8  MV034   
label values mv034a_1 MV034A  
label values mv034a_2 MV034A  
label values mv034a_3 MV034A  
label values mv034a_4 MV034A  
label values mv034a_5 MV034A  
label values mv034a_6 MV034A  
label values mv034a_7 MV034A  
label values mv034a_8 MV034A  
label values mv035    MV035   
label values mv803    MV803   
label values mv101    MV101   
label values mv102    MV102   
label values mv103    MV103   
label values mv104    MV104   
label values mv105    MV105   
label values mv106    MV106   
label values mv107    MV107   
label values mv130    MV130   
label values mv133    MV133   
label values mv134    MV134   
label values mv135    MV135   
label values mv149    MV149   
label values mv150    MV150   
label values mv151    MV151   
label values mv152    MV152   
label values mv155    MV155   
label values mv156    MV156   
label values mv157    MV157   
label values mv158    MV158   
label values mv159    MV159   
label values mv167    MV167   
label values mv168    MV168   
label values mv190    MV190   
label values mv213    MV213   
label values mv217    MV217   
label values mv225    MV225   
label values mv246    MV246   
label values mv248    MV248   
label values mv249    MV249   
label values mv250    MV250   
label values mv251    MV251   
label values mv252    MV252   
label values mv301    MV301   
label values mv302    MV302   
label values m304a_01 M304A   
label values m304a_02 M304A   
label values m304a_03 M304A   
label values m304a_04 M304A   
label values m304a_05 M304A   
label values m304a_06 M304A   
label values m304a_07 M304A   
label values m304a_08 M304A   
label values m304a_09 M304A   
label values m304a_10 M304A   
label values m304a_11 M304A   
label values m304a_12 M304A   
label values m304a_13 M304A   
label values m304a_14 M304A   
label values m304a_15 M304A   
label values m304a_16 M304A   
label values m304a_17 M304A   
label values m304a_18 M304A   
label values m304a_19 M304A   
label values m304a_20 M304A   
label values mv304_01 MV304   
label values mv304_02 MV304   
label values mv304_03 MV304   
label values mv304_04 MV304   
label values mv304_05 MV304   
label values mv304_06 MV304   
label values mv304_07 MV304   
label values mv304_08 MV304   
label values mv304_09 MV304   
label values mv304_10 MV304   
label values mv304_11 MV304   
label values mv304_12 MV304   
label values mv304_13 MV304   
label values mv304_14 MV304   
label values mv304_15 MV304   
label values mv304_16 MV304   
label values mv304_17 MV304   
label values mv304_18 MV304   
label values mv304_19 MV304   
label values mv304_20 MV304   
label values mv305_01 MV305   
label values mv305_02 MV305   
label values mv305_03 MV305   
label values mv305_04 MV305   
label values mv305_05 MV305   
label values mv305_06 MV305   
label values mv305_07 MV305   
label values mv305_08 MV305   
label values mv305_09 MV305   
label values mv305_10 MV305   
label values mv305_11 MV305   
label values mv305_12 MV305   
label values mv305_13 MV305   
label values mv305_14 MV305   
label values mv305_15 MV305   
label values mv305_16 MV305   
label values mv305_17 MV305   
label values mv305_18 MV305   
label values mv305_19 MV305   
label values mv305_20 MV305   
label values mv307_01 MV307   
label values mv307_02 MV307   
label values mv307_03 MV307   
label values mv307_04 MV307   
label values mv307_05 MV307   
label values mv307_06 MV307   
label values mv307_07 MV307   
label values mv307_08 MV307   
label values mv307_09 MV307   
label values mv307_10 MV307   
label values mv307_11 MV307   
label values mv307_12 MV307   
label values mv307_13 MV307   
label values mv307_14 MV307   
label values mv307_15 MV307   
label values mv307_16 MV307   
label values mv307_17 MV307   
label values mv307_18 MV307   
label values mv307_19 MV307   
label values mv307_20 MV307   
label values mv312    MV312   
label values mv313    MV313   
label values mv323a   MV323A  
label values mv325b   MV325B  
label values mv372a   MV372A  
label values mv384a   MV384A  
label values mv384b   MV384B  
label values mv384c   MV384C  
label values mv395    MV395   
label values mv396    MV396   
label values mv3a09b  MV3A09B 
label values mv3b17   MV3B17  
label values mv3b25a  MV3B25A 
label values mv3b25b  MV3B25B 
label values mv463a   MV463A  
label values mv463b   MV463B  
label values mv463c   MV463C  
label values mv463d   MV463D  
label values mv463e   MV463E  
label values mv463f   MV463F  
label values mv463g   MV463G  
label values mv463x   MV463X  
label values mv463z   MV463Z  
label values mv464    MV464   
label values mv474    MV474   
label values mv474a   MV474A  
label values mv474b   MV474B  
label values mv474c   MV474C  
label values mv474d   MV474D  
label values mv474e   MV474E  
label values mv474f   MV474F  
label values mv474g   MV474G  
label values mv474h   MV474H  
label values mv474i   MV474I  
label values mv474j   MV474J  
label values mv474x   MV474X  
label values mv474z   MV474Z  
label values mv475    MV475   
label values mv476    MV476   
label values mv477    MV477   
label values mv478    MV478   
label values mv479    MV479   
label values mv480    MV480   
label values mv481    MV481   
label values mv481a   MV481A  
label values mv481b   MV481B  
label values mv481c   MV481C  
label values mv481d   MV481D  
label values mv481e   MV481E  
label values mv481f   MV481F  
label values mv481g   MV481G  
label values mv481h   MV481H  
label values mv481x   MV481X  
label values mv482a   MV482A  
label values mv482b   MV482B  
label values mv482c   MV482C  
label values mv483    MV483   
label values mv483a   MV483A  
label values mv483b   MV483B  
label values mv483c   MV483C  
label values mv501    MV501   
label values mv502    MV502   
label values mv503    MV503   
label values mv504    MV504   
label values mv510    MV510   
label values mv513    MV513   
label values mv525    MV525   
label values mv527    MV527   
label values mv528    MV528   
label values mv529    MV529   
label values mv531    MV531   
label values mv532    MV532   
label values mv535    MV535   
label values mv536    MV536   
label values mv541    MV541   
label values mv602    MV602   
label values mv603    MV603   
label values mv604    MV604   
label values mv605    MV605   
label values mv613    MV613   
label values mv614    MV614   
label values mv616    MV616   
label values mv621    MV621   
label values mv627    MV627   
label values mv628    MV628   
label values mv629    MV629   
label values mv631    MV631   
label values mv633a   MV633A  
label values mv633b   MV633B  
label values mv633c   MV633C  
label values mv633d   MV633D  
label values mv633e   MV633E  
label values mv633f   MV633F  
label values mv633g   MV633G  
label values mv634a   MV634A  
label values mv634b   MV634B  
label values mv634c   MV634C  
label values mv634d   MV634D  
label values mv714    MV714   
label values mv714a   MV714A  
label values mv716    MV716   
label values mv717    MV717   
label values mv719    MV719   
label values mv721    MV721   
label values mv731    MV731   
label values mv732    MV732   
label values mv739    MV739   
label values mv740    MV740   
label values mv741    MV741   
label values mv743a   MV743A  
label values mv743b   MV743B  
label values mv743c   MV743C  
label values mv743d   MV743D  
label values mv743e   MV743E  
label values mv743f   MV743F  
label values mv743g   MV743G  
label values mv744a   MV744A  
label values mv744b   MV744B  
label values mv744c   MV744C  
label values mv744d   MV744D  
label values mv744e   MV744E  
label values mv745a   MV745A  
label values mv745b   MV745B  
label values mv747a   MV747A  
label values mv747b   MV747B  
label values mv750    MV750   
label values mv751    MV751   
label values mv754bp  MV754BP 
label values mv754cp  MV754CP 
label values mv754dp  MV754DP 
label values mv754jp  MV754JP 
label values mv754wp  MV754WP 
label values mv756    MV756   
label values mv761    MV761   
label values mv761b   MV761B  
label values mv761c   MV761C  
label values mv762aa  MV762AA 
label values mv762ab  MV762AB 
label values mv762ac  MV762AC 
label values mv762ad  MV762AD 
label values mv762ae  MV762AE 
label values mv762af  MV762AF 
label values mv762ag  MV762AG 
label values mv762ah  MV762AH 
label values mv762ai  MV762AI 
label values mv762aj  MV762AJ 
label values mv762ak  MV762AK 
label values mv762al  MV762AL 
label values mv762am  MV762AM 
label values mv762an  MV762AN 
label values mv762ao  MV762AO 
label values mv762ap  MV762AP 
label values mv762aq  MV762AQ 
label values mv762ar  MV762AR 
label values mv762as  MV762AS 
label values mv762at  MV762AT 
label values mv762au  MV762AU 
label values mv762av  MV762AV 
label values mv762aw  MV762AW 
label values mv762ax  MV762AX 
label values mv762az  MV762AZ 
label values mv762ba  MV762BA 
label values mv762bb  MV762BB 
label values mv762bc  MV762BC 
label values mv762bd  MV762BD 
label values mv762be  MV762BE 
label values mv762bf  MV762BF 
label values mv762bg  MV762BG 
label values mv762bh  MV762BH 
label values mv762bi  MV762BI 
label values mv762bj  MV762BJ 
label values mv762bk  MV762BK 
label values mv762bl  MV762BL 
label values mv762bm  MV762BM 
label values mv762bn  MV762BN 
label values mv762bo  MV762BO 
label values mv762bp  MV762BP 
label values mv762bq  MV762BQ 
label values mv762br  MV762BR 
label values mv762bs  MV762BS 
label values mv762bt  MV762BT 
label values mv762bu  MV762BU 
label values mv762bv  MV762BV 
label values mv762bw  MV762BW 
label values mv762bx  MV762BX 
label values mv762bz  MV762BZ 
label values mv763a   MV763A  
label values mv763b   MV763B  
label values mv763c   MV763C  
label values mv763d   MV763D  
label values mv763e   MV763E  
label values mv763f   MV763F  
label values mv763g   MV763G  
label values mv766a   MV766A  
label values mv766b   MV766B  
label values mv767a   MV767A  
label values mv767b   MV767B  
label values mv767c   MV767C  
label values mv768a   MV768A  
label values mv768b   MV768B  
label values mv768c   MV768C  
label values mv769    MV769   
label values mv769a   MV769A  
label values mv770    MV770   
label values mv770a   MV770A  
label values mv770b   MV770B  
label values mv770c   MV770C  
label values mv770d   MV770D  
label values mv770e   MV770E  
label values mv770f   MV770F  
label values mv770g   MV770G  
label values mv770h   MV770H  
label values mv770i   MV770I  
label values mv770j   MV770J  
label values mv770k   MV770K  
label values mv770l   MV770L  
label values mv770m   MV770M  
label values mv770n   MV770N  
label values mv770o   MV770O  
label values mv770p   MV770P  
label values mv770q   MV770Q  
label values mv770r   MV770R  
label values mv770s   MV770S  
label values mv770t   MV770T  
label values mv770u   MV770U  
label values mv770v   MV770V  
label values mv770w   MV770W  
label values mv770x   MV770X  
label values mv774a   MV774A  
label values mv774b   MV774B  
label values mv774c   MV774C  
label values mv775    MV775   
label values mv777    MV777   
label values mv778    MV778   
label values mv779    MV779   
label values mv780    MV780   
label values mv781    MV781   
label values mv783    MV783   
label values mv784a   MV784A  
label values mv784b   MV784B  
label values mv784c   MV784C  
label values mv784d   MV784D  
label values mv784e   MV784E  
label values mv784f   MV784F  
label values mv784g   MV784G  
label values mv784h   MV784H  
label values mv784i   MV784I  
label values mv784j   MV784J  
label values mv784k   MV784K  
label values mv784l   MV784L  
label values mv784m   MV784M  
label values mv784n   MV784N  
label values mv784o   MV784O  
label values mv784p   MV784P  
label values mv784q   MV784Q  
label values mv784r   MV784R  
label values mv784s   MV784S  
label values mv784t   MV784T  
label values mv784u   MV784U  
label values mv784v   MV784V  
label values mv784x   MV784X  
label values mv785    MV785   
label values mv791    MV791   
label values mv793    MV793   
label values mv793a   MV793A  
label values mv793b   MV793B  
label values mv820    MV820   
label values mv822    MV822   
label values mv823    MV823   
label values mv824    MV824   
label values mv825    MV825   
label values mv826    MV826   
label values mv826a   MV826A  
label values mv827    MV827   
label values mv828    MV828   
label values mv829    MV829   
label values mv832b   MV832B  
label values mv832c   MV832C  
label values mv833a   MV833A  
label values mv833b   MV833B  
label values mv833c   MV833C  
label values mv834a   MV834A  
label values mv834b   MV834B  
label values mv834c   MV834C  
label values mv835a   MV835A  
label values mv835b   MV835B  
label values mv835c   MV835C  
label values mv836    MV836   
label values mv837    MV837   
label values mv844    MV844   
label values mv845    MV845   
label values mv846    MV846   
label values mv847    MV847   
label values mv848    MV848   
label values mv849    MV849   
label values mv851a   MV851A  
label values mv851b   MV851B  
label values mv851c   MV851C  
label values mv851d   MV851D  
label values mv851e   MV851E  
label values mv851f   MV851F  
label values mv851g   MV851G  
label values mv851h   MV851H  
label values mv851i   MV851I  
label values mv851j   MV851J  
label values mv851k   MV851K  
label values mv851l   MV851L  
label values mv852a   MV852A  
label values mv852b   MV852B  
label values mv852c   MV852C  
label values mv853a   MV853A  
label values mv853b   MV853B  
label values mv853c   MV853C  
label values mv854a   MV854A  
label values mv854b   MV854B  
label values smzone   SMZONE  
label values smlangin SMLANGIN
label values smlangrs SMLANGRS
label values sminterp SMINTERP
label values sm101b   SM101B  
label values sm101ca  SM101CA 
label values sm101cb  SM101CB 
label values sm101cc  SM101CC 
label values sm101e   SM101E  
label values smbp1s   SMBP1S  
label values smbp1d   SMBP1D  
label values smbp2s   SMBP2S  
label values smbp2d   SMBP2D  
label values smbp3s   SMBP3S  
label values smbp3d   SMBP3D  
label values smbpaves SMBPAVES
label values smbpaved SMBPAVED
label values smbpref  SMBPREF 
label values sm105    SM105   
label values sm106    SM106   
label values sm117    SM117   
label values sm118    SM118   
label values sm120    SM120   
label values sm122    SM122   
label values sm123    SM123   
label values sm124    SM124   
label values sm302d   SM302D  
label values sm404    SM404   
label values sm404a   SM404A  
label values sm707a   SM707A  
label values sm707ba  SM707BA 
label values sm707bb  SM707BB 
label values sm707bc  SM707BC 
label values sm707bx  SM707BX 
label values sm707bz  SM707BZ 
label values sm717aa  SM717AA 
label values sm717ab  SM717AB 
label values sm717ac  SM717AC 
label values sm717ad  SM717AD 
label values sm717ae  SM717AE 
label values sm717af  SM717AF 
label values sm717ag  SM717AG 
label values sm717ah  SM717AH 
label values sm717ai  SM717AI 
label values sm717aj  SM717AJ 
label values sm717ak  SM717AK 
label values sm717al  SM717AL 
label values sm717ax  SM717AX 
label values sm717az  SM717AZ 
label values sm717c   SM717C  
label values sm801aa  SM801AA 
label values sm801ab  SM801AB 
label values sm801ac  SM801AC 
label values sm801ad  SM801AD 
label values sm801c   SM801C  
label values sm801d   SM801D  
label values sm801e   SM801E  
label values sm801f   SM801F  
label values sm801g   SM801G  
label values sm801h   SM801H  
label values sm801i   SM801I  
label values sm801j   SM801J  
label values sm801k   SM801K  
label values sm804a   SM804A  
label values sm804ba  SM804BA 
label values sm804bb  SM804BB 
label values sm804bc  SM804BC 
label values sm804bd  SM804BD 
label values sm804be  SM804BE 
label values sm804bf  SM804BF 
label values sm804bg  SM804BG 
label values sm804bh  SM804BH 
label values sm804bi  SM804BI 
label values sm804bj  SM804BJ 
label values sm804bx  SM804BX 
label values sm804by  SM804BY 
label values sm804bz  SM804BZ 
label values sm804ca  SM804CA 
label values sm804cb  SM804CB 
label values sm804cc  SM804CC 
label values sm804cd  SM804CD 
label values sm804ce  SM804CE 
label values sm804cf  SM804CF 
label values sm804cg  SM804CG 
label values sm804cx  SM804CX 
label values sm804cz  SM804CZ 
label values sm805a   SM805A  
label values sm805b   SM805B  
label values sm805c   SM805C  
label values sm805d   SM805D  
label values sm812a   SM812A  
label values sm812aaa SM812AAA
label values sm812aab SM812AAB
label values sm812aac SM812AAC
label values sm812aad SM812AAD
label values sm812aae SM812AAE
label values sm812aaf SM812AAF
label values sm812aag SM812AAG
label values sm812aah SM812AAH
label values sm812aax SM812AAX
label values sm812aaz SM812AAZ
label values sm812b   SM812B  
label values sm812c   SM812C  
label values sm812d   SM812D  
label values sm812e   SM812E  
label values sm812f   SM812F  
label values sm812g   SM812G  
label values sm812h   SM812H  
label values sm812ia  SM812IA 
label values sm812ib  SM812IB 
label values sm812ic  SM812IC 
label values sm812id  SM812ID 
label values sm812ie  SM812IE 
label values sm812if  SM812IF 
label values sm812ig  SM812IG 
label values sm812j   SM812J  
label values sm812k   SM812K  
